(function(root){
  "use strict";
  const core=root.HHEnglishAcademyCore,esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const btn=(action,text,extra="")=>'<button type="button" data-hha-action="'+action+'" '+extra+'>'+text+'</button>';
  const bindings=new WeakMap(),labels={choice:"Trắc nghiệm",gap:"Điền đáp án",order:"Sắp xếp câu",dictation:"Chép chính tả",match:"Ghép nghĩa",correction:"Sửa lựa chọn"};
  function exercise(t,draft={},attributes=""){
    if(!t)return '<p>Chưa có dữ liệu cho dạng bài này. Hãy chọn dạng khác.</p>';
    let fields="";
    if(t.type==="choice")fields='<fieldset><legend>Chọn đáp án</legend>'+t.options.map(x=>'<label><input type="radio" name="answer" value="'+esc(x)+'" '+(draft.answer===x?'checked':'')+' required>'+esc(x)+'</label>').join("")+'</fieldset>';
    else if(t.type==="match")fields=t.pairs.map(p=>'<label>'+esc(p.term)+'<select name="pair-'+p.id+'" required><option value="">Chọn nghĩa</option>'+t.choices.map(c=>'<option value="'+c.id+'" '+(draft["pair-"+p.id]===c.id?'selected':'')+'>'+esc(c.meaning)+'</option>').join("")+'</select></label>').join("");
    else if(t.type==="order")fields='<p class="hha-tiles">'+t.tiles.map(c=>btn("tile",esc(c.word),'data-id="'+c.id+'"')).join("")+'</p><label>Câu của bạn (bàn phím hoặc nút từ)<input name="answer" value="'+esc(draft.answer||"")+'" required autocomplete="off"></label>'+btn("clear-order","Xóa câu đang ghép");
    else fields=(t.type==="dictation"?'<p>Giọng tổng hợp; không có timestamp audio thật.</p><div class="hha-actions"><button type="button" data-hhe-speak="'+esc(t.sample)+'">Nghe mẫu TTS</button><button type="button" data-hhe-speak="'+esc(t.sample)+'" data-hhe-speak-rate="0.7">Nghe chậm</button></div>':'')+(t.wrong?'<p>Lựa chọn chưa phù hợp: '+esc(t.wrong)+'</p><small>'+esc(t.instruction)+'</small>':'')+'<label>Câu trả lời<input name="answer" value="'+esc(draft.answer||"")+'" required autocomplete="off"></label>';
    return '<form class="hha-exercise" '+attributes+' data-task-type="'+t.type+'"><small>BÀI LUYỆN · '+esc(labels[t.type])+'</small><h3>'+esc(t.prompt)+'</h3>'+fields+'<button type="submit">Kiểm tra câu trả lời</button><output role="status"></output><details><summary>Gợi ý cách làm</summary><p>'+esc(t.type==="order"?"Đối chiếu trật tự câu trong bài học.":t.type==="dictation"?"Nghe lại mẫu TTS rồi gõ câu nghe được.":"Đọc kỹ đề và ngữ cảnh bài học; xem giải thích sau khi trả lời.")+'</p></details></form>';
  }
  function writing(state,ctx){
    const level=ctx.selectedLevelId(state),template=core.writingTemplates.find(t=>t.id===level),draft=state.writingDrafts?.[level]||(level==="A0"?state.writingDraft:"")||"",a=core.normalizeAcademy(state).learningOS.academy,w=a.writing[level]||{},versions=w.versions||[],feedback=core.writingFeedback(draft,template);
    return '<section class="hha hha-writing"><header><small>WRITING STUDIO · '+esc(template.label)+'</small><h2>Viết, tự kiểm tra và sửa có chủ đích</h2><p>Bản nháp theo hồ sơ/cấp độ; phiên bản không phải điểm chấm bài.</p></header><div class="hha-writing-grid"><aside><h3>'+esc(template.title)+'</h3><p>'+esc(template.prompt)+'</p><ol>'+template.outline.map(x=>'<li>'+esc(x)+'</li>').join("")+'</ol>'+btn("outline","Chèn dàn ý · không ghi đè bản đang viết")+'<small>Nội dung gốc · bản biên soạn cần rà soát, không trích bài thương mại.</small></aside><div><label>Bài viết<textarea data-hhe-writing data-level="'+level+'" rows="12" maxlength="12000">'+esc(draft)+'</textarea></label><p><b data-hhe-word-count>'+feedback.words+'</b> từ · <span data-hha-save-state>Đang dùng bản thiết bị</span></p><div class="hha-actions">'+btn("version-save","Lưu phiên bản")+btn("writing-export","Tải bài TXT")+btn("writing-check","Kiểm tra cấu trúc cục bộ")+'</div><div data-hha-writing-feedback role="status"></div><fieldset><legend>Checklist tự đánh giá</legend>'+template.checklist.map((text,i)=>'<label><input type="checkbox" data-hha-writing-check="'+i+'" '+(w.checklist?.includes(i)?'checked':'')+'>'+esc(text)+'</label>').join("")+'</fieldset></div></div><section><h3>Phiên bản đã lưu · '+versions.length+' · tối đa 20 bản trên toàn hồ sơ</h3>'+(versions.length?'<label>So sánh với bản đang viết<select data-hha-version><option value="">Chọn phiên bản</option>'+versions.map((v,i)=>'<option value="'+i+'">'+esc(new Date(v.at).toLocaleString("vi-VN"))+' · '+v.words+' từ</option>').join("")+'</select></label><div class="hha-compare"><article><h4>Bản đã chọn</h4><pre data-hha-before></pre></article><article><h4>Bản đang viết</h4><pre data-hha-after>'+esc(draft)+'</pre></article></div>'+btn("version-restore","Đưa bản đã chọn trở lại bản nháp · giữ bản hiện tại"):'<p>Chưa có phiên bản. Lưu để giữ quá trình sửa bài.</p>')+'</section></section>';
  }
  function supplement(state,ctx){
    const a=core.normalizeAcademy(state).learningOS.academy,view=state.activeView;let html="";
    if(view==="practice-hub"||view==="practice"){
      const lesson=ctx.getLesson(state.activeLesson)||ctx.nextLessonFor(state),row=a.practice[lesson.id]||{},t=core.task(lesson,a.exerciseType);
      html='<button type="button" data-hvx-action="open-atlas">240 từ/cụm · 24 bộ & 9 cách luyện</button><header><small>ACTIVE PRACTICE LAB</small><h2>Luyện đúng nội dung đang học</h2><p>'+esc(lesson.title)+' · '+esc(lesson.level)+' · kết quả từ đáp án của bài, không chấm câu tự do.</p></header><nav>'+Object.entries(labels).map(([type,label])=>btn("type",label,'data-type="'+type+'" aria-pressed="'+(type===a.exerciseType)+'"')).join("")+'</nav>'+exercise(t,row.drafts?.[a.exerciseType]||{},"data-hha-practice")+'<p>'+Number(row.attempts||0)+' lượt kiểm tra đã lưu · '+Number(row.correct||0)+' lượt đúng. Bài gốc và ID không đổi.</p>';
    }
    if(view==="speaking"){
      const sound=core.sounds.find(s=>s.id===a.soundId),scenario=core.conversations.find(s=>s.id===a.scenarioId),record=a.conversation[scenario.id]||{},replies=record.replies||[],turn=Math.min(replies.length,scenario.turns.length),feedback=core.conversationFeedback(replies,scenario);
      html='<header><small>SPEAKING LAB · SCRIPTED CONVERSATION</small><h2>Luyện âm và giao tiếp có mục tiêu</h2><p>Không chấm âm vị từ transcript; giọng nghe là TTS của thiết bị.</p></header><label>Bài tự luyện âm<select data-hha-sound>'+core.sounds.map(s=>'<option value="'+s.id+'" '+(s.id===sound.id?'selected':'')+'>'+esc(s.title)+'</option>').join("")+'</select></label><article><h3>'+esc(sound.title)+'</h3><p>'+esc(sound.tip)+'</p><div class="hha-actions">'+sound.pairs.flat().map(word=>'<button type="button" data-hhe-speak="'+esc(word)+'">'+esc(word)+'</button>').join("")+'</div><button type="button" data-hhe-speak="'+esc(sound.phrase)+'">Nghe cụm mẫu</button><p>'+esc(sound.phrase)+'</p></article><label>Tình huống<select data-hha-scenario>'+core.conversations.map(s=>'<option value="'+s.id+'" '+(s.id===scenario.id?'selected':'')+'>'+esc(s.title)+'</option>').join("")+'</select></label><article><h3>'+esc(scenario.title)+'</h3><p>'+esc(scenario.goal)+'</p><p>Cụm gợi ý: '+esc(scenario.phrases.join(" · "))+'</p><p>Tiêu chí tự đánh giá: '+esc(scenario.criterion)+'</p><ol>'+replies.map((answer,i)=>'<li><strong>Nhân vật kịch bản: </strong>'+esc(scenario.turns[i])+'<p><strong>Bạn: </strong>'+esc(answer)+'</p></li>').join("")+'</ol>'+(turn<scenario.turns.length?'<form data-hha-conversation><h4>'+esc(scenario.turns[turn])+'</h4><button type="button" data-hhe-speak="'+esc(scenario.turns[turn])+'">Nghe câu hỏi TTS</button><label>Câu trả lời của bạn<textarea name="answer" maxlength="2000" required>'+esc(record.draft||"")+'</textarea></label><button>Lưu lượt trả lời</button><output role="status"></output></form>':'<p>Đã lưu '+feedback.turns+' lượt trả lời. Đây là hoàn thành kịch bản, không phải chứng nhận giao tiếp thành thạo.</p>')+btn("conversation-export","Tải hội thoại TXT")+btn("conversation-restart","Luyện lại · giữ tối đa 10 lịch sử")+'</article><p class="hha-notice">AI Tutor chuyên sâu: chưa nối dịch vụ trong workspace này. Hội thoại trên là kịch bản gốc, không giả phản hồi AI. Không có audio gửi ra ngoài bởi công cụ kịch bản.</p>';
    }
    if(view==="mistakes"){
      const rows=(state.learningOS.mistakeRecords||[]).filter(m=>m.status!=="resolved"&&m.expected).slice(0,10);
      html='<header><small>ERROR CLINIC · RETRY</small><h2>Thử sửa lỗi bằng câu trả lời thật</h2><p>Câu mở cần tự đánh giá hoặc người chấm; bộ đối chiếu chỉ dùng đáp án đã lưu.</p></header>'+(rows.length?rows.map(m=>'<form data-hha-mistake="'+esc(m.id)+'"><h3>'+esc(m.prompt)+'</h3><p>Lần trước: '+esc(m.answer)+'</p><label>Thử lại<input name="answer" required maxlength="500"></label><button>Kiểm tra và ghi bằng chứng sửa lỗi</button><output role="status"></output></form>').join(""):'<p>Không có lỗi có đáp án đang chờ luyện lại.</p>');
    }
    if(view==="dashboard"||view==="pathways"){
      const weekly=a.weekly||{},days=state.studyDays||[];
      html='<header><small>PERSONAL WEEK · LOCAL PLAN</small><h2>Kế hoạch tuần của bạn</h2><p>Gợi ý theo lịch đã chọn, không tự gửi nhắc học hay đo sự chú ý.</p></header><form data-hha-weekly><label>Mục tiêu tuần<input name="goal" maxlength="160" value="'+esc(weekly.goal||state.settings?.goal||"")+'"></label><label>Kỹ năng ưu tiên<select name="skill">'+["listening","speaking","reading","writing","grammar","vocabulary"].map(s=>'<option value="'+s+'" '+(weekly.skill===s?'selected':'')+'>'+esc(s)+'</option>').join("")+'</select></label><button>Lưu kế hoạch tuần</button></form><p>Lịch hiện tại: '+(days.length?days.map(d=>["CN","T2","T3","T4","T5","T6","T7"][d]).join(" · "):"Chưa chọn ngày học")+'. Có thể chỉnh ở Cài đặt.</p>'+btn("group","Mở Học cùng nhau · không tự vào cuộc gọi");
    }
    if(view==="progress"){
      const attempts=state.learningOS.reviewAttempts||[],sessions=a.timerSessions||[];
      html='<header><small>EVIDENCE · NOT CERTIFICATION</small><h2>Bằng chứng và tự đánh giá</h2></header><div class="hha-stats"><article><strong>'+attempts.filter(x=>x.correct===true&&x.graded!==false).length+'</strong><span>Lượt trả lời đúng đã lưu</span></article><article><strong>'+sessions.length+'</strong><span>Phiên đồng hồ đã kết thúc</span></article></div><p>Thời lượng bài trong dữ liệu cũ là dự kiến. Đồng hồ không chứng minh thời gian thực sự học. Không tự quy đổi XP/đáp án thành chứng chỉ hoặc band thi.</p>';
    }
    if(view==="listening"||view==="listen-read")html+=root.HHEnglishAcademyMedia?.markup?.()||"";
    if(view==="settings"||state.learningOS.sync?.status==="conflict"||state.learningOS.localSave?.status==="memory"){
      html+='<section class="hha-sync"><h3>Lưu thiết bị và đồng bộ</h3><p data-hha-sync-state>'+esc(state.learningOS.sync?.lastError||"Bản thiết bị và bản máy chủ được xác nhận riêng.")+'</p><div class="hha-actions">'+btn("sync-retry","Thử đồng bộ")+btn("sync-preview","Xem thông tin bản máy chủ")+btn("backup","Xuất bản thiết bị JSON")+'</div><p data-hha-remote-info></p><label><input type="checkbox" data-hha-sync-confirm>Tôi đã xuất bản cần giữ và muốn xử lý hai bản khác nhau.</label><div class="hha-actions">'+btn("sync-local","Giữ bản thiết bị · gửi sau kiểm tra revision")+btn("sync-server","Dùng bản máy chủ · thay bản thiết bị")+'</div><details><summary>Xóa bản máy chủ của hồ sơ này</summary><label>Nhập đúng learner profile ID<input data-hha-delete-profile autocomplete="off" placeholder="'+esc(state.learnerProfileId)+'"></label>'+btn("sync-delete","Xóa bản máy chủ · không xóa bản thiết bị")+'</details></section>';
    }
    if(["lesson","writing","speaking","listening","reading"].includes(view))html+='<footer class="hha-handoff">'+btn("share","Tạo liên kết bài học hiện tại")+btn("group","Mở nhóm luyện tập")+'<p data-hha-share role="status"></p></footer>';
    if(html&&["lesson","practice-hub","writing","speaking"].includes(view))html+='<details><summary>Nguồn nội dung và giới hạn đánh giá</summary><p>Nội dung gốc HH English, bản biên soạn có hỗ trợ AI · cần rà soát học thuật. Các bài luyện mới dùng mục tiêu/đáp án của curriculum đang có. Bản nâng cấp 09/10/2026 không nhập tài nguyên thương mại. A0 là cấp dự bị nội bộ; không phải một bậc CEFR chuẩn.</p></details>';
    return html?'<section class="hha hha-supplement" aria-label="Cosmic Academy '+esc(view)+'">'+html+'</section>':"";
  }
  function bind(runtime){
    const host=runtime.host;if(bindings.has(host)){bindings.get(host).runtime=runtime;return;}const bag={runtime,urls:new Map(),busy:false};bindings.set(host,bag);
    const current=()=>bag.runtime,read=()=>core.normalizeAcademy(current().readState()),save=s=>current().writeState(s),render=()=>current().render({preserveScroll:true}),q=s=>host.querySelector(s);
    function message(text,bad=false){current().toast(text,bad?"error":"success");}
    function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement("a");a.href=url;a.download=name;host.append(a);a.click();a.remove();bag.urls.set(url,setTimeout(()=>{URL.revokeObjectURL(url);bag.urls.delete(url);},1000));}
    function updateDraft(event){
      const f=event.target.closest("[data-hha-practice],[data-hha-conversation],[data-hha-weekly]");if(!f)return;const s=read(),a=s.learningOS.academy;
      if(f.hasAttribute("data-hha-practice")){const id=s.activeLesson,row=a.practice[id]||{attempts:0,correct:0,drafts:{}};row.drafts={...row.drafts,[a.exerciseType]:Object.fromEntries(new FormData(f))};a.practice[id]=row;}
      if(f.hasAttribute("data-hha-conversation")){const row=a.conversation[a.scenarioId]||{replies:[],history:[]};row.draft=f.elements.answer.value;a.conversation[a.scenarioId]=row;}
      if(f.hasAttribute("data-hha-weekly"))a.weekly={...a.weekly,...Object.fromEntries(new FormData(f))};save(s);
    }
    const input=e=>updateDraft(e);
    const change=e=>{
      const s=read(),a=s.learningOS.academy;if(e.target.matches("[data-hha-sound]")){a.soundId=e.target.value;save(s);render();}
      if(e.target.matches("[data-hha-scenario]")){a.scenarioId=e.target.value;save(s);render();}
      if(e.target.matches("[data-hha-writing-check]")){const level=current().context.selectedLevelId(s),row=a.writing[level]||{versions:[],checklist:[]},i=Number(e.target.dataset.hhaWritingCheck);row.checklist=e.target.checked?[...new Set([...(row.checklist||[]),i])]:(row.checklist||[]).filter(v=>v!==i);a.writing[level]=row;save(s);}
      if(e.target.matches("[data-hha-version]")){const row=a.writing[current().context.selectedLevelId(s)]||{};q("[data-hha-before]").textContent=row.versions?.[Number(e.target.value)]?.body||"";}
      updateDraft(e);
    };
    const click=async e=>{
      const b=e.target.closest("[data-hha-action]");if(!b||bag.busy)return;e.preventDefault();e.stopPropagation();const action=b.dataset.hhaAction,r=current(),s=read(),a=s.learningOS.academy,level=r.context.selectedLevelId(s),template=core.writingTemplates.find(t=>t.id===level),draft=s.writingDrafts?.[level]||s.writingDraft||"";
      try{
        if(action==="type"){a.exerciseType=b.dataset.type;save(s);render();}
        if(action==="tile"){const f=b.closest("form"),t=core.task(r.context.getLesson(s.activeLesson),f.dataset.taskType),item=t.tiles.find(i=>i.id===b.dataset.id);f.elements.answer.value=(f.elements.answer.value+" "+item.word).trim();f.elements.answer.dispatchEvent(new Event("input",{bubbles:true}));f.elements.answer.focus();}
        if(action==="clear-order"){const f=b.closest("form");f.elements.answer.value="";f.elements.answer.dispatchEvent(new Event("input",{bubbles:true}));}
        if(action==="outline"){s.writingDrafts=s.writingDrafts||{};s.writingDrafts[level]=(draft?draft+"\n\n":"")+template.outline.join("\n");if(level==="A0")s.writingDraft=s.writingDrafts[level];save(s);render();message("Đã thêm dàn ý vào bản nháp, không tự viết bài thay bạn.");}
        if(action==="writing-check"){const f=core.writingFeedback(draft,template);q("[data-hha-writing-feedback]").textContent=f.words+" từ, "+f.paragraphs+" đoạn. "+(f.lengthSuggested?"Đạt gợi ý độ dài.":"Độ dài gợi ý: ít nhất "+template.min+" từ.")+" "+f.disclaimer;}
        if(action==="version-save"||action==="version-restore"){
          if(!draft.trim()&&action==="version-save")throw Error("Chưa có nội dung.");const row=a.writing[level]||{versions:[],checklist:[]};if(row.versions?.some(v=>v.body===draft)&&action==="version-save"){message("Bản này đã có trong lịch sử.");return;}const selected=q("[data-hha-version]")?.value,chosen=row.versions?.[Number(selected)];if(action==="version-restore"&&(!selected||!chosen))throw Error("Chọn phiên bản.");
          row.versions=[{body:draft,words:core.writingFeedback(draft,template).words,at:new Date().toISOString()},...(row.versions||[])].slice(0,20);a.writing[level]=row;core.boundVersions(a.writing);
          if(action==="version-restore"){s.writingDrafts[level]=chosen.body;if(level==="A0")s.writingDraft=chosen.body;}save(s);render();message("Đã giữ phiên bản trên thiết bị; trạng thái đồng bộ được báo riêng.");
        }
        if(action==="writing-export")download(draft,"HH-English-"+level+".txt","text/plain;charset=utf-8");
        if(action==="conversation-export"){const scenario=core.conversations.find(c=>c.id===a.scenarioId),record=a.conversation[scenario.id]||{};download((record.replies||[]).map((text,i)=>"Script: "+scenario.turns[i]+"\nYou: "+text).join("\n\n"),"HH-English-roleplay.txt","text/plain;charset=utf-8");}
        if(action==="conversation-restart"){const row=a.conversation[a.scenarioId]||{};a.conversation[a.scenarioId]={replies:[],draft:"",history:[{replies:row.replies||[],at:new Date().toISOString()},...(row.history||[])].slice(0,10)};save(s);render();}
        if(action==="backup")download(JSON.stringify({version:1,data:s},null,2),"HH-English-device.json","application/json");
        if(action==="group"){save(s);if(root.HHApp?.navigate)root.HHApp.navigate("/learn/study-together");else location.hash="#/learn/study-together";}
        if(action==="share"){const url=new URL(location.href);url.hash="/english/lesson?lesson="+encodeURIComponent(s.activeLesson);q("[data-hha-share]").textContent=url.href+" · Chỉ chia sẻ ID bài gốc, không có tiến độ/ghi âm/token.";}
        if(action.startsWith("sync-")){bag.busy=true;host.querySelectorAll('[data-hha-action^="sync-"]').forEach(n=>n.disabled=true);let result;
          if(action==="sync-retry")result=await r.sync.sync();
          if(action==="sync-preview"){const p=await r.sync.preview();q("[data-hha-remote-info]").textContent="Revision "+p.revision+" · "+p.completed+" bài đã lưu · "+p.words+" từ · "+new Date(p.updatedAt).toLocaleString("vi-VN");}
          if(action==="sync-local"||action==="sync-server")result=await r.sync.resolve(action==="sync-local"?"local":"server",q("[data-hha-sync-confirm]").checked);
          if(action==="sync-delete")result=await r.sync.deleteRemote(q("[data-hha-delete-profile]").value);
          if(action!=="sync-preview"){render();message(result?"Máy chủ đã xác nhận thao tác.":"Chưa được máy chủ xác nhận. Bản thiết bị vẫn được giữ.",!result);}
        }
      }catch(error){message(error.message,true);}finally{bag.busy=false;host.querySelectorAll('[data-hha-action^="sync-"]').forEach(n=>n.disabled=false);if(b.isConnected)b.disabled=false;}
    };
    const submit=e=>{
      const f=e.target;if(!f.matches("[data-hha-practice],[data-hha-conversation],[data-hha-mistake],[data-hha-weekly]"))return;e.preventDefault();e.stopPropagation();const r=current(),s=read(),a=s.learningOS.academy,v=Object.fromEntries(new FormData(f));
      if(f.hasAttribute("data-hha-weekly")){a.weekly={...v,at:new Date().toISOString()};save(s);message("Đã giữ kế hoạch tuần; không tự gửi thông báo.");return;}
      if(f.hasAttribute("data-hha-conversation")){const scenario=core.conversations.find(c=>c.id===a.scenarioId),row=a.conversation[scenario.id]||{replies:[],history:[]};if(!v.answer.trim()||v.answer.length>2000)return;row.replies=[...(row.replies||[]),v.answer.trim()].slice(0,scenario.turns.length);row.draft="";row.updatedAt=new Date().toISOString();a.conversation[scenario.id]=row;save(s);render();message("Đã lưu lời của bạn; chưa có chấm ngữ pháp/độ trôi chảy.");return;}
      if(f.hasAttribute("data-hha-mistake")){const row=s.learningOS.mistakeRecords.find(m=>m.id===f.dataset.hhaMistake),correct=core.normalize(v.answer)===core.normalize(row.expected);row.retryEvidence={answer:v.answer,correct,method:"saved-answer-comparison",at:new Date().toISOString()};if(correct){row.status="resolved";row.resolvedBy="assessed-retry";}else row.nextReviewAt=new Date().toISOString();save(s);f.querySelector("output").textContent=correct?"Khớp đáp án đã lưu; đã ghi nhận lượt sửa lỗi.":"Chưa khớp. "+row.explanation;return;}
      const lesson=r.context.getLesson(s.activeLesson),t=core.task(lesson,f.dataset.taskType),answer=t.type==="match"?t.pairs.map(p=>({id:p.id,value:v["pair-"+p.id]})):v.answer,result=core.evaluate(t,answer),row=a.practice[lesson.id]||{attempts:0,correct:0,drafts:{}};
      row.attempts++;if(result.correct)row.correct++;row.last={type:t.type,answer,correct:result.correct,at:new Date().toISOString()};row.drafts={...row.drafts,[t.type]:v};a.practice[lesson.id]=row;s.learningOS.reviewAttempts.unshift({id:"academy-"+Date.now(),lessonId:lesson.id,type:t.type,correct:result.correct,score:result.score,graded:true,method:result.method,at:new Date().toISOString()});s.learningOS.reviewAttempts=s.learningOS.reviewAttempts.slice(0,1000);
      if(!result.correct)root.HHEnglishLearningOS.recordMistake(s,{type:t.type,prompt:t.prompt,answer:typeof answer==="string"?answer:JSON.stringify(answer),expected:result.expected,explanation:result.explanation,lessonId:lesson.id});save(s);f.querySelector("output").textContent=(result.correct?"Đúng. ":"Chưa đúng. Đáp án đối chiếu: "+result.expected+". ")+result.explanation;
    };
    bag.handlers={click,input,change,submit};host.addEventListener("click",click,true);host.addEventListener("input",input);host.addEventListener("change",change);host.addEventListener("submit",submit,true);
  }
  function unbind(host){const bag=bindings.get(host);if(!bag)return;for(const[type,fn]of Object.entries(bag.handlers))host.removeEventListener(type,fn,type==="click"||type==="submit");for(const[url,timer]of bag.urls){clearTimeout(timer);URL.revokeObjectURL(url);}bindings.delete(host);}
  root.HHEnglishAcademy=Object.freeze({exercise,writing,supplement,bind,unbind});
})(window);
