(() => {
  "use strict";
  const stateKey = "hh-feature-engine-state";
  const readState = () => { try { return JSON.parse(localStorage.getItem(stateKey) || "{}"); } catch { return {}; } };
  const writeState = value => localStorage.setItem(stateKey, JSON.stringify(value));
  const download = (name, content, type = "text/plain") => { const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([content], { type })); a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000); };
  const fileText = accept => new Promise((resolve, reject) => { const picker = document.createElement("input"); picker.type = "file"; picker.accept = accept; picker.onchange = () => { const file = picker.files?.[0]; if (!file) return reject(new Error("Chưa chọn file")); const reader = new FileReader(); reader.onload = () => resolve({ file, value: reader.result }); reader.onerror = reject; reader.readAsText(file); }; picker.click(); });
  const imageFile = () => new Promise((resolve, reject) => { const picker = document.createElement("input"); picker.type = "file"; picker.accept = "image/*"; picker.onchange = () => { const file = picker.files?.[0]; if (!file) return reject(new Error("Chưa chọn ảnh")); const img = new Image(); img.onload = () => resolve({ file, img }); img.onerror = reject; img.src = URL.createObjectURL(file); }; picker.click(); });
  const listFeatures = new Set(["History Manager","Favorite Manager","AI Prompt Library","Workspace Tabs","Widget Marketplace","Plugin System","Version History","File Explorer","Notes","Todo","Kanban","Calendar","Reminder","Clipboard Manager","Clipboard History","Activity Timeline","Recent Files","Pinned Tools","Bookmark","Notification Center","User Preferences Center","Settings Center","Keyboard Shortcut System"]);
  const monitorFeatures = new Set(["System Status","Network Speed","FPS Monitor","Memory Usage","Storage Usage","Analytics Dashboard","Error Monitor","Console Log Viewer"]);
  const designFeatures = new Set(["Color Studio","Color Picker","Gradient Generator","Typography Studio","Icon Browser","SVG Editor"]);
  const aiPromptFeatures = new Set(["AI Prompt Optimizer","AI Image Prompt Generator","AI Prompt Library"]);
  const outputList = (name, input) => { const store = readState(); const items = input.split(/\n+/).map(x => x.trim()).filter(Boolean); store[name] = { items, updatedAt: new Date().toISOString() }; writeState(store); return `${name}: ${items.length} mục\n\n${items.map((x, i) => `${i + 1}. ${x}`).join("\n") || "Danh sách trống"}`; };
  const systemReport = async name => { let storage = "Không hỗ trợ"; if (navigator.storage?.estimate) { const e = await navigator.storage.estimate(); storage = `${((e.usage || 0) / 1048576).toFixed(2)} / ${((e.quota || 0) / 1048576).toFixed(0)} MB`; } return `${name}\nOnline: ${navigator.onLine}\nViewport: ${innerWidth}×${innerHeight}\nCPU: ${navigator.hardwareConcurrency || "N/A"} cores\nMemory: ${navigator.deviceMemory || "N/A"} GB\nStorage: ${storage}\nConnection: ${navigator.connection?.effectiveType || "N/A"}\nTime: ${new Date().toLocaleString("vi-VN")}`; };
  const optimizePrompt = (input, image = false) => image ? `Create a ${input || "cinematic"} image. Subject clearly separated from background, professional composition, realistic lighting, high detail, coherent colors, no watermark, no malformed anatomy. Include camera angle, lens, mood, palette, environment and negative prompt.` : `VAI TRÒ\nBạn là chuyên gia phù hợp nhất với nhiệm vụ.\n\nMỤC TIÊU\n${input || "Nêu mục tiêu cụ thể"}\n\nQUY TRÌNH\n1. Phân tích yêu cầu và nêu giả định.\n2. Thực hiện theo từng bước.\n3. Kiểm tra độ chính xác và khả năng áp dụng.\n\nRÀNG BUỘC\nKhông bịa dữ kiện; chỉ rõ phần chưa chắc chắn.\n\nĐẦU RA\nTrình bày rõ ràng, có ví dụ và checklist hành động.`;
  const run = async (name, input, output) => {
    if (listFeatures.has(name)) return outputList(name, input);
    if (monitorFeatures.has(name)) return systemReport(name);
    if (aiPromptFeatures.has(name)) return optimizePrompt(input, name === "AI Image Prompt Generator");
    if (name === "Global Search" || name === "Smart Search" || name === "Command Palette++") { const q = input.trim().toLowerCase(); const found = [...document.querySelectorAll("[data-module-id]")].map(x => ({ id: x.dataset.moduleId, text: x.textContent.trim().replace(/\s+/g, " ") })).filter(x => !q || x.text.toLowerCase().includes(q)).slice(0, 30); return `${found.length} kết quả\n${found.map(x => `• ${x.id}: ${x.text.slice(0, 120)}`).join("\n")}`; }
    if (name === "Dark Light Auto Mode") { const mode = /light/i.test(input) ? "light" : /auto/i.test(input) ? "normal" : "dark"; document.documentElement.style.colorScheme = mode; localStorage.setItem("hh-color-mode", mode); return `Đã áp dụng chế độ ${mode}.`; }
    if (name === "Theme Color Switcher") { const color = input.trim() || "#00e5ff"; if (!/^#[0-9a-f]{6}$/i.test(color)) throw new Error("Nhập màu HEX dạng #00e5ff"); document.documentElement.style.setProperty("--accent", color); localStorage.setItem("hh-theme-color", color); return `Đã áp dụng màu ${color}.`; }
    if (name === "Realtime Notification") { if (!("Notification" in window)) throw new Error("Trình duyệt không hỗ trợ Notification"); const permission = await Notification.requestPermission(); if (permission === "granted") new Notification("HH Platform", { body: input || "Thông báo realtime đang hoạt động." }); return `Quyền thông báo: ${permission}`; }
    if (name === "Text To Speech") { speechSynthesis.cancel(); const voice = new SpeechSynthesisUtterance(input || "HH Platform đã sẵn sàng"); voice.lang = "vi-VN"; speechSynthesis.speak(voice); return "Đang đọc văn bản bằng giọng hệ thống."; }
    if (name === "Speech To Text" || name === "Voice Search") { const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!Recognition) throw new Error("Trình duyệt này chưa hỗ trợ nhận dạng giọng nói"); return new Promise((resolve, reject) => { const rec = new Recognition(); rec.lang = "vi-VN"; rec.onresult = e => resolve(e.results[0][0].transcript); rec.onerror = e => reject(new Error(e.error)); rec.start(); }); }
    if (name === "Export Data") { const data = JSON.stringify(Object.fromEntries(Object.keys(localStorage).map(k => [k, localStorage.getItem(k)])), null, 2); download("hh-platform-backup.json", data, "application/json"); return "Đã xuất toàn bộ dữ liệu local."; }
    if (name === "Import Data") { const { value } = await fileText("application/json,.json"); const data = JSON.parse(value); Object.entries(data).forEach(([k, v]) => localStorage.setItem(k, typeof v === "string" ? v : JSON.stringify(v))); return `Đã nhập ${Object.keys(data).length} khóa dữ liệu.`; }
    if (["PWA","Offline Mode"].includes(name)) { const reg = await navigator.serviceWorker?.getRegistration(); return `Service Worker: ${reg ? "đã đăng ký" : "chưa đăng ký"}\nOnline: ${navigator.onLine}\nCache API: ${"caches" in window ? "có" : "không"}`; }
    if (name === "Install App") { window.dispatchEvent(new CustomEvent("hh:request-install")); return "Nếu trình duyệt hỗ trợ, hộp thoại cài đặt sẽ xuất hiện; nếu không, dùng menu › Cài đặt ứng dụng."; }
    if (name === "Focus Mode") { document.body.classList.toggle("focus-mode"); return `Focus Mode: ${document.body.classList.contains("focus-mode") ? "bật" : "tắt"}`; }
    if (name === "Loading Skeleton") { document.body.classList.add("is-loading"); setTimeout(() => document.body.classList.remove("is-loading"), 1600); return "Đã chạy skeleton trong 1,6 giây."; }
    if (name === "Page Progress Bar") { scrollTo({ top: document.body.scrollHeight, behavior: "smooth" }); return "Thanh tiến độ trang đang theo dõi vị trí cuộn."; }
    if (/JSON/.test(name)) return JSON.stringify(JSON.parse(input), null, 2);
    if (name === "Markdown Editor") return input.replace(/^### (.+)$/gm, "<h3>$1</h3>").replace(/^## (.+)$/gm, "<h2>$1</h2>").replace(/^# (.+)$/gm, "<h1>$1</h1>").replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>").replace(/\n/g, "<br>");
    if (name === "Regex Playground") { const [pattern, replacement = "", ...lines] = input.split("\n"); const re = new RegExp(pattern, "gmi"), text = lines.join("\n"), matches = [...text.matchAll(re)]; return `Match: ${matches.length}\nThay thế:\n${text.replace(re, replacement)}\n\n${matches.map((m, i) => `${i + 1}. ${m[0]} @${m.index}`).join("\n")}`; }
    if (name === "API Tester") { const [first, ...body] = input.split("\n"), parts = first.trim().split(/\s+/), method = parts.length > 1 ? parts.shift().toUpperCase() : "GET", url = parts.join(" ") || first; const res = await fetch(url, { method, headers: { "Content-Type": "application/json" }, ...(body.length && method !== "GET" ? { body: body.join("\n") } : {}) }); return `HTTP ${res.status}\n${await res.text()}`; }
    if (name === "GitHub Integration") { const repo = input.trim() || "hoangdaika13/hoangdaika13.github.io", res = await fetch(`https://api.github.com/repos/${repo}`), data = await res.json(); if (!res.ok) throw new Error(data.message); return `${data.full_name}\nStars: ${data.stargazers_count}\nForks: ${data.forks_count}\nIssues: ${data.open_issues_count}\nUpdated: ${data.updated_at}`; }
    if (name === "Base64 Encoder") return `Encode: ${btoa(unescape(encodeURIComponent(input)))}\nDecode (nếu hợp lệ): ${(() => { try { return decodeURIComponent(escape(atob(input))); } catch { return "N/A"; } })()}`;
    if (name === "Hash Generator") return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(input))), x => x.toString(16).padStart(2, "0")).join("");
    if (name === "UUID Generator") return `${crypto.randomUUID()}\n${crypto.randomUUID()}`;
    if (name === "Timestamp Converter") { const d = input ? (/^\d+$/.test(input) ? new Date(Number(input) * 1000) : new Date(input)) : new Date(); if (isNaN(d)) throw new Error("Thời gian không hợp lệ"); return `ISO: ${d.toISOString()}\nUnix: ${Math.floor(d / 1000)}\nLocal: ${d.toLocaleString("vi-VN")}`; }
    if (name === "Calculator") { if (!/^[\d\s+\-*/().%]+$/.test(input)) throw new Error("Biểu thức không hợp lệ"); return String(Function(`"use strict";return (${input})`)()); }
    if (name === "Unit Converter") { const [value, from, to] = input.trim().split(/\s+/); const n = Number(value), factors = { m: 1, km: 1000, cm: .01, mm: .001, kg: 1, g: .001 }; if (!(from in factors) || !(to in factors)) throw new Error("Ví dụ: 5 km m hoặc 1200 g kg"); return `${n} ${from} = ${n * factors[from] / factors[to]} ${to}`; }
    if (name === "Lorem Ipsum") return Array(Math.max(1, Math.min(20, Number(input) || 3))).fill("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.").join("\n\n");
    if (name === "Password Toolkit") { const chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%&*", length = Math.max(12, Math.min(128, Number(input) || 24)); return Array.from(crypto.getRandomValues(new Uint32Array(length)), x => chars[x % chars.length]).join(""); }
    if (designFeatures.has(name)) { const color = (input.match(/#[0-9a-f]{6}/i) || ["#00e5ff"])[0]; return `${name}\nPrimary: ${color}\nGradient: linear-gradient(135deg, ${color}, #ff3bd1)\nContrast target: WCAG AA ≥ 4.5:1`; }
    if (["Image Compressor","Image Converter","Image Toolkit"].includes(name)) { const { file, img } = await imageFile(), canvas = document.createElement("canvas"), max = Math.max(64, Math.min(2400, Number(input) || 1400)), scale = Math.min(1, max / Math.max(img.width, img.height)); canvas.width = Math.round(img.width * scale); canvas.height = Math.round(img.height * scale); canvas.getContext("2d").drawImage(img, 0, 0, canvas.width, canvas.height); const blob = await new Promise(r => canvas.toBlob(r, "image/webp", .82)); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = `${file.name.replace(/\.[^.]+$/, "")}.webp`; a.click(); return `Đã chuyển ${file.name}\n${img.width}×${img.height} → ${canvas.width}×${canvas.height}\n${file.size} → ${blob.size} bytes`; }
    if (name === "QR Toolkit") { const url = `https://quickchart.io/qr?size=300&text=${encodeURIComponent(input || location.href)}`; window.open(url, "_blank", "noopener"); return `Đã tạo QR:\n${url}`; }
    if (["Pomodoro","Stopwatch","Countdown"].includes(name)) { clearInterval(window.__hhFeatureTimer); let seconds = name === "Pomodoro" ? 1500 : Number(input) || 60; window.__hhFeatureTimer = setInterval(() => { seconds += name === "Stopwatch" ? 1 : -1; output.textContent = `${Math.floor(Math.abs(seconds) / 60).toString().padStart(2, "0")}:${(Math.abs(seconds) % 60).toString().padStart(2, "0")}`; if (seconds <= 0 && name !== "Stopwatch") clearInterval(window.__hhFeatureTimer); }, 1000); return "Đã bắt đầu bộ đếm."; }
    if (name === "Weather Widget") { const [lat = "21.0285", lon = "105.8542"] = input.split(/[,\s]+/); const res = await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${encodeURIComponent(lat)}&longitude=${encodeURIComponent(lon)}&current=temperature_2m,wind_speed_10m,weather_code`), data = await res.json(); return `Nhiệt độ: ${data.current?.temperature_2m}°C\nGió: ${data.current?.wind_speed_10m} km/h\nWeather code: ${data.current?.weather_code}`; }
    if (name === "Clock") return new Date().toLocaleString("vi-VN", { dateStyle: "full", timeStyle: "medium" });
    if (name === "Multi-language" || name === "Language Switcher") { const lang = /en/i.test(input) ? "en" : "vi"; document.documentElement.lang = lang; localStorage.setItem("hh-language", lang); return `Ngôn ngữ giao diện: ${lang}`; }
    if (name === "Clipboard History") { const text = await navigator.clipboard.readText(); const store = readState(); store[name] = { items: [text, ...(store[name]?.items || [])].slice(0, 20) }; writeState(store); return store[name].items.join("\n---\n"); }
    if (name === "AI Chat Assistant") throw new Error("AI Chat cần API key/model hợp lệ. Hãy dùng AI Center và cấu hình API thay vì trả lời giả.");
    if (["OCR","PDF Toolkit","QR Scanner","Monaco Code Editor"].includes(name)) throw new Error(`${name} cần thư viện xử lý chuyên dụng chưa được tải. Chức năng không báo thành công giả.`);
    throw new Error(`${name} chưa có engine riêng. Không tạo kết quả giả.`);
  };
  document.addEventListener("click", async event => {
    const button = event.target.closest(".feature-lab [data-lab-run]");
    if (!button) return;
    event.preventDefault(); event.stopImmediatePropagation();
    const root = button.closest(".feature-lab"), name = root.querySelector("[data-lab-title]")?.textContent.trim(), input = root.querySelector("[data-lab-input]")?.value || "", output = root.querySelector("[data-lab-output]");
    output.textContent = `Đang chạy ${name}...`;
    try { output.textContent = await run(name, input, output); } catch (error) { output.textContent = `Không thể chạy: ${error.message}`; }
  }, true);
})();
