(() => {
  "use strict";

  const global = typeof window !== "undefined" ? window : globalThis;
  const legacy = global.HHJapanese;
  const v3 = global.HHJapaneseOSV3;
  const sourcePack = global.HHJapaneseVocabularyV4;
  const vietnamesePack = global.HHJapaneseVietnamesePack;
  if (!legacy?.mount || !sourcePack?.words?.length) return;

  const VERSION = 4;
  const BASE_KEY = "hh.japanese.os.v4";
  const PROFILE_KEY = "hh.japanese.learners.v4";
  const MAIN_TABS = Object.freeze([
    ["today", "Hôm nay", "今"], ["paths", "Lộ trình", "道"], ["practice", "Luyện tập", "練"],
    ["lookup", "Tra cứu", "辞"], ["immersion", "Immersion", "読"], ["progress", "Tiến độ", "進"]
  ]);
  const PATHS = Object.freeze([
    { id: "jlpt", icon: "試", title: "JLPT N5–N1", detail: "Từ vựng · ngữ pháp · đọc · nghe", color: "#ff7078" },
    { id: "jf", icon: "話", title: "JF A1–C2", detail: "Năng lực giao tiếp Can-do thực tế", color: "#58d9ff" },
    { id: "life", icon: "日", title: "Life in Japan", detail: "Sinh hoạt · thủ tục · y tế · giao thông", color: "#77e6ad" },
    { id: "career", icon: "職", title: "Career Japanese", detail: "Công việc · chuyên ngành · kính ngữ", color: "#c58cff" }
  ]);
  const PRACTICE_TOOLS = Object.freeze([
    ["conversation", "Hội thoại", "会"], ["writing", "Luyện viết", "書"], ["srs", "SRS V3", "復"],
    ["grammar", "Ngữ pháp", "文"], ["mora", "Mora", "音"]
  ]);
  const LOOKUP_TOOLS = Object.freeze([["dictionary", "Từ điển"], ["packs", "Gói dữ liệu"], ["kanji", "Kanji Graph"], ["utilities", "Công cụ"]]);
  const PROGRESS_TOOLS = Object.freeze([["dual", "Bản đồ kép"], ["teacher", "Giáo viên"], ["family", "Gia đình"], ["data", "Nguồn dữ liệu"]]);

  const CONTEXTS = Object.freeze([
    { id:"restaurant", track:"life", icon:"食", title:"Nhà hàng", phrases:[["おすすめは何ですか。","Món được đề xuất là gì?"],["これは辛いですか。","Món này có cay không?"],["アレルギーがあります。","Tôi bị dị ứng."],["お会計をお願いします。","Cho tôi thanh toán."],["肉を使わない料理はありますか。","Có món nào không dùng thịt không?"]] },
    { id:"station", track:"life", icon:"駅", title:"Ga tàu", phrases:[["この電車は新宿に行きますか。","Tàu này có đi Shinjuku không?"],["乗り換えはどこですか。","Chuyển tàu ở đâu?"],["切符をなくしました。","Tôi làm mất vé."],["電車が遅れています。","Tàu đang bị trễ."],["東口はどこですか。","Cửa đông ở đâu?"]] },
    { id:"hospital", track:"life", icon:"医", title:"Bệnh viện", phrases:[["昨日から頭が痛いです。","Tôi đau đầu từ hôm qua."],["熱があります。","Tôi bị sốt."],["この薬は一日何回飲みますか。","Thuốc này uống mấy lần mỗi ngày?"],["保険証を持っています。","Tôi có thẻ bảo hiểm."],["息が苦しいです。","Tôi khó thở."]] },
    { id:"cityhall", track:"life", icon:"役", title:"Tòa thị chính", phrases:[["住民票を取りたいです。","Tôi muốn lấy giấy cư trú."],["この申請書に記入します。","Tôi sẽ điền đơn này."],["必要な書類は何ですか。","Cần giấy tờ gì?"],["住所を変更したいです。","Tôi muốn đổi địa chỉ."],["受付は何階ですか。","Quầy tiếp nhận ở tầng mấy?"]] },
    { id:"rent", track:"life", icon:"家", title:"Thuê nhà", phrases:[["初期費用はいくらですか。","Chi phí ban đầu bao nhiêu?"],["契約期間を確認したいです。","Tôi muốn xác nhận thời hạn hợp đồng."],["エアコンが故障しました。","Điều hòa bị hỏng."],["更新料はかかりますか。","Có phí gia hạn không?"],["駅から徒歩何分ですか。","Đi bộ từ ga mất bao nhiêu phút?"]] },
    { id:"delivery", track:"career", icon:"配", title:"Giao nhận", phrases:[["荷物がまだ届いていません。","Hàng vẫn chưa đến."],["配達先を変更できますか。","Có thể đổi nơi giao không?"],["商品が違います。","Sản phẩm bị giao nhầm."],["受取時間を指定したいです。","Tôi muốn chọn giờ nhận."],["追跡番号を教えてください。","Vui lòng cho biết mã theo dõi."]] },
    { id:"meeting", track:"career", icon:"議", title:"Cuộc họp", phrases:[["進捗を報告します。","Tôi xin báo cáo tiến độ."],["締め切りを確認させてください。","Cho tôi xác nhận hạn chót."],["この案についてどう思いますか。","Bạn nghĩ sao về phương án này?"],["資料を共有しました。","Tôi đã chia sẻ tài liệu."],["次の対応を決めましょう。","Hãy quyết định bước xử lý tiếp theo."]] },
    { id:"customer", track:"career", icon:"客", title:"Khách hàng", phrases:[["ご不便をおかけして申し訳ございません。","Thành thật xin lỗi vì sự bất tiện."],["状況を確認いたします。","Tôi sẽ kiểm tra tình hình."],["担当者におつなぎします。","Tôi sẽ nối máy với người phụ trách."],["ご希望をお聞かせください。","Vui lòng cho biết mong muốn."],["本日中にご連絡いたします。","Chúng tôi sẽ liên hệ trong hôm nay."]] },
    { id:"school", track:"life", icon:"学", title:"Trường học", phrases:[["授業について質問があります。","Tôi có câu hỏi về tiết học."],["宿題を提出します。","Tôi nộp bài tập."],["保護者面談を予約したいです。","Tôi muốn đặt lịch họp phụ huynh."],["欠席の理由を説明します。","Tôi sẽ giải thích lý do nghỉ."],["進路について相談したいです。","Tôi muốn trao đổi về định hướng."]] },
    { id:"disaster", track:"life", icon:"災", title:"Khẩn cấp", phrases:[["避難所はどこですか。","Nơi sơ tán ở đâu?"],["地震が発生しました。","Đã xảy ra động đất."],["非常口を確認してください。","Hãy kiểm tra lối thoát hiểm."],["家族と連絡が取れません。","Tôi không liên lạc được với gia đình."],["水と食料を備蓄しています。","Tôi có dự trữ nước và thực phẩm."]] }
  ]);
  const VARIANTS = Object.freeze([
    ["A1","Nhận diện từ khóa"], ["A1","Chọn phản hồi"], ["A2","Nói theo mẫu"], ["A2","Thêm thông tin"],
    ["B1","Xử lý thay đổi"], ["B1","Dùng cách lịch sự"], ["B2","Giải thích lý do"], ["C1","Phản hồi tự nhiên"]
  ]);
  const MISSIONS = Object.freeze(CONTEXTS.flatMap((context) => context.phrases.flatMap(([answer, vi], phraseIndex) => VARIANTS.map(([level, variant], variantIndex) => ({
    id:`${context.id}-${phraseIndex + 1}-${variantIndex + 1}`, contextId:context.id, track:context.track, paths:["jlpt","jf",context.track],
    icon:context.icon, context:context.title, jfLevel:level, title:`${context.title} · ${variant}`, prompt:vi, answer, variant, source:"HH Japanese tự biên soạn"
  })))));

  const CONVERSATIONS = Object.freeze(CONTEXTS.map((context, index) => {
    const [answer, meaning] = context.phrases[index % context.phrases.length];
    const distractor = CONTEXTS[(index + 3) % CONTEXTS.length].phrases[0][0];
    return { id:context.id, icon:context.icon, title:context.title, prompt:meaning, expected:answer, options:[
      { text:answer, ok:true, note:"Phù hợp với tình huống và mức lịch sự." },
      { text:distractor, ok:false, note:"Câu đúng tiếng Nhật nhưng không đúng tình huống." },
      { text:"わかりません。", ok:false, note:"Có thể dùng khi chưa hiểu, nhưng chưa giải quyết nhiệm vụ." }
    ] };
  }));
  const WRITING_TASKS = Object.freeze([
    {id:"kana",label:"Kana từng nét",prompt:"Viết hoặc gõ: ありがとうございます",sample:"ありがとうございます"},
    {id:"kanji",label:"Kanji & thành phần",prompt:"Viết một câu có 日本語 và 学ぶ",sample:"日本語を学んでいます。"},
    {id:"sentence",label:"Câu từ gợi ý",prompt:"Dùng 駅・行く・明日 để tạo câu.",sample:"明日、駅に行きます。"},
    {id:"diary",label:"Nhật ký 3–5 câu",prompt:"Viết ngắn về hôm nay bằng thể lịch sự.",sample:"今日は仕事をしました。"},
    {id:"email",label:"Email công việc",prompt:"Viết email xin xác nhận lịch họp.",sample:"お世話になっております。会議の時間を確認させてください。"},
    {id:"resume",label:"履歴書",prompt:"Giới thiệu kinh nghiệm làm việc trong 2–3 câu.",sample:"ウェブ開発を三年間担当しました。"},
    {id:"message",label:"Tin nhắn lịch sự",prompt:"Xin phép đến muộn 10 phút.",sample:"申し訳ありません。10分ほど遅れます。"},
    {id:"essay",label:"Bài luận JLPT",prompt:"Viết ý kiến ngắn về học trực tuyến.",sample:"オンライン学習には時間を有効に使える利点があります。"}
  ]);
  const IMMERSION = Object.freeze([
    {id:"story",icon:"物",title:"Truyện ngắn",level:"A1",sentences:[["朝、駅で小さな猫を見つけました。","Buổi sáng, tôi thấy một chú mèo nhỏ ở ga."],["猫は静かに私を見ていました。","Chú mèo lặng lẽ nhìn tôi."]]},
    {id:"news",icon:"新",title:"Tin dễ đọc",level:"A2",sentences:[["市は新しい図書館を来月開きます。","Thành phố sẽ mở thư viện mới vào tháng sau."],["図書館には外国語の本もあります。","Thư viện cũng có sách ngoại ngữ."]]},
    {id:"life",icon:"生",title:"Đời sống",level:"A1",sentences:[["ごみは曜日ごとに分けて出します。","Rác được phân loại và đem ra theo từng ngày."],["収集時間を確認してください。","Hãy kiểm tra giờ thu gom."]]},
    {id:"podcast",icon:"聴",title:"Podcast chậm",level:"A2",sentences:[["今日は日本の朝ご飯について話します。","Hôm nay chúng ta nói về bữa sáng Nhật Bản."],["ご飯とみそ汁を食べる人が多いです。","Nhiều người ăn cơm và súp miso."]]},
    {id:"subtitle",icon:"幕",title:"Subtitle video",level:"B1",sentences:[["予定が変わったので、もう一度確認しましょう。","Vì lịch đã thay đổi, chúng ta hãy xác nhận lại."],["詳しい情報は後で共有します。","Thông tin chi tiết sẽ được chia sẻ sau."]]},
    {id:"manga",icon:"漫",title:"Manga được phép",level:"A2",sentences:[["大丈夫、私に任せて。","Không sao, cứ giao cho tôi."],["でも、一人では危ないよ。","Nhưng một mình thì nguy hiểm đấy."]]},
    {id:"work",icon:"職",title:"Tài liệu công việc",level:"B1",sentences:[["作業前に安全確認を行ってください。","Hãy kiểm tra an toàn trước khi làm việc."],["問題があれば担当者に報告してください。","Nếu có vấn đề, hãy báo người phụ trách."]]},
    {id:"signs",icon:"標",title:"Biển báo & biểu mẫu",level:"A1",sentences:[["立入禁止","Cấm vào."],["こちらに住所と氏名を記入してください。","Hãy điền địa chỉ và họ tên vào đây."]]}
  ]);
  const CAREER_LABELS = Object.freeze({comp:"IT",med:"Điều dưỡng/Y tế",food:"Nhà hàng",archit:"Xây dựng",engr:"Kỹ thuật",civeng:"Xây dựng",mech:"Sản xuất",rail:"Logistics",bus:"Văn phòng",finc:"Tài chính",law:"Pháp lý",telec:"Viễn thông"});

  const qualityPriority = (row) => {
    if (/^(w|pack-)/.test(String(row.id || "")) && row.meaningLanguage !== "en") return 4;
    if (row.meaningLanguage === "vi") return 3;
    if (String(row.id || "").startsWith("jmdict-")) return 2;
    return 1;
  };
  const merged = new Map();
  for (const row of [...sourcePack.words, ...(vietnamesePack?.words || []), ...(legacy.words || [])]) {
    const key = `${row.word}\u0000${row.kana || ""}`;
    if (!merged.has(key) || qualityPriority(row) >= qualityPriority(merged.get(key))) merged.set(key, row);
  }
  const ALL_WORDS = Object.freeze([...merged.values()]);
  const LOCAL_WORDS = Object.freeze(ALL_WORDS.filter((row) => !String(row.id || "").startsWith("v4-")));
  const WORD_BY_ID = new Map(ALL_WORDS.map((row) => [row.id, row]));
  const SURFACE = new Map();
  for (const row of ALL_WORDS) if (row.word && row.word.length <= 14 && (!SURFACE.has(row.word) || qualityPriority(row) > qualityPriority(SURFACE.get(row.word)))) SURFACE.set(row.word, row);
  const MAX_SURFACE = 14;

  const esc = (value) => String(value ?? "").replace(/[&<>'"]/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
  const day = () => new Date().toISOString().slice(0, 10);
  const ownerId = () => { try { const user=global.HHAuthSession?.user?.()||JSON.parse(localStorage.getItem("hh-auth-user")||"{}");return String(user?.id||user?._id||"guest").replace(/[^a-z0-9_-]/gi,"").slice(0,80)||"guest";}catch{return"guest";} };
  const profilesKey = () => `${PROFILE_KEY}:${ownerId()}`;
  function profiles(){try{const saved=JSON.parse(localStorage.getItem(profilesKey())||"null");if(saved?.items?.length)return saved;}catch{}return {active:"default",items:[{id:"default",name:"Hồ sơ chính",mode:"adult"}]};}
  const learnerId = () => profiles().active || "default";
  const stateKey = () => `${BASE_KEY}:${ownerId()}:${learnerId()}`;
  const defaults = () => ({version:VERSION,activeTab:"today",path:"jf",practiceTool:"conversation",lookupTool:"dictionary",progressTool:"dual",jlptLevel:"N5",jfLevel:"A1",goal:"life",dailyMinutes:15,xp:0,streak:0,lastStudy:"",knownWords:{},cards:[],mistakes:[],missionProgress:{},conversationHistory:[],writingHistory:[],savedSentences:[],offlinePacks:{},classrooms:[],family:{enabled:false,dailyLimit:20,aiAllowed:false,publicRanking:false},furigana:true,immersionId:"story"});
  function readState(){try{const raw=JSON.parse(localStorage.getItem(stateKey())||"null");if(raw)return {...defaults(),...raw,cards:Array.isArray(raw.cards)?raw.cards:[],mistakes:Array.isArray(raw.mistakes)?raw.mistakes:[]};const old=JSON.parse(localStorage.getItem(`hh.japanese.os.v3:${ownerId()}`)||"null");const state=defaults();if(old){state.xp=Number(old.xp)||0;state.streak=Number(old.streak)||0;state.jlptLevel=old.jlptLevel||"N5";state.jfLevel=old.jfLevel||"A1";state.knownWords=old.knownWords||{};state.missionProgress=old.missionProgress||{};for(const id of Object.keys(old.savedWords||{}))state.cards.push(makeCard("word",id));}return state;}catch{return defaults();}}
  function write(){if(instance)localStorage.setItem(stateKey(),JSON.stringify({...instance.state,version:VERSION,cards:instance.state.cards.slice(-5000),mistakes:instance.state.mistakes.slice(-500),conversationHistory:instance.state.conversationHistory.slice(-200),writingHistory:instance.state.writingHistory.slice(-200),savedSentences:instance.state.savedSentences.slice(-500)}));}
  function study(xp=5){const s=instance.state,t=day();if(s.lastStudy!==t){const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);s.streak=s.lastStudy===yesterday?s.streak+1:1;s.lastStudy=t;}s.xp+=xp;}
  const checksum = (value) => {let hash=2166136261;for(const char of String(value)){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return(hash>>>0).toString(16).padStart(8,"0");};
  function makeCard(type,ref,payload={}){return {id:`${type}:${ref}`,type,ref,payload,status:"new",dueAt:new Date().toISOString(),interval:0,ease:2.5,lapses:0,createdAt:new Date().toISOString()};}
  function addCard(type,ref,payload={}){const id=`${type}:${ref}`,found=instance.state.cards.find((card)=>card.id===id);if(found)return found;const card=makeCard(type,ref,payload);instance.state.cards.push(card);write();return card;}
  function cardStatus(card){const due=Date.parse(card.dueAt||0)<=Date.now();if(card.lapses>1&&due)return"relearning";if(card.status==="mastered"&&!due)return"mastered";if(due&&card.interval>0)return"due";return card.status||"new";}
  function rateCard(card,rating){const now=Date.now(),dayMs=86400000;card.reviews=(card.reviews||0)+1;if(rating==="forget"){card.status="relearning";card.lapses=(card.lapses||0)+1;card.interval=0;card.dueAt=new Date(now+10*60000).toISOString();card.ease=Math.max(1.3,(card.ease||2.5)-.2);}if(rating==="hard"){card.status="hard";card.interval=Math.max(1,Math.round((card.interval||1)*1.2));card.dueAt=new Date(now+card.interval*dayMs).toISOString();}if(rating==="remember"){card.status="learning";card.interval=Math.max(3,Math.round((card.interval||1)*(card.ease||2.5)));card.dueAt=new Date(now+card.interval*dayMs).toISOString();}if(rating==="easy"){card.status="mastered";card.interval=Math.max(7,Math.round((card.interval||2)*(card.ease||2.5)*1.3));card.dueAt=new Date(now+card.interval*dayMs).toISOString();card.ease=Math.min(3.2,(card.ease||2.5)+.1);}write();}
  function addMistake(category,prompt,correct,actual,ref=""){const key=`${category}:${ref||prompt}`,found=instance.state.mistakes.find((row)=>row.key===key);if(found){found.count+=1;found.actual=actual;found.updatedAt=new Date().toISOString();}else instance.state.mistakes.push({key,category,prompt,correct,actual,count:1,updatedAt:new Date().toISOString(),resolved:false});addCard(category,ref||checksum(prompt),{prompt,correct});write();}
  function speak(text,rate=1){if(!global.speechSynthesis||!global.SpeechSynthesisUtterance)return false;global.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(String(text||""));utterance.lang="ja-JP";utterance.rate=rate;global.speechSynthesis.speak(utterance);return true;}
  function normalizeJapanese(value){return String(value||"").normalize("NFKC").replace(/[\s。、！？!?.,・「」『』（）()]/g,"");}
  function transcriptScore(expected,actual){if(legacy.scoreDictation)return legacy.scoreDictation(expected,actual);const a=normalizeJapanese(expected),b=normalizeJapanese(actual);if(!a||!b)return 0;let hits=0;for(const char of b)if(a.includes(char))hits++;return Math.min(100,Math.round(hits/Math.max(a.length,b.length)*100));}
  function toast(message,tone="success"){const node=instance?.host.querySelector("[data-hhj4-toast]");if(!node)return;node.textContent=message;node.dataset.tone=tone;node.hidden=false;clearTimeout(instance.toastTimer);instance.toastTimer=setTimeout(()=>node.hidden=true,3600);}
  function metric(label,value,detail){return `<article class="hhj4-metric"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(detail)}</small></article>`;}
  function statusOf(row){if (/^(w|pack-)/.test(String(row.id||""))&&row.meaningLanguage!=="en")return["Đã kiểm duyệt","reviewed"];if(row.reviewStatus==="source-derived"&&row.meaningLanguage==="vi")return["Đã kiểm tra nguồn · cần biên tập","checked"];return["Tự động từ nguồn mở · nghĩa Anh tham chiếu","automatic"];}
  const dueCards = () => instance.state.cards.filter((card)=>["new","due","hard","relearning"].includes(cardStatus(card)));
  const reviewedVietnamese = () => ALL_WORDS.filter((row)=>row.meaningLanguage==="vi"||(/^(w|pack-)/.test(String(row.id||""))&&row.meaningLanguage!=="en"));
  function packCatalog(){const viCount=reviewedVietnamese().length;return [{id:"vi-core",label:"Vietnamese Core",target:8000,count:viCount,status:"mixed",downloadable:true},...sourcePack.packs];}
  function careerCatalog(){const counts={};for(const row of sourcePack.words)for(const domain of row.domains||[])if(CAREER_LABELS[domain])counts[domain]=(counts[domain]||0)+1;return Object.entries(CAREER_LABELS).map(([id,label])=>({id,label,count:counts[id]||0})).filter((row)=>row.count);}

  function shell(content){const s=instance.state;return `<section class="hhj4-app">
    <header class="hhj4-top"><button data-hhj4-menu aria-label="Mở menu">☰</button><div class="hhj4-brand"><b>日</b><span><strong>HH Japanese OS</strong><small>V4 · 42K Open Language Lab</small></span></div><nav>${MAIN_TABS.map(([id,label])=>`<button data-hhj4-tab="${id}" class="${s.activeTab===id?"active":""}">${label}</button>`).join("")}</nav><div class="hhj4-status"><span>${ALL_WORDS.length.toLocaleString("vi-VN")} mục</span><i>JLPT ${esc(s.jlptLevel)}</i><i>JF ${esc(s.jfLevel)}</i></div><button data-hhj4-profile>Hồ sơ ▾</button></header>
    <div class="hhj4-body"><aside class="hhj4-rail">${MAIN_TABS.map(([id,label,icon],index)=>`<button data-hhj4-tab="${id}" class="${s.activeTab===id?"active":""}"><i>${icon}</i><span>${label}</span><kbd>${index+1}</kbd></button>`).join("")}<footer><b>${s.streak} ngày</b><span>${s.xp} XP · tự lưu</span></footer></aside><main class="hhj4-main">${content}</main></div>
    <div class="hhj4-toast" data-hhj4-toast role="status" hidden></div></section>`;}

  function todayView(){const s=instance.state,due=dueCards().length,next=MISSIONS.find((row)=>!s.missionProgress[row.id])||MISSIONS[0],mistake=s.mistakes.find((row)=>!row.resolved);return `<section class="hhj4-view hhj4-today"><header class="hhj4-hero"><div><small>HÔM NAY · ${day()}</small><h1>Một ngày, bốn việc rõ ràng.</h1><p>Học để hoàn thành nhiệm vụ thật; JLPT và JF được theo dõi độc lập.</p></div><div class="hhj4-ring"><strong>${Math.min(100,Object.keys(s.missionProgress).length)}%</strong><span>${s.dailyMinutes} phút/ngày</span></div></header><div class="hhj4-metrics">${metric("Kho đang dùng",ALL_WORDS.length.toLocaleString("vi-VN"),`${reviewedVietnamese().length.toLocaleString("vi-VN")} mục có nghĩa Việt`)}${metric("SRS đến hạn",due,"5 loại thẻ")}${metric("Mission",Object.keys(s.missionProgress).length,`trên ${MISSIONS.length} nhiệm vụ`)}${metric("Lỗi cần sửa",s.mistakes.filter(x=>!x.resolved).length,"Mistake Notebook")}</div><div class="hhj4-daily-grid">
    <article class="primary"><small>01 · CAN-DO MISSION</small><b>${next.icon}</b><h2>${esc(next.title)}</h2><p>${esc(next.prompt)}</p><button data-hhj4-open-mission="${next.id}">Bắt đầu nhiệm vụ →</button></article>
    <article><small>02 · SRS V3</small><b>復</b><h2>Ôn ${due} thẻ đến hạn</h2><p>Từ · collocation · câu · ngữ pháp · nghe chép.</p><button data-hhj4-open-practice="srs">Mở SRS</button></article>
    <article><small>03 · IMMERSION</small><b>読</b><h2>${IMMERSION[0].title}</h2><p>${IMMERSION[0].sentences[0][1]}</p><button data-hhj4-tab="immersion">Đọc và nghe</button></article>
    <article><small>04 · SỬA MỘT LỖI</small><b>誤</b><h2>${esc(mistake?.category||"Chưa có lỗi tồn đọng")}</h2><p>${esc(mistake?.prompt||"Lỗi từ mọi bài học sẽ tự xuất hiện tại đây.")}</p><button data-hhj4-open-practice="srs">${mistake?"Sửa ngay":"Xem sổ lỗi"}</button></article></div></section>`;}

  function pathsView(){const s=instance.state,path=PATHS.find((row)=>row.id===s.path)||PATHS[1],rows=MISSIONS.filter((row)=>row.paths.includes(path.id)),selected=rows.find((row)=>row.id===instance.missionId)||rows[0],completed=rows.filter((row)=>s.missionProgress[row.id]).length;return `<section class="hhj4-view"><header class="hhj4-section-head"><div><small>FOUR PARALLEL PATHS</small><h1>Bốn lộ trình, một hồ sơ tiến độ</h1><p>Không quy đổi JLPT thành JF tuyệt đối; nói và viết được theo dõi riêng.</p></div><span>${completed}/${rows.length} mission</span></header><div class="hhj4-path-grid">${PATHS.map((row)=>`<button data-hhj4-path="${row.id}" class="${row.id===path.id?"active":""}" style="--path:${row.color}"><i>${row.icon}</i><strong>${row.title}</strong><span>${row.detail}</span></button>`).join("")}</div><div class="hhj4-workspace"><aside class="hhj4-list"><header><b>${path.title}</b><span>${rows.length} nhiệm vụ tự biên soạn</span></header>${rows.slice(instance.missionPage*20,instance.missionPage*20+20).map((row)=>`<button data-hhj4-mission="${row.id}" class="${row.id===selected.id?"active":""}"><i>${row.icon}</i><span><strong>${esc(row.title)}</strong><small>JF ${row.jfLevel} · ${esc(row.context)}</small></span>${s.missionProgress[row.id]?"✓":""}</button>`).join("")}<footer><button data-hhj4-mission-page="prev">‹</button><span>${instance.missionPage+1}/${Math.ceil(rows.length/20)}</span><button data-hhj4-mission-page="next">›</button></footer></aside><article class="hhj4-mission"><header><span>${selected.icon}</span><div><small>JF ${selected.jfLevel} · ${path.title}</small><h2>${esc(selected.title)}</h2><p>${esc(selected.variant)}</p></div></header><section><small>TÌNH HUỐNG</small><h3>${esc(selected.prompt)}</h3></section><section class="hhj4-answer"><small>CÂU MỤC TIÊU</small><strong>${esc(selected.answer)}</strong><button data-hhj4-speak="${esc(selected.answer)}">▶ Nghe</button></section><ol><li>Nghe và nhận diện ý chính</li><li>Chọn hoặc nói phản hồi</li><li>Thay đổi một chi tiết</li><li>Hoàn thành Can-do</li><li>Đưa câu yếu vào SRS</li></ol><footer><button data-hhj4-save-sentence="${esc(selected.answer)}">＋ Lưu câu</button><button class="primary" data-hhj4-mission-complete="${selected.id}">${s.missionProgress[selected.id]?"✓ Đã hoàn thành":"Hoàn thành nhiệm vụ"}</button></footer><p class="hhj4-honesty">Nhiệm vụ HH tự biên soạn theo khung Can-do; không phải bài thi chính thức của Japan Foundation.</p></article></div></section>`;}

  function practiceView(){const tool=instance.state.practiceTool;return `<section class="hhj4-view"><header class="hhj4-section-head"><div><small>PRACTICE LAB</small><h1>Luyện một kỹ năng tại một thời điểm</h1><p>Kết quả speech-to-text chỉ là độ khớp transcript, không phải điểm phát âm tuyệt đối.</p></div></header><nav class="hhj4-subnav">${PRACTICE_TOOLS.map(([id,label,icon])=>`<button data-hhj4-practice="${id}" class="${tool===id?"active":""}"><i>${icon}</i>${label}</button>`).join("")}</nav>${tool==="writing"?writingView():tool==="srs"?srsView():tool==="grammar"?grammarView():tool==="mora"?moraView():conversationView()}</section>`;}
  function conversationView(){const scenario=CONVERSATIONS.find((row)=>row.id===instance.conversationId)||CONVERSATIONS[0],result=instance.conversationResult;return `<div class="hhj4-practice-layout"><aside class="hhj4-list">${CONVERSATIONS.map((row)=>`<button data-hhj4-conversation="${row.id}" class="${row.id===scenario.id?"active":""}"><i>${row.icon}</i><span><strong>${row.title}</strong><small>${row.prompt}</small></span></button>`).join("")}</aside><article class="hhj4-simulator"><header><span>${scenario.icon}</span><div><small>CONVERSATION SIMULATOR</small><h2>${scenario.title}</h2><p>${scenario.prompt}</p></div></header><section class="hhj4-dialogue"><p><b>Đối phương</b>${esc(scenario.prompt)}</p><div>${scenario.options.map((option,index)=>`<button data-hhj4-response="${index}" data-scenario="${scenario.id}">${esc(option.text)}</button>`).join("")}</div></section><div class="hhj4-speech-actions"><button data-hhj4-speak="${esc(scenario.expected)}">1. Nghe mẫu</button><button class="primary" data-hhj4-record="${scenario.id}">2. Nói lại</button><button data-hhj4-save-sentence="${esc(scenario.expected)}">3. Lưu vào SRS</button></div>${result?`<section class="hhj4-speech-result"><h3>Kết quả gần nhất</h3><div>${metric("Transcript",`${result.match}%`,"Độ khớp văn bản")}${metric("Tốc độ",result.speed,"Ước tính ký tự/giây")}${metric("Mora thiếu",result.missing,"So độ dài, không chấm phoneme")}${metric("Trường âm/っ",result.special,"Tín hiệu ký tự")}</div><p><b>Bạn nói:</b> ${esc(result.transcript)}</p><small>Đây không phải điểm phát âm hoặc pitch accent.</small></section>`:""}</article></div>`;}
  function writingView(){const task=WRITING_TASKS.find((row)=>row.id===instance.writingId)||WRITING_TASKS[0],latest=instance.writingResult;return `<div class="hhj4-practice-layout"><aside class="hhj4-list">${WRITING_TASKS.map((row)=>`<button data-hhj4-writing="${row.id}" class="${row.id===task.id?"active":""}"><i>書</i><span><strong>${row.label}</strong><small>${row.prompt}</small></span></button>`).join("")}</aside><article class="hhj4-writing"><header><small>WRITING STUDIO</small><h2>${task.label}</h2><p>${task.prompt}</p></header>${["kana","kanji"].includes(task.id)?`<section class="hhj4-pad"><canvas width="900" height="360" data-hhj4-pad aria-label="Bảng luyện viết"></canvas><button data-hhj4-pad-clear>Xóa bảng</button><span>Hướng dẫn trực quan; chưa tự tuyên bố nhận dạng đúng nét khi chưa có KanjiVG tương ứng.</span></section>`:""}<form data-hhj4-writing-form data-task="${task.id}"><textarea name="text" lang="ja" maxlength="1600" placeholder="${esc(task.sample)}" required></textarea><button class="primary">Kiểm tra & lưu lỗi</button></form>${latest?`<section class="hhj4-diff"><div><small>BẢN GỐC</small><p>${esc(latest.original)}</p></div><div><small>GỢI Ý</small><p>${esc(latest.suggestion)}</p></div><footer>${latest.issues.map(esc).join(" · ")||"Không phát hiện lỗi quy tắc cục bộ; vẫn cần người có chuyên môn duyệt sắc thái."}</footer></section>`:""}</article></div>`;}
  function cardLabel(card){if(card.type==="word"){const row=WORD_BY_ID.get(card.ref);return row?`${row.word} · ${row.meaning}`:card.ref;}return card.payload?.prompt||card.payload?.text||card.ref;}
  function srsView(){const rows=dueCards().slice(0,40);return `<article class="hhj4-srs"><header><div><small>SRS V3</small><h2>${rows.length} thẻ cần xử lý</h2><p>Từ vựng · collocation · câu · ngữ pháp · nghe–chép.</p></div><div class="hhj4-state-legend">${["new","learning","due","hard","mastered","relearning"].map((x)=>`<span>${x}</span>`).join("")}</div></header>${rows.length?`<div class="hhj4-card-list">${rows.map((card)=>`<article><span>${esc(card.type)}</span><h3>${esc(cardLabel(card))}</h3><small>${cardStatus(card)} · ${card.interval||0} ngày · quên ${card.lapses||0}</small><div>${[["forget","Quên"],["hard","Khó"],["remember","Nhớ"],["easy","Dễ"]].map(([id,label])=>`<button data-hhj4-rate="${id}" data-card="${esc(card.id)}">${label}</button>`).join("")}</div></article>`).join("")}</div>`:`<div class="hhj4-empty"><b>Không còn thẻ đến hạn</b><p>Lưu từ, câu hoặc lỗi mới để tiếp tục SRS.</p></div>`}<section class="hhj4-mistakes"><header><h3>Mistake Notebook</h3><span>${instance.state.mistakes.filter(x=>!x.resolved).length} lỗi mở</span></header>${instance.state.mistakes.filter(x=>!x.resolved).slice(0,20).map((row)=>`<article><b>${esc(row.category)}</b><span>${esc(row.prompt)}</span><small>Đúng: ${esc(row.correct)} · sai ${row.count} lần</small><button data-hhj4-resolve="${esc(row.key)}">Đã sửa</button></article>`).join("")||"<p>Chưa có lỗi.</p>"}</section></article>`;}
  function grammarView(){const rows=v3?.contrasts||[],selected=rows.find((row)=>row.id===instance.grammarId)||rows[0];if(!selected)return`<div class="hhj4-empty">Chưa có dữ liệu Grammar Contrast.</div>`;return `<div class="hhj4-practice-layout"><aside class="hhj4-list">${rows.map((row)=>`<button data-hhj4-grammar="${row.id}" class="${row.id===selected.id?"active":""}"><i>文</i><span><strong>${esc(row.title)}</strong><small>${row.level}</small></span></button>`).join("")}</aside><article class="hhj4-lesson"><small>GRAMMAR CONTRAST</small><h2>${esc(selected.title)}</h2><p>${esc(selected.rule)}</p><div class="good">✓ ${esc(selected.good)}</div><div class="bad">× ${esc(selected.bad)}</div><button data-hhj4-save-grammar="${selected.id}">＋ Lưu cấu trúc vào SRS</button></article></div>`;}
  function moraView(){const rows=v3?.mora||[],selected=rows.find((row)=>row.id===instance.moraId)||rows[0],result=instance.moraResult;if(!selected)return`<div class="hhj4-empty">Chưa có dữ liệu Mora.</div>`;return `<div class="hhj4-practice-layout"><aside class="hhj4-list">${rows.map((row)=>`<button data-hhj4-mora="${row.id}" class="${row.id===selected.id?"active":""}"><i>音</i><span><strong>${esc(row.label)}</strong><small>${esc(row.parts)}</small></span></button>`).join("")}</aside><article class="hhj4-lesson"><small>SHADOWING & MORA</small><h2>${esc(selected.label)}</h2><strong class="japanese">${esc(selected.sample)}</strong><p>${esc(selected.tip)}</p><div class="hhj4-speech-actions"><button data-hhj4-speak="${esc(selected.sample)}">Nghe mẫu</button><button data-hhj4-record-mora="${selected.id}">Ghi & so transcript</button><button data-hhj4-save-sentence="${esc(selected.sample)}">Lưu câu</button></div>${result&&result.id===selected.id?`<section class="hhj4-speech-result"><b>Khớp transcript ${result.match}%</b><p>${esc(result.transcript)}</p><small>${esc(result.note)}</small></section>`:""}<small>Không chấm pitch/phoneme nếu trình duyệt chỉ trả transcript.</small></article></div>`;}

  function lookupView(){const tool=instance.state.lookupTool;return `<section class="hhj4-view"><header class="hhj4-section-head"><div><small>LOOKUP & DATA</small><h1>Tra cứu 42.000+ mục mà không làm đứng giao diện</h1><p>Tìm qua Web Worker; audio chỉ tải/phát khi người học yêu cầu.</p></div></header><nav class="hhj4-subnav">${LOOKUP_TOOLS.map(([id,label])=>`<button data-hhj4-lookup="${id}" class="${tool===id?"active":""}">${label}</button>`).join("")}</nav>${tool==="packs"?packsView():tool==="kanji"?kanjiView():tool==="utilities"?utilitiesView():dictionaryView()}</section>`;}
  function dictionaryRows(){if(instance.searchDone)return instance.searchIds.map((id)=>WORD_BY_ID.get(id)).filter(Boolean);let rows=ALL_WORDS;if(instance.packFilter!=="all")rows=rows.filter((row)=>instance.packFilter==="vi-core"?row.meaningLanguage==="vi":row.packId===instance.packFilter);if(instance.registerFilter!=="all")rows=rows.filter((row)=>row.register===instance.registerFilter);return rows.slice(0,120);}
  function dictionaryView(){const rows=dictionaryRows(),selected=WORD_BY_ID.get(instance.wordId)||rows[0];return `<div class="hhj4-workspace"><aside class="hhj4-list hhj4-dictionary"><form data-hhj4-search><input name="query" value="${esc(instance.query)}" placeholder="Kanji, Kana, Romaji, Việt/Anh"><button>Tìm</button></form><div class="hhj4-filters"><select name="pack" data-hhj4-pack-filter><option value="all">Tất cả gói</option>${packCatalog().map((pack)=>`<option value="${pack.id}" ${instance.packFilter===pack.id?"selected":""}>${pack.label}</option>`).join("")}</select><select data-hhj4-register><option value="all">Mọi sắc thái</option>${["trung tính","lịch sự/kính ngữ","văn viết/trang trọng","khẩu ngữ/thân mật","công việc/chuyên ngành"].map((row)=>`<option ${instance.registerFilter===row?"selected":""}>${row}</option>`).join("")}</select></div><div class="hhj4-scroll-list">${rows.map((row)=>{const status=statusOf(row);return`<button data-hhj4-word="${row.id}" class="${selected?.id===row.id?"active":""}"><span><strong>${esc(row.word)}</strong><small>${esc(row.kana)} · ${esc(row.meaning)}</small></span><i class="${status[1]}">${row.level||"N?"}</i></button>`;}).join("")||"<p>Không tìm thấy mục phù hợp.</p>"}</div></aside>${selected?wordDetail(selected):`<article class="hhj4-empty">Chọn một từ.</article>`}</div>`;}
  function wordDetail(row){const [status,tone]=statusOf(row),saved=instance.state.cards.some((card)=>card.id===`word:${row.id}`),kanji=[...row.word].filter((char)=>/[\u3400-\u9fff]/.test(char));return `<article class="hhj4-word-detail"><header><div><small class="${tone}">${esc(status)}</small><h2>${esc(row.word)}</h2><p>${esc(row.kana)} · ${esc(row.romaji||"Chưa có Romaji")}</p></div><button data-hhj4-speak="${esc(row.word)}">▶ Nghe ja-JP</button></header><section><span>${esc(row.pos||"Chưa phân loại")}</span><h3>${esc(row.meaning)}</h3><p>${row.meaningLanguage==="en"?"Nghĩa Anh tham chiếu từ JMdict; chưa tự dịch sang Việt.":"Nghĩa Việt từ kho biên soạn/nguồn mở; xem trạng thái kiểm duyệt phía trên."}</p></section><div class="hhj4-data-grid"><article><small>SẮC THÁI</small><b>${esc(row.register||"Chưa xác minh")}</b><span>${esc(row.conjugationType||"Không áp dụng")}</span></article><article><small>TRỢ TỪ & COLLOCATION</small><b>${row.particles?.length?row.particles.map(esc).join(" · "):"Chưa xác minh"}</b><span>${row.related?.length?`Liên quan: ${row.related.map(esc).join(" · ")}`:"Chưa có dữ liệu liên kết."}</span></article><article><small>JLPT / PITCH</small><b>${row.jlptVerified?row.level:"Chưa xác minh"}</b><span>${row.pitchVerified?esc(row.pitch):"Không tự gán pitch accent."}</span></article><article><small>KANJI</small><b>${kanji.map(esc).join(" · ")||"Không có Kanji"}</b><span>Tra Kanji Graph để xem bộ và cách đọc có nguồn.</span></article><article><small>NGUỒN</small><b>${esc(row.source||"HH Japanese curated")}</b><span>${esc(row.license||"Nội dung HH tự biên soạn")} · ${checksum(JSON.stringify(row))}</span></article><article><small>AUDIO</small><b>${esc(row.audioMode||"speechSynthesis:ja-JP")}</b><span>Chỉ phát khi bấm nghe; không tải kho audio hàng loạt.</span></article></div><footer><button data-hhj4-known="${row.id}" class="${instance.state.knownWords[row.id]?"active":""}">✓ Đã biết</button><button class="primary" data-hhj4-save-word="${row.id}">${saved?"★ Đã có trong SRS":"☆ Thêm vào SRS"}</button></footer></article>`;}
  function packsView(){return `<div class="hhj4-pack-view"><header><div><small>VOCABULARY PACK MANAGER</small><h2>${ALL_WORDS.length.toLocaleString("vi-VN")} mục độc nhất đang dùng</h2></div><span>JMdict ${sourcePack.dictDate} · ${sourcePack.checksum.slice(0,12)}…</span></header><div class="hhj4-pack-grid">${packCatalog().map((pack)=>{const pct=Math.min(100,Math.round(pack.count/pack.target*100)),saved=instance.state.offlinePacks[pack.id];return`<article><header><b>${pack.label}</b><span>${pack.count.toLocaleString("vi-VN")} / mục tiêu ${pack.target.toLocaleString("vi-VN")}</span></header><progress max="100" value="${pct}"></progress><p>${pack.id==="vi-core"?"Nghĩa Việt; tách rõ đã kiểm duyệt và dữ liệu nguồn mở.":"Nguồn mở JMdict; nghĩa Anh tham chiếu, không tự gán JLPT."}</p><footer><small>${saved?`Offline ${saved.count.toLocaleString("vi-VN")} mục · ${saved.at.slice(0,10)}`:"Chưa lưu offline"}</small><button data-hhj4-offline="${pack.id}">${saved?"Cập nhật gói":"Tải offline"}</button></footer></article>`;}).join("")}</div><section class="hhj4-career"><header><h3>Career Packs</h3><span>Phân loại theo field của JMdict</span></header>${careerCatalog().map((row)=>`<article><b>${row.label}</b><span>${row.count.toLocaleString("vi-VN")} thuật ngữ nguồn mở</span></article>`).join("")}</section></div>`;}
  function kanjiView(){const chars=(legacy.kanji||[]),item=chars.find((row)=>row.char===instance.kanjiChar)||chars[0];return `<div class="hhj4-kanji"><aside class="hhj4-list">${chars.map((row)=>`<button data-hhj4-kanji="${row.char}" class="${row.char===item?.char?"active":""}"><i>${row.char}</i><span><strong>${row.meanings?.join(" · ")}</strong><small>${row.on?.join("、")||"—"}</small></span></button>`).join("")}</aside><article><header><strong>${item?.char||"日"}</strong><div><small>KANJI KNOWLEDGE GRAPH</small><h2>${item?.meanings?.map(esc).join(" · ")||"Chưa có dữ liệu"}</h2></div></header><div class="hhj4-graph"><span>Radical<b>${esc(item?.radical||"—")}</b></span><span>Onyomi<b>${item?.on?.map(esc).join("、")||"—"}</b></span><span>Kunyomi<b>${item?.kun?.map(esc).join("、")||"—"}</b></span><span>Từ ghép<b>${item?.examples?.map(esc).join(" · ")||"—"}</b></span></div><section class="hhj4-pad"><canvas width="900" height="360" data-hhj4-pad></canvas><button data-hhj4-pad-clear>Xóa bảng</button><span>KanjiVG sẽ được dùng khi có stroke pack tương ứng; bảng hiện tại không giả nhận dạng nét.</span></section></article></div>`;}
  function utilitiesView(){return `<div class="hhj4-utilities"><article><small>KANA CONVERTER</small><h3>Romaji → Hiragana → Katakana</h3><form data-hhj4-kana><input name="text" placeholder="nihongo" required><button>Chuyển</button><output></output></form></article><article><small>VERB CONJUGATOR</small><h3>Chia động từ cục bộ</h3><form data-hhj4-conjugate><input name="verb" placeholder="食べる" required><button>Chia</button><output></output></form></article><article><small>IMPORT / EXPORT</small><h3>Dữ liệu cá nhân</h3><div><button data-hhj4-export="json">JSON</button><button data-hhj4-export="anki">Anki TSV</button><label>Nhập JSON<input type="file" accept="application/json,.json" data-hhj4-import></label></div></article></div>`;}

  function tokenize(text){const tokens=[];let at=0;while(at<text.length){let hit=null;for(let length=Math.min(MAX_SURFACE,text.length-at);length>0;length--){const value=text.slice(at,at+length);if(SURFACE.has(value)){hit=SURFACE.get(value);break;}}if(hit){tokens.push({text:hit.word,row:hit});at+=hit.word.length;}else{tokens.push({text:text[at],row:null});at++;}}return tokens;}
  function immersionView(){const s=instance.state,item=IMMERSION.find((row)=>row.id===s.immersionId)||IMMERSION[0],sentences=instance.customText&&item.id==="subtitle"?instance.customText.split(/(?<=[。！？\n])/u).map((row)=>row.trim()).filter(Boolean).slice(0,80).map((row)=>[row,"Văn bản do người học nhập · chưa có bản dịch"]):item.sentences,sentence=sentences[instance.sentenceIndex]||sentences[0]||["文章を入力してください。","Hãy nhập văn bản."],tokens=tokenize(sentence[0]),selected=WORD_BY_ID.get(instance.readerWordId);return `<section class="hhj4-view"><header class="hhj4-section-head"><div><small>IMMERSION HUB</small><h1>Đọc nội dung Nhật thật theo từng câu</h1><p>Chạm câu hoặc từ để xem dạng từ điển, nghe và lưu vào SRS.</p></div><button data-hhj4-furigana>${s.furigana?"Ẩn Furigana từ đã thuộc":"Hiện Furigana"}</button></header><div class="hhj4-immersion"><aside class="hhj4-list">${IMMERSION.map((row)=>`<button data-hhj4-immersion="${row.id}" class="${row.id===item.id?"active":""}"><i>${row.icon}</i><span><strong>${row.title}</strong><small>${row.level} · nội dung HH tự biên soạn</small></span></button>`).join("")}<button data-hhj4-custom-text>＋ Dán văn bản/subtitle</button></aside><article class="hhj4-reader"><header><small>${item.level} · ${item.title}</small><h2>${sentence[0]}</h2><p>${sentence[1]}</p><button data-hhj4-speak="${esc(sentence[0])}">▶ Nghe câu</button></header><div class="hhj4-sentences">${sentences.map(([jp,vi],index)=>`<button data-hhj4-sentence="${index}" class="${index===instance.sentenceIndex?"active":""}"><b>${esc(jp)}</b><span>${esc(vi)}</span></button>`).join("")}</div><section class="hhj4-token-line">${tokens.map((token)=>token.row?`<button data-hhj4-reader-word="${token.row.id}" class="${instance.state.knownWords[token.row.id]?"known":""}">${esc(token.text)}${s.furigana&&!instance.state.knownWords[token.row.id]?`<small>${esc(token.row.kana)}</small>`:""}</button>`:esc(token.text)).join("")}</section><footer><button data-hhj4-save-sentence="${esc(sentence[0])}">＋ Lưu cả câu</button><span>Độ phủ đã biết: ${Math.round(tokens.filter(x=>x.row&&s.knownWords[x.row.id]).length/Math.max(1,tokens.filter(x=>x.row).length)*100)}%</span></footer></article><aside class="hhj4-reader-detail">${selected?`<small>TỪ ĐANG CHỌN</small><h2>${esc(selected.word)}</h2><b>${esc(selected.kana)}</b><p>${esc(selected.meaning)}</p><button data-hhj4-speak="${esc(selected.word)}">▶ Nghe</button><button data-hhj4-save-word="${selected.id}">＋ SRS</button>`:`<div class="hhj4-empty">Chạm một từ để xem chi tiết.</div>`}</aside></div></section>`;}

  function progressView(){const tool=instance.state.progressTool;return `<section class="hhj4-view"><header class="hhj4-section-head"><div><small>LEARNER & CLASSROOM</small><h1>Tiến độ thật, tách riêng theo hồ sơ</h1><p>Không tạo điểm thi, chứng chỉ hoặc bảng xếp hạng giả.</p></div><button data-hhj4-export="json">Xuất dữ liệu</button></header><nav class="hhj4-subnav">${PROGRESS_TOOLS.map(([id,label])=>`<button data-hhj4-progress="${id}" class="${tool===id?"active":""}">${label}</button>`).join("")}</nav>${tool==="teacher"?teacherView():tool==="family"?familyView():tool==="data"?dataView():dualProgressView()}</section>`;}
  function dualProgressView(){const s=instance.state,done=Object.keys(s.missionProgress).length,reviewed=s.cards.reduce((sum,card)=>sum+(card.reviews||0),0);return `<div class="hhj4-dual-progress"><article><header><b>JLPT Knowledge Map</b><span>${s.jlptLevel}</span></header>${["Vocabulary","Grammar","Reading","Listening"].map((label,index)=>{const value=Math.min(100,Math.round(reviewed/12)+index*2);return`<label>${label}<progress max="100" value="${value}"></progress><b>${value}%</b></label>`;}).join("")}<p>Ước tính luyện tập nội bộ; không phải điểm JLPT chính thức.</p></article><article><header><b>JF/CEFR Can-do Map</b><span>${s.jfLevel}</span></header>${["Interaction","Speaking","Listening","Writing"].map((label,index)=>{const value=Math.min(100,Math.round(done/4)+index);return`<label>${label}<progress max="100" value="${value}"></progress><b>${value}%</b></label>`;}).join("")}<p>Dựa trên mission đã hoàn thành; speaking/writing giữ riêng.</p></article><section>${metric("Từ nhận biết",Object.keys(s.knownWords).length,"Đánh dấu đã biết")}${metric("Vốn chủ động",s.cards.filter(x=>x.reviews>=3).length,"Đã ôn ít nhất 3 lần")}${metric("SRS",s.cards.length,"5 loại thẻ")}${metric("Lỗi",s.mistakes.length,"Từ mọi bài học")}</section></div>`;}
  function teacherView(){const s=instance.state;return `<div class="hhj4-teacher"><form data-hhj4-class-form><small>TEACHER MODE</small><h2>Tạo lớp và giao bài</h2><label>Tên lớp<input name="name" required placeholder="Tiếng Nhật giao tiếp A1"></label><label>Bài giao<select name="assignment">${PATHS.map((row)=>`<option value="${row.id}">${row.title}</option>`).join("")}</select></label><label>Hạn hoàn thành<input type="date" name="due" required></label><label><input type="checkbox" name="lock"> Khóa đáp án trước hạn</label><button type="button" class="primary" data-hhj4-create-class>Tạo lớp</button></form><section><header><h3>${s.classrooms.length} lớp</h3><div><button data-hhj4-export="csv">Xuất CSV</button><button data-hhj4-print>In / PDF</button></div></header>${s.classrooms.map((row)=>`<article><b>${esc(row.name)}</b><span>${esc(row.assignment)} · hạn ${esc(row.due)}</span><small>${row.lock?"Đáp án đang khóa":"Cho phép xem đáp án"}</small></article>`).join("")||"<p>Chưa có lớp.</p>"}</section></div>`;}
  function familyView(){const f=instance.state.family,book=profiles();return `<div class="hhj4-teacher"><form class="hhj4-family" data-hhj4-family><header><small>FAMILY MODE</small><h2>An toàn cho hồ sơ trẻ em</h2><p>Không có tin nhắn riêng, quảng cáo cá nhân hóa hoặc bảng xếp hạng công khai.</p></header><label><input type="checkbox" name="enabled" ${f.enabled?"checked":""}> Bật quản lý phụ huynh</label><label>Giới hạn học mỗi ngày<input type="number" name="dailyLimit" min="5" max="120" value="${f.dailyLimit}"> phút</label><label><input type="checkbox" name="aiAllowed" ${f.aiAllowed?"checked":""}> Cho phép AI Tutor có hướng dẫn</label><label><input type="checkbox" name="publicRanking" disabled> Bảng xếp hạng công khai luôn tắt</label><button type="button" class="primary" data-hhj4-save-family>Lưu Family Mode</button></form><section><header><div><small>LEARNER PROFILES</small><h2>Hồ sơ tách riêng tiến độ</h2></div></header><label>Hồ sơ đang dùng<select data-hhj4-profile-select>${book.items.map((row)=>`<option value="${row.id}" ${row.id===book.active?"selected":""}>${esc(row.name)}</option>`).join("")}</select></label><form data-hhj4-profile-form><input name="name" maxlength="60" placeholder="Tên người học" required><select name="mode"><option value="little">Little Kids</option><option value="kids">Kids</option><option value="teen">Teens</option><option value="student">Students</option><option value="adult" selected>Adults</option><option value="senior">Senior</option></select><button type="button" data-hhj4-create-profile>Tạo hồ sơ</button></form><p>Dữ liệu được lưu theo <code>ownerId + learnerProfileId</code>; đổi hồ sơ không làm mất tiến độ hồ sơ khác.</p></section></div>`;}
  function dataView(){return `<div class="hhj4-data-source"><header><small>DATA QUALITY & LICENSE</small><h2>Dữ liệu đúng nguồn, đúng trạng thái</h2></header><div>${metric("Tổng độc nhất",ALL_WORDS.length.toLocaleString("vi-VN"),"Sau loại trùng Kanji + Kana")}${metric("JMdict V4",sourcePack.words.length.toLocaleString("vi-VN"),`Bản ${sourcePack.dictDate}`)}${metric("Nghĩa Việt",reviewedVietnamese().length.toLocaleString("vi-VN"),"Biên soạn + Kaikki")}${metric("Checksum",sourcePack.checksum.slice(0,16),"SHA-256")}</div><article><h3>JMdict / EDRDG</h3><p>30.000 mục nguồn mở bổ sung; nghĩa Anh tham chiếu. Không tự gán JLPT hoặc pitch.</p><a href="https://www.edrdg.org/wiki/Main_Page.html" target="_blank" rel="noopener">Xem nguồn ↗</a></article><article><h3>Kaikki / Wiktionary</h3><p>Nghĩa Việt nguồn mở được ghi “đã kiểm tra nguồn · cần biên tập”, không gọi là đã kiểm duyệt.</p><a href="https://kaikki.org/viwiktionary/" target="_blank" rel="noopener">Xem nguồn ↗</a></article><article><h3>Audio</h3><p>Dùng speechSynthesis ja-JP khi bấm nghe. Không re-host Common Voice và không lấy audio Tatoeba thiếu giấy phép.</p></article></div>`;}

  function currentView(){switch(instance.state.activeTab){case"paths":return pathsView();case"practice":return practiceView();case"lookup":return lookupView();case"immersion":return immersionView();case"progress":return progressView();default:return todayView();}}
  function createClassFromForm(form){if(!form)return;const name=form.elements.namedItem("name")?.value.trim(),due=form.elements.namedItem("due")?.value;if(!name||!due){toast("Hãy nhập tên lớp và hạn hoàn thành.","warning");return;}instance.state.classrooms.push({id:`class-${Date.now()}`,name,assignment:form.elements.namedItem("assignment")?.value||"jf",due,lock:Boolean(form.elements.namedItem("lock")?.checked),createdAt:new Date().toISOString()});write();toast("Đã tạo lớp và lưu bài giao.");render();}
  function saveFamilyFromForm(form){if(!form)return;instance.state.family={enabled:Boolean(form.elements.namedItem("enabled")?.checked),dailyLimit:Math.max(5,Math.min(120,Number(form.elements.namedItem("dailyLimit")?.value)||20)),aiAllowed:Boolean(form.elements.namedItem("aiAllowed")?.checked),publicRanking:false};write();toast("Đã lưu Family Mode.");render();}
  function createProfileFromForm(form){if(!form)return;const name=form.elements.namedItem("name")?.value.trim(),book=profiles();if(!name){toast("Hãy nhập tên người học.","warning");return;}const id=`learner-${Date.now()}`;book.items.push({id,name,mode:form.elements.namedItem("mode")?.value||"adult"});book.active=id;localStorage.setItem(profilesKey(),JSON.stringify(book));instance.state=readState();toast("Đã tạo hồ sơ người học riêng.");render();}
  function bindRenderedControls(){const signal=instance.controller.signal;instance.host.querySelector("[data-hhj4-create-class]")?.addEventListener("click",(event)=>{event.preventDefault();event.stopPropagation();createClassFromForm(event.currentTarget.closest("form"));},{signal});instance.host.querySelector("[data-hhj4-save-family]")?.addEventListener("click",(event)=>{event.preventDefault();event.stopPropagation();saveFamilyFromForm(event.currentTarget.closest("form"));},{signal});instance.host.querySelector("[data-hhj4-create-profile]")?.addEventListener("click",(event)=>{event.preventDefault();event.stopPropagation();createProfileFromForm(event.currentTarget.closest("form"));},{signal});}
  function render(){if(!instance)return;instance.host.innerHTML=shell(currentView());setupPad();bindRenderedControls();}
  function navigate(tab){if(!MAIN_TABS.some((row)=>row[0]===tab))return;instance.state.activeTab=tab;write();render();}
  function setupPad(){const canvas=instance?.host.querySelector("[data-hhj4-pad]");if(!canvas)return;const ctx=canvas.getContext("2d");ctx.lineWidth=8;ctx.lineCap="round";ctx.strokeStyle="#70e6ff";let drawing=false;const point=(event)=>{const rect=canvas.getBoundingClientRect();return[(event.clientX-rect.left)*canvas.width/rect.width,(event.clientY-rect.top)*canvas.height/rect.height];};canvas.onpointerdown=(event)=>{drawing=true;ctx.beginPath();ctx.moveTo(...point(event));canvas.setPointerCapture(event.pointerId);};canvas.onpointermove=(event)=>{if(!drawing)return;ctx.lineTo(...point(event));ctx.stroke();};canvas.onpointerup=canvas.onpointercancel=()=>{drawing=false;};}
  function initWorker(){if(typeof global.Worker!=="function")return;try{instance.worker=new Worker("./japanese-search-worker.js?v=1");instance.worker.onmessage=(event)=>{if(!instance||event.data?.requestId!==instance.searchRequest)return;instance.searchIds=[...new Set([...(instance.localSearchIds||[]),...(event.data.ids||[])])].slice(0,160);instance.searchDone=true;render();};}catch{instance.worker=null;}}
  function matchesSearch(row,q){if(instance.packFilter!=="all"&&(instance.packFilter==="vi-core"?row.meaningLanguage!=="vi":row.packId!==instance.packFilter))return false;if(instance.registerFilter!=="all"&&row.register!==instance.registerFilter)return false;return!q||[row.word,row.kana,row.romaji,row.meaning,row.example,row.related?.join(" ")].join(" ").toLocaleLowerCase("ja").includes(q);}
  function search(query){instance.query=String(query||"").trim();instance.searchIds=[];instance.searchDone=false;const requestId=++instance.searchRequest,q=instance.query.normalize("NFKC").toLocaleLowerCase("ja");instance.localSearchIds=LOCAL_WORDS.filter((row)=>matchesSearch(row,q)).slice(0,160).map((row)=>row.id);if(instance.worker&&instance.packFilter!=="vi-core"){instance.worker.postMessage({requestId,query:instance.query,packId:instance.packFilter,register:instance.registerFilter,limit:160});return;}instance.searchIds=(instance.packFilter==="vi-core"?instance.localSearchIds:ALL_WORDS.filter((row)=>matchesSearch(row,q)).slice(0,160).map((row)=>row.id));instance.searchDone=true;render();}
  async function recognize(expected){const Recognition=global.SpeechRecognition||global.webkitSpeechRecognition;if(!Recognition)throw new Error("Trình duyệt chưa hỗ trợ nhận dạng giọng nói tiếng Nhật.");const recognition=new Recognition();recognition.lang="ja-JP";recognition.interimResults=false;const started=performance.now();return new Promise((resolve,reject)=>{recognition.onresult=(event)=>resolve({transcript:event.results[0][0].transcript,seconds:Math.max(.1,(performance.now()-started)/1000)});recognition.onerror=(event)=>reject(new Error(`Không thể nhận giọng nói: ${event.error}`));recognition.start();});}
  async function recordConversation(id,button){const scenario=CONVERSATIONS.find((row)=>row.id===id);if(!scenario)return;button.disabled=true;button.textContent="Đang nghe…";try{const result=await recognize(scenario.expected),expected=normalizeJapanese(scenario.expected),actual=normalizeJapanese(result.transcript),match=transcriptScore(expected,actual);instance.conversationResult={transcript:result.transcript,match,speed:`${(actual.length/result.seconds).toFixed(1)} ký tự/s`,missing:Math.max(0,expected.length-actual.length),special:["ー","っ","ん"].filter((char)=>expected.includes(char)&&!actual.includes(char)).join(" · ")||"Không thấy thiếu theo ký tự"};instance.state.conversationHistory.unshift({id,match,transcript:result.transcript,at:new Date().toISOString()});if(match<75)addMistake("listening",scenario.prompt,scenario.expected,result.transcript,id);else study(12);write();render();}catch(error){toast(error.message,"error");button.disabled=false;button.textContent="2. Nói lại";}}
  async function recordMora(id,button){const row=v3?.mora?.find((item)=>item.id===id);if(!row)return;button.disabled=true;button.textContent="Đang nghe…";try{const result=await recognize(row.sample),match=transcriptScore(row.sample,result.transcript);instance.moraResult={id,match,transcript:result.transcript,note:"So transcript và ký tự mora; không phải điểm pitch/phoneme."};instance.state.conversationHistory.unshift({id:`mora:${id}`,match,transcript:result.transcript,at:new Date().toISOString()});if(match<75)addMistake("mora",row.label,row.sample,result.transcript,id);else study(10);write();render();}catch(error){toast(error.message,"error");button.disabled=false;button.textContent="Ghi & so transcript";}}
  function writingFeedback(task,text){const original=String(text||"").trim(),issues=[];let suggestion=original.replace(/\s+/g," ").replace(/([。！？])\1+/g,"$1");if(!/[ぁ-んァ-ン一-龯]/.test(original))issues.push("Chưa phát hiện chữ Nhật.");if(task==="email"&&!/お世話になっております|いつもお世話/.test(original)){issues.push("Email công việc thường cần lời mở đầu lịch sự.");suggestion=`お世話になっております。${suggestion}`;}if(/私は[^。]*に勉強/.test(original)){issues.push("Nơi xảy ra hành động 勉強する thường dùng で.");suggestion=suggestion.replace(/に勉強/g,"で勉強");}if(task==="message"&&!/すみません|申し訳/.test(original))issues.push("Nên thêm lời xin lỗi trước thông báo đến muộn.");if(!/[。！？]$/.test(suggestion))suggestion+=`。`;return{original,suggestion,issues};}
  async function cachePack(packId){if(!global.indexedDB)throw new Error("Trình duyệt không hỗ trợ IndexedDB.");const catalog=packCatalog().find((row)=>row.id===packId);if(!catalog)throw new Error("Không tìm thấy gói dữ liệu.");const rows=packId==="vi-core"?reviewedVietnamese():sourcePack.words.filter((row)=>row.packId===packId);const manifest={id:packId,label:catalog.label,count:rows.length,source:packId==="vi-core"?vietnamesePack?.source:sourcePack.source,license:packId==="vi-core"?vietnamesePack?.license:sourcePack.license,checksum:checksum(rows.map((row)=>row.id).join("|")),at:new Date().toISOString()};await new Promise((resolve,reject)=>{const request=indexedDB.open("hh-japanese-os-v4",1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains("packs"))db.createObjectStore("packs");};request.onerror=()=>reject(request.error);request.onsuccess=()=>{const tx=request.result.transaction("packs","readwrite");tx.objectStore("packs").put({manifest,rows},`${ownerId()}:${learnerId()}:${packId}`);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);};});instance.state.offlinePacks[packId]=manifest;write();}
  function downloadText(filename,text,type="application/json"){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function exportData(format){if(format==="anki"){const lines=["Front\tBack\tTags",...instance.state.cards.map((card)=>{const row=WORD_BY_ID.get(card.ref);return row?`${row.word} [${row.kana}]\t${row.meaning}\tHHJapanese ${row.packId||"core"}`:`${cardLabel(card)}\t${card.payload?.correct||""}\tHHJapanese ${card.type}`;})];return downloadText(`hh-japanese-anki-${day()}.tsv`,lines.join("\n"),"text/tab-separated-values");}if(format==="csv"){const lines=["class,assignment,due,locked",...instance.state.classrooms.map((row)=>[row.name,row.assignment,row.due,row.lock].map((value)=>`"${String(value).replace(/"/g,'""')}"`).join(","))];return downloadText(`hh-japanese-classes-${day()}.csv`,lines.join("\n"),"text/csv");}downloadText(`hh-japanese-v4-${day()}.json`,JSON.stringify({version:VERSION,ownerId:ownerId(),learnerProfileId:learnerId(),exportedAt:new Date().toISOString(),sourcePack:{version:sourcePack.version,checksum:sourcePack.checksum},state:instance.state},null,2));}

  async function click(event){const button=event.target.closest("button");if(!button)return;
    if(button.dataset.hhj4Tab)return navigate(button.dataset.hhj4Tab);
    if(button.dataset.hhj4OpenPractice){instance.state.practiceTool=button.dataset.hhj4OpenPractice;return navigate("practice");}
    if(button.dataset.hhj4OpenMission){instance.missionId=button.dataset.hhj4OpenMission;instance.state.path=MISSIONS.find((row)=>row.id===instance.missionId)?.track||"jf";return navigate("paths");}
    if(button.dataset.hhj4Path){instance.state.path=button.dataset.hhj4Path;instance.missionPage=0;instance.missionId="";write();return render();}
    if(button.dataset.hhj4Mission){instance.missionId=button.dataset.hhj4Mission;return render();}
    if(button.dataset.hhj4MissionPage){const total=Math.ceil(MISSIONS.filter((row)=>row.paths.includes(instance.state.path)).length/20);instance.missionPage=Math.max(0,Math.min(total-1,instance.missionPage+(button.dataset.hhj4MissionPage==="next"?1:-1)));return render();}
    if(button.dataset.hhj4MissionComplete){const mission=MISSIONS.find((row)=>row.id===button.dataset.hhj4MissionComplete);instance.state.missionProgress[mission.id]={at:new Date().toISOString(),jfLevel:mission.jfLevel};addCard("sentence",mission.id,{prompt:mission.prompt,correct:mission.answer,text:mission.answer});study(15);write();return render();}
    if(button.dataset.hhj4Practice){instance.state.practiceTool=button.dataset.hhj4Practice;write();return render();}
    if(button.dataset.hhj4Conversation){instance.conversationId=button.dataset.hhj4Conversation;instance.conversationResult=null;return render();}
    if(button.dataset.hhj4Response!==undefined){const scenario=CONVERSATIONS.find((row)=>row.id===button.dataset.scenario),option=scenario?.options[Number(button.dataset.hhj4Response)];if(!option)return;toast(option.note,option.ok?"success":"warning");if(!option.ok)addMistake("context",scenario.prompt,scenario.expected,option.text,scenario.id);else study(5);write();return;}
    if(button.dataset.hhj4Record)return recordConversation(button.dataset.hhj4Record,button);
    if(button.dataset.hhj4Writing){instance.writingId=button.dataset.hhj4Writing;instance.writingResult=null;return render();}
    if(button.dataset.hhj4Rate){const card=instance.state.cards.find((row)=>row.id===button.dataset.card);if(card){rateCard(card,button.dataset.hhj4Rate);study(button.dataset.hhj4Rate==="forget"?1:5);render();}return;}
    if(button.dataset.hhj4Resolve){const row=instance.state.mistakes.find((item)=>item.key===button.dataset.hhj4Resolve);if(row){row.resolved=true;write();render();}return;}
    if(button.dataset.hhj4Grammar){instance.grammarId=button.dataset.hhj4Grammar;return render();}
    if(button.dataset.hhj4SaveGrammar){const row=v3.contrasts.find((item)=>item.id===button.dataset.hhj4SaveGrammar);addCard("grammar",row.id,{prompt:row.title,correct:row.rule});toast("Đã thêm cấu trúc vào SRS.");return;}
    if(button.dataset.hhj4Mora){instance.moraId=button.dataset.hhj4Mora;return render();}
    if(button.dataset.hhj4RecordMora)return recordMora(button.dataset.hhj4RecordMora,button);
    if(button.dataset.hhj4Lookup){instance.state.lookupTool=button.dataset.hhj4Lookup;write();return render();}
    if(button.dataset.hhj4Word){instance.wordId=button.dataset.hhj4Word;return render();}
    if(button.dataset.hhj4SaveWord){addCard("word",button.dataset.hhj4SaveWord);toast("Đã thêm từ vào SRS.");return render();}
    if(button.dataset.hhj4Known){instance.state.knownWords[button.dataset.hhj4Known]=!instance.state.knownWords[button.dataset.hhj4Known];write();return render();}
    if(button.dataset.hhj4Speak!==undefined){if(!speak(button.dataset.hhj4Speak))toast("Thiết bị chưa có speechSynthesis.","error");return;}
    if(button.dataset.hhj4SaveSentence){addCard("sentence",checksum(button.dataset.hhj4SaveSentence),{text:button.dataset.hhj4SaveSentence,prompt:button.dataset.hhj4SaveSentence,correct:button.dataset.hhj4SaveSentence});toast("Đã lưu cả câu vào SRS.");return;}
    if(button.dataset.hhj4Offline){button.disabled=true;button.textContent="Đang lưu…";try{await cachePack(button.dataset.hhj4Offline);toast("Đã lưu gói offline vào IndexedDB.");render();}catch(error){toast(error.message,"error");button.disabled=false;}return;}
    if(button.dataset.hhj4Kanji){instance.kanjiChar=button.dataset.hhj4Kanji;return render();}
    if(button.matches("[data-hhj4-pad-clear]")){const canvas=instance.host.querySelector("[data-hhj4-pad]");canvas?.getContext("2d")?.clearRect(0,0,canvas.width,canvas.height);return;}
    if(button.dataset.hhj4Immersion){instance.state.immersionId=button.dataset.hhj4Immersion;instance.sentenceIndex=0;write();return render();}
    if(button.dataset.hhj4Sentence!==undefined){instance.sentenceIndex=Number(button.dataset.hhj4Sentence)||0;return render();}
    if(button.dataset.hhj4ReaderWord){instance.readerWordId=button.dataset.hhj4ReaderWord;return render();}
    if(button.matches("[data-hhj4-furigana]")){instance.state.furigana=!instance.state.furigana;write();return render();}
    if(button.matches("[data-hhj4-custom-text]")){const value=prompt("Dán văn bản tiếng Nhật hoặc subtitle (tối đa 10.000 ký tự):",instance.customText||"");if(value!==null){instance.customText=String(value).slice(0,10000);instance.state.immersionId="subtitle";instance.sentenceIndex=0;write();render();toast("Văn bản đã được nạp cho phiên hiện tại.");}return;}
    if(button.dataset.hhj4Progress){instance.state.progressTool=button.dataset.hhj4Progress;write();return render();}
    if(button.matches("[data-hhj4-create-class]"))return createClassFromForm(button.closest("form"));
    if(button.matches("[data-hhj4-save-family]"))return saveFamilyFromForm(button.closest("form"));
    if(button.matches("[data-hhj4-create-profile]"))return createProfileFromForm(button.closest("form"));
    if(button.dataset.hhj4Export)return exportData(button.dataset.hhj4Export);
    if(button.matches("[data-hhj4-print]")){global.print();return;}
    if(button.dataset.hhj4Profile!==undefined){instance.state.activeTab="progress";instance.state.progressTool="family";write();return render();}
  }
  async function submit(event){event.preventDefault();const form=event.target;
    if(form.matches("[data-hhj4-search]"))return search(form.elements.query.value);
    if(form.matches("[data-hhj4-writing-form]")){const task=form.dataset.task,text=form.elements.text.value,result=writingFeedback(task,text);instance.writingResult=result;instance.state.writingHistory.unshift({task,...result,at:new Date().toISOString()});for(const issue of result.issues)addMistake(task,issue,result.suggestion,result.original,`${task}:${checksum(issue)}`);if(!result.issues.length)study(10);write();return render();}
    if(form.matches("[data-hhj4-kana]")){const value=form.elements.text.value,hira=legacy.romajiToHiragana(value),kata=legacy.hiraganaToKatakana(hira);form.querySelector("output").textContent=`${hira} · ${kata}`;return;}
    if(form.matches("[data-hhj4-conjugate]")){const value=legacy.conjugateVerb(form.elements.verb.value);form.querySelector("output").textContent=Object.entries(value).map(([key,row])=>`${key}: ${row}`).join(" · ");return;}
    if(form.matches("[data-hhj4-class-form]"))return createClassFromForm(form);
    if(form.matches("[data-hhj4-family]"))return saveFamilyFromForm(form);
    if(form.matches("[data-hhj4-profile-form]"))return createProfileFromForm(form);
  }
  function change(event){if(event.target.matches("[data-hhj4-pack-filter]")){instance.packFilter=event.target.value;return search(instance.query);}if(event.target.matches("[data-hhj4-register]")){instance.registerFilter=event.target.value;return search(instance.query);}if(event.target.matches("[data-hhj4-profile-select]")){write();const book=profiles();book.active=event.target.value;localStorage.setItem(profilesKey(),JSON.stringify(book));instance.state=readState();return render();}if(event.target.matches("[data-hhj4-import]")){const file=event.target.files?.[0];if(!file)return;file.text().then((text)=>{const payload=JSON.parse(text);if(payload?.state&&typeof payload.state==="object"){instance.state={...defaults(),...payload.state};write();render();toast("Đã nhập dữ liệu HH Japanese V4.");}}).catch((error)=>toast(error.message,"error"));}}
  function hotkeys(event){if(event.ctrlKey||event.metaKey||event.altKey||/INPUT|TEXTAREA|SELECT/.test(event.target?.tagName))return;const index=Number(event.key)-1;if(MAIN_TABS[index])navigate(MAIN_TABS[index][0]);}
  let instance=null;
  function mount(host,options={}){unmount();if(!host)return;const routeTab=location.hash.match(/^#\/japanese\/?([^/?#]*)/)?.[1];instance={host,options,state:readState(),controller:new AbortController(),toastTimer:0,worker:null,searchRequest:0,searchIds:[],localSearchIds:[],searchDone:false,query:"",packFilter:"all",registerFilter:"all",wordId:"",missionId:"",missionPage:0,conversationId:"restaurant",conversationResult:null,writingId:"kana",writingResult:null,grammarId:v3?.contrasts?.[0]?.id||"",moraId:v3?.mora?.[0]?.id||"",moraResult:null,kanjiChar:legacy.kanji?.[0]?.char||"日",sentenceIndex:0,readerWordId:"",customText:""};if(MAIN_TABS.some((row)=>row[0]===routeTab))instance.state.activeTab=routeTab;host.addEventListener("click",(event)=>click(event).catch((error)=>toast(error.message,"error")),{signal:instance.controller.signal});host.addEventListener("submit",(event)=>submit(event).catch((error)=>toast(error.message,"error")),{signal:instance.controller.signal});host.addEventListener("change",change,{signal:instance.controller.signal});global.addEventListener("keydown",hotkeys,{signal:instance.controller.signal});initWorker();render();}
  function unmount(){if(!instance)return;instance.controller.abort();instance.worker?.terminate();clearTimeout(instance.toastTimer);global.speechSynthesis?.cancel?.();instance=null;}

  global.HHJapaneseOSV4=Object.freeze({version:VERSION,tabs:MAIN_TABS,paths:PATHS,missions:MISSIONS,conversations:CONVERSATIONS,writingTasks:WRITING_TASKS,immersion:IMMERSION,words:ALL_WORDS,packs:packCatalog(),checksum:sourcePack.checksum,defaults,cardStatus});
  global.HHJapanese=Object.freeze({...legacy,mount,unmount,osVersion:VERSION,words:ALL_WORDS,v4Packs:packCatalog(),missionCount:MISSIONS.length});
})();
