(() => {
  "use strict";

  const global = typeof window !== "undefined" ? window : globalThis;
  const legacy = global.HHJapanese;
  if (!legacy?.mount) return;
  const VIETNAMESE_PACK = Array.isArray(global.HHJapaneseVietnamesePack?.words) ? global.HHJapaneseVietnamesePack.words : [];

  const VERSION = 3;
  const BASE_KEY = "hh.japanese.os.v3";
  const TABS = Object.freeze([
    ["today", "Hôm nay", "今"], ["missions", "Can-do", "✓"], ["vocabulary", "Từ vựng", "辞"],
    ["reader", "Reader", "読"], ["grammar", "Ngữ pháp", "文"], ["mora", "Mora", "音"],
    ["kanji", "Kanji", "漢"], ["jlpt", "JLPT", "試"], ["life", "Đời sống Nhật", "日"], ["progress", "Tiến độ", "↗"]
  ]);
  const MODES = Object.freeze({
    little: ["Little Kids", "5 từ · hình và âm thanh", 5], kids: ["Kids", "8 từ · truyện và trò chơi", 8],
    teen: ["Teens", "10–12 từ · trường học và giao tiếp", 12], student: ["Students", "JLPT, du học và học thuật", 15],
    adult: ["Adults", "Đời sống, công việc và giao tiếp", 15], senior: ["Senior", "Chữ lớn · audio chậm · ít thao tác", 8]
  });
  const MISSIONS = Object.freeze([
    { id:"restaurant", level:"A1", title:"Gọi món và hỏi về món ăn", place:"Nhà hàng", icon:"🍜", words:[["注文","ちゅうもん","gọi món"],["おすすめ","おすすめ","món được đề xuất"],["辛い","からい","cay"]], pattern:"おすすめは何ですか。", listen:"すみません、おすすめは何ですか。", prompt:"Hỏi nhân viên món được đề xuất", answer:"おすすめは何ですか" },
    { id:"station", level:"A1", title:"Báo rằng mình bị lạc", place:"Ga tàu", icon:"🚉", words:[["駅員","えきいん","nhân viên ga"],["迷う","まよう","bị lạc"],["出口","でぐち","lối ra"]], pattern:"道に迷いました。", listen:"すみません、道に迷いました。東口はどこですか。", prompt:"Nói rằng bạn bị lạc", answer:"道に迷いました" },
    { id:"hospital", level:"A2", title:"Giải thích triệu chứng", place:"Bệnh viện", icon:"🏥", words:[["症状","しょうじょう","triệu chứng"],["痛い","いたい","đau"],["熱","ねつ","sốt"]], pattern:"昨日から頭が痛いです。", listen:"昨日から頭が痛くて、熱があります。", prompt:"Nói rằng bạn đau đầu từ hôm qua", answer:"昨日から頭が痛いです" },
    { id:"work", level:"A2", title:"Giới thiệu công việc", place:"Nơi làm việc", icon:"💼", words:[["担当","たんとう","phụ trách"],["開発","かいはつ","phát triển"],["経験","けいけん","kinh nghiệm"]], pattern:"ウェブ開発を担当しています。", listen:"私はウェブ開発を担当しています。", prompt:"Giới thiệu phần việc bạn phụ trách", answer:"担当しています" },
    { id:"cityhall", level:"A2", title:"Điền mẫu đơn đơn giản", place:"Tòa thị chính", icon:"🏛️", words:[["申請書","しんせいしょ","đơn đăng ký"],["住所","じゅうしょ","địa chỉ"],["記入","きにゅう","điền thông tin"]], pattern:"この申請書に記入します。", listen:"住所と電話番号を記入してください。", prompt:"Xác nhận bạn sẽ điền đơn", answer:"申請書に記入します" },
    { id:"neighbor", level:"B1", title:"Chào hỏi hàng xóm mới", place:"Khu dân cư", icon:"🏠", words:[["引っ越す","ひっこす","chuyển nhà"],["近所","きんじょ","hàng xóm/khu phố"],["よろしく","よろしく","mong được giúp đỡ"]], pattern:"隣に引っ越してきました。よろしくお願いします。", listen:"昨日、隣に引っ越してきました。よろしくお願いします。", prompt:"Tự giới thiệu với hàng xóm", answer:"引っ越してきました" }
  ]);
  const CONTRASTS = Object.freeze([
    { id:"wa-ga", title:"は và が", level:"N5", rule:"は đặt chủ đề hoặc đối chiếu; が xác định chủ thể/thông tin mới.", good:"私は学生です。だれが来ましたか。田中さんが来ました。", bad:"だれは来ましたか。", question:"だれ___来ましたか。", answer:"が", choices:["は","が"] },
    { id:"ni-de", title:"に và で", level:"N5", rule:"に chỉ đích đến, thời điểm hoặc nơi tồn tại; で chỉ nơi hành động xảy ra.", good:"学校に行きます。図書館で勉強します。", bad:"図書館に勉強します。", question:"図書館___勉強します。", answer:"で", choices:["に","で"] },
    { id:"sou-you-rashii", title:"そうだ・ようだ・らしい", level:"N3", rule:"そうだ: vẻ ngoài/nghe nói; ようだ: suy đoán có căn cứ; らしい: nghe nói hoặc đúng chất.", good:"雨が降りそうです。彼は来ないらしいです。", bad:"雨が降るようそうです。", question:"空が暗い。雨が降り___です。", answer:"そう", choices:["そう","らしい","ため"] },
    { id:"tame-you", title:"ために và ように", level:"N3", rule:"ために đi với mục tiêu có chủ ý; ように thường đi với khả năng/trạng thái khó kiểm soát.", good:"留学するために勉強します。忘れないようにメモします。", bad:"忘れないためにメモします (tùy ngữ cảnh nhưng kém tự nhiên hơn).", question:"忘れない___メモします。", answer:"ように", choices:["ために","ように"] },
    { id:"tokoro-bakari-hazu", title:"ところ・ばかり・はず", level:"N3", rule:"ところ: đúng thời điểm; ばかり: vừa mới/chỉ toàn; はず: dự đoán có căn cứ.", good:"今から出るところです。着いたばかりです。来るはずです。", bad:"今から出たはずです。", question:"電車はもう着く___です。", answer:"はず", choices:["ところ","ばかり","はず"] },
    { id:"teiru", title:"ている: hành động và trạng thái", level:"N4", rule:"Có thể diễn tả đang làm, thói quen hoặc trạng thái kết quả tùy động từ.", good:"今、読んでいます。結婚しています。", bad:"毎日、今読んでいます。", question:"田中さんは結婚して___。", answer:"います", choices:["あります","います"] },
    { id:"keigo", title:"尊敬語・謙譲語・丁寧語", level:"N2", rule:"Tôn kính nâng người nghe/người thứ ba; khiêm nhường hạ người nói; lịch sự dùng です/ます.", good:"先生がいらっしゃいます。私が伺います。", bad:"先生が伺います。", question:"私が明日___。", answer:"伺います", choices:["いらっしゃいます","伺います"] }
  ]);
  const MORA = Object.freeze([
    {id:"long",label:"Trường âm",sample:"おばあさん",tip:"Kéo dài đúng một mora: お・ば・あ・さ・ん",parts:"お｜ば｜あ｜さ｜ん"},
    {id:"small-tsu",label:"Âm ngắt っ",sample:"きって",tip:"Giữ một nhịp ngắn trước phụ âm tiếp theo.",parts:"き｜っ｜て"},
    {id:"n",label:"Mora ん",sample:"しんぶん",tip:"ん chiếm một mora riêng, không nuốt mất nhịp.",parts:"し｜ん｜ぶ｜ん"},
    {id:"devoice",label:"Devoicing",sample:"すきです",tip:"Âm /u/ trong す có thể nhẹ đi; công cụ chỉ so transcript.",parts:"す｜き｜で｜す"},
    {id:"rhythm",label:"Nhịp mora",sample:"ありがとうございます",tip:"Gõ nhịp đều, không nhấn trọng âm kiểu tiếng Anh.",parts:"あ｜り｜が｜と｜う｜ご｜ざ｜い｜ま｜す"},
    {id:"link",label:"Nối âm tự nhiên",sample:"何をしていますか",tip:"Giữ trợ từ を và ranh giới mora rõ nhưng không ngắt câu vụn.",parts:"な｜に｜を｜し｜て｜い｜ま｜す｜か"}
  ]);
  const LIFE = Object.freeze([
    ["shop","Cửa hàng & nhà hàng","注文、会計、アレルギー","🛒"],["hospital","Bệnh viện","症状、保険証、薬","🏥"],["station","Ga tàu","乗り換え、遅延、出口","🚉"],
    ["city","Tòa thị chính","住民票、申請、窓口","🏛️"],["rent","Thuê nhà","契約、敷金、設備","🔑"],["bank","Ngân hàng","口座、振込、暗証番号","🏦"],
    ["career","Phỏng vấn & công việc","面接、担当、報告","💼"],["disaster","Phòng chống thiên tai","避難所、地震、備蓄","⛑️"],
    ["manners","Quy tắc ứng xử","ごみ、騒音、列","🙏"],["neighbor","Giao tiếp hàng xóm","挨拶、自治会、回覧板","🏠"]
  ].map(([id,title,kit,icon],index)=>({id,title,kit,icon,level:index<3?"A1":index<7?"A2":"B1"})));
  const esc = (value) => String(value ?? "").replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
  const ownerId = () => { try { const user=global.HHAuthSession?.user?.()||JSON.parse(localStorage.getItem("hh-auth-user")||"{}"); return String(user?.id||user?._id||"guest").replace(/[^a-z0-9_-]/gi,"").slice(0,80)||"guest"; } catch { return "guest"; } };
  const key = () => `${BASE_KEY}:${ownerId()}`;
  const day = () => new Date().toISOString().slice(0,10);
  const defaults = () => ({version:VERSION,activeTab:"today",mode:"adult",jlptLevel:"N5",jfLevel:"A1",goal:"life",dailyMinutes:15,largeText:false,reducedMotion:false,furigana:true,missionId:"restaurant",missionStep:0,missionProgress:{},savedWords:{},knownWords:{},hardWords:{},savedSentences:[],readerId:"",readerText:"",readerWordId:"",grammarId:"wa-ga",grammarResults:{},moraId:"long",moraAttempts:[],kanjiChar:"日",kanjiMistakes:{},jlptSection:"vocabulary",jlptHistory:[],lifeId:"shop",lifeProgress:{},xp:0,streak:0,lastStudy:"",tutorOpen:false,tutorHistory:[],offlinePacks:{}});
  function readState(){try{const raw=JSON.parse(localStorage.getItem(key())||"null");const old=JSON.parse(localStorage.getItem(`hh.japanese.state.v1:${ownerId()}`)||"null");return {...defaults(),...(raw&&typeof raw==="object"?raw:{}),xp:Number(raw?.xp??old?.xp??0),streak:Number(raw?.streak??old?.streak??0),missionProgress:raw?.missionProgress||{},savedWords:raw?.savedWords||old?.saved||{},knownWords:raw?.knownWords||{},hardWords:raw?.hardWords||{},grammarResults:raw?.grammarResults||{},kanjiMistakes:raw?.kanjiMistakes||{},jlptHistory:Array.isArray(raw?.jlptHistory)?raw.jlptHistory.slice(0,100):[],lifeProgress:raw?.lifeProgress||{},tutorHistory:Array.isArray(raw?.tutorHistory)?raw.tutorHistory.slice(0,30):[],savedSentences:Array.isArray(raw?.savedSentences)?raw.savedSentences.slice(0,100):[]};}catch{return defaults();}}
  function write(){if(!instance)return;localStorage.setItem(key(),JSON.stringify({...instance.state,version:VERSION,moraAttempts:instance.state.moraAttempts.slice(-50),tutorHistory:instance.state.tutorHistory.slice(-30),savedSentences:instance.state.savedSentences.slice(-100)}));}
  function study(xp=5){const s=instance.state,t=day();if(s.lastStudy!==t){const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);s.streak=s.lastStudy===yesterday?s.streak+1:1;s.lastStudy=t;}s.xp+=xp;}
  const checksum = value => {let hash=2166136261;for(const char of String(value)){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return (hash>>>0).toString(16).padStart(8,"0");};
  const ALL_WORDS = Object.freeze([...((legacy.words || [])), ...VIETNAMESE_PACK].filter((row, index, list) => list.findIndex(item => `${item.word}\u0000${item.kana || ""}` === `${row.word}\u0000${row.kana || ""}`) === index));
  const words = () => ALL_WORDS;
  const reviewedWords = () => ALL_WORDS.filter(row=>/^w\d+$/.test(row.id)||String(row.source||"").includes("thematic")||row.reviewStatus==="source-derived");
  const quality = row => row.meaningLanguage==="en"?{label:"Tham chiếu Anh · chưa kiểm duyệt Việt",tone:"reference",jlpt:false}:{label:row.exampleVi?"Việt · có ví dụ":"Việt · cần bổ sung ví dụ",tone:row.exampleVi?"reviewed":"draft",jlpt:/^N[1-5]$/.test(row.level)};
  function speak(text,rate=1){if(!global.speechSynthesis||!global.SpeechSynthesisUtterance)return false;global.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(String(text||""));utterance.lang="ja-JP";utterance.rate=rate;global.speechSynthesis.speak(utterance);return true;}
  function score(expected,actual){const a=String(expected||"").normalize("NFKC").replace(/[\s。、！？!?.,]/g,"");const b=String(actual||"").normalize("NFKC").replace(/[\s。、！？!?.,]/g,"");if(!a||!b)return 0;if(a.includes(b)||b.includes(a))return 100;const set=new Set([...a]);return Math.round([...b].filter(c=>set.has(c)).length/Math.max(a.length,b.length)*100);}
  function toast(message,tone="success"){const node=instance?.host.querySelector("[data-hhj3-toast]");if(!node)return;node.textContent=message;node.dataset.tone=tone;node.hidden=false;clearTimeout(instance.toastTimer);instance.toastTimer=setTimeout(()=>node.hidden=true,3200);}

  function metric(label,value,detail){return `<article class="hhj3-metric"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(detail)}</small></article>`;}
  function shell(content){const s=instance.state,mode=MODES[s.mode]||MODES.adult;return `<section class="hhj3-app ${s.largeText?"is-large":""} ${s.reducedMotion?"reduce-motion":""}">
    <header class="hhj3-top"><button class="hhj3-menu" data-hhj3-menu aria-label="Mở menu">☰</button><div class="hhj3-brand"><b>日</b><span><strong>HH Japanese OS</strong><small>V3 · học theo Can-do</small></span></div><div class="hhj3-route"><span>${TABS.find(x=>x[0]===s.activeTab)?.[1]||"Hôm nay"}</span><i>JLPT ${esc(s.jlptLevel)}</i><i>JF ${esc(s.jfLevel)}</i></div><button data-hhj3-tutor>✦ Gia sư</button><button data-hhj3-profile>${esc(mode[0])} ▾</button></header>
    <div class="hhj3-shell"><aside class="hhj3-nav" data-hhj3-nav><nav>${TABS.map(([id,label,icon],index)=>`<button data-hhj3-tab="${id}" class="${s.activeTab===id?"active":""}"><i>${icon}</i><span>${label}</span><kbd>${index===9?0:index+1}</kbd></button>`).join("")}</nav><footer><b>${s.streak} ngày</b><span>${s.xp} XP · tự lưu</span></footer></aside><main class="hhj3-main">${content}</main></div>
    ${s.tutorOpen?tutorPanel():""}<div class="hhj3-toast" data-hhj3-toast role="status" hidden></div></section>`;}

  function todayView(){const s=instance.state,done=Object.keys(s.missionProgress).length,review=Object.keys(s.savedWords).length;return `<section class="hhj3-view hhj3-today"><header class="hhj3-hero"><div><small>HÔM NAY · ${esc((MODES[s.mode]||MODES.adult)[0])}</small><h1>Học để <em>làm được</em><br>một việc bằng tiếng Nhật.</h1><p>JLPT theo dõi kiến thức; JF/CEFR theo dõi nhiệm vụ giao tiếp. Hai hệ tiến độ được giữ độc lập.</p><div><button class="primary" data-hhj3-tab="missions">Tiếp tục nhiệm vụ →</button><button data-hhj3-tab="vocabulary">Ôn ${review} từ đã lưu</button></div></div><aside><span>Mục tiêu hôm nay</span><strong>${Math.min(100,done*20)}%</strong><small>${done} nhiệm vụ đã hoàn thành</small></aside></header><div class="hhj3-metrics">${metric("JLPT",s.jlptLevel,"Từ vựng · ngữ pháp · đọc · nghe")}${metric("JF/CEFR",s.jfLevel,"Speaking và writing theo dõi riêng")}${metric("Kho dùng được",words().length.toLocaleString("vi-VN"),`${reviewedWords().length.toLocaleString("vi-VN")} nghĩa Việt · JMdict tham chiếu`)}${metric("Đang ôn",review,"Từ/cụm trong SRS")}</div><section class="hhj3-card hhj3-next"><header><div><small>CAN-DO TIẾP THEO</small><h2>${esc(MISSIONS.find(x=>x.id===s.missionId)?.title||MISSIONS[0].title)}</h2></div><span>10–15 phút</span></header><div class="hhj3-flow"><b>Tình huống</b><i>→</i><b>Từ/cụm</b><i>→</i><b>Mẫu câu</b><i>→</i><b>Nghe</b><i>→</i><b>Hội thoại</b><i>→</i><b>Nhiệm vụ</b><i>→</i><b>SRS</b></div><button class="primary" data-hhj3-tab="missions">Mở Mission Player</button></section><section class="hhj3-dual"><article><header><b>JLPT Knowledge</b><span>Không gồm nói/viết</span></header>${["Từ vựng","Ngữ pháp","Đọc","Nghe"].map((x,i)=>`<label>${x}<progress max="100" value="${Math.min(100,10+s.jlptHistory.length*8+i*4)}"></progress></label>`).join("")}</article><article><header><b>JF Can-do</b><span>Năng lực thực tế</span></header>${["Interaction","Speaking","Listening","Writing"].map((x,i)=>`<label>${x}<progress max="100" value="${Math.min(100,done*12+i*3)}"></progress></label>`).join("")}</article></section></section>`;}

  function missionsView(){const s=instance.state,m=MISSIONS.find(x=>x.id===s.missionId)||MISSIONS[0],step=Math.min(6,s.missionStep||0),labels=["Tình huống","Từ/cụm","Mẫu câu","Nghe","Hội thoại","Nhiệm vụ","Đưa vào SRS"];let body="";
    if(step===0)body=`<div class="hhj3-stage-intro"><b>${m.icon}</b><small>${m.level} · ${esc(m.place)}</small><h1>${esc(m.title)}</h1><p>Bạn sẽ hoàn thành một tình huống thật. Mỗi bước chỉ mở sau khi hoàn thành bước trước.</p></div>`;
    if(step===1)body=`<div class="hhj3-word-kit">${m.words.map(([word,kana,meaning])=>`<article><button data-hhj3-speak="${esc(word)}">▶</button><h2>${esc(word)}</h2><span>${esc(kana)}</span><strong>${esc(meaning)}</strong></article>`).join("")}</div>`;
    if(step===2)body=`<div class="hhj3-pattern"><small>MẪU CÂU CHÍNH</small><h1>${esc(m.pattern)}</h1><p>${esc(m.prompt)}</p><button data-hhj3-speak="${esc(m.pattern)}">▶ Nghe mẫu câu</button></div>`;
    if(step===3)body=`<div class="hhj3-listen"><button class="hhj3-orb" data-hhj3-speak="${esc(m.listen)}">▶</button><h2>Nghe câu trong tình huống</h2><p>Nghe ít nhất một lần rồi tiếp tục. Có thể nghe lại ở tốc độ chậm.</p><button data-hhj3-speak-slow="${esc(m.listen)}">0.8× Nghe chậm</button></div>`;
    if(step===4)body=`<div class="hhj3-dialog"><p><b>Nhân viên</b>${esc(m.listen)}</p><p><b>Bạn</b>${esc(m.pattern)}</p><button data-hhj3-speak="${esc(`${m.listen} ${m.pattern}`)}">▶ Nghe hội thoại</button></div>`;
    if(step===5)body=`<form class="hhj3-mission-form" data-hhj3-mission-check data-answer="${esc(m.answer)}"><small>NHIỆM VỤ CUỐI</small><h2>${esc(m.prompt)}</h2><textarea name="answer" lang="ja" required placeholder="Nhập câu trả lời bằng tiếng Nhật"></textarea><button class="primary">Hoàn thành nhiệm vụ</button><output></output></form>`;
    if(step===6)body=`<div class="hhj3-complete"><b>✓</b><h1>Can-do đã hoàn thành</h1><p>Từ và mẫu câu của nhiệm vụ có thể được lưu vào SRS. Tiến độ JF được cập nhật riêng với JLPT.</p><button class="primary" data-hhj3-mission-save>Lưu bộ từ vào SRS</button></div>`;
    return `<section class="hhj3-view hhj3-workspace"><aside class="hhj3-list"><header><small>CAN-DO MISSIONS</small><h2>Nhiệm vụ thực tế</h2></header>${MISSIONS.map(item=>`<button data-hhj3-mission="${item.id}" class="${item.id===m.id?"active":""}"><i>${item.icon}</i><span><strong>${esc(item.title)}</strong><small>${item.level} · ${esc(item.place)}</small></span>${s.missionProgress[item.id]?"✓":""}</button>`).join("")}</aside><article class="hhj3-player"><header><button data-hhj3-mission-back ${step===0?"disabled":""}>←</button><div>${labels.map((label,i)=>`<span class="${i===step?"active":i<step?"done":""}">${i<step?"✓":i+1}<small>${label}</small></span>`).join("")}</div><strong>${step+1}/7</strong></header><div class="hhj3-stage">${body}</div><footer><span>${step===6?"Sẵn sàng chuyển nhiệm vụ":"Hoàn thành bước hiện tại để tiếp tục"}</span>${step!==5&&step!==6?`<button class="primary" data-hhj3-mission-next>Tiếp tục →</button>`:""}</footer></article></section>`;}

  function vocabularyView(){const s=instance.state,q=String(instance.query||"").toLowerCase(),filter=instance.vocabFilter||"vi",rows=words().filter(row=>{const hay=[row.word,row.kana,row.romaji,row.meaning,row.example,row.topic].join(" ").toLowerCase();if(q&&!hay.includes(q))return false;if(filter==="vi"&&row.meaningLanguage==="en")return false;if(filter==="reference"&&row.meaningLanguage!=="en")return false;if(filter==="saved"&&!s.savedWords[row.id])return false;return true;}).slice(0,120);const selected=rows.find(x=>x.id===instance.wordId)||words().find(x=>x.id===instance.wordId)||rows[0];return `<section class="hhj3-view hhj3-workspace hhj3-vocab"><aside class="hhj3-list"><header><small>VIETNAMESE CORE 5000 · ${reviewedWords().length.toLocaleString("vi-VN")} CÓ NGHĨA VIỆT</small><h2>Kho dữ liệu có kiểm soát</h2><form data-hhj3-vocab-search><input name="query" value="${esc(instance.query||"")}" placeholder="Kanji, Kana, Romaji, nghĩa"><button>Tìm</button></form><select data-hhj3-vocab-filter><option value="vi" ${filter==="vi"?"selected":""}>Nghĩa Việt từ nguồn mở</option><option value="reference" ${filter==="reference"?"selected":""}>JMdict tham chiếu Anh</option><option value="saved" ${filter==="saved"?"selected":""}>Đã lưu SRS</option><option value="all" ${filter==="all"?"selected":""}>Tất cả ${words().length.toLocaleString("vi-VN")}</option></select></header><div class="hhj3-scroll-list">${rows.map(row=>`<button data-hhj3-word="${row.id}" class="${row.id===selected?.id?"active":""}"><span><strong>${esc(row.word)}</strong><small>${esc(row.kana)} · ${esc(row.meaning)}</small></span><i class="${quality(row).tone}">${row.level||"N?"}</i></button>`).join("")||"<p>Không tìm thấy từ phù hợp.</p>"}</div></aside>${selected?wordDetail(selected):"<article class=\"hhj3-empty\">Chọn một từ để xem.</article>"}</section>`;}
  function wordDetail(row){const s=instance.state,q=quality(row),chars=[...row.word].filter(c=>/[\u3400-\u9fff]/.test(c));return `<article class="hhj3-detail"><header><div><small>${esc(q.label)}</small><h1>${esc(row.word)}</h1><p>${esc(row.kana)}${row.romaji?` · ${esc(row.romaji)}`:""}</p></div><button data-hhj3-speak="${esc(row.word)}">▶ Nghe</button></header><section class="hhj3-meaning"><span>${esc(row.pos||"Chưa phân loại")}</span><h2>${esc(row.meaning)}</h2><p>${row.meaningLanguage==="en"?"Chưa có nghĩa Việt đã kiểm duyệt. Không tự dịch hoặc tự gán JLPT.":"Nghĩa Việt trong kho biên soạn; hãy dùng nút báo lỗi nếu cần hiệu chỉnh."}</p></section><div class="hhj3-data-grid"><section><small>VÍ DỤ NHẬT–VIỆT</small><b>${esc(row.example||"Đang bổ sung ví dụ đã kiểm duyệt.")}</b><span>${esc(row.exampleVi||"Chưa có bản dịch ví dụ.")}</span></section><section><small>JLPT & PITCH</small><b>${q.jlpt?esc(row.level):"Chưa xác minh"}</b><span>Pitch accent: chưa có nguồn được cấp phép trong gói này.</span></section><section><small>KANJI / RADICAL</small><b>${chars.map(esc).join(" · ")||"Không có Kanji"}</b><span>Mở Kanji Graph để xem liên kết đã có dữ liệu.</span></section><section><small>NGUỒN & PHIÊN BẢN</small><b>${esc(row.source||"HH Japanese curated core")}</b><span>Checksum ${checksum(JSON.stringify(row))}</span></section></div><footer><button data-hhj3-mark="known:${row.id}" class="${s.knownWords[row.id]?"active":""}">✓ Đã biết</button><button data-hhj3-mark="hard:${row.id}" class="${s.hardWords[row.id]?"active":""}">! Khó nhớ</button><button class="primary" data-hhj3-save-word="${row.id}">${s.savedWords[row.id]?"★ Đã lưu SRS":"☆ Thêm vào SRS"}</button></footer></article>`;}

  function annotate(text){const pool=reviewedWords().filter(w=>w.word.length>1&&text.includes(w.word)).sort((a,b)=>b.word.length-a.word.length);let at=0,html="",known=0,total=0;while(at<text.length){const hit=pool.find(w=>text.startsWith(w.word,at));if(hit){total++;if(instance.state.knownWords[hit.id])known++;html+=`<button data-hhj3-reader-word="${hit.id}">${esc(hit.word)}</button>`;at+=hit.word.length;}else{html+=esc(text[at]);at++;}}instance.coverage=total?Math.round(known/total*100):0;return html;}
  function readerView(){const s=instance.state,readings=legacy.readings||[],selected=readings.find(x=>x.id===s.readerId)||readings[0],text=s.readerText||selected?.text||"",html=annotate(text),word=words().find(x=>x.id===s.readerWordId);return `<section class="hhj3-view hhj3-reader"><aside class="hhj3-list"><header><small>SMART READER V2</small><h2>Nguồn đọc</h2></header>${[["story","Truyện ngắn"],["news","Tin đơn giản"],["life","Đời sống Nhật"],["licensed","Manga được cấp phép"],["custom","Văn bản của bạn"],["subtitle","Subtitle video"]].map(([id,label])=>`<button data-hhj3-reader-mode="${id}"><i>読</i><span><strong>${label}</strong><small>${id==="licensed"?"Chỉ nội dung có quyền sử dụng":"Chạm từ để tra và lưu câu"}</small></span></button>`).join("")}${readings.map(item=>`<button data-hhj3-reading="${item.id}" class="${item.id===selected?.id&&!s.readerText?"active":""}"><span><strong>${esc(item.title)}</strong><small>${item.level} · ${item.minutes} phút</small></span></button>`).join("")}</aside><article class="hhj3-reader-center"><header><div><small>ĐỘ PHỦ TỪ ĐÃ BIẾT</small><strong>${instance.coverage||0}%</strong></div><button data-hhj3-furigana>${s.furigana?"Ẩn":"Hiện"} Furigana đã thuộc</button><button data-hhj3-speak="${esc(text)}">▶ Nghe</button></header><div class="hhj3-reading-text ${s.furigana?"with-furigana":""}">${html||"Chọn bài đọc hoặc dán văn bản của bạn."}</div><footer><button data-hhj3-save-sentence>＋ Lưu cả câu vào SRS</button><button data-hhj3-reader-custom>Nhập văn bản / subtitle</button><span>Tokenizer từ điển cục bộ · không tuyên bố phân tích hình thái đầy đủ.</span></footer></article><aside class="hhj3-inspector">${word?wordInspector(word):"<div class=\"hhj3-empty\"><b>Chạm một từ</b><p>Dạng từ điển, cách đọc, nghĩa và trạng thái dữ liệu sẽ xuất hiện ở đây.</p></div>"}</aside></section>`;}
  function wordInspector(row){const q=quality(row);return `<div class="hhj3-word-inspector"><small>${esc(q.label)}</small><h1>${esc(row.word)}</h1><p>${esc(row.kana)} · ${esc(row.romaji||"")}</p><h2>${esc(row.meaning)}</h2><dl><dt>Dạng từ điển</dt><dd>${esc(row.word)}</dd><dt>Loại từ</dt><dd>${esc(row.pos||"Chưa xác định")}</dd><dt>JLPT</dt><dd>${q.jlpt?esc(row.level):"Chưa xác minh"}</dd><dt>Pitch</dt><dd>Chưa có dữ liệu được cấp phép</dd></dl><button data-hhj3-speak="${esc(row.word)}">▶ Nghe</button><button class="primary" data-hhj3-save-word="${row.id}">＋ Lưu từ</button></div>`;}

  function grammarView(){const s=instance.state,item=CONTRASTS.find(x=>x.id===s.grammarId)||CONTRASTS[0],result=s.grammarResults[item.id];return `<section class="hhj3-view hhj3-workspace"><aside class="hhj3-list"><header><small>GRAMMAR CONTRAST LAB</small><h2>Phân biệt để dùng đúng</h2></header>${CONTRASTS.map(row=>`<button data-hhj3-grammar="${row.id}" class="${row.id===item.id?"active":""}"><i>${row.level}</i><span><strong>${esc(row.title)}</strong><small>Bài sửa lỗi theo ngữ cảnh</small></span>${s.grammarResults[row.id]?.ok?"✓":""}</button>`).join("")}</aside><article class="hhj3-detail hhj3-grammar-detail"><header><div><small>${item.level} · CẤU TRÚC DỄ NHẦM</small><h1>${esc(item.title)}</h1></div></header><section><small>CÁCH DÙNG & SẮC THÁI</small><p>${esc(item.rule)}</p></section><div class="hhj3-example good"><b>✓ Ví dụ đúng</b><p>${esc(item.good)}</p></div><div class="hhj3-example bad"><b>× Cần sửa</b><p>${esc(item.bad)}</p></div><form data-hhj3-grammar-check data-id="${item.id}" data-answer="${esc(item.answer)}"><h2>${esc(item.question)}</h2><div>${item.choices.map(choice=>`<label><input type="radio" name="answer" value="${esc(choice)}" required><span>${esc(choice)}</span></label>`).join("")}</div><button class="primary">Kiểm tra</button><output>${result?result.ok?"✓ Chính xác":`Chưa đúng · Đáp án: ${esc(item.answer)}`:""}</output></form></article></section>`;}

  function moraView(){const s=instance.state,item=MORA.find(x=>x.id===s.moraId)||MORA[0],last=[...s.moraAttempts].reverse().find(x=>x.id===item.id);return `<section class="hhj3-view hhj3-workspace"><aside class="hhj3-list"><header><small>SHADOWING & MORA</small><h2>Nghe đúng nhịp Nhật</h2></header>${MORA.map(row=>`<button data-hhj3-mora="${row.id}" class="${row.id===item.id?"active":""}"><i>音</i><span><strong>${esc(row.label)}</strong><small>${esc(row.sample)}</small></span></button>`).join("")}</aside><article class="hhj3-mora-player"><header><small>${esc(item.label)}</small><h1>${esc(item.sample)}</h1><p>${esc(item.parts)}</p></header><section><div class="hhj3-wave">${item.parts.split("｜").map((x,i)=>`<i style="--h:${34+(i%3)*18}%"><b>${esc(x)}</b></i>`).join("")}</div><p>${esc(item.tip)}</p></section><div class="hhj3-mora-actions"><button data-hhj3-speak="${esc(item.sample)}">1. Nghe mẫu</button><button class="primary" data-hhj3-record="${esc(item.sample)}">2. Ghi âm & so transcript</button><button data-hhj3-speak-slow="${esc(item.sample)}">Nghe chậm</button></div><output class="hhj3-mora-output">${last?`Transcript: ${esc(last.transcript)} · Độ khớp chữ ${last.score}%`:"Micro chỉ bật khi bấm Ghi âm. Trình duyệt không chấm pitch/phoneme nếu chỉ có transcript."}</output><aside><b>Giới hạn minh bạch</b><p>Điểm trên là độ khớp văn bản do trình duyệt nhận dạng, không phải điểm phát âm, cao độ hay phoneme.</p></aside></article></section>`;}

  function kanjiView(){const s=instance.state,rows=legacy.kanji||[],item=rows.find(x=>x.char===s.kanjiChar)||rows[0],confuse={"未":"末","末":"未","土":"士","士":"土","待":"持","持":"待"}[item?.char]||"未 / 末 · 土 / 士 · 待 / 持";return `<section class="hhj3-view hhj3-kanji"><aside class="hhj3-list"><header><small>KNOWLEDGE GRAPH</small><h2>Học Kanji trong từ</h2></header><div class="hhj3-kanji-grid">${rows.map(row=>`<button data-hhj3-kanji="${row.char}" class="${row.char===item?.char?"active":""}"><b>${row.char}</b><small>${row.level}</small></button>`).join("")}</div><button data-hhj3-kanji-mistake="${item?.char}">! Đánh dấu hay viết sai (${s.kanjiMistakes[item?.char]||0})</button></aside><article class="hhj3-graph"><header><div><small>${item?.level} · ${item?.strokes} NÉT</small><h1>${item?.char}</h1><p>${item?.meanings?.map(esc).join(" · ")}</p></div><button data-hhj3-speak="${item?.char}">▶ Nghe</button></header><div class="hhj3-graph-map"><b>${item?.char}</b><span>Radical<strong>${esc(item?.radical)}</strong></span><span>Onyomi<strong>${item?.on?.map(esc).join("、")||"—"}</strong></span><span>Kunyomi<strong>${item?.kun?.map(esc).join("、")||"—"}</strong></span><span>Từ ghép<strong>${item?.examples?.map(esc).join(" · ")}</strong></span><span>Dễ nhầm<strong>${esc(confuse)}</strong></span></div><section class="hhj3-stroke"><header><div><b>Luyện từng nét</b><span>Bảng luyện không tự tuyên bố nhận dạng chính xác.</span></div><button data-hhj3-pad-clear>Xóa</button></header><canvas width="900" height="420" data-hhj3-pad aria-label="Bảng luyện Kanji"></canvas></section></article></section>`;}

  function sectionNames(level){return ["N1","N2","N3"].includes(level)?["Kiến thức ngôn ngữ","Đọc hiểu","Nghe hiểu"]:["Kiến thức + Đọc","Nghe hiểu"];}
  function makeQuestions(level,section){const curated=reviewedWords().filter(x=>x.level===level&&x.meaningLanguage!=="en").slice(0,12);const pool=curated.length>=4?curated:reviewedWords().filter(x=>x.meaningLanguage!=="en").slice(0,12);return pool.slice(0,6).map((row,i)=>{const opts=[row.meaning,...pool.filter(x=>x.id!==row.id).slice(i,i+3).map(x=>x.meaning)].filter(Boolean).slice(0,4);return {id:row.id,prompt:section==="listening"?"Nghe và chọn nghĩa phù hợp":`「${row.word}」の意味は何ですか。`,audio:section==="listening"?row.word:"",answer:row.meaning,options:[...new Set(opts)].sort((a,b)=>a.localeCompare(b,"vi"))};});}
  function jlptView(){const s=instance.state,section=s.jlptSection,questions=makeQuestions(s.jlptLevel,section),mock=section==="mock",names=sectionNames(s.jlptLevel),latest=s.jlptHistory.find(x=>x.level===s.jlptLevel);return `<section class="hhj3-view hhj3-jlpt"><header><div><small>JLPT SIMULATOR · NỘI DUNG TỰ BIÊN SOẠN</small><h1>Luyện đúng cấu trúc, không giả điểm chính thức</h1><p>${s.jlptLevel} có ${names.length} nhóm điểm: ${names.join(" · ")}. Phải đạt tổng điểm và điểm tối thiểu từng phần.</p></div><select data-hhj3-jlpt-level>${["N5","N4","N3","N2","N1"].map(x=>`<option ${x===s.jlptLevel?"selected":""}>${x}</option>`).join("")}</select></header><nav>${[["vocabulary","Vocabulary"],["grammar","Grammar"],["reading","Reading"],["listening","Listening"],["mock","Full Mock Test"]].map(([id,label])=>`<button data-hhj3-jlpt-section="${id}" class="${section===id?"active":""}">${label}</button>`).join("")}</nav><div class="hhj3-jlpt-meta">${metric("Cấp",s.jlptLevel,names.join(" + "))}${metric("Chế độ",mock?"Mock Test":"Practice",mock?"Không tạm dừng":"Có giải thích")}${metric("Thời gian",mock?"Theo cấu trúc mô phỏng":"Không giới hạn","Không sao chép đề chính thức")}${metric("Gần nhất",latest?`${latest.score}%`:"—","Ước tính luyện tập")}</div><form class="hhj3-test" data-hhj3-test data-section="${section}">${questions.map((q,i)=>`<fieldset data-answer="${esc(q.answer)}"><legend><b>${i+1}</b>${esc(q.prompt)}<button type="button" data-hhj3-flag="${q.id}" title="Đánh dấu xem lại">⚑</button></legend>${q.audio?`<button type="button" data-hhj3-speak="${esc(q.audio)}">▶ Nghe</button>`:""}${q.options.map(x=>`<label><input type="radio" name="q${i}" value="${esc(x)}" required><span>${esc(x)}</span></label>`).join("")}<output></output></fieldset>`).join("")}<footer><span>${mock?"Nộp bài để xem ước tính luyện tập":"Sai sẽ được đưa vào Mistake Notebook"}</span><button class="primary">Nộp bài</button><output data-hhj3-test-result></output></footer></form></section>`;}

  function lifeView(){const s=instance.state,item=LIFE.find(x=>x.id===s.lifeId)||LIFE[0],mission=MISSIONS.find(x=>x.id===item.id)||MISSIONS.find(x=>x.place.includes(item.title.split(" ")[0]));return `<section class="hhj3-view hhj3-workspace"><aside class="hhj3-list"><header><small>LIFE IN JAPAN TRACK</small><h2>Giao tiếp để sống & làm việc</h2></header>${LIFE.map(row=>`<button data-hhj3-life="${row.id}" class="${row.id===item.id?"active":""}"><i>${row.icon}</i><span><strong>${esc(row.title)}</strong><small>JF ${row.level}</small></span>${s.lifeProgress[row.id]?"✓":""}</button>`).join("")}</aside><article class="hhj3-life-detail"><header><b>${item.icon}</b><div><small>JF ${item.level} · CAN-DO</small><h1>${esc(item.title)}</h1><p>Thực hành bằng nhiệm vụ, không chỉ ghi nhớ danh sách từ.</p></div></header><section><small>BỘ TỪ TÌNH HUỐNG</small><h2>${esc(item.kit)}</h2></section><div class="hhj3-life-steps">${["Nhận diện biển báo/từ khóa","Nghe hội thoại ngắn","Chọn phản hồi phù hợp","Nói hoặc viết câu của bạn","Đánh dấu Can-do"].map((x,i)=>`<article><b>${i+1}</b><span>${x}</span></article>`).join("")}</div><footer>${mission?`<button data-hhj3-open-life-mission="${mission.id}">Mở nhiệm vụ liên quan</button>`:""}<button class="primary" data-hhj3-life-complete="${item.id}">${s.lifeProgress[item.id]?"✓ Đã hoàn thành":"Đánh dấu hoàn thành"}</button></footer></article></section>`;}

  function progressView(){const s=instance.state,missions=Object.keys(s.missionProgress).length,grammar=Object.values(s.grammarResults).filter(x=>x.ok).length;return `<section class="hhj3-view hhj3-progress"><header><div><small>DUAL PROGRESS MAP</small><h1>Hai bản đồ, không quy đổi sai</h1><p>JLPT phản ánh các kỹ năng bài thi đo; JF/CEFR phản ánh Can-do giao tiếp. Speaking, Writing và Interaction được theo dõi riêng.</p></div><button data-hhj3-export>↓ Xuất tiến độ JSON</button></header><div class="hhj3-progress-columns"><section><header><b>JLPT Knowledge Map</b><span>${s.jlptLevel}</span></header>${["Vocabulary","Grammar","Reading","Listening"].map((x,i)=>`<article><span>${x}</span><progress max="100" value="${Math.min(100,s.jlptHistory.length*12+grammar*5+i*3)}"></progress><b>${Math.min(100,s.jlptHistory.length*12+grammar*5+i*3)}%</b></article>`).join("")}<p>Kết quả là tiến độ nội bộ, không phải chứng chỉ hoặc điểm JLPT chính thức.</p></section><section><header><b>JF/CEFR Can-do Map</b><span>${s.jfLevel}</span></header>${[["Interaction",missions*14],["Speaking",missions*11],["Listening",missions*12],["Writing",Object.keys(s.lifeProgress).length*9]].map(([x,v])=>`<article><span>${x}</span><progress max="100" value="${Math.min(100,v)}"></progress><b>${Math.min(100,v)}%</b></article>`).join("")}<p>Không tuyên bố ${s.jlptLevel} tương đương tuyệt đối với JF ${s.jfLevel}.</p></section></div><section class="hhj3-provenance"><header><div><small>DATA QUALITY PIPELINE</small><h2>Vietnamese Core 5000</h2></div><button data-hhj3-offline>↓ Lưu gói Việt nguồn mở offline</button></header><div>${metric("Mục tiêu","5.000","Kiểm duyệt theo độ phổ biến")}${metric("Hiện có",reviewedWords().length.toLocaleString("vi-VN"),"Việt biên soạn + Kaikki nguồn mở")}${metric("Tham chiếu",words().filter(x=>x.meaningLanguage==="en").length.toLocaleString("vi-VN"),"JMdict · không tự dịch")}${metric("Checksum",checksum(reviewedWords().map(x=>x.id).join("|")),"Phiên bản V4 data pack")}</div><p>Mỗi mục hiển thị nguồn, trạng thái nghĩa, JLPT và pitch. Kaikki/Wiktionary là dữ liệu nguồn mở cần biên tập tiếp; trường chưa có nguồn đáng tin cậy được ghi “Chưa xác minh”.</p></section></section>`;}

  function profileView(){const s=instance.state;return `<section class="hhj3-view hhj3-profile"><header><small>UNIVERSAL LEARNER PROFILE</small><h1>HH Japanese cho mọi người</h1><p>Đổi chế độ không làm mất tiến độ SRS, JLPT hoặc Can-do.</p></header><form data-hhj3-profile-form><section><h2>Chế độ trải nghiệm</h2><div class="hhj3-mode-grid">${Object.entries(MODES).map(([id,[label,detail,count]])=>`<label><input type="radio" name="mode" value="${id}" ${s.mode===id?"checked":""}><span><strong>${label}</strong><small>${detail}</small><b>${count} từ/bài</b></span></label>`).join("")}</div></section><section class="hhj3-profile-fields"><label>JLPT hiện tại<select name="jlptLevel">${["N5","N4","N3","N2","N1"].map(x=>`<option ${x===s.jlptLevel?"selected":""}>${x}</option>`).join("")}</select></label><label>JF/CEFR hiện tại<select name="jfLevel">${["A1","A2","B1","B2","C1","C2"].map(x=>`<option ${x===s.jfLevel?"selected":""}>${x}</option>`).join("")}</select></label><label>Mục tiêu<select name="goal"><option value="life">Đời sống Nhật</option><option value="jlpt">JLPT</option><option value="study">Du học</option><option value="work">Công việc</option><option value="conversation">Giao tiếp</option></select></label><label>Phút mỗi ngày<input type="number" name="dailyMinutes" min="5" max="90" value="${s.dailyMinutes}"></label></section><section class="hhj3-support"><h2>Hỗ trợ tiếp cận</h2><label><input type="checkbox" name="largeText" ${s.largeText?"checked":""}> Chữ và vùng bấm lớn</label><label><input type="checkbox" name="reducedMotion" ${s.reducedMotion?"checked":""}> Giảm chuyển động</label><p>Little Kids/Kids dùng gia sư có hướng dẫn; không mở chat tự do.</p></section><button class="primary">Lưu hồ sơ</button></form></section>`;}
  function tutorPanel(){const s=instance.state,isChild=["little","kids"].includes(s.mode);return `<aside class="hhj3-tutor"><header><div><small>AI JAPANESE TUTOR</small><b>Gia sư có giới hạn</b></div><button data-hhj3-tutor-close>×</button></header><div class="hhj3-tutor-log">${s.tutorHistory.map(x=>`<p class="${x.role}"><b>${x.role==="user"?"Bạn":"Gia sư"}</b>${esc(x.text)}</p>`).join("")||`<div class="hhj3-empty"><b>${isChild?"Chọn một hoạt động có hướng dẫn":"Nhập câu cần giải thích hoặc sửa"}</b><p>Không tự gán JLPT/pitch. Bản gốc luôn được giữ để so sánh.</p></div>`}</div>${isChild?`<div class="hhj3-guided">${["Giải thích mẫu câu đang học","Luyện lại từ sai","Tạo câu hỏi từ bài hiện tại"].map(x=>`<button data-hhj3-guided="${x}">${x}</button>`).join("")}</div>`:`<form data-hhj3-tutor-form><textarea name="message" maxlength="800" required placeholder="Ví dụ: sửa câu 私は昨日学校に行きます"></textarea><button class="primary">Giải thích có nguồn</button></form>`}<footer>Dùng kho từ/ngữ pháp cục bộ trước; HH AI chỉ chạy khi hệ thống đã cấu hình.</footer></aside>`;}

  function view(){switch(instance.state.activeTab){case"missions":return missionsView();case"vocabulary":return vocabularyView();case"reader":return readerView();case"grammar":return grammarView();case"mora":return moraView();case"kanji":return kanjiView();case"jlpt":return jlptView();case"life":return lifeView();case"progress":return progressView();case"profile":return profileView();default:return todayView();}}
  function render(){instance.host.innerHTML=shell(view());setupPad();}
  function navigate(tab){instance.state.activeTab=tab;write();render();}
  function setupPad(){const canvas=instance.host.querySelector("[data-hhj3-pad]");if(!canvas)return;const ctx=canvas.getContext("2d");ctx.lineWidth=8;ctx.lineCap="round";ctx.strokeStyle="#e4585e";let drawing=false;const point=e=>{const r=canvas.getBoundingClientRect();return[(e.clientX-r.left)*canvas.width/r.width,(e.clientY-r.top)*canvas.height/r.height];};canvas.onpointerdown=e=>{drawing=true;ctx.beginPath();ctx.moveTo(...point(e));canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drawing)return;ctx.lineTo(...point(e));ctx.stroke();};canvas.onpointerup=canvas.onpointercancel=()=>drawing=false;}
  async function record(expected){const Recognition=global.SpeechRecognition||global.webkitSpeechRecognition;if(!Recognition)throw new Error("Trình duyệt chưa hỗ trợ nhận dạng giọng nói tiếng Nhật.");const rec=new Recognition();rec.lang="ja-JP";rec.interimResults=false;return new Promise((resolve,reject)=>{rec.onresult=e=>resolve(e.results[0][0].transcript);rec.onerror=e=>reject(new Error(`Không thể nhận giọng nói: ${e.error}`));rec.start();});}
  async function cacheOffline(){const data={version:VERSION,createdAt:new Date().toISOString(),source:"HH Japanese curated + Kaikki/Wiktionary viwiktionary",license:"CC BY-SA 4.0 / GFDL · source-derived entries require attribution",checksum:checksum(reviewedWords().map(x=>x.id).join("|")),words:reviewedWords().slice(0,5000)};if(!global.indexedDB)throw new Error("Trình duyệt không hỗ trợ IndexedDB.");await new Promise((resolve,reject)=>{const req=indexedDB.open("hh-japanese-os",1);req.onupgradeneeded=()=>req.result.createObjectStore("packs");req.onerror=()=>reject(req.error);req.onsuccess=()=>{const tx=req.result.transaction("packs","readwrite");tx.objectStore("packs").put(data,"vi-core");tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);};});instance.state.offlinePacks.viCore={checksum:data.checksum,at:data.createdAt,count:data.words.length};write();}
  function localTutor(text){const hits=reviewedWords().filter(x=>text.includes(x.word)).slice(0,5);const grammar=CONTRASTS.find(x=>text.includes(x.title.split(" và ")[0]))||CONTRASTS.find(x=>text.includes(x.answer));const parts=[`Bản gốc: ${text}`];if(hits.length)parts.push(`Từ nhận diện: ${hits.map(x=>`${x.word} (${x.meaning})`).join("; ")}.`);if(grammar)parts.push(`Ngữ pháp liên quan: ${grammar.title} — ${grammar.rule}`);if(!hits.length&&!grammar)parts.push("Chưa đủ mục từ/ngữ pháp có nguồn trong kho cục bộ để giải thích chắc chắn. Không tự gán JLPT hoặc pitch accent.");return parts.join("\n");}

  async function click(event){const b=event.target.closest("button");if(!b)return;
    if(b.dataset.hhj3Tab)return navigate(b.dataset.hhj3Tab);
    if(b.matches("[data-hhj3-menu]")){instance.host.querySelector("[data-hhj3-nav]")?.classList.toggle("open");return;}
    if(b.matches("[data-hhj3-profile]"))return navigate("profile");
    if(b.matches("[data-hhj3-tutor]")){instance.state.tutorOpen=true;write();render();return;}
    if(b.matches("[data-hhj3-tutor-close]")){instance.state.tutorOpen=false;write();render();return;}
    if(b.dataset.hhj3Speak!==undefined){if(!speak(b.dataset.hhj3Speak))toast("Thiết bị chưa hỗ trợ giọng đọc.","error");return;}
    if(b.dataset.hhj3SpeakSlow!==undefined){speak(b.dataset.hhj3SpeakSlow,.8);return;}
    if(b.dataset.hhj3Mission){instance.state.missionId=b.dataset.hhj3Mission;instance.state.missionStep=instance.state.missionProgress[b.dataset.hhj3Mission]?6:0;write();render();return;}
    if(b.matches("[data-hhj3-mission-next]")){instance.state.missionStep=Math.min(6,instance.state.missionStep+1);study(2);write();render();return;}
    if(b.matches("[data-hhj3-mission-back]")){instance.state.missionStep=Math.max(0,instance.state.missionStep-1);write();render();return;}
    if(b.matches("[data-hhj3-mission-save]")){const m=MISSIONS.find(x=>x.id===instance.state.missionId);m.words.forEach(([word])=>{const row=words().find(x=>x.word===word);if(row)instance.state.savedWords[row.id]={at:new Date().toISOString(),source:`mission:${m.id}`};});instance.state.missionProgress[m.id]={at:new Date().toISOString(),jf:m.level};study(20);write();toast("Đã lưu Can-do và bộ từ vào SRS.");render();return;}
    if(b.dataset.hhj3Word){instance.wordId=b.dataset.hhj3Word;render();return;}
    if(b.dataset.hhj3SaveWord){const id=b.dataset.hhj3SaveWord;if(instance.state.savedWords[id])delete instance.state.savedWords[id];else instance.state.savedWords[id]={at:new Date().toISOString(),dueAt:new Date().toISOString()};study(2);write();render();return;}
    if(b.dataset.hhj3Mark){const [kind,id]=b.dataset.hhj3Mark.split(":");const map=kind==="known"?instance.state.knownWords:instance.state.hardWords;if(map[id])delete map[id];else map[id]=true;write();render();return;}
    if(b.dataset.hhj3Reading){instance.state.readerId=b.dataset.hhj3Reading;instance.state.readerText="";write();render();return;}
    if(b.dataset.hhj3ReaderWord){instance.state.readerWordId=b.dataset.hhj3ReaderWord;write();render();return;}
    if(b.matches("[data-hhj3-furigana]")){instance.state.furigana=!instance.state.furigana;write();render();return;}
    if(b.matches("[data-hhj3-reader-custom]")){const value=prompt("Dán văn bản tiếng Nhật hoặc subtitle (tối đa 10.000 ký tự):",instance.state.readerText||"");if(value!==null){instance.state.readerText=String(value).slice(0,10000);write();render();}return;}
    if(b.matches("[data-hhj3-save-sentence]")){const text=instance.state.readerText||(legacy.readings||[]).find(x=>x.id===instance.state.readerId)?.text||"";if(text&&!instance.state.savedSentences.some(x=>x.text===text))instance.state.savedSentences.push({text,at:new Date().toISOString()});study(4);write();toast("Đã lưu câu/bài đọc vào SRS.");return;}
    if(b.dataset.hhj3Grammar){instance.state.grammarId=b.dataset.hhj3Grammar;write();render();return;}
    if(b.dataset.hhj3Mora){instance.state.moraId=b.dataset.hhj3Mora;write();render();return;}
    if(b.dataset.hhj3Record!==undefined){b.disabled=true;b.textContent="Đang nghe…";try{const transcript=await record(b.dataset.hhj3Record);const value=score(b.dataset.hhj3Record,transcript);instance.state.moraAttempts.push({id:instance.state.moraId,transcript,score:value,at:new Date().toISOString()});study(value>=80?10:3);write();render();}catch(error){toast(error.message,"error");b.disabled=false;b.textContent="2. Ghi âm & so transcript";}return;}
    if(b.dataset.hhj3Kanji){instance.state.kanjiChar=b.dataset.hhj3Kanji;write();render();return;}
    if(b.dataset.hhj3KanjiMistake){instance.state.kanjiMistakes[b.dataset.hhj3KanjiMistake]=(instance.state.kanjiMistakes[b.dataset.hhj3KanjiMistake]||0)+1;write();render();return;}
    if(b.matches("[data-hhj3-pad-clear]")){const c=instance.host.querySelector("[data-hhj3-pad]");c?.getContext("2d")?.clearRect(0,0,c.width,c.height);return;}
    if(b.dataset.hhj3JlptSection){instance.state.jlptSection=b.dataset.hhj3JlptSection;write();render();return;}
    if(b.dataset.hhj3Flag){b.classList.toggle("active");return;}
    if(b.dataset.hhj3Life){instance.state.lifeId=b.dataset.hhj3Life;write();render();return;}
    if(b.dataset.hhj3LifeComplete){instance.state.lifeProgress[b.dataset.hhj3LifeComplete]={at:new Date().toISOString()};study(12);write();render();return;}
    if(b.dataset.hhj3OpenLifeMission){instance.state.missionId=b.dataset.hhj3OpenLifeMission;instance.state.missionStep=0;return navigate("missions");}
    if(b.matches("[data-hhj3-offline]")){b.disabled=true;b.textContent="Đang lưu…";try{await cacheOffline();toast("Đã lưu gói Việt vào IndexedDB.");render();}catch(error){toast(error.message,"error");b.disabled=false;}return;}
    if(b.matches("[data-hhj3-export]")){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),ownerId:ownerId(),state:instance.state},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`hh-japanese-v3-${day()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0);return;}
    if(b.dataset.hhj3Guided){const reply=localTutor(b.dataset.hhj3Guided);instance.state.tutorHistory.push({role:"user",text:b.dataset.hhj3Guided},{role:"assistant",text:reply});write();render();return;}
  }
  function change(event){if(event.target.matches("[data-hhj3-vocab-filter]")){instance.vocabFilter=event.target.value;render();}if(event.target.matches("[data-hhj3-jlpt-level]")){instance.state.jlptLevel=event.target.value;write();render();}}
  async function submit(event){event.preventDefault();const form=event.target;
    if(form.matches("[data-hhj3-vocab-search]")){instance.query=form.elements.query.value.trim();render();return;}
    if(form.matches("[data-hhj3-mission-check]")){const actual=form.elements.answer.value,value=score(form.dataset.answer,actual),out=form.querySelector("output");out.textContent=value>=75?`✓ Hoàn thành · khớp nội dung ${value}%`:`Chưa đủ ý · gợi ý: ${form.dataset.answer}`;if(value>=75){instance.state.missionStep=6;study(10);write();setTimeout(render,550);}return;}
    if(form.matches("[data-hhj3-grammar-check]")){const ok=form.elements.answer.value===form.dataset.answer;instance.state.grammarResults[form.dataset.id]={ok,at:new Date().toISOString()};study(ok?8:2);write();render();return;}
    if(form.matches("[data-hhj3-test]")){let correct=0;const fields=[...form.querySelectorAll("fieldset")];fields.forEach((field,i)=>{const value=form.elements[`q${i}`]?.value,ok=value===field.dataset.answer;if(ok)correct++;field.querySelector("output").textContent=ok?"✓ Đúng":`✕ Đáp án: ${field.dataset.answer}`;});const pct=Math.round(correct/Math.max(1,fields.length)*100);instance.state.jlptHistory.unshift({level:instance.state.jlptLevel,section:form.dataset.section,score:pct,at:new Date().toISOString()});study(correct*4);write();form.querySelector("[data-hhj3-test-result]").textContent=`${pct}% · ước tính luyện tập`;return;}
    if(form.matches("[data-hhj3-profile-form]")){const data=new FormData(form);instance.state.mode=MODES[data.get("mode")]?data.get("mode"):"adult";instance.state.jlptLevel=String(data.get("jlptLevel"));instance.state.jfLevel=String(data.get("jfLevel"));instance.state.goal=String(data.get("goal"));instance.state.dailyMinutes=Math.max(5,Math.min(90,Number(data.get("dailyMinutes"))||15));instance.state.largeText=data.has("largeText");instance.state.reducedMotion=data.has("reducedMotion");write();navigate("today");toast("Đã lưu hồ sơ người học.");return;}
    if(form.matches("[data-hhj3-tutor-form]")){const text=form.elements.message.value.trim();instance.state.tutorHistory.push({role:"user",text});let reply=localTutor(text);if(instance.options.runAI){try{const result=await instance.options.runAI({task:"japanese-tutor-bounded",text,instruction:"Giải thích bằng tiếng Việt dựa trên mục từ/ngữ pháp có nguồn. Giữ nguyên câu gốc. Không tự gán JLPT hoặc pitch accent. Nếu không chắc, nói rõ chưa đủ dữ liệu."});reply=String(result?.text||result?.output||result||reply);}catch{reply+=`\nHH AI chưa phản hồi; đây là phân tích cục bộ.`;}}instance.state.tutorHistory.push({role:"assistant",text:reply});write();render();return;}
  }
  let instance=null;
  function mount(host,options={}){unmount();if(!host)return;const oldHash=location.hash.match(/^#\/japanese\/?([^/?#]*)/)?.[1];instance={host,options,state:readState(),query:"",vocabFilter:"vi",wordId:"",coverage:0,controller:new AbortController(),toastTimer:0};if(TABS.some(x=>x[0]===oldHash))instance.state.activeTab=oldHash;host.addEventListener("click",e=>click(e).catch(error=>toast(error.message,"error")),{signal:instance.controller.signal});host.addEventListener("change",change,{signal:instance.controller.signal});host.addEventListener("submit",e=>submit(e).catch(error=>toast(error.message,"error")),{signal:instance.controller.signal});global.addEventListener("keydown",hotkeys,{signal:instance.controller.signal});render();}
  function hotkeys(event){if(event.ctrlKey||event.metaKey||event.altKey||/INPUT|TEXTAREA|SELECT/.test(event.target?.tagName))return;const n=Number(event.key);if(Number.isInteger(n)){const index=n===0?9:n-1;if(TABS[index])navigate(TABS[index][0]);}}
  function unmount(){if(!instance)return;instance.controller.abort();clearTimeout(instance.toastTimer);global.speechSynthesis?.cancel?.();instance=null;}
  global.HHJapaneseOSV3=Object.freeze({version:VERSION,tabs:TABS,missions:MISSIONS,contrasts:CONTRASTS,mora:MORA,life:LIFE,checksum,quality,defaults});
  global.HHJapanese=Object.freeze({...legacy,mount,unmount,osVersion:VERSION});
})();
