/* Original Patin overview. Reads existing local data; filters use the same store, never a second search/auth system. */
(function(root,factory){const api=factory(root,typeof module==='object'&&module.exports?require('./patin-data'):root.HHPatinData,typeof module==='object'&&module.exports?require('./patin-core'):root.HHPatinCore,typeof module==='object'&&module.exports?require('./patin-guide'):root.HHPatinGuide);if(typeof module==='object'&&module.exports)module.exports=api;else root.HHPatinHome=api;})(typeof globalThis!=='undefined'?globalThis:this,function(scope,D,C,G){
 'use strict';
 const e=C.escape,lesson=id=>D.skills.find(s=>s.id===id),link=(r,t,cls='pt-chip')=>'<a class="'+cls+'" href="#'+r+'" data-app-route="'+r+'">'+e(t)+'</a>',skillLink=id=>lesson(id)?link('/patin/skills/'+id,lesson(id).title):'';
 const paths=[['foundation','Chuẩn bị nền tảng','Giày, tư thế, di chuyển và cách dừng đã được hướng dẫn.','/patin/path'],...D.disciplines.map(d=>[d.id,d.label,d.stages[0].title,'/patin/'+d.id]),['quad','Quad & nghệ thuật','Thiết bị và định hướng riêng; không áp dụng nguyên xi kỹ thuật inline.','/patin/skills']];
 function facts(registry=D){const skills=registry.skills||[],videos=registry.videos||[],ids=new Set(skills.map(s=>s.id)),direct=new Set(videos.flatMap(v=>v.skillIds).filter(id=>ids.has(id))),verified=C.arena.catalog().filter(r=>r.reference&&ids.has(r.id));return {lessons:skills.length,videos:videos.length,categories:registry.categories.length,levels:registry.levels.length,illustrated:skills.filter(s=>G.guide(s.id)).length,direct:direct.size,verified:verified.length,rulebooks:registry.arena.systems.length};}
 function recommendations(state){
  const chosen=[],push=(id,reason)=>{const s=lesson(id);if(s&&!chosen.some(x=>x.id===id)&&chosen.length<3)chosen.push({id,title:s.title,reason,route:'/patin/skills/'+id,orientation:s.scope==='orientation'});};
  if(state.lastSkill&&!state.progress[state.lastSkill]?.read)push(state.lastSkill,'Bài bạn mở gần nhất và chưa đánh dấu đã đọc; chỉ là gợi ý tiếp tục đọc.');
  for(const id of state.favorites)if(!state.progress[id]?.read)push(id,'Bạn đã lưu bài này và chưa đánh dấu đã đọc. Yêu thích không xác nhận đủ nền tảng thực hành.');
  for(const phase of D.pathway)for(const id of phase.ids)if(!state.progress[id]?.read)push(id,'Bài chưa đánh dấu đã đọc trong lộ trình hiện có: '+phase.title+'. Không khóa bài khác hoặc suy ra khả năng thể chất.');
  if(!chosen.length)for(const id of state.favorites.concat(state.lastSkill||[],D.pathway[0].ids))push(id,'Gợi ý đọc lại từ bài đã lưu/gần đây hoặc nền tảng. Đã đọc không đồng nghĩa thành thạo.');
  return chosen;
 }
 function prepareLibrary(state,options={}){const allowed=['method','discipline','category','level','favorites','status'];if(Object.keys(options).some(k=>!allowed.includes(k)))throw Error('Không hỗ trợ bộ lọc này.');C.setLibrary(state,{query:'',category:'all',discipline:'all',level:'all',favorites:false,mode:state.workshop.library.mode,status:'all',sort:state.workshop.library.sort,page:1,method:'all',...options});}
 function stats(s){const v=C.summary(s);return '<div class="pt-stats" aria-label="Tự ghi nhận trên thiết bị"><span><b>'+v.read+'/'+D.skills.length+'</b> Đã đọc</span><span><b>'+v.tried+'</b> Đã thử · tự ghi</span><span><b>'+v.sessions+'</b> Buổi tự ghi</span><span><b>'+v.minutes+'</b> Phút đã tự nhập</span></div>';}
 const tile=(name,kicker,body,footer,tone='cyan')=>'<article class="pt-card pth-card" data-tone="'+tone+'"><p class="pt-kicker">'+kicker+'</p><h3>'+name+'</h3>'+body+'<div class="pth-card-actions">'+footer+'</div></article>';
 function personal(s){
  const last=lesson(s.lastSkill),video=D.videos.find(v=>v.id===s.workshop.videos.lastVideo),p=s.workshop.plan,a=s.workshop.arena,r=a.routine,prep=a.preparation,notes=Object.entries(s.progress).filter(([,p])=>p.note.trim()).slice(-3).reverse(),journal=[...s.journal].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3),favorites=D.skills.filter(x=>s.favorites.includes(x.id)),vf=D.videos.filter(v=>s.workshop.videos.favorites.includes(v.id)),hasPrep=prep.event||prep.notes||prep.date||prep.url||prep.checked.length;
  return stats(s)+'<div class="pth-personal-grid">'+
   tile('Tiếp tục từ nơi bạn dừng','CONTINUE YOUR FLOW',(last?'<p>'+skillLink(last.id)+'</p>':'<p>Chưa mở bài nào. Hãy chọn một bài nền tảng để bắt đầu đọc.</p>')+(video?'<p>'+link('/patin/videos/'+video.id,video.title)+'</p>':'<p class="pt-muted">Chưa chọn video; trình phát luôn chờ thao tác của bạn.</p>'),link('/patin/skills','Thư viện bài học'))+
   tile('Kế hoạch buổi tới','NEXT SESSION',p?'<p><strong>'+e(p.title||'Kế hoạch riêng')+'</strong></p><p>'+e(p.date||'Chưa đặt ngày')+' · '+p.minutes+' phút dự kiến, không phải thời lượng đã tập.</p><div class="pt-chips">'+p.skills.map(skillLink).join('')+'</div>':'<p>Chưa có kế hoạch. Ghi mục tiêu và bài muốn trao đổi với HLV; không tự tăng tải tập từ số liệu ứng dụng.</p>',link('/patin/path',p?'Chỉnh kế hoạch':'Tạo kế hoạch'),'gold')+
   tile('Tổ hợp đang soạn','ROUTINE DRAFT',r.items.length||r.title?'<p><strong>'+e(r.title||'Tổ hợp riêng')+'</strong> · '+r.items.length+' mục</p><div class="pt-chips">'+r.items.slice(0,3).map(it=>skillLink(it.skillId)).join('')+'</div><p class="pt-muted">Dự thảo và câu hỏi; không cộng điểm từ tên động tác.</p>':'<p>Chưa có tổ hợp. Chọn các bài đã trao đổi với HLV và ghi phần chuyển nối.</p>',link('/patin/routine',r.items.length?'Tiếp tục tổ hợp':'Tạo tổ hợp'),'violet')+
   tile('Chuẩn bị sự kiện','EVENT CHECKLIST',hasPrep?'<p><strong>'+e(prep.event||'Checklist riêng')+'</strong></p><p>'+e(prep.date||'Chưa đặt ngày')+' · '+prep.checked.length+'/'+D.arena.checklist.length+' mục tự đánh dấu</p><p class="pt-muted">Đối chiếu điều lệ của sự kiện, không phải xác nhận đăng ký.</p>':'<p>Chưa ghi sự kiện. Lưu liên kết điều lệ, ngày dự kiến và câu hỏi cho ban tổ chức; không lưu giấy tờ nhạy cảm.</p>',link('/patin/routine','Mở checklist'),'orange')+
   tile('Bài & video đã lưu','FAVORITES','<p>'+favorites.length+' bài · '+vf.length+' video yêu thích</p><div class="pt-chips">'+favorites.slice(0,3).map(x=>skillLink(x.id)).join('')+vf.slice(0,2).map(v=>link('/patin/videos/'+v.id,v.title)).join('')+'</div>'+(!favorites.length&&!vf.length?'<p>Chưa có yêu thích. Dùng nút sao trong bài hoặc Video Studio để lưu.</p>':''),'<button type="button" data-pth-library data-favorites="true">Mở bài yêu thích</button>'+link('/patin/videos','Thư viện video'),'magenta')+
   tile('Ghi chú mang tới HLV','COACH QUESTIONS',notes.length?notes.map(([id,p])=>'<section>'+skillLink(id)+'<p class="pt-user-text">'+e(p.note.slice(0,180))+(p.note.length>180?'…':'')+'</p></section>').join('')+'<p class="pt-muted">Một số ghi chú đang lưu, không suy ra thứ tự chỉnh sửa.</p>':'<p>Chưa có ghi chú. Sau khi đọc hoặc xem, ghi điều chưa rõ trong bài để hỏi HLV.</p>',link('/patin/skills','Mở bài để ghi chú'))+
   tile('Nhật ký đã ghi','REAL MANUAL LOG',journal.length?journal.map(j=>'<section><strong>'+e(j.date)+' · '+j.minutes+' phút tự nhập</strong><p class="pt-user-text">'+e(j.note.slice(0,130)||'Không có ghi chú')+'</p></section>').join(''):'<p>Chưa có buổi đã ghi. Chỉ lưu thời lượng bạn thực sự đã tập; xem bài hoặc chạy timer không tự tạo buổi.</p>',link('/patin/journal',journal.length?'Xem nhật ký':'Ghi một buổi đã tập'),'cyan')+'</div>';
 }
 function suggestionMarkup(s){return recommendations(s).map(x=>tile(x.title,'GỢI Ý ĐỌC · KHÔNG ĐÁNH GIÁ NĂNG LỰC','<p>'+e(x.reason)+'</p>'+(x.orientation?'<p class="pt-muted">Chuyên sâu: chỉ định hướng, cần HLV và điều kiện phù hợp.</p>':''),link(x.route,'Mở bài'))).join('');}
 function markup(s,skateArt=''){
  const f=facts();
  const portals=[['skills','Thư viện kỹ năng',f.lessons+' bài · '+f.categories+' nhóm · '+f.levels+' mức tiếp cận HH'],['videos','Video Studio',f.videos+' video có nguồn, liên kết trực tiếp với '+f.direct+' bài'],['studio','Minh họa tương tác',f.illustrated+' thẻ khái niệm và sơ đồ nền tảng'],['map','Bản đồ kỹ năng','Xem nền tảng gợi ý, không khóa bài bằng tiến trình'],['competition','Góc thi đấu',f.verified+' ví dụ được đối chiếu · không phải leaderboard'],['routine','Tổ hợp & checklist','Kéo thả, ghi phần nối và xuất TXT'],['path','Lộ trình & kế hoạch','Tách dự kiến với thời lượng đã tập'],['gear','Giày & an toàn','Setup theo model, bảo hộ và sân phù hợp'],['journal','Nhật ký & sao lưu','Tự ghi, bản nháp, CSV/JSON và bảo vệ xung đột'],['resources','Tra cứu & nguồn',D.glossary.length+' thuật ngữ · '+D.faq.length+' câu hỏi']];
  return '<section class="pth-root"><section class="pt-hero pth-hero"><div class="pth-hero-copy"><p class="pt-kicker">HH PATIN / 3D COMMAND ARENA</p><h2>Chọn nhịp của bạn.<br><span>Học rõ. Lăn có kiểm soát.</span></h2><p>Nền tảng, Speed, Slide và Slalom — một bàn điều khiển để đọc, quan sát và chuẩn bị buổi học cùng HLV.</p><div class="pt-actions">'+link('/patin/skills','Khám phá '+f.lessons+' kỹ năng & bài học','pt-primary')+link('/patin/videos','Học qua video','pt-secondary')+link('/patin/competition','Tra cứu thi đấu','pt-secondary')+'</div><div class="pth-facts" aria-label="Nội dung thư viện"><span><b>'+f.lessons+'</b> bài đang có</span><span><b>'+f.videos+'</b> video có nguồn</span><span><b>'+f.illustrated+'</b> thẻ hình khái niệm</span></div></div><figure class="pth-hero-figure"><div class="pth-scene" data-pth-scene role="img" aria-label="Mô hình giày inline, bánh và cọc trên sân thu nhỏ, chỉ minh họa cách điệu"><div class="pth-scene-fallback" aria-hidden="true"><span class="pta-lane"></span>'+skateArt+'<span class="pth-fallback-cones">▲ ▲ ▲</span></div></div><figcaption data-pth-scene-status role="status">Minh họa SVG sẵn sàng · đang chuẩn bị cảnh 3D</figcaption><div class="pth-scene-controls" aria-label="Góc nhìn mô hình"><button type="button" disabled data-pth-view="left" aria-label="Xoay góc nhìn sang trái">↶</button><button type="button" disabled data-pth-view="right" aria-label="Xoay góc nhìn sang phải">↷</button><button type="button" disabled data-pth-view="closer" aria-label="Đưa mô hình gần hơn">＋</button><button type="button" disabled data-pth-view="farther" aria-label="Đưa mô hình xa hơn">−</button><button type="button" disabled data-pth-view="reset">Góc ban đầu</button><button type="button" data-pth-retry hidden>Thử lại 3D</button></div><label class="pth-quality">Hiệu năng cảnh<select data-pth-quality><option value="auto">Tự điều chỉnh</option><option value="economy">3D nhẹ</option><option value="static">SVG tiết kiệm</option></select></label><small>Mô hình giày cách điệu, bóng tiếp xúc mô phỏng bằng hình học; không dạy chuyển động hoặc đánh giá kỹ thuật.</small></figure></section>'+
   '<section class="pt-card pth-command"><div><p class="pt-kicker">FIND YOUR NEXT STEP</p><h3>Tìm trong Patin</h3></div><label class="pt-field">Bài học, tên Việt–Anh, video, thuật ngữ & tham chiếu<input type="search" maxlength="120" data-pt-omni value="'+e(s.workshop.arena.query)+'" placeholder="Fish, phanh, Classic, double push…"></label><div data-pt-omni-results></div></section>'+
   '<section aria-labelledby="pth-branches-title"><header class="pth-section-head"><p class="pt-kicker">CHỌN KHÔNG GIAN HỌC</p><h3 id="pth-branches-title">Một nền tảng, nhiều hướng khám phá</h3></header><div class="pth-branches">'+paths.map(([id,t,desc,r])=>'<article class="pth-branch" data-discipline="'+id+'"><span class="pth-branch-art" aria-hidden="true">'+({foundation:'◌',speed:'↗',slide:'↔',slalom:'∞',quad:'♫'}[id])+'</span><h4>'+link(r,t)+'</h4><p>'+e(desc)+'</p>'+(id==='quad'?'<button type="button" data-pth-library data-category="quad">Lọc bài Quad</button>':link(r,'Mở hướng học'))+'</article>').join('')+'</div></section>'+
   '<section aria-labelledby="pth-personal-title"><header class="pth-section-head"><p class="pt-kicker">YOUR LOCAL WORKSPACE</p><h3 id="pth-personal-title">Không gian của bạn</h3><p>Lưu riêng trên thiết bị cho tài khoản/khách hiện tại. Kế hoạch, xem video và buổi đã tập là ba việc khác nhau.</p></header><div data-pth-personal>'+personal(s)+'</div></section>'+
   '<section><header class="pth-section-head"><p class="pt-kicker">SUGGESTED, NEVER LOCKED</p><h3>Gợi ý để tiếp tục đọc</h3><p>Dựa trên bài gần đây, yêu thích và dấu “đã đọc” bạn tự ghi. Không dùng AI hoặc suy ra khả năng thể chất.</p></header><div class="pth-suggestions" data-pth-suggestions>'+suggestionMarkup(s)+'</div>'+link('/patin/path','Xem toàn bộ lộ trình hiện có')+'</section>'+
   '<section><header class="pth-section-head"><p class="pt-kicker">LEARN YOUR WAY</p><h3>Khám phá đúng cách học bạn cần</h3></header><div class="pth-methods">'+[['written','Bản đọc tiếng Việt',f.lessons,'Nội dung gốc HH, chưa được HLV rà soát'],['visual','Hình khái niệm SVG',f.illustrated,'Phóng to, chọn điểm quan sát và tải SVG'],['video','Video liên kết trực tiếp',f.direct,'Chỉ hiển thị bài có video đã liên kết'],['verified','Mức có nguồn đối chiếu',f.verified,'Mức kỹ thuật không phải độ an toàn']].map(([id,t,n,desc])=>'<button type="button" data-pth-library data-method="'+id+'"><b>'+n+'</b><strong>'+t+'</strong><span>'+desc+'</span></button>').join('')+'</div><div class="pth-portals">'+portals.map(([id,t,desc])=>tile(t,'WORKSPACE', '<p>'+e(desc)+'</p>',link('/patin/'+id,'Mở chức năng'))).join('')+'</div></section>'+
   '<section class="pth-knowledge"><header class="pth-section-head"><p class="pt-kicker">BEFORE THE NEXT SESSION</p><h3>Ba điều hữu ích trước khi tập</h3></header><div class="pth-knowledge-grid">'+tile('Chuẩn bị giày, bảo hộ và sân','01 / PREPARE','<p>Kiểm tra theo đúng model, chọn vùng trống và phương án dừng đã được hướng dẫn. Checklist không chứng nhận an toàn.</p>',link('/patin/gear','Giày & an toàn')+skillLink('gear-check'),'gold')+tile('Đọc video theo toàn lượt','02 / OBSERVE','<p>Nhìn phần trước và sau động tác, góc quay, biến thể và điều chưa thấy rõ. Không suy ra lực hoặc tốc độ từ hình.</p>',skillLink('learning-video')+link('/patin/videos','Video Studio'),'violet')+tile('Ghi đúng việc đã làm','03 / RECORD','<p>Đọc bài, xem video và lên kế hoạch không tự tính là đã tập. Chỉ ghi thời lượng thực tế và câu hỏi muốn trao đổi với HLV.</p>',link('/patin/journal','Ghi buổi đã tập'),'cyan')+'</div></section>'+
   '<section class="pt-card pth-competition"><p class="pt-kicker">COMPETITION / SOURCE DESK</p><h3>Đọc mức thi đấu đúng bối cảnh</h3><p>'+f.verified+' ví dụ có mức đối chiếu trong '+f.rulebooks+' tài liệu đã khảo sát. Những mục khác ghi chưa đối chiếu hoặc không áp dụng; không gộp Speed với Freestyle.</p><div class="pth-format-grid">'+D.arena.formats.map(fmt=>{const src=D.arena.systems.find(s=>s.id===fmt.system),count=C.arena.catalog({format:fmt.id}).filter(r=>r.reference).length;return '<article><h4>'+e(fmt.title)+'</h4><p>'+e(src.title)+' · '+e(src.issuer)+'</p><small>Đối chiếu '+src.checkedAt+' · '+(count?count+' ví dụ gốc có mức':'Chưa gán mức kỹ thuật trong HH cho thể thức này')+'</small>'+link('/patin/competition/format-'+fmt.id,'Mở đúng thể thức')+'</article>';}).join('')+'</div><aside class="pt-notice">Mức tiếp cận HH, độ khó kỹ thuật trong luật và xếp hạng VĐV là các thông tin khác nhau. Không cộng tên động tác thành điểm, không tạo leaderboard từ số phút hoặc dấu tích.</aside>'+link('/patin/competition','Nguồn luật, kết quả và rankings chính thức')+'</section></section>';
 }
 function mount(host,{store,onStatus=()=>{}}={}){
  let alive=true,scene=null,idle=null,pending=null,loading=false,qualityMode='auto',generation=0;
  const listeners=[],doc=host.ownerDocument,on=(t,n,f)=>{t.addEventListener(n,f);listeners.push(()=>t.removeEventListener(n,f));};
  const stage=host.querySelector('[data-pth-scene]'),statusBox=host.querySelector('[data-pth-scene-status]'),motion=()=>store.getState().workshop.arena.motion==='on';
  function sceneStatus(text){if(!alive)return;statusBox.textContent=text;const state=stage.dataset.pthSceneState;host.querySelector('[data-pth-retry]').hidden=!['fallback','error'].includes(state);host.querySelectorAll('[data-pth-view]').forEach(b=>b.disabled=state!=='webgl');}
  async function start(){
   if(!alive||loading||scene)return;loading=true;const rev=++generation;sceneStatus('Minh họa SVG vẫn dùng được · đang tải mô hình 3D');
   try{
    if(!scope.HHPatinHomeScene){if(!scope.HHAssetLoader?.ensureGroup)throw Error('Lazy loader unavailable');await scope.HHAssetLoader.ensureGroup('patin-home-3d');}
    if(!alive||rev!==generation)return;
    scene=scope.HHPatinHomeScene.mount(stage,{motion:motion(),onStatus:sceneStatus});if(qualityMode!=='auto')scene.setQuality(qualityMode);
   }catch(err){if(alive&&rev===generation){stage.dataset.pthSceneState='error';stage.dataset.pthFailure=String(err.message).slice(0,500);sceneStatus('Chưa tải được cảnh 3D · dùng SVG, có thể thử lại.');}}finally{if(rev===generation)loading=false;}
  }
  function schedule(){if(scope.requestIdleCallback)idle=scope.requestIdleCallback(()=>{idle=null;start();},{timeout:1600});else pending=scope.setTimeout(()=>{pending=null;start();},80);}
  function refresh(){if(!alive)return;const s=store.getState();host.querySelector('[data-pth-personal]').innerHTML=personal(s);host.querySelector('[data-pth-suggestions]').innerHTML=suggestionMarkup(s);}
  on(host,'click',event=>{const b=event.target.closest('button');if(!b)return;if(b.hasAttribute('data-pth-library')){const options={};for(const k of ['method','category','discipline','level','status'])if(b.dataset[k])options[k]=b.dataset[k];if(b.hasAttribute('data-favorites'))options.favorites=b.dataset.favorites==='true';try{const saved=store.mutate(s=>prepareLibrary(s,options));if(!saved)onStatus(store.getStatus().error);scope.location.hash='#/patin/skills';}catch(err){onStatus(err.message);}}
   if(b.hasAttribute('data-pth-view'))scene?.setView(b.dataset.pthView);if(b.hasAttribute('data-pth-retry')){if(scene)scene.retry();else start();}});
  on(host,'change',event=>{if(event.target.hasAttribute('data-pth-quality')){qualityMode=event.target.value;scene?.setQuality(qualityMode);}});
  schedule();
  return {refresh,setMotion:value=>scene?.setMotion(value),snapshot:()=>scene?.snapshot()||{alive,loading,webgl:false},destroy:()=>{if(!alive)return;alive=false;generation++;if(idle!==null)scope.cancelIdleCallback(idle);if(pending!==null)scope.clearTimeout(pending);scene?.destroy();scene=null;listeners.splice(0).forEach(f=>f());}};
 }
 return Object.freeze({version:1,facts,recommendations,prepareLibrary,markup,mount});
});
