(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./patin-disciplines.js'):root.HHPatinDisciplines,typeof module==='object'&&module.exports?require('./patin-learning-data.js'):root.HHPatinLearningData,typeof module==='object'&&module.exports?require('./patin-arena-data.js'):root.HHPatinArenaData,typeof module==='object'&&module.exports?require('./patin-video-expansion.js'):root.HHPatinVideoExpansion);if(typeof module==='object'&&module.exports)module.exports=api;else root.HHPatinData=api;})(globalThis,function(expansion,learning,arena,videoExpansion){
  'use strict';
  if(!expansion)throw Error('Chưa tải dữ liệu bộ môn Patin.');
  const sources=Object.freeze([
    {id:'cpsc',title:'CPSC · Skate Safely',url:'https://www.cpsc.gov/s3fs-public/5014.pdf',publisher:'U.S. Consumer Product Safety Commission',scope:'Bảo hộ, nơi tập và phanh gót cơ bản',checkedAt:'2026-10-10'},
    {id:'beginner',title:'Skatefresh · Beginner lessons',url:'https://skatefresh.com/inline-skating-lessons/beginner/',publisher:'Skatefresh',scope:'Cấu trúc kỹ năng người mới; không sao chép giáo án/khóa học',checkedAt:'2026-10-10'},
    {id:'faq',title:'Skatefresh · Questions about learning',url:'https://skatefresh.com/faq/',publisher:'Skatefresh',scope:'Học với HLV, bảo hộ và giữ phanh khi chưa có cách dừng thay thế',checkedAt:'2026-10-10'},
    {id:'gear',title:'Rollerblade · Guides & maintenance',url:'https://www.rollerblade.com/usa/en/maintenance-list',publisher:'Rollerblade',scope:'Chọn giày, kiểm tra và bảo dưỡng theo đúng model',checkedAt:'2026-10-10'},
    {id:'instructor',title:'SkateIA · Instructor association',url:'https://www.skateia.org/',publisher:'Skate Instructors Association',scope:'Đào tạo HLV cho inline/quad và các hướng chuyên sâu',checkedAt:'2026-10-10'},
    {id:'rules',title:'World Skate · Inline Freestyle regulations',url:'https://www.worldskate.org/inline-freestyle/about/regulations.html',publisher:'World Skate',scope:'Tra cứu bản luật hiện hành; không chép lại toàn bộ luật hoặc tự cấp chứng chỉ',checkedAt:'2026-10-10'},
    ...expansion.sources,...learning.sources,...arena.sources
  ]);
  const categories=Object.freeze([['foundation','Nền tảng','◌'],['braking','Phanh & kiểm soát','⏹'],['turning','Rẽ & đổi hướng','↪'],['slalom','Slalom & freestyle','∞'],['fitness','Fitness & speed','↗'],['specialist','Chuyên sâu / skatepark','◇'],['quad','Quad & nghệ thuật','♫'],['speed','Speed chuyên môn','↗'],['slide','Slide chuyên môn','↔']].map(([id,title,icon])=>({id,title,icon})));
  const levels=Object.freeze([{id:'intro',title:'Làm quen'},{id:'basic',title:'Cơ bản'},{id:'control',title:'Nâng mức kiểm soát'},{id:'advanced',title:'Chuyên sâu · có HLV'}]);
  const rows=[
    ['gear-check','Kiểm tra trước khi mang giày','foundation','intro',[],'Nhận biết bộ phận cần kiểm tra và điều kiện phải dừng sử dụng.','Đối chiếu khóa, dây, bánh, trục, frame và phanh với hướng dẫn của nhà sản xuất. Không dùng giày có phần bị nứt hoặc lỏng chưa xử lý.','Chỉ nhìn vẻ ngoài mà bỏ qua khóa hoặc phanh.','Tự mô tả được từng bộ phận và biết hỏi kỹ thuật viên khi không chắc.'],
    ['ready-stance','Tư thế sẵn sàng','foundation','intro',['gear-check'],'Giữ một tư thế thấp, dễ điều chỉnh thay vì khóa cứng gối.','Làm quen ở vị trí không lăn; gối hơi gập, hai chân có khoảng cách tự nhiên, mắt nhìn phía trước. Nhờ HLV kiểm tra tư thế trước khi tập chuyển động.','Gối thẳng cứng, nhìn chằm chằm xuống bánh hoặc dồn thân ra sau.','Có thể đứng và đổi tư thế chậm mà không phải bám kéo người khác.'],
    ['stand-up','Đứng lên và ngồi xuống có kiểm soát','foundation','intro',['ready-stance'],'Không bị kéo đi khi thay đổi tư thế thấp–cao.','Tập trên khu vực không lăn với điểm hỗ trợ ổn định và người hướng dẫn. Học trình tự đứng/ngồi phù hợp thể trạng trước khi thử trên nền lăn.','Nhờ người khác kéo mạnh tay hoặc đứng vội.','Biết dừng và yêu cầu hỗ trợ thay vì cố đứng khi mất thăng bằng.'],
    ['fall-awareness','Nhận biết mất thăng bằng & học ngã với HLV','foundation','intro',['ready-stance'],'Biết vai trò của bảo hộ và giới hạn của hướng dẫn bằng chữ.','Dành một phần buổi đầu cho HLV hướng dẫn hạ trọng tâm và phản ứng khi mất cân bằng trong môi trường được kiểm soát. Không tự thử ngã chủ động trên nền cứng.','Tin rằng đeo bảo hộ có thể loại bỏ mọi chấn thương.','Đã trao đổi với HLV về phản ứng khi mất cân bằng; đây không phải chứng nhận ngã an toàn.'],
    ['static-steps','Bước nhỏ khi chưa lăn','foundation','intro',['ready-stance'],'Điều chỉnh vị trí chân mà vẫn làm chủ cơ thể.','Tập vài bước ngắn ở vùng không lăn, dừng giữa các bước. Giữ khoảng trống quanh người và dùng hỗ trợ đúng cách khi cần.','Bước quá dài hoặc cố chạy ngay khi mới mang giày.','Có thể đặt lại chân và chủ động dừng sau vài bước.'],
    ['march-roll','Từ bước nhỏ sang lăn chậm','foundation','basic',['static-steps','heel-brake'],'Bắt đầu di chuyển ở tốc độ thấp với phương án dừng đã học.','Chọn một đoạn ngắn để lăn, rồi dừng chủ động. Chỉ tăng chiều dài đoạn tập khi vẫn giữ được tư thế và dừng trong khoảng đã chừa.','Để tốc độ tăng tự nhiên rồi mới tìm cách dừng.','Biết kết thúc mỗi lượt trong vùng trống đã chọn.'],
    ['forward-stride','Đẩy chân tiến cơ bản','foundation','basic',['march-roll'],'Tạo chuyển động đều, không chạy bằng mũi chân.','Luyện các nhịp đẩy nhỏ và thu chân về dưới cơ thể. Ưu tiên kiểm soát hơn lực đẩy; xin HLV sửa hướng đẩy nếu hai chân va nhau.','Sải quá rộng hoặc đạp mạnh khi chưa kiểm soát tốc độ.','Có thể đẩy nhẹ nhiều nhịp mà vẫn chủ động phanh.'],
    ['two-foot-glide','Lướt hai chân','foundation','basic',['march-roll'],'Giữ hướng và cân bằng khi bánh đang lăn.','Lăn chậm trên đoạn thẳng ngắn, giảm động tác tay không cần thiết và kết thúc bằng cách dừng đã biết.','Nín thở, khóa gối hoặc để chân cách nhau quá rộng.','Có thể lướt ngắn mà không tự tăng tốc để giữ thăng bằng.'],
    ['scissor','Tư thế hai chân trước–sau','foundation','basic',['two-foot-glide'],'Tạo vị trí chân có thể dùng khi học phanh hoặc đổi hướng.','Làm quen việc đưa một chân hơi trước chân kia ở tốc độ rất thấp; đổi bên dưới hướng dẫn. Khoảng cách không cần lớn.','Tách chân quá xa hoặc dồn toàn bộ trọng lượng bất ngờ.','Có thể vào/ra tư thế trước–sau mà không giật thân.'],
    ['weight-transfer','Chuyển trọng lượng','foundation','basic',['two-foot-glide'],'Cảm nhận chân đang chịu tải trước khi học một chân.','Tập chuyển tải nhẹ giữa hai chân khi đứng, sau đó thử trong lướt rất chậm với HLV. Vẫn giữ được phương án dừng.','Nhấc chân còn lại trước khi chân trụ đã ổn định.','Mô tả được chân đang chịu tải mà không cần tự thử tốc độ cao.'],
    ['one-foot','Lướt một chân ngắn','foundation','control',['weight-transfer','heel-brake'],'Giữ trục cơ thể trong một đoạn lướt ngắn.','Bắt đầu từ đoạn lướt hai chân, giảm hỗ trợ của một chân từng chút dưới giám sát. Không đặt mục tiêu khoảng cách trước khi ổn định cả hai bên.','Nghiêng hông quá mức hoặc chỉ tập chân thuận.','Tự ghi nhận từng bên riêng; chưa coi là điều kiện đủ để trượt ngoài đường.'],
    ['look-ahead','Nhìn trước & giữ khoảng trống','foundation','basic',['march-roll'],'Quan sát lối đi thay vì chỉ nhìn bánh.','Chọn điểm nhìn phía trước trên đường tập, nhận biết người/vật có thể đi vào vùng dừng. Ngừng lượt nếu khu vực không còn trống.','Tập sát người khác hoặc dựa vào phản xạ để né vào phút cuối.','Có thể giải thích vì sao phải chừa vùng dừng theo tốc độ và mặt nền.'],
    ['heel-brake','Phanh gót cho inline có phanh','braking','basic',['ready-stance'],'Học cách dừng cơ bản trên bộ giày có phanh gót hoạt động.','Sau khi HLV kiểm tra phanh, tập ở tốc độ rất thấp: chân có phanh hơi phía trước, nhấc mũi chân đó để má phanh chạm nền rồi tăng lực nhẹ. Duy trì gối gập; không áp dụng cho quad.','Ngả toàn thân ra sau, đưa chân phanh quá xa hoặc bỏ phanh khi chưa có cách dừng thay thế.','Dừng lặp lại ở tốc độ thấp với người hướng dẫn và khoảng trống thích hợp.'],
    ['plough','Phanh chữ A / plough','braking','control',['two-foot-glide','heel-brake'],'Tìm hiểu cách giảm tốc bằng hai chân; không dùng làm phương án cứu nguy mặc định.','Học cách tạo/thu chữ A và kiểm soát hướng bánh trực tiếp với HLV. Khả năng giảm tốc phụ thuộc kỹ thuật và mặt nền, không đồng nghĩa luôn dừng được.','Ép mũi chân vào nhau hoặc thử trên dốc trước khi kiểm soát tốt.','Phân biệt được giảm tốc với dừng hẳn.'],
    ['t-stop','T-stop','braking','control',['one-foot','weight-transfer'],'Học một cách phanh yêu cầu cân bằng chân trụ.','Để HLV hướng dẫn vị trí chân kéo, phân bổ tải và giữ hướng. Bắt đầu rất chậm; không coi hình chữ T đứng yên là bằng chứng đã phanh được.','Đè mạnh chân sau làm xoay người hoặc bỏ phanh gót quá sớm.','Có người hướng dẫn đánh giá khả năng giữ hướng và dừng, không chỉ hình dáng động tác.'],
    ['stepping-stop','Giảm tốc bằng bước nhỏ','braking','basic',['static-steps','heel-brake'],'Biết một bài phối hợp chuyển động ở tốc độ rất thấp.','Chỉ luyện các bước nhỏ có kiểm soát theo bài HLV giao. Không nhảy lên lề, cỏ hoặc vật cản để thay cho phanh.','Xem bước nhỏ như cách dừng từ tốc độ bất kỳ.','Biết giới hạn tốc độ và điều kiện của bài tập này.'],
    ['stop-zone','Vùng dừng & bài phản ứng','braking','basic',['heel-brake','look-ahead'],'Lập vùng tập có đủ khoảng trống để chủ động dừng.','Đánh dấu vùng xuất phát/vùng dừng bằng vật mềm ngoài đường lăn. Dùng cùng một tốc độ chậm cho các lượt; nếu không dừng được thì giảm tốc và xin hướng dẫn.','Cố đạt khoảng dừng ngắn nhất hoặc thi tốc độ với người mới.','Ghi nhận điều kiện buổi tập thay vì suy ra một khoảng dừng luôn đúng.'],
    ['slide-stops','Powerslide / hockey-style stop','braking','advanced',['t-stop','edge-control'],'Nhận biết đây là kỹ thuật khác, không phải bước bắt buộc cho người mới.','Chỉ xem định hướng và tìm HLV có kinh nghiệm về phanh trượt. Cần bề mặt, giày và giám sát phù hợp; không tự học bằng cách tăng tốc rồi xoay ngang.','Dùng tên động tác như lời đảm bảo sẽ dừng an toàn ở mọi nơi.','Có HLV xác nhận điều kiện học; website không xác minh kỹ năng này.'],
    ['step-turn','Quay hướng bằng bước nhỏ','turning','basic',['static-steps'],'Thay đổi hướng ở trạng thái chậm hoặc gần đứng yên.','Luyện đổi hướng từng bước nhỏ trong khoảng trống, hai bên đều nhau. Không xoay gấp khi bánh vẫn đang lăn nhanh.','Xoay vai mạnh rồi để chân theo sau không kiểm soát.','Chủ động đặt lại chân trước khi lăn tiếp.'],
    ['a-turn','Rẽ chữ A','turning','basic',['two-foot-glide','heel-brake'],'Học đổi hướng vòng rộng ở tốc độ thấp.','Bắt đầu với vòng rộng và khoảng trống lớn; nhờ HLV kiểm tra hướng chân/tải trọng. Dừng nếu đường tập có người đi vào.','Rẽ gấp để tránh vật cản hoặc nghĩ rẽ thay thế được phanh.','Có thể rẽ rộng cả hai bên và vẫn dùng được cách dừng đã học.'],
    ['parallel-turn','Rẽ song song','turning','control',['scissor','weight-transfer','a-turn'],'Phối hợp hai chân và thân khi đổi hướng.','Tập vòng rộng dưới giám sát; chuyển từ tư thế trước–sau sang hướng rẽ nhẹ. Không cố tạo góc nghiêng lớn hoặc ôm cua nhanh.','Chỉ xoay cổ chân hoặc giữ thân cứng.','Có thể nhận biết tải trọng và ưu tiên thoát lượt/dừng khi mất ổn định.'],
    ['edge-control','Cảm nhận cạnh bánh / edge control','turning','control',['weight-transfer','parallel-turn'],'Hiểu cách tải trọng và hướng nghiêng ảnh hưởng đường lăn.','Dùng bài tập chậm của HLV để cảm nhận hai phía cạnh bánh. Đây là nền tảng kỹ thuật, không phải mẹo để vào cua ở tốc độ cao.','Ép nghiêng giày quá mức hoặc bỏ qua sự khác biệt giữa hai bên.','Có thể nói rõ điều đang tập và điều chưa kiểm soát được.'],
    ['crossovers','Crossovers tiến','turning','control',['one-foot','parallel-turn'],'Phối hợp bước chéo khi đi vòng.','Luyện từng thành phần đứng yên, rồi vòng rộng tốc độ thấp với HLV. Không bắt đầu bằng vòng hẹp đông người.','Đặt chân chéo trước khi chân trụ vững hoặc chỉ tập một chiều.','Tự theo dõi hai chiều riêng, không tự nhận kỹ năng speed racing.'],
    ['transitions','Đổi tiến–lùi / transition','turning','advanced',['edge-control','backward-roll'],'Chuyển hướng lăn cần phối hợp chân và quan sát phía sau.','Học trực tiếp với HLV trong sân kiểm soát. Biết dừng và kiểm tra vùng phía sau trước khi học chuyển hướng liên tục.','Xoay nhanh theo video mà chưa làm chủ trượt lùi.','Có người hướng dẫn chọn bài phù hợp; không luyện trên lối đi công cộng.'],
    ['cone-lines','Làm quen hàng cọc','slalom','basic',['a-turn','stop-zone'],'Thiết lập một bài luồn vòng rộng, không phải thi đấu.','Dùng ít cọc mềm, cách xa hơn nhu cầu của mình và đặt xa người khác. Chỉ lăn chậm khi có vùng dừng trống.','Dùng khoảng cách thi đấu ngay khi mới học hoặc dùng vật cứng sắc.','Giữ được tốc độ kiểm soát và có thể bỏ lượt an toàn.'],
    ['fish','Fish hai chân','slalom','control',['cone-lines','parallel-turn'],'Tìm hiểu phối hợp hai chân đi qua một hàng cọc.','Để HLV hướng dẫn đường lăn và nhịp đổi cạnh, khởi đầu không cọc hoặc cọc thưa. Không dùng động tác lắc thân để bù cho thiếu kiểm soát chân.','Cố bám sát cọc thay vì giữ hướng và nhịp.','Hai chân phối hợp ở tốc độ thấp mà vẫn có thể dừng.'],
    ['snake','Snake','slalom','control',['fish','scissor'],'Phối hợp đường lăn một chân trước một chân sau.','Tập với cọc thưa và HLV; đổi bên dẫn khi đã kiểm soát. Không coi việc chân trước–sau đơn thuần là snake hoàn chỉnh.','Chân sau bị kéo cứng hoặc chỉ xoay phần trên cơ thể.','Mô tả được bên dẫn và giới hạn của lượt tập.'],
    ['slalom-cross','Cross / criss-cross','slalom','control',['crossovers','cone-lines'],'Đan chân theo nhịp mà không va hai giày.','Học từng phần đứng yên rồi cọc thưa dưới giám sát. HLV cần kiểm tra khoảng cách và hướng bánh trước khi tăng nhịp.','Bắt chéo quá nhanh hoặc gắng kéo chân đang bị vướng.','Có thể trở lại tư thế ổn định và dừng chủ động.'],
    ['slalom-one-foot','Slalom một chân','slalom','advanced',['one-foot','edge-control','fish'],'Tìm hiểu một nhánh chuyên sâu cần cân bằng và đổi cạnh tốt.','Tập nền tảng với HLV; không tự đặt mục tiêu vượt cả hàng cọc khi chưa điều khiển chân trụ.','Cố hoàn thành số cọc bằng tốc độ hoặc đà.','Có HLV đánh giá nền tảng; tự ghi nhận chỉ là nhật ký cá nhân.'],
    ['backward-roll','Trượt lùi có quan sát','slalom','control',['weight-transfer','heel-brake','look-ahead'],'Biết trượt lùi là kỹ năng riêng, cần vùng tập và cách dừng phù hợp.','Học nhịp lùi chậm với HLV trong sân trống; tập quan sát phía sau trước khi nối các động tác.','Tập lùi trên lối dùng chung hoặc tin người phía sau sẽ tự tránh.','Biết từ bỏ lượt khi tầm nhìn/vùng trống không đủ.'],
    ['toe-heel','Toe/heel balance','slalom','advanced',['one-foot','edge-control'],'Nhận biết kỹ thuật tải trọng trên ít bánh có rủi ro và phụ thuộc setup.','Chỉ tìm hiểu dưới hướng dẫn chuyên môn và theo setup giày phù hợp. Không tự nâng lên một bánh từ tốc độ cao.','Cho rằng video ngắn thể hiện đủ điều kiện và cách thoát động tác.','Đã trao đổi với HLV; không có đánh giá tự động của website.'],
    ['routine-flow','Ghép tổ hợp freestyle','slalom','advanced',['fish','snake','slalom-cross'],'Tổ chức các kỹ năng đã học thành một chuỗi có lối thoát.','Ưu tiên động tác đã được HLV đánh giá; chừa phần vào/ra và dừng. Nếu chuẩn bị thi đấu, đọc luật hiện hành thay vì dựa vào bảng điểm của ứng dụng.','Ghép kỹ thuật chưa học chỉ để đủ một combo.','Có thể nêu mục tiêu từng phần, không tự coi hoàn thành combo là chứng chỉ.'],
    ['steady-pace','Nhịp lăn đều cho fitness','fitness','control',['forward-stride','heel-brake','parallel-turn'],'Tập nhịp đều trong sân, không đặt yêu cầu tốc độ hay quãng đường cố định.','Chọn buổi ngắn phù hợp sức khỏe hiện tại, xen kẽ nghỉ và ưu tiên dừng/rẽ. Dừng tập khi thấy không khỏe; hỏi chuyên gia nếu có vấn đề sức khỏe.','So thành tích với người khác hoặc bỏ qua mệt/đau.','Tự ghi thời lượng đã tập; ứng dụng không đo thể lực hay lượng calo.'],
    ['efficient-stride','Hiệu quả sải chân','fitness','control',['forward-stride','one-foot'],'Học kỹ thuật đẩy/thu chân hiệu quả trước khi tăng tốc.','Nhờ HLV quan sát các đoạn lăn ngắn hoặc video do bạn chủ động chia sẻ ngoài ứng dụng. Không ép biên độ sải chân để đạt tốc độ.','Bắt chước tư thế vận động viên mà không kiểm soát được thân.','Có phản hồi thực tế về kỹ thuật, không suy ra từ timer.'],
    ['speed-basics','Định hướng speed skating','fitness','advanced',['crossovers','efficient-stride','stop-zone'],'Phân biệt trượt giải trí và huấn luyện tốc độ trên đường tập chuyên dụng.','Làm việc với HLV/CLB về giày, đường tập, kỹ thuật và quy định. Nền tảng dừng/đổi hướng cần được đánh giá trước khi tập tốc độ.','Bỏ phanh hoặc đổi sang giày đua chỉ vì nhìn chuyên nghiệp hơn.','Có kế hoạch chuyên môn phù hợp; không tự thử thi tốc độ trên đường công cộng.'],
    ['group-ethics','Trượt nhóm & ứng xử ở sân','fitness','control',['look-ahead','stop-zone'],'Giữ không gian chung và tín hiệu giao tiếp dễ hiểu.','Thống nhất quy tắc tại sân, chừa khoảng dừng, không bám đẩy nhau và rời nhóm nếu nhịp vượt khả năng.','Để áp lực theo nhóm thay thế đánh giá cá nhân.','Biết chủ động xin nghỉ hoặc giảm tốc mà không ảnh hưởng người khác.'],
    ['park-intro','Định hướng skatepark / aggressive','specialist','advanced',['edge-control','stop-zone'],'Nhận biết skatepark là môi trường chuyên biệt với setup và quy tắc riêng.','Tìm HLV phù hợp và làm quen cách quan sát lượt chạy, khu vực đứng chờ và giới hạn thiết bị. Chưa thực hiện ramp hoặc rail theo hướng dẫn chữ.','Mang giày bất kỳ vào mọi khu vực hoặc cắt ngang lượt của người khác.','Biết điều kiện cần học trực tiếp; đọc bài không đồng nghĩa được phép tự thử.'],
    ['jumps-intro','Nhảy và tiếp đất · định hướng','specialist','advanced',['park-intro','one-foot'],'Hiểu nhảy cần chuẩn bị nền tảng, bề mặt và người giám sát.','Đăng ký hướng dẫn trực tiếp phù hợp. Không có bài hướng dẫn nhảy cầu thang, vượt vật cứng hoặc flip trong ứng dụng này.','Ước lượng độ khó qua chiều cao hoặc theo trào lưu.','Có HLV đánh giá điều kiện thực tế, không tự tăng độ cao.'],
    ['rail-ramp','Rail / ramp · chỉ tìm hiểu','specialist','advanced',['park-intro','jumps-intro'],'Phân biệt thông tin môn thể thao với một bài tự học mạo hiểm.','Tìm hiểu thiết bị, địa điểm quản lý và khóa học từ tổ chức phù hợp. Kỹ thuật grind/ramp không được mô phỏng là an toàn bằng một checklist.','Tự thử trên lan can công cộng hoặc đồ vật không được thiết kế cho môn này.','Nhận biết rõ giới hạn của nguồn chữ và cần giám sát chuyên môn.'],
    ['quad-basics','Quad và inline khác nhau thế nào?','quad','intro',[],'Không dùng hướng dẫn phanh của inline cho mọi loại patin.','Quad có bố trí bánh và cơ chế toe stop khác inline. Học với HLV có kinh nghiệm đúng loại giày; tham khảo hướng dẫn của model để nhận biết bộ phận.','Nhầm toe stop ở phía trước với phanh gót inline phía sau.','Gọi đúng loại giày và cơ chế dừng cần học.'],
    ['dance-intro','Roller dance · định hướng','quad','control',['quad-basics'],'Tìm hiểu nhịp, chuyển tải và di chuyển trong sân phù hợp.','Học các bước nền với HLV, dùng nhạc nếu địa điểm cho phép nhưng vẫn nghe/nhìn được môi trường. Không tự quay nhanh khi chưa kiểm soát.','Ưu tiên biểu diễn hơn khả năng dừng và không gian chung.','Có thể mô tả yêu cầu về sân, giày và hướng dẫn trực tiếp.'],
    ['artistic-intro','Artistic skating · định hướng','quad','advanced',['dance-intro'],'Phân biệt các nội dung nghệ thuật trên quad/inline và huấn luyện thi đấu.','Tìm CLB/HLV và luật đúng môn. Các bài spin, nhảy và chương trình thi đấu cần giáo án trực tiếp; ứng dụng chỉ cung cấp định hướng.','Dùng luật của một môn cho môn khác hoặc tự coi video là chứng nhận năng lực.','Biết tìm nguồn đúng môn và đánh giá thực tế với HLV.']
  ];
  const skills=Object.freeze([...rows.map(([id,title,category,level,prerequisites,goal,drill,mistake,check])=>Object.freeze({id,title,category,discipline:expansion.legacyDiscipline(id),level,prerequisites,goal,drill,mistake,check,supervised:level==='advanced'||['fall-awareness','stand-up'].includes(id),scope:level==='advanced'?'orientation':'guided-learning',sources:id==='heel-brake'?['cpsc','beginner']:category==='quad'?['instructor','rules']:['beginner','instructor'],authorship:'HH original educational summary · needs coach review',reviewedAt:null})),...expansion.entries,...learning.entries,...arena.entries].map(s=>Object.freeze({...s,aka:Object.freeze(s.aka||arena.aliases[s.id]||[]),learningConditions:s.level==='advanced'?'Chỉ định hướng; cần HLV, setup và môi trường chuyên dụng.':'Học theo khả năng với hướng dẫn trực tiếp, giày/bảo hộ và sân phù hợp.'})));
  const gear=Object.freeze([
    ['inline-quad','Inline / quad','Inline xếp bánh thành một hàng; quad bố trí hai cặp ngang. Kỹ thuật dừng và thiết bị không hoàn toàn giống nhau. Phần phanh gót của HH chỉ áp dụng inline có phanh.'],
    ['fit','Kích cỡ & độ ôm','Thử giày với loại tất sẽ dùng. Cần giữ chân chắc mà không đau, tê hoặc ép khó chịu. Bảng size khác nhau theo hãng/model; không chỉ dựa vào cỡ giày thường.'],
    ['boot','Boot, cuff, liner, khóa','Boot/cuff hỗ trợ chân; liner là lớp lót. Dây/khóa cần hoạt động đúng và không có phần thừa vướng bánh. Nếu hỏng hoặc không chắc cách chỉnh, hỏi nhà sản xuất/kỹ thuật viên.'],
    ['wheels','Bánh & frame','Kiểm tra số bánh, đường kính, độ cứng, chiều dài frame và tương thích của model. Không có một cấu hình tốt nhất cho mọi người; hãy chọn cùng HLV/người bán có chuyên môn theo mục tiêu và khả năng.'],
    ['bearings','Vòng bi & trục','Vòng bi ảnh hưởng chuyển động, nhưng nhãn ABEC không tự nói lên toàn bộ độ phù hợp của giày. Dùng hướng dẫn bảo dưỡng/model; không tự siết lực hay thay linh kiện theo một con số chung.'],
    ['brake','Phanh & bảo trì','Người mới cần cách dừng đã được học và thiết bị phanh phù hợp. Xem má phanh có mòn/lỏng không; làm theo tài liệu model. Đừng tháo phanh chỉ vì muốn thực hiện động tác khác.'],
    ['protection','Bảo hộ','Mũ phù hợp hoạt động, bảo vệ cổ tay, gối và khuỷu tay là các phần cần chuẩn bị. Chọn đúng cỡ, cách đeo và hướng dẫn của nhà sản xuất; bảo hộ không loại bỏ mọi rủi ro.'],
    ['care','Sau buổi tập','Làm sạch nhẹ và để giày/liner khô theo hướng dẫn. Kiểm tra mòn bánh/phanh và dấu hiệu lỏng hoặc nứt. Chỉ đảo/thay bánh, vòng bi khi đúng model và biết quy trình. Không hotlink hoặc tải tài liệu hãng vào HH.']
  ].map(([id,title,text])=>({id,title,text,sources:['gear']})));
  const safety=Object.freeze([['helmet','Mũ phù hợp, đúng cỡ và đeo đúng'],['pads','Bảo hộ cổ tay, gối, khuỷu đã chuẩn bị'],['equipment','Giày, bánh, trục, khóa và phanh đã kiểm tra'],['surface','Sân phẳng, khô, không cát/sỏi/dầu hay vật cản'],['space','Có vùng dừng trống, không xe cộ hoặc người đi vào lượt'],['light','Đủ ánh sáng; không tập nơi tối hoặc tầm nhìn kém'],['support','Có hướng dẫn phù hợp; trẻ em có người giám sát']].map(([id,label])=>({id,label})));
  const glossary=Object.freeze([['inline','Patin bánh xếp thành hàng'],['quad','Patin hai cặp bánh ngang'],['boot','Thân giày'],['cuff','Phần hỗ trợ quanh cổ chân'],['liner','Lớp lót trong giày'],['frame','Khung gắn bánh'],['axle','Trục bánh'],['bearing','Vòng bi'],['spacer','Ống đệm theo cấu hình bánh/vòng bi'],['heel brake','Má phanh gót inline'],['toe stop','Bộ phận dừng phía trước ở một số giày quad'],['wrist guard','Bảo vệ cổ tay'],['knee pad','Bảo vệ gối'],['elbow pad','Bảo vệ khuỷu'],['ready position','Tư thế chuẩn bị'],['stride','Nhịp đẩy và thu chân'],['glide','Lướt khi bánh đang lăn'],['scissor','Tư thế hai chân trước–sau'],['edge','Phía cạnh bánh khi nghiêng/tải trọng thay đổi'],['plough','Kỹ thuật chữ A; cần học cách tạo lực và giữ hướng'],['T-stop','Một cách phanh có chân kéo phía sau'],['crossover','Bước chéo khi đi vòng'],['transition','Đổi hướng lăn tiến–lùi'],['slalom','Luồn qua hàng cọc theo một kỹ thuật'],['rocker','Cấu hình chiều cao/tiếp xúc bánh; không phải setup bắt buộc'],['freestyle','Nhánh kỹ thuật tự do'],['fitness skating','Trượt phục vụ vận động theo khả năng'],['speed skating','Môn/nhánh huấn luyện tốc độ'],['aggressive','Nhánh skatepark/street chuyên biệt'],['artistic','Trượt nghệ thuật theo môn và bộ luật tương ứng']].map(([term,meaning])=>({term,meaning})));
  const faq=Object.freeze([
    ['Bao lâu sẽ trượt được?','Không có số buổi bảo đảm cho mọi người. Sức khỏe, thiết bị, sân tập và hướng dẫn ảnh hưởng tiến trình. Ưu tiên dừng, giữ hướng và tự biết giới hạn trước khi tăng tốc.'],
    ['Người mới có nên tháo phanh gót?','Không tháo chỉ vì hình thức hoặc vì muốn thử slalom. Hãy để HLV đánh giá cách dừng thay thế và tuân thủ cấu hình/hướng dẫn của model.'],
    ['Tôi có cần HLV không?','Một buổi hướng dẫn trực tiếp giúp kiểm tra tư thế, giày và cách dừng. Càng nên có hướng dẫn khi thường xuyên mất cân bằng, mới chuyển loại giày hoặc muốn học chuyên sâu.'],
    ['Có thể tập trời mưa hoặc đường đông xe?','Không dùng môi trường đó làm nơi tự học. Nước, cát/sỏi, vật cản và xe cộ làm việc kiểm soát/dừng khó hơn. Tìm sân phù hợp và quy định tại chỗ.'],
    ['Tập lùi, crossovers hay slalom trước?','Không có thứ tự chung cho mọi mục tiêu. Xem nền tảng gợi ý của kỹ năng và trao đổi với HLV; không dùng trạng thái tự đánh dấu để quyết định rằng mình đã đủ năng lực.'],
    ['Trẻ em tập như người lớn?','Cần giày/bảo hộ phù hợp, giám sát và cách dạy phù hợp lứa tuổi. Không coi tuổi hoặc size mở rộng là bảo đảm thiết bị vừa và bài tập phù hợp.'],
    ['Bánh lớn có luôn tốt hơn?','Không. Cấu hình phải phù hợp loại giày, sân, người dùng và mục tiêu. Tài liệu model/HLV quan trọng hơn việc chạy theo một kích thước.'],
    ['Điểm tiến độ trong HH có phải chứng chỉ?','Không. “Đã đọc” và “đã thử” là tự ghi nhận; bài kiểm tra chỉ đối chiếu kiến thức bằng chữ. HH không quan sát động tác hay đo thể lực.'],
    ['Nếu thấy đau hoặc không khỏe khi tập?','Dừng buổi tập và tìm hướng dẫn chuyên môn phù hợp; ứng dụng không chẩn đoán hoặc thay thế chăm sóc y tế. Không dùng mục tiêu thời lượng để ép tiếp tục.'],
    ['Có video tự phát hoặc camera phân tích không?','Không. HH chỉ dẫn liên kết tới nguồn; bạn chủ động mở. Không xin camera/mic/GPS, không tự ghi hình hay tính calo.'],
    ['Các luật thi đấu có cố định không?','Không. Môn và phiên bản luật có thể khác nhau. Mở trang chính thức World Skate để kiểm tra tài liệu đang được áp dụng, không dùng một bản tóm tắt làm luật đầy đủ.'],
    ['Dữ liệu của tôi lưu ở đâu?','Nhật ký, dấu trang và ghi chú lưu trên thiết bị theo tài khoản hoặc định danh khách. Không đồng bộ máy chủ trong phiên bản này; hãy xuất JSON nếu muốn mang sang thiết bị khác.']
  ].map(([question,answer])=>({question,answer})));
  const pathway=Object.freeze([['Chuẩn bị','intro',['gear-check','ready-stance','fall-awareness','static-steps']],['Di chuyển & dừng','basic',['heel-brake','march-roll','two-foot-glide','look-ahead','stop-zone']],['Kiểm soát hai bên','basic',['forward-stride','scissor','weight-transfer','step-turn','a-turn']],['Nền tảng tiếp theo','control',['one-foot','parallel-turn','edge-control','crossovers']],['Chọn hướng chuyên môn','advanced',['cone-lines','steady-pace','speed-basics','park-intro','quad-basics']]].map(([title,level,ids])=>({title,level,ids})));
  const quiz=Object.freeze([
    {id:'q1',prompt:'Người mới nên ưu tiên điều gì trước khi tăng tốc?',options:['Cách dừng và kiểm soát đã học','Giày có bánh lớn nhất','Bỏ phanh gót'],answer:0,explanation:'Tốc độ không thay thế nền tảng giữ hướng, dừng và đánh giá thực tế.'},
    {id:'q2',prompt:'Hướng dẫn phanh gót inline có áp dụng nguyên xi cho quad không?',options:['Có, mọi giày đều như nhau','Không, bố trí bánh và cơ chế dừng có thể khác','Chỉ khi bật nhạc'],answer:1,explanation:'Hãy học kỹ thuật đúng loại giày với HLV và tài liệu model.'},
    {id:'q3',prompt:'Đọc và đánh dấu “đã thử” một kỹ năng có chứng minh làm được không?',options:['Có, ứng dụng cấp chứng chỉ','Không, chỉ là tự ghi nhận','Có nếu đọc nhanh'],answer:1,explanation:'HH không quan sát động tác; cần đánh giá trực tiếp cho kỹ năng thực hành.'},
    {id:'q4',prompt:'Địa điểm nào phù hợp hơn để bắt đầu?',options:['Đường có xe chạy','Dốc dài để lấy đà','Sân phẳng, khô, trống và có vùng dừng'],answer:2,explanation:'Chọn môi trường kiểm soát được theo khả năng và hướng dẫn.'},
    {id:'q5',prompt:'Khi giày có phần bị nứt hoặc lỏng chưa xử lý, nên làm gì?',options:['Dừng sử dụng và hỏi nhà sản xuất/kỹ thuật viên','Siết theo một lực bất kỳ','Trượt nhanh để thử'],answer:0,explanation:'Bảo dưỡng cần đúng model và quy trình, không đoán bằng vẻ ngoài.'},
    {id:'q6',prompt:'Khi muốn học ramp/rail hoặc kỹ thuật phanh trượt chuyên sâu?',options:['Tự tăng tốc theo video ngắn','Học trực tiếp trong điều kiện và thiết bị phù hợp','Dùng checklist của ứng dụng như bảo đảm an toàn'],answer:1,explanation:'Những mục này chỉ định hướng; không thay thế HLV và đánh giá điều kiện thực tế.'}
  ]);
  return Object.freeze({VERSION:5,arena,videos:Object.freeze([...learning.videos,...videoExpansion.videos]),disciplines:Object.freeze(expansion.disciplines.map(d=>Object.freeze({...d,stages:Object.freeze([...d.stages,Object.freeze({title:"Quan sát video & phản hồi",ids:Object.freeze(learning.entries.filter(s=>s.discipline===d.id).map(s=>s.id))}),Object.freeze({title:"Thi đấu & nhánh mở rộng",ids:Object.freeze(arena.entries.filter(s=>s.discipline===d.id).map(s=>s.id))})])}))),sources,categories,levels,skills,gear,safety,glossary:Object.freeze([...glossary,...arena.glossary]),faq:Object.freeze([...faq,...arena.faq]),pathway,quiz,authorship:{owner:'HH original Vietnamese educational content',license:'Project-owned text and original SVG; external pages linked only; publisher videos via opt-in standard embeds, no redistribution',reviewStatus:'draft-coach-review-needed',createdAt:'2026-10-10'}});
});
