/* Original HH learning dossiers. Reading routes are recommendations, never skill certification. */
(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./patin-data'):root.HHPatinData);if(typeof module==='object'&&module.exports)module.exports=api;else root.HHPatinAcademy=api;})(globalThis,function(D){
 'use strict';
 const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const groups=Object.freeze([['foundation','Nền tảng'],['freeskate','Freeskate & đổi hướng'],['speed','Speed'],['slide','Slide'],['slalom','Slalom'],['quad','Quad'],['specialist','Skatepark · định hướng']].map(([id,title])=>Object.freeze({id,title})));
 const families=Object.freeze([['equipment','Thiết bị & bối cảnh'],['balance','Tư thế & thăng bằng'],['travel','Di chuyển & nhịp'],['stop','Dừng & giảm tốc'],['turn','Rẽ & chuyển hướng'],['cones','Cọc & footwork'],['contact','Ít bánh · sitting · jumping'],['review','Quan sát & phản hồi'],['rules','Luật & thi đấu']].map(([id,title])=>Object.freeze({id,title})));
 function group(s){return s.category==='quad'?'quad':s.discipline||(['turning','braking'].includes(s.category)?'freeskate':s.category==='specialist'?'specialist':'foundation');}
 function shoe(s){if(s.category==='quad')return 'quad';if(['gear-check','ready-stance','stand-up','fall-awareness','static-steps','learning-video','practice-feedback','competition-documents','competition-briefing','competition-review','competition-result-provenance'].includes(s.id))return 'context';return 'inline';}
 function family(s){if(/(?:rules|judging|validation|tech-art|competition-|time-trial|points-elimination|classic-battle|music-rights)/.test(s.id))return 'rules';if(/(?:review|observation|video|feedback|notes|language)/.test(s.id))return 'review';if(/gear|equipment|setup|surface|preparation/.test(s.id))return 'equipment';if(/toe|heel-line|wheel-switch|footgun|christie|daffy|wiper|jump|rail|ramp/.test(s.id))return 'contact';if(group(s)==='slide'||s.category==='braking')return 'stop';if(s.category==='turning'||/curve|crossover|transition/.test(s.id))return 'turn';if(group(s)==='slalom')return 'cones';if(s.category==='foundation'&&/stance|weight|one-foot|stand-up|fall/.test(s.id))return 'balance';return 'travel';}
 const checks=Object.freeze([{id:'context',title:'Đã đọc điều kiện, loại giày và giới hạn của bài.'},{id:'basis',title:'Đã xem nền tảng liên quan; đánh dấu không xác minh năng lực.'},{id:'question',title:'Đã ghi điều cần hỏi HLV vào ghi chú riêng.'},{id:'review',title:'Đã tự đối chiếu mục tiêu với phản hồi thực tế, nếu có.'}]);
 const readingLinks=Object.freeze([
  ['gear-check','protective-gear','Putting On Your Protective Gear'],
  ['stand-up','how-to-stand-up','How to Stand up on Rollerblades'],
  ['heel-brake','stopping-using-the-heel-brake','How to Heelbrake'],
  ['a-turn','how-to-turn','How to Turn'],
  ['backward-roll','skate-backwards','How to Skate Backwards'],
  ['look-ahead','get-passed-an-obstacle','How to Skate Over and Around Obstacles']
 ].map(([skill,path,title])=>Object.freeze({skill,title,publisher:'Sikana / Roller Squad Institut',url:'https://www.sikana.tv/en/sport/inline-skating/'+path,scope:'Tài liệu/video liên quan mở ở website tác giả; không chứng nhận hướng dẫn HH hoặc là đúng mọi biến thể.',checkedAt:'2026-10-10',rights:'External publisher-owned page, link only; no media, transcript or license to redistribute imported.'})));
 const assessments=Object.freeze([['none','Chưa tự đánh giá'],['need-help','Cần HLV giải thích thêm'],['practicing','Đang luyện theo hướng dẫn'],['review-with-coach','Muốn HLV quan sát lại']]);
 const posture={
  foundation:['Hai giày trong khoảng tự nhiên; không cố sao chép góc chân của người khác.','Gối mềm theo khả năng, không khóa thẳng hoặc ép gập.','Thân và hông ổn định; mắt nhìn khoảng trống phía trước.','Chuyển tải nhỏ theo bài HLV giao; chưa nhấc chân nếu chưa ổn định.'],
  freeskate:['Nhận diện chân trụ và chân đổi hướng/phanh trước khi thực hiện.','Giữ gối linh hoạt; tránh xoay riêng cổ chân để ép giày.','Quan sát đường vào, đường ra và vùng dừng; rẽ không thay cho phanh.','Phân bổ tải và thứ tự chuyển chân cần HLV quan sát từng bên.'],
  speed:['Phân biệt chân đang đẩy, chân đang lướt và chân đang thu.','Không ép tư thế thấp hoặc biên độ sải theo hình người thi đấu.','Nhìn hướng chạy và vùng dùng chung; góc quay video không đo lực.','Nhờ HLV kiểm tra chu kỳ đẩy–thu và hai bên; không tự tăng tốc để bù lỗi.'],
  slide:['Vị trí chân phụ thuộc đúng biến thể và setup; tên Slide không mô tả đủ kỹ thuật.','Không tự ép đầu gối, xoắn cổ chân hoặc thử tăng tải từ hình minh họa.','Phải có lối thoát và vùng dừng được HLV kiểm tra trực tiếp.','Lực, góc và tốc độ không được suy ra từ sơ đồ; chỉ xem định hướng.'],
  slalom:['Nhận diện bên dẫn và thứ tự chân trong đúng biến thể.','Gối, hông và thân phối hợp theo phản hồi trực tiếp, không lắc thân để bù.','Nhìn đường cọc và khoảng thoát, không chỉ nhìn mũi giày.','Học chuyển cạnh/tải trước khi ghép nhịp; ít bánh và jumping cần HLV chuyên môn.'],
  quad:['Hai trục bánh ngang khác inline; không áp dụng phanh gót inline.','Setup toe stop và bài đổi cạnh phải theo giày và HLV Quad.','Giữ vùng tập trống; không suy kỹ thuật nghệ thuật từ tư thế inline.','Website chỉ định hướng; chưa có giáo trình Quad chi tiết được HLV rà soát.'],
  specialist:['Setup skatepark khác sân phẳng; không tự thử rail, ramp hoặc nhảy.','Bảo hộ không loại bỏ rủi ro; cần HLV và khu vực chuyên dụng.','Chỉ đọc để hiểu điều kiện, không dùng sơ đồ làm bài thực hành.','Không có góc, lực hoặc công thức tiếp đất dùng chung cho mọi người.']
 };
 // These sequences elaborate HH's existing short guides; no external course text is reproduced.
 const sequences={
  'gear-check':['Đọc tài liệu của đúng model giày, phanh và bảo hộ.','Kiểm tra khóa, dây, bánh, trục và frame trước khi mang.','Nếu có nứt, lỏng hoặc phanh hỏng: ngừng sử dụng, hỏi kỹ thuật viên.','Chọn sân phù hợp rồi nhờ người hướng dẫn kiểm tra lại.'],
  'ready-stance':['Làm quen ở vùng không lăn với hỗ trợ ổn định.','Đặt hai chân trong khoảng tự nhiên.','Thả mềm gối và nhìn phía trước, không dồn thân ra sau.','Đổi nhẹ giữa đứng và tư thế sẵn sàng; nhờ HLV sửa.'],
  'static-steps':['Đứng ở vùng không lăn, kiểm tra khoảng trống.','Thực hiện một bước ngắn rồi dừng lại.','Đặt chân về tư thế ổn định trước bước tiếp theo.','Đổi bên dưới hướng dẫn, không chạy hoặc bước dài.'],
  'march-roll':['Ôn cách dừng đã học trước khi xuất phát.','Chọn một đoạn thẳng rất ngắn và vùng dừng trống.','Chuyển từ bước nhỏ sang lăn chậm theo hướng dẫn.','Kết thúc lượt chủ động; không tăng chiều dài nếu chưa dừng được.'],
  'two-foot-glide':['Xuất phát chậm trên đoạn thẳng có phương án dừng.','Giữ hai chân trong khoảng dễ điều chỉnh.','Để giày lăn ngắn, gối mềm và mắt nhìn phía trước.','Dừng bằng kỹ thuật đã được hướng dẫn; không lấy đà để giữ thăng bằng.'],
  'forward-stride':['Ôn lướt chậm và cách dừng trên cùng mặt sân.','Nhờ HLV chỉ hướng đẩy phù hợp, bắt đầu bằng nhịp nhỏ.','Thu chân về dưới cơ thể thay vì chạy bằng mũi chân.','Luân phiên hai bên và kết thúc lượt trước khi tốc độ vượt kiểm soát.'],
  scissor:['Bắt đầu từ lướt hai chân rất chậm có hướng dẫn.','Đưa một chân hơi trước chân còn lại, không tách quá xa.','Giữ thân ổn định, tránh dồn tải bất ngờ.','Về tư thế ban đầu rồi đổi bên; dừng nếu mất ổn định.'],
  'weight-transfer':['Nhờ HLV kiểm tra tư thế khi đứng ở vùng không lăn.','Chuyển tải nhẹ giữa hai chân, vẫn giữ hỗ trợ hai bên.','Nói rõ chân nào đang chịu tải; không nhấc chân vội.','Chỉ thử lướt rất chậm khi HLV chọn bài phù hợp.'],
  'heel-brake':['Nhờ HLV kiểm tra phanh gót hoạt động trên giày inline.','Lăn rất chậm, đưa chân có phanh hơi trước chân còn lại.','Giữ gối linh hoạt; nhấc mũi chân phanh để má phanh chạm nền.','Tăng lực nhẹ theo hướng dẫn, không ngả toàn thân ra sau.','Dừng trong khoảng trống đã chọn; không áp dụng cho Quad.'],
  'look-ahead':['Chọn đường tập ngắn và vùng dừng trống.','Nhìn điểm phía trước thay vì nhìn chằm chằm bánh.','Quan sát người hoặc vật có thể đi vào đường tập.','Nếu vùng trống mất đi: bỏ lượt, chủ động dừng bằng cách đã học.'],
  'stop-zone':['Chọn tốc độ chậm đã được hướng dẫn.','Đặt vật đánh dấu mềm ngoài đường lăn, không tạo chướng ngại.','Xác định vùng xuất phát và vùng kết thúc còn đủ trống.','Nếu vượt vùng dừng: giảm yêu cầu và xin HLV sửa, không thi khoảng dừng.'],
  'step-turn':['Bắt đầu gần đứng yên ở khoảng trống.','Đổi hướng bằng bước nhỏ, không xoay giật vai.','Đặt lại chân ổn định giữa các bước.','Ôn cả hai bên trước khi lăn tiếp.'],
  'cone-lines':['Ôn rẽ rộng và dừng có kiểm soát trước.','Dùng ít cọc mềm, khoảng thưa phù hợp do HLV chọn.','Lăn chậm và ưu tiên đường thoát, không cố ôm sát cọc.','Bỏ lượt nếu đường dừng bị người khác đi vào.'],
  'stance-reset':['Kết thúc lượt bằng cách dừng đã học.','Đặt lại chân ở khoảng dễ điều chỉnh.','Thả mềm gối, nhìn trước và kiểm tra sân.','Chỉ bắt đầu lượt mới khi có khoảng trống và người hướng dẫn phù hợp.'],
  'learning-video':['Đọc tên kỹ năng, tác giả và giới hạn video.','Xem trọn phần vào, thực hiện và kết thúc; không suy từ một khung ảnh.','Phân biệt video đúng bài với clip nền tảng liên quan.','Ghi câu hỏi cho HLV; xem xong không tự đánh dấu đã thử.'],
  'practice-feedback':['Chọn một bài và mô tả điều đang chưa hiểu.','Ghi bên, mặt sân và phản hồi HLV thực sự nhận được.','Tách nhận xét cá nhân khỏi đánh giá chuyên môn.','Chọn một việc cần hỏi lại; không tự kết luận thành thạo.']
 };
 const routeRows=[
  ['beginner','Bắt đầu có hướng dẫn','Thiết bị → tư thế → dừng → lăn ngắn. Không yêu cầu tăng tốc.',['gear-check','ready-stance','stand-up','fall-awareness','static-steps','heel-brake','march-roll','two-foot-glide'],'Trao đổi với HLV về tư thế và khả năng dừng trước khi tăng yêu cầu.'],
  ['control','Kiểm soát & dừng','Chuẩn bị vùng dừng, tải trọng và đổi hướng hai bên.',['look-ahead','heel-brake','stop-zone','scissor','weight-transfer','one-foot','a-turn','parallel-turn','t-stop'],'Bài sau chỉ là gợi ý đọc; HLV chọn cách phanh phù hợp từng loại giày.'],
  ['speed','Nền tảng Speed','Setup → quan sát tư thế → chu kỳ đẩy–thu → đọc bối cảnh.',['speed-equipment','speed-posture','speed-push','speed-recovery','speed-single-support','speed-cadence','speed-session-review','speed-time-trial'],'Không suy từ số bài đã đọc rằng đủ điều kiện đua hoặc tập tốc độ cao.'],
  ['slide','Nền tảng Slide','Đọc setup, mặt sân, ngôn ngữ kỹ thuật và phản hồi trước khi tìm HLV.',['slide-preparation','slide-surface','edge-control','slide-movement-language','slide-viewing-checklist','slide-setup-differences','slide-coach-review','slide-judging-context'],'Nhánh tìm hiểu, không phải chuỗi tự thực hành phanh trượt.'],
  ['slalom','Nền tảng Slalom','Setup, cọc, đường lăn và nhịp → tìm hiểu biến thể.',['slalom-setup','cone-lines','fish','snake','slalom-cross','slalom-leading-foot','slalom-rhythm','slalom-bilateral','slalom-session-review'],'Khoảng cọc và biến thể do HLV điều chỉnh; không khóa bài chuyên sâu.']
 ];
 const paths=Object.freeze(routeRows.map(([id,title,reason,ids,criteria])=>Object.freeze({id,title,reason,ids:Object.freeze(ids),criteria})));
 function lesson(id){const s=D.skills.find(x=>x.id===id);if(!s)return null;const g=group(s),orientation=s.scope==='orientation',technical=!!sequences[id];
  const steps=sequences[id]||[s.learningConditions,'Ôn tên và mục tiêu: '+s.goal,(orientation?'Chỉ đọc cùng HLV: ':'Bài do HLV điều chỉnh: ')+s.drill,'Điểm cần đối chiếu: '+s.mistake,'Kết thúc bằng câu hỏi: '+s.check];
  return {skill:s,group:g,shoe:shoe(s),family:family(s),orientation,technical,author:'HH · bản biên soạn gốc',checkedAt:'2026-10-10',review:'Chưa được HLV rà soát trực tiếp',steps,posture:posture[g],risk:orientation?'Chỉ định hướng · cần HLV chuyên môn':'Có rủi ro · cần hướng dẫn phù hợp',equipment:shoe(s)==='quad'?'Giày Quad và bảo hộ phù hợp; không dùng công thức phanh inline.':shoe(s)==='context'?'Kiểm tra loại giày thực tế với HLV; bài chung không xác nhận tương thích mọi setup.':'Giày inline phù hợp đúng bài; kiểm tra phanh, frame và bánh theo model.',surface:orientation?'Sân chuyên dụng và điều kiện do HLV đánh giá; không thử trên đường công cộng.':'Sân phẳng, khô, thoáng; không có xe, cát, dầu hoặc người trong vùng dừng.',preparation:s.prerequisites.length?s.prerequisites:['gear-check'].filter(x=>x!==s.id),errors:[{sign:s.mistake,action:orientation?'Dừng ở việc đọc, ghi lại tên biến thể và hỏi HLV; không tự sửa bằng tăng tốc.':'Giảm yêu cầu, đặt lại tư thế đã học và nhờ HLV quan sát trước lượt mới.'}],drills:[{title:'Trước lượt',text:'Kiểm tra sân/giày, ôn nền tảng và thống nhất một mục tiêu nhỏ với HLV.'},{title:orientation?'Quan sát có hướng dẫn':'Bài chính',text:s.drill},{title:'Sau lượt / sau khi đọc',text:s.check}],previous:s.prerequisites,next:D.skills.filter(x=>x.prerequisites.includes(id)).map(x=>x.id).slice(0,6),sources:[...D.sources.filter(x=>s.sources.includes(x.id)),...readingLinks.filter(x=>x.skill===id)],checks};
 }
 function filter(items,{shoe:sh='all',family:fa='all'}={}){if(!['all','inline','quad','context'].includes(sh)||!['all',...families.map(f=>f.id)].includes(fa))throw Error('Bộ lọc Academy không hợp lệ.');return items.filter(s=>(sh==='all'||shoe(s)===sh)&&(fa==='all'||family(s)===fa));}
 function validateRecords(value){if(value===undefined)return {version:1,records:{}};if(!value||value.version!==1||!value.records||typeof value.records!=='object'||Array.isArray(value.records)||Object.keys(value.records).length>D.skills.length)throw Error('Dữ liệu luyện tập không hợp lệ.');const records={};for(const [id,r]of Object.entries(value.records)){if(!lesson(id)||!r||!Array.isArray(r.checks)||r.checks.length>checks.length||new Set(r.checks).size!==r.checks.length||r.checks.some(x=>!checks.some(c=>c.id===x))||!assessments.some(([x])=>x===r.assessment))throw Error('Checklist hoặc tự đánh giá không hợp lệ.');records[id]={checks:[...r.checks],assessment:r.assessment};}return {version:1,records};}
 function record(state,id){return state.workshop.academy?.records[id]||{checks:[],assessment:'none'};}
 function setRecord(state,id,patch,expected){if(!lesson(id))throw Error('Không có bài học.');if(JSON.stringify(record(state,id))!==JSON.stringify(expected))throw Error('Checklist đã đổi ở tab khác. Bản của bạn giữ trong phiên; xuất hoặc tải lại để đối chiếu.');const clean=validateRecords({version:1,records:{[id]:patch}});state.workshop.academy=validateRecords(state.workshop.academy);state.workshop.academy.records[id]=clean.records[id];}
 const link=id=>'<a class="pt-chip" href="#/patin/skills/'+id+'" data-app-route="/patin/skills/'+id+'">'+escape(D.skills.find(s=>s.id===id)?.title||id)+'</a>';
 function pathsMarkup(state){return '<section class="pta-learning-paths"><h3>Chọn đường đọc · không khóa kỹ năng</h3><p>Thứ tự giúp tìm bài, không xác nhận đủ năng lực thực hành.</p>'+paths.map(p=>'<details class="pt-card" data-pta-path="'+p.id+'"><summary>'+escape(p.title)+' · '+p.ids.length+' bài</summary><p>'+escape(p.reason)+'</p><ol>'+p.ids.map(id=>'<li>'+link(id)+(state.progress[id]?.read?' <span class="pt-tag">Đã đọc · tự ghi</span>':'')+'</li>').join('')+'</ol><p class="pt-notice">'+escape(p.criteria)+'</p></details>').join('')+'</section>';}
 function dossierMarkup(id,{detailed=false}={}){const l=lesson(id);if(!l)return '';const s=l.skill;return '<section class="pta-dossier" data-pta-dossier="'+id+'"><p class="ptg-read-label">'+escape(l.author+' · '+l.review)+'</p>'+(detailed?'<div class="pta-dossier-meta"><span>'+escape(groups.find(x=>x.id===l.group).title)+'</span><span>'+escape(l.equipment)+'</span><span>'+escape(l.risk)+'</span></div><p>'+escape(l.surface)+'</p>':'<p><strong>'+escape(l.risk)+'</strong></p><details><summary>Điều kiện, bảo hộ & loại giày</summary><p>'+escape(l.equipment)+'</p><p>'+escape(l.surface)+'</p></details>')+'<h4>'+ (l.technical?'Từng bước có hướng dẫn':'Lộ trình đọc & trao đổi — không phải công thức động tác')+'</h4><ol class="ptg-read-steps">'+l.steps.map((p,i)=>'<li><span aria-hidden="true">'+String(i+1).padStart(2,'0')+'</span><section><p>'+escape(p)+'</p></section></li>').join('')+'</ol><section class="ptg-coach"><h4>Lỗi & cách quay về bài phù hợp</h4>'+l.errors.map(x=>'<p><strong>Nhận diện:</strong> '+escape(x.sign)+'</p><p><strong>Xử lý:</strong> '+escape(x.action)+'</p>').join('')+'</section>'+(detailed?'<section class="pt-card"><h4>Chân · gối · hông · thân · hướng nhìn</h4><ul>'+l.posture.map(p=>'<li>'+escape(p)+'</li>').join('')+'</ul><p>Tư thế là điểm quan sát chung theo nhóm, không phải góc chuẩn hoặc hướng dẫn cá nhân.</p></section><section class="pt-card"><h4>Chuẩn bị / bài chính / tự đối chiếu</h4>'+l.drills.map(d=>'<h5>'+escape(d.title)+'</h5><p>'+escape(d.text)+'</p>').join('')+'</section><section class="pt-card"><h4>Nền tảng và nhánh tiếp theo</h4><p>Liên hệ do kho bài hiện có cung cấp, không chứng nhận điều kiện đủ.</p><div class="pt-chips">'+l.previous.map(link).join('')+'</div><h5>Bài dùng nền tảng này</h5><div class="pt-chips">'+(l.next.map(link).join('')||'Chưa có nhánh tiếp theo trong kho.')+'</div></section><section class="pt-card"><h4>Tác giả, nguồn & giới hạn</h4><p>'+escape(l.author)+' · tổ chức/nguồn liên quan đối chiếu '+l.checkedAt+'. Không phải ngày HLV duyệt bài.</p><ul>'+l.sources.map(x=>'<li><a href="'+escape(x.url)+'" target="_blank" rel="noopener noreferrer">'+escape(x.title)+' ↗</a><small>'+escape(x.publisher||'Nguồn liên quan')+' · '+escape(x.checkedAt||'Chưa ghi ngày đối chiếu')+'</small><p>'+escape(x.scope)+'</p></li>').join('')+'</ul><p>Không trích chép khóa học; nguồn liên quan không chứng nhận mọi câu hướng dẫn HH. Không có thời gian thành thạo đảm bảo.</p></section>':'')+'<p class="pt-muted">Mã tra cứu: '+escape(s.id)+(s.aka.length?' · Tên liên quan: '+escape(s.aka.join(' · ')):'')+'</p><p class="pt-muted">Mục tiêu: '+escape(s.goal)+' · tự quan sát: '+escape(s.check)+'</p></section>';}
 function writtenText(id){const l=lesson(id);if(!l)throw Error('Không có bài.');return ['HH PATIN SKILL ACADEMY',l.skill.title,l.author,l.review,l.equipment,l.surface,l.risk,...l.steps.map((s,i)=>(i+1)+'. '+s),'Điểm quan sát chung:',...l.posture,'Lỗi: '+l.skill.mistake,'Tự đối chiếu: '+l.skill.check,...l.sources.map(s=>s.title+' — '+s.url),'Sơ đồ và nội dung không chứng nhận kỹ thuật, thể lực hoặc an toàn.'].join('\n\n');}
 function audit(){return {topics:D.skills.length,technical:Object.keys(sequences).length,orientation:D.skills.filter(s=>s.scope==='orientation').length,directVideo:D.skills.filter(s=>D.videos.some(v=>v.skillIds.includes(s.id))).length,groups:groups.map(g=>({...g,count:D.skills.filter(s=>group(s)===g.id).length})),paths:paths.length};}
 return Object.freeze({version:1,groups,families,group,shoe,family,lesson,filter,checks,readingLinks,assessments,paths,pathsMarkup,dossierMarkup,writtenText,audit,validateRecords,record,setRecord});
});
