/* HH original SVG teaching cards. Not motion capture, force geometry, or coaching certification. */
(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./patin-data'):root.HHPatinData,typeof module==='object'&&module.exports?require('./patin-core'):root.HHPatinCore,typeof module==='object'&&module.exports?require('./patin-visuals'):root.HHPatinVisuals);if(typeof module==='object'&&module.exports)module.exports=api;else root.HHPatinGuide=api;})(globalThis,function(D,C,V){
 'use strict';
 const e=C.escape,sk=id=>D.skills.find(s=>s.id===id),wheel=(x,y)=>'<circle class="pt-figure-wheel" cx="'+x+'" cy="'+y+'" r="9"/>';
 const shoe=(x,y,a=0)=>'<g transform="translate('+x+' '+y+') rotate('+a+')"><rect class="pt-figure-body" x="-14" y="-36" width="28" height="72" rx="12"/>'+[-22,0,22].map(y=>wheel(0,y)).join('')+'</g>';
 const line=d=>'<path class="pt-figure-ground" d="'+d+'"/>',route=d=>'<path class="ptg-route" d="'+d+'"/>';
 const cones=()=>[80,145,210,275,340].map(x=>'<path class="ptg-cone" d="m'+x+' 146-8 18h16Z"/>').join('');
 const references=new Map(C.arena.catalog().map(r=>[r.id,r]));
 const headings=['Nhận diện','Điểm quan sát','Bối cảnh & giới hạn'];
 const familyData=[
 ['footwork','Bước nhỏ & vị trí hai giày',shoe(160,145,-16)+shoe(255,175,16)+line('M85 260h250'),'Hướng mũi giày và khoảng trống; không ấn định góc mở chân.',[160,255,95]],
 ['glide','Giữ hướng lăn',shoe(165,145)+shoe(250,145)+route('M165 200V80 M250 200V80'),'Đường hướng lăn khái niệm; không mô tả lực đẩy hoặc tốc độ.',[165,250,80]],
 ['load','Hai bên và phần chân trụ',shoe(150,180)+shoe(285,180)+'<ellipse class="ptg-zone" cx="150" cy="180" rx="35" ry="63"/>'+line('M100 264h235'),'Vùng nhấn chỉ là điểm quan sát, không mô tả trọng lượng hay góc nghiêng.',[150,285,100]],
 ['swizzles','Mở–thu hai đường chân',route('M185 265C80 190 80 110 185 45 M235 265C340 190 340 110 235 45')+shoe(130,155,-20)+shoe(290,155,20),'Đường mở–thu cách điệu, không theo tỷ lệ và không quy định tốc độ.',[130,290,210]],
 ['turn','Hướng vào, đường cong, lối ra',route('M60 245Q210 245 285 80')+shoe(176,225,-45)+'<circle class="ptg-zone" cx="285" cy="80" r="24"/>','Đường cong là bối cảnh quan sát, không quy định bán kính hay cách nghiêng người.',[80,176,285]],
 ['edge','Vùng tiếp xúc bánh',wheel(155,195)+wheel(265,195)+line('M65 205h290')+'<path class="ptg-zone" d="M135 85h40v80h-40Z M245 85h40v80h-40Z"/>','Chỉ nhận diện bánh và nền; không chỉ định góc ép, tải hoặc cách nghiêng.',[155,265,75]],
 ['cones','Hàng cọc và khoảng trống',cones()+shoe(95,75)+line('M45 240h330'),'Hàng cọc không theo tỷ lệ. Xác nhận khoảng cọc và lối dừng với HLV.',[80,210,340]],
 ['fish','Đường lượn song song qua cọc',cones()+route('M42 112Q85 35 120 112T245 112T370 112 M42 132Q85 55 120 132T245 132T370 132'),'Hai nét minh họa sự song song; không là quỹ đạo chính xác của Fish trong mọi lượt.',[80,210,340]],
 ['snake','Một đường lượn quanh cọc',cones()+route('M42 132Q85 70 120 170T245 170T370 170'),'Đường giữa cách điệu để nhìn bối cảnh Snake, không đặt vị trí chân/độ nghiêng.',[80,210,340]],
 ['cross','Hai đường giao nhau',cones()+route('M45 100Q112 225 180 100T315 100 M45 205Q112 75 180 205T315 205'),'Giao đường chỉ là ký hiệu nhận diện Cross, không mô tả thứ tự bắt chéo thực tế.',[112,180,315]],
 ['contact','Cấu hình tiếp xúc ít bánh',shoe(140,150)+shoe(280,150)+'<circle class="ptg-zone" cx="140" cy="172" r="18"/><circle class="ptg-zone" cx="280" cy="128" r="18"/>','Chỉ nhận diện vùng bánh cần hỏi lại. Không hướng dẫn toe/heel, nhấc bánh hoặc giữ thăng bằng.',[140,280,95]],
 ['speed-cycle','Đẩy, thu và nhịp quan sát',shoe(150,150,-25)+shoe(270,150,25)+route('M110 235Q65 120 150 60 M310 235Q355 120 270 60')+'<path class="ptg-zone" d="M205 70v150h10V70Z"/>','Các nét là ký hiệu chu kỳ quan sát, không phải đường đẩy/thu chuẩn hay double-push.',[150,270,210]],
 ['circuit','Track / Road và vùng dùng chung','<rect class="ptg-zone" x="55" y="60" width="310" height="180" rx="85"/><rect class="ptg-zone" x="95" y="98" width="230" height="104" rx="50"/>'+shoe(208,66,90),'Sơ đồ sân khái niệm, không vẽ cự ly/làn hoặc một chiến thuật vượt người.',[75,208,340]],
 ['slide-context','Vào – toàn lượt – kết thúc','<rect class="ptg-zone" x="38" y="75" width="102" height="150" rx="18"/><rect class="ptg-zone" x="158" y="75" width="102" height="150" rx="18"/><rect class="ptg-zone" x="278" y="75" width="102" height="150" rx="18"/>'+shoe(89,150)+shoe(209,150)+shoe(329,150),'Ba vùng ghi chú khi xem video, KHÔNG là vị trí chân thực hiện một Slide.',[89,209,329]],
 ['notes','Quan sát, ghi lại, trao đổi','<rect class="pt-figure-body" x="80" y="45" width="260" height="220" rx="18"/>'+[95,135,175,215].map(y=>line('M120 '+y+'h180')).join(''),'Thẻ đọc và ghi chú, không phải hình thực hiện động tác.',[120,210,300]],
 ['rules','Tài liệu, phiên bản, kết quả','<rect class="pt-figure-body" x="65" y="65" width="125" height="190" rx="12"/><rect class="pt-figure-body" x="230" y="65" width="125" height="190" rx="12"/>'+line('M88 100h78 M88 135h78 M253 100h78 M253 135h78'),'Thẻ nguồn: phân biệt mức kỹ thuật, đánh giá lượt và thứ hạng VĐV. Không cộng điểm từ tên bài.',[100,210,310]]
 ];
 const families=Object.freeze(familyData.map(([id,title,body,scope,x])=>Object.freeze({id,title,body,scope,points:x.map((x,i)=>({x,y:75+i*65,label:headings[i]}))})));
 const byFamily=id=>families.find(f=>f.id===id);
 const exact={ 'gear-check':'equipment','quad-basics':'types','fall-awareness':'protection','ready-stance':'stance','stance-reset':'stance','weight-transfer':'load',scissor:'stance','heel-brake':'brake','look-ahead':'space','stop-zone':'space','group-ethics':'space','static-steps':'footwork','duck-walk':'footwork','march-roll':'footwork','stepping-stop':'footwork','stand-up':'stance','two-foot-glide':'glide','one-foot':'load','speed-single-support':'load','forward-swizzles':'swizzles','alternating-swizzles':'swizzles','lemon-drops':'swizzles','slalom-back-swizzles':'swizzles','step-turn':'turn','a-turn':'turn','parallel-turn':'turn','edge-control':'edge','slalom-setup':'cones','cone-lines':'cones',fish:'fish',snake:'snake','slalom-cross':'cross','toe-heel':'contact','slalom-toe-roll':'contact','slalom-daffy':'contact' };
 function familyFor(s){if(exact[s.id])return exact[s.id];if(/(?:rules|time-trial|points-elimination|classic-battle|tech-art|validation-context|judging-context|music-rights|competition-)/.test(s.id))return 'rules';if(/(?:review|feedback|video|session|notes)/.test(s.id))return 'notes';if(s.discipline==='slide')return 'slide-context';if(s.discipline==='speed')return /curve|crossover|paceline|passing|relay|drafting|finish/.test(s.id)?'circuit':'speed-cycle';if(s.discipline==='slalom')return s.level==='advanced'?'notes':'cones';if(s.category==='turning')return 'turn';if(s.category==='braking')return 'space';if(s.category==='quad'||s.category==='specialist')return 'notes';return 'glide';}
 function guide(id){const s=sk(id);if(!s)return null;const family=familyFor(s),f=byFamily(family)||V.get(family),direct=D.videos.filter(v=>v.skillIds.includes(id)),ancestorIds=new Set(s.prerequisites),related=D.videos.filter(v=>!direct.includes(v)&&v.skillIds.some(id=>ancestorIds.has(id))).slice(0,3);return {skill:s,family,visualTitle:f.title,scope:f.scope||f.description,body:f.body,points:f.points,exactConcept:!!exact[id],direct,related,questions:s.coachQuestions?.length?s.coachQuestions:[s.check+' Phần nào cần HLV quan sát trực tiếp?'],observations:[s.goal,s.drill,s.check],reference:references.get(id)||null};}
 function badges(id){const g=guide(id);return {written:true,visual:true,video:g?.direct.length>0,verified:!!g?.reference?.reference};}
 function filter(items,{method='all'}={}){if(!['all','video','visual','written','verified'].includes(method))throw Error('Kiểu học không hợp lệ.');return method==='all'?items:items.filter(s=>badges(s.id)[method]);}
 function svg(id,{point=0,zoom=1,panX=0,panY=0,standalone=false,uid='ptg'}={}){const g=guide(id);if(!g)throw Error('Không có bài để minh họa.');point=Math.max(0,Math.min(2,Number.isInteger(point)?point:0));zoom=[1,1.25,1.5,2].includes(zoom)?zoom:1;const width=420/zoom,height=300/zoom,maxX=(420-width)/2,maxY=(300-height)/2,x=210-width/2+Math.max(-maxX,Math.min(maxX,Number(panX)||0)),y=150-height/2+Math.max(-maxY,Math.min(maxY,Number(panY)||0)),safeUid=/^[a-z0-9-]+$/i.test(uid)?uid:'ptg';
 const desc=g.scope+' '+headings[point]+': '+g.observations[point],style=standalone?'<style>svg{background:#0e1930;color:#eef6ff}.pt-figure-body{fill:#34526b;stroke:#a8e4dd;stroke-width:3}.pt-figure-line{fill:none;stroke:#d6dcff;stroke-width:8;stroke-linecap:round}.pt-figure-ground,.ptg-route{fill:none;stroke:#83eadb;stroke-width:4;stroke-linecap:round}.ptg-route{stroke-dasharray:8 6}.pt-figure-wheel,.ptg-zone{fill:#293854;stroke:#c9b2ff;stroke-width:3}.pt-figure-brake,.ptg-cone{fill:#efc988;stroke:#fff0c3;stroke-width:2}.pt-figure-hub{fill:#88ffe1}.pt-figure-pad{fill:#8068a6;stroke:#ecdeff}.ptg-point circle{fill:#20314a;stroke:#cab3ff;stroke-width:2}.ptg-point text{fill:#fff;font:bold 15px system-ui}.ptg-point.is-active circle{fill:#ffe1a0}.ptg-point.is-active text{fill:#102430}</style>':'';
 return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="'+[x,y,width,height].join(' ')+'" role="img" aria-labelledby="'+safeUid+'-title '+safeUid+'-desc" data-ptg-svg="'+e(id)+'"><title id="'+safeUid+'-title">'+e(g.skill.title+' · '+g.visualTitle)+'</title><desc id="'+safeUid+'-desc">'+e(desc)+'</desc>'+style+'<g aria-hidden="true">'+g.body+g.points.map((p,i)=>'<g class="ptg-point '+(i===point?'is-active':'')+'"><circle cx="'+p.x+'" cy="'+p.y+'" r="15"/><text x="'+p.x+'" y="'+(p.y+5)+'" text-anchor="middle">'+(i+1)+'</text></g>').join('')+'</g></svg>';
 }
 function writtenText(id){const g=guide(id);if(!g)throw Error('Không tìm thấy bài.');const s=g.skill;return ['HH PATIN · Bản đọc gốc HH, chưa được HLV rà soát',s.title,'Tên liên quan: '+s.aka.join(' · '),'Mức học HH: '+D.levels.find(l=>l.id===s.level).title+' (không phải xếp hạng thi đấu)','Mục tiêu: '+s.goal,'Điều kiện: '+s.learningConditions,'Nền tảng: '+s.prerequisites.map(id=>sk(id).title).join(' · '),'Hướng tiếp cận: '+s.drill,'Điều dễ hiểu sai: '+s.mistake,'Tự quan sát: '+s.check,'Câu hỏi cho HLV: '+g.questions.join('\n'),'Video đúng bài: '+(g.direct.length?g.direct.map(v=>v.originalTitle+' — '+v.watchUrl).join('\n'):'Chưa có video trực tiếp được HH đối chiếu.'),'Minh họa: '+g.scope,'Nguồn: '+D.sources.filter(x=>s.sources.includes(x.id)).map(x=>x.title+' — '+x.url).join('\n'),'Không phải hướng dẫn để tự thử kỹ thuật nguy hiểm hoặc chứng nhận thành thạo.'].join('\n\n');}
 return Object.freeze({version:1,families,guide,badges,filter,svg,writtenText,headings});
});
