(() => {
  "use strict";

  const STORAGE_KEY = "hh.developer-toolbox.v2";
  const GROUPS = ["Dữ liệu", "Bảo mật", "Văn bản", "Thiết kế", "Tiện ích", "Mạng & API", "Mã nguồn", "Hệ thống"];
  const TOOLS = [
    { id: "json", icon: "{}", name: "JSON Formatter", group: "Dữ liệu", description: "Định dạng, kiểm tra, truy vấn, chuyển đổi và so sánh JSON.", caps: ["Validate", "Tree", "Convert", "JSONPath"] },
    { id: "base64", icon: "64", name: "Base64", group: "Dữ liệu", description: "Mã hóa văn bản UTF-8, dữ liệu nhị phân và tệp bất kỳ.", caps: ["UTF-8", "URL safe", "File", "Preview"] },
    { id: "uuid", icon: "#", name: "UUID & Token", group: "Bảo mật", description: "Tạo UUID v1/v4/v6/v7, ULID, NanoID, token và đọc JWT.", caps: ["UUID", "ULID", "JWT", "Entropy"] },
    { id: "password", icon: "✦", name: "Password Generator", group: "Bảo mật", description: "Sinh mật khẩu, passphrase, đo entropy và kiểm tra rò rỉ.", caps: ["CSPRNG", "Passphrase", "Strength", "Pwned check"] },
    { id: "timestamp", icon: "◷", name: "Timestamp", group: "Dữ liệu", description: "Chuyển Unix, ISO, múi giờ, đếm ngược và tính chênh lệch.", caps: ["Unix", "ISO 8601", "Timezone", "Relative"] },
    { id: "regex", icon: ".*", name: "Regex Tester", group: "Văn bản", description: "Thử biểu thức chính quy, capture group, replace và đo hiệu năng.", caps: ["Highlight", "Groups", "Replace", "Timing"] },
    { id: "text", icon: "T", name: "Text Utilities", group: "Văn bản", description: "Chuẩn hóa chữ, dòng, slug, encode và thống kê văn bản.", caps: ["30+ transforms", "Stats", "Encode", "Markdown"] },
    { id: "color", icon: "◉", name: "Color Studio", group: "Thiết kế", description: "Chuyển đổi màu, tạo palette, gradient và kiểm tra WCAG.", caps: ["HEX/RGB/HSL", "Palette", "Contrast", "CSS"] },
    { id: "compare", icon: "⇄", name: "Text Compare", group: "Văn bản", description: "So sánh hai văn bản theo dòng với bộ lọc và thống kê.", caps: ["Line diff", "Ignore rules", "Patch", "Export"] },
    { id: "calculator", icon: "∑", name: "Calculator", group: "Tiện ích", description: "Máy tính chuẩn, khoa học, programmer và chuyển đổi đơn vị.", caps: ["Scientific", "Binary/Hex", "Units", "History"] },
    { id: "notes", icon: "✓", name: "Notes & Todo", group: "Tiện ích", description: "Ghi chú và checklist có ưu tiên, tìm kiếm, ghim và autosave.", caps: ["Markdown", "Checklist", "Priority", "Offline"] },
    { id: "system", icon: "◫", name: "System Monitor", group: "Hệ thống", description: "Thông tin trình duyệt, bộ nhớ, pin, mạng, màn hình và WebGL.", caps: ["Realtime", "Battery", "Network", "Performance"] },
    { id: "hash", icon: "#", name: "Hash Tools", group: "Bảo mật", description: "Tạo SHA, CRC32, HMAC cho văn bản hoặc tệp.", caps: ["SHA-1/256/512", "CRC32", "HMAC", "File hash"] },
    { id: "encryption", icon: "◇", name: "Encryption", group: "Bảo mật", description: "Mã hóa AES-GCM, tạo khóa an toàn và kiểm tra JWT.", caps: ["AES-GCM", "PBKDF2", "JWT", "Keygen"] },
    { id: "url", icon: "↗", name: "URL Tools", group: "Mạng & API", description: "Phân tích URL, query, encode/decode và tạo UTM.", caps: ["Parser", "Query", "UTM", "Encode"] },
    { id: "qr-barcode", icon: "▦", name: "QR & Barcode", group: "Dữ liệu", description: "Tạo QR tùy màu và barcode Code 39 để tải PNG.", caps: ["QR", "Code 39", "PNG", "Local"] },
    { id: "api", icon: "⇆", name: "API Tester", group: "Mạng & API", description: "Gửi HTTP request, headers, JSON body và đo response timing.", caps: ["REST", "Headers", "Body", "Timing"] },
    { id: "image", icon: "▧", name: "Image Tools", group: "Thiết kế", description: "Resize, rotate, filter, nén và chuyển đổi ảnh cục bộ.", caps: ["Resize", "Filters", "WebP", "Metadata"] },
    { id: "sql", icon: "DB", name: "SQL Tools", group: "Mã nguồn", description: "Định dạng, minify và chuẩn hóa từ khóa SQL.", caps: ["Format", "Minify", "Keywords", "Stats"] },
    { id: "markdown", icon: "M", name: "Markdown", group: "Mã nguồn", description: "Editor, preview, mục lục và xuất HTML hoàn chỉnh.", caps: ["Preview", "TOC", "HTML", "Autosave"] },
    { id: "cron", icon: "◴", name: "Cron", group: "Mã nguồn", description: "Phân tích cron 5 trường và tính các lần chạy tiếp theo.", caps: ["Parser", "Next runs", "Presets", "Explain"] },
    { id: "network", icon: "◎", name: "DNS / IP", group: "Mạng & API", description: "Tra DNS qua Google DoH, IP công khai và HTTP headers.", caps: ["DNS", "Public IP", "Headers", "Latency"] }
  ];

  const state = { host: null, root: null, active: "json", file: null, image: null, imageUrl: "", timer: 0, systemTimer: 0, lastOutput: "", undo: [], redo: [] };
  const $ = (root, selector) => root?.querySelector(selector);
  const $$ = (root, selector) => [...(root?.querySelectorAll(selector) || [])];
  const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]);
  const clamp = (value, min, max) => Math.min(max, Math.max(min, Number(value) || 0));
  const uid = () => crypto.randomUUID?.() || `${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const toolById = (id) => TOOLS.find((tool) => tool.id === id) || TOOLS[0];
  const formatBytes = (value) => value < 1024 ? `${value} B` : value < 1048576 ? `${(value / 1024).toFixed(1)} KB` : `${(value / 1048576).toFixed(2)} MB`;
  const readStore = () => { try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}"); } catch { return {}; } };
  const writeStore = (patch) => { const next = { ...readStore(), ...patch }; localStorage.setItem(STORAGE_KEY, JSON.stringify(next)); return next; };
  const randomBytes = (length) => crypto.getRandomValues(new Uint8Array(length));
  const hex = (buffer) => [...new Uint8Array(buffer)].map((value) => value.toString(16).padStart(2, "0")).join("");
  const bytesToBase64 = (bytes) => { let binary = ""; for (let index = 0; index < bytes.length; index += 0x8000) binary += String.fromCharCode(...bytes.subarray(index, index + 0x8000)); return btoa(binary); };
  const base64ToBytes = (value) => { const normalized = value.replace(/-/g, "+").replace(/_/g, "/").replace(/\s/g, ""), padded = normalized + "=".repeat((4 - normalized.length % 4) % 4); return Uint8Array.from(atob(padded), (char) => char.charCodeAt(0)); };
  const utf8ToBase64 = (value) => bytesToBase64(new TextEncoder().encode(value));
  const base64ToUtf8 = (value) => new TextDecoder("utf-8", { fatal: true }).decode(base64ToBytes(value));
  const download = (content, filename, type = "text/plain;charset=utf-8") => { const blob = content instanceof Blob ? content : new Blob([content], { type }); const anchor = document.createElement("a"); anchor.href = URL.createObjectURL(blob); anchor.download = filename; anchor.click(); setTimeout(() => URL.revokeObjectURL(anchor.href), 2000); };
  const copy = async (value) => { await navigator.clipboard.writeText(String(value)); toast("Đã sao chép vào clipboard.", "success"); };
  const toast = (message, kind = "info") => { const node = $(state.root, "[data-dev-toast]"); if (!node) return; node.textContent = message; node.dataset.state = kind; node.hidden = false; clearTimeout(state.timer); state.timer = setTimeout(() => { node.hidden = true; }, 2600); };
  const setStatus = (message, kind = "info") => { const node = $(state.root, "[data-dev-status]"); if (node) { node.textContent = message; node.dataset.state = kind; } };
  const setOutput = (value, { html = false } = {}) => { const output = $(state.root, "[data-dev-output]"); state.lastOutput = typeof value === "string" ? value : JSON.stringify(value, null, 2); if (!output) return; if (html) output.innerHTML = value; else output.textContent = state.lastOutput; output.dataset.empty = state.lastOutput ? "false" : "true"; };
  const currentInput = () => $(state.root, "[data-dev-input]")?.value || "";
  const secondInput = () => $(state.root, "[data-dev-secondary]")?.value || "";
  const option = (name) => $(state.root, `[data-dev-option='${name}']`)?.value ?? "";
  const checked = (name) => Boolean($(state.root, `[data-dev-check='${name}']`)?.checked);
  const recordHistory = (summary) => { const store = readStore(), row = { id: uid(), tool: state.active, summary, at: new Date().toISOString() }; writeStore({ history: [row, ...(store.history || [])].slice(0, 80), recent: [state.active, ...(store.recent || []).filter((id) => id !== state.active)].slice(0, 12) }); updateMetrics(); };
  const saveDraft = () => { const store = readStore(), sensitive = ["password", "encryption"].includes(state.active), inputs = {}; $$ (state.root, "[data-dev-input],[data-dev-secondary]").forEach((input) => { inputs[input.dataset.devInput !== undefined ? "input" : "secondary"] = sensitive ? "" : input.value; }); const options = {}; $$ (state.root, "[data-dev-option]").forEach((input) => { options[input.dataset.devOption] = sensitive && ["password", "key"].includes(input.dataset.devOption) ? "" : input.value; }); writeStore({ drafts: { ...(store.drafts || {}), [state.active]: { inputs, options, updatedAt: Date.now() } } }); };
  const restoreDraft = () => { const draft = readStore().drafts?.[state.active]; if (!draft) return; const input = $(state.root, "[data-dev-input]"), secondary = $(state.root, "[data-dev-secondary]"); if (input && draft.inputs?.input !== undefined) input.value = draft.inputs.input; if (secondary && draft.inputs?.secondary !== undefined) secondary.value = draft.inputs.secondary; Object.entries(draft.options || {}).forEach(([key, value]) => { const control = $(state.root, `[data-dev-option='${key}']`); if (control) control.value = value; }); };
  const quickMarkup = (store = readStore()) => { const ids = [...new Set([...(store.favorites || []), ...(store.recent || [])])].filter((id) => toolById(id).id === id).slice(0, 8); return `<span>Truy cập nhanh</span>${ids.map((id) => { const tool = toolById(id); return `<button type="button" data-app-route="/dev-tools/${tool.id}"><i>${tool.icon}</i>${esc(tool.name)}</button>`; }).join("") || '<small>Chạy hoặc yêu thích một tool để ghim tại đây.</small>'}`; };

  const field = (label, control, className = "") => `<label class="dev-field ${className}"><span>${label}</span>${control}</label>`;
  const select = (name, options, selected = "") => `<select data-dev-option="${name}">${options.map(([value, label]) => `<option value="${value}" ${value === selected ? "selected" : ""}>${label}</option>`).join("")}</select>`;
  const commonButtons = (runLabel = "Chạy") => `<div class="dev-actions"><button class="is-primary" type="button" data-dev-run>${runLabel}</button><button type="button" data-dev-copy>Sao chép</button><button type="button" data-dev-download>Tải kết quả</button><button type="button" data-dev-clear>Xóa</button></div>`;
  const outputPane = (label = "Kết quả") => `<section class="dev-pane dev-pane--output"><header><strong>${label}</strong><small>Output</small></header><pre data-dev-output data-empty="true">Chọn tác vụ rồi nhấn Chạy.</pre><div data-dev-preview></div></section>`;
  const editorPane = (label, placeholder, secondary = "") => `<section class="dev-pane"><header><strong>${label}</strong><small>Autosave</small></header><textarea data-dev-input spellcheck="false" placeholder="${esc(placeholder)}"></textarea>${secondary ? `<textarea data-dev-secondary spellcheck="false" placeholder="${esc(secondary)}"></textarea>` : ""}</section>`;

  function toolMarkup(id) {
    if (id === "json") return `<div class="dev-controls">${field("Tác vụ", select("mode", [["beautify", "Beautify"], ["minify", "Minify"], ["validate", "Validate"], ["tree", "Tree view"], ["path", "JSONPath query"], ["yaml", "JSON → YAML"], ["xml", "JSON → XML"], ["csv", "JSON → CSV"], ["toml", "JSON → TOML"], ["markdown", "Markdown table"], ["diff", "JSON diff"], ["schema", "Schema validate"]]))}${field("JSONPath / tìm", '<input data-dev-option="query" placeholder="$.users[0].name">')}${commonButtons()}</div><div class="dev-editor-grid">${editorPane("JSON đầu vào", '{\n  "hello": "world"\n}', "JSON thứ hai hoặc schema cho chế độ Diff/Schema")}${outputPane()}</div>`;
    if (id === "base64") return `<div class="dev-controls">${field("Chế độ", select("mode", [["encode", "Encode UTF-8"], ["decode", "Decode UTF-8"], ["hex-encode", "Text → Hex"], ["hex-decode", "Hex → Text"], ["file", "File → Base64"]]))}<label class="dev-check"><input type="checkbox" data-dev-check="urlsafe"> URL safe</label><label class="dev-file-button">Chọn tệp<input type="file" data-dev-file></label>${commonButtons()}</div><div class="dev-editor-grid">${editorPane("Dữ liệu", "Nhập văn bản Unicode hoặc chọn tệp...")}${outputPane()}</div>`;
    if (id === "uuid") return `<div class="dev-controls">${field("Loại", select("mode", [["v1", "UUID v1"], ["v4", "UUID v4"], ["v6", "UUID v6"], ["v7", "UUID v7"], ["ulid", "ULID"], ["nanoid", "NanoID"], ["token", "Random token"], ["api", "API key"], ["session", "Session ID"], ["jwt", "JWT Inspector"]], "v7"))}${field("Số lượng", '<input type="number" min="1" max="100" value="5" data-dev-option="count">')}${field("Độ dài", '<input type="number" min="8" max="256" value="32" data-dev-option="length">')}${commonButtons("Tạo / Phân tích")}</div><div class="dev-editor-grid">${editorPane("JWT đầu vào (nếu dùng)", "eyJhbGciOi...")}${outputPane()}</div>`;
    if (id === "password") return `<div class="dev-controls">${field("Kiểu", select("mode", [["password", "Mật khẩu"], ["passphrase", "Passphrase"], ["custom", "Custom charset"]]))}${field("Độ dài", '<input type="number" min="4" max="256" value="20" data-dev-option="length">')}${field("Số lượng", '<input type="number" min="1" max="50" value="5" data-dev-option="count">')}<label class="dev-check"><input type="checkbox" data-dev-check="upper" checked> A-Z</label><label class="dev-check"><input type="checkbox" data-dev-check="lower" checked> a-z</label><label class="dev-check"><input type="checkbox" data-dev-check="number" checked> 0-9</label><label class="dev-check"><input type="checkbox" data-dev-check="special" checked> Ký tự đặc biệt</label><label class="dev-check"><input type="checkbox" data-dev-check="similar" checked> Loại ký tự giống nhau</label>${commonButtons("Tạo mật khẩu")}<button type="button" data-dev-pwned>Kiểm tra rò rỉ</button></div><div class="dev-editor-grid">${editorPane("Custom charset / mật khẩu cần kiểm tra", "Để trống khi sinh tự động")}${outputPane("Mật khẩu & độ mạnh")}</div>`;
    if (id === "timestamp") return `<div class="dev-controls">${field("Múi giờ hiển thị", '<input data-dev-option="timezone" value="Asia/Bangkok" list="dev-timezones"><datalist id="dev-timezones"><option>Asia/Bangkok</option><option>Asia/Ho_Chi_Minh</option><option>UTC</option><option>America/New_York</option><option>Europe/London</option><option>Asia/Tokyo</option></datalist>')}${field("Ngày thứ hai", '<input data-dev-option="second" placeholder="2027-01-01">')}<button type="button" data-dev-now>Dùng thời gian hiện tại</button>${commonButtons("Chuyển đổi")}</div><div class="dev-editor-grid">${editorPane("Unix, milliseconds, ISO hoặc ngày", "1720956000")}${outputPane()}</div>`;
    if (id === "regex") return `<div class="dev-controls">${field("Pattern", '<input data-dev-option="pattern" value="\\b\\w{4,}\\b" spellcheck="false">')}${field("Flags", '<input data-dev-option="flags" value="gim" maxlength="7">')}${field("Replace", '<input data-dev-option="replace" placeholder="$1 hoặc nội dung thay thế">')}${field("Tác vụ", select("mode", [["match", "Match"], ["replace", "Replace"], ["split", "Split"]]))}${commonButtons("Test Regex")}</div><div class="dev-editor-grid">${editorPane("Test string", "Regex tester cho phép tìm nhiều kết quả trên nhiều dòng.")}${outputPane("Matches, groups & performance")}</div>`;
    if (id === "text") return `<div class="dev-controls">${field("Biến đổi", select("mode", [["upper", "UPPERCASE"], ["lower", "lowercase"], ["title", "Title Case"], ["sentence", "Sentence case"], ["camel", "camelCase"], ["pascal", "PascalCase"], ["snake", "snake_case"], ["kebab", "kebab-case"], ["slug", "Slugify"], ["trim", "Trim lines"], ["dedupe", "Remove duplicate lines"], ["empty", "Remove empty lines"], ["html-strip", "Remove HTML"], ["markdown-strip", "Strip Markdown"], ["sort", "Sort lines"], ["reverse", "Reverse"], ["url-encode", "URL Encode"], ["url-decode", "URL Decode"], ["html-encode", "HTML Encode"], ["html-decode", "HTML Decode"], ["rot13", "ROT13"], ["stats", "Statistics"]]))}${commonButtons("Biến đổi")}</div><div class="dev-editor-grid">${editorPane("Văn bản", "Nhập văn bản cần xử lý...")}${outputPane()}</div>`;
    if (id === "color") return `<div class="dev-controls">${field("Màu chính", '<input type="color" value="#17d9e6" data-dev-option="color">')}${field("HEX / CSS color", '<input value="#17d9e6" data-dev-option="colorText">')}${field("Màu chữ", '<input type="color" value="#081018" data-dev-option="foreground">')}${field("Màu gradient", '<input type="color" value="#ef5bc8" data-dev-option="second">')}${field("Góc", '<input type="number" min="0" max="360" value="135" data-dev-option="angle">')}${commonButtons("Phân tích màu")}</div><div class="dev-editor-grid"><section class="dev-pane"><header><strong>Color preview</strong><small>WCAG</small></header><div class="dev-color-preview" data-dev-color-preview><strong>HH Developer Toolbox</strong><span>Văn bản kiểm tra độ tương phản</span></div><div class="dev-palette" data-dev-palette></div></section>${outputPane("Mã màu & CSS")}</div>`;
    if (id === "compare") return `<div class="dev-controls"><label class="dev-check"><input type="checkbox" data-dev-check="case"> Bỏ qua hoa/thường</label><label class="dev-check"><input type="checkbox" data-dev-check="space"> Bỏ qua khoảng trắng</label><label class="dev-check"><input type="checkbox" data-dev-check="blank"> Bỏ qua dòng trống</label>${commonButtons("So sánh")}</div><div class="dev-editor-grid dev-editor-grid--three">${editorPane("Văn bản A", "Phiên bản cũ...")}${editorPane("Văn bản B", "Phiên bản mới...").replace("data-dev-input", "data-dev-secondary")}${outputPane("Diff")}</div>`;
    if (id === "calculator") return `<div class="dev-controls">${field("Chế độ", select("mode", [["standard", "Standard / Scientific"], ["programmer", "Programmer"], ["unit", "Unit converter"], ["percentage", "Percentage"], ["bmi", "BMI"]]))}${field("Từ đơn vị", select("from", [["km", "km"], ["m", "m"], ["cm", "cm"], ["mi", "mile"], ["kg", "kg"], ["lb", "lb"], ["c", "°C"], ["f", "°F"]], "km"))}${field("Sang", select("to", [["mi", "mile"], ["km", "km"], ["m", "m"], ["cm", "cm"], ["lb", "lb"], ["kg", "kg"], ["f", "°F"], ["c", "°C"]], "mi"))}${commonButtons("Tính")}</div><div class="dev-editor-grid">${editorPane("Biểu thức / giá trị", "sqrt(144) + sin(PI / 2) hoặc 1200*15%")}${outputPane()}</div>`;
    if (id === "notes") return `<div class="dev-controls">${field("Tìm", '<input data-dev-option="search" placeholder="Tìm ghi chú, tag...">')}${field("Loại", select("mode", [["note", "Ghi chú"], ["todo", "Todo"]]))}${field("Ưu tiên", select("priority", [["normal", "Thường"], ["high", "Cao"], ["urgent", "Khẩn cấp"]]))}<button class="is-primary" type="button" data-dev-note-add>Thêm mới</button><button type="button" data-dev-notes-export>Xuất dữ liệu</button></div><div class="dev-notes-layout"><section class="dev-pane"><header><strong>Nội dung mới</strong><small>Markdown</small></header><textarea data-dev-input placeholder="Viết ghi chú hoặc công việc..."></textarea><input data-dev-option="tags" placeholder="Tags, cách nhau bằng dấu phẩy"></section><section class="dev-note-list" data-dev-note-list></section></div>`;
    if (id === "system") return `<div class="dev-controls"><button class="is-primary" type="button" data-dev-system-refresh>Làm mới thông tin</button><button type="button" data-dev-system-copy>Sao chép báo cáo</button></div><div class="dev-system-grid" data-dev-system-grid></div><section class="dev-chart-card"><header><strong>Realtime performance</strong><small>5 giây gần nhất</small></header><canvas width="900" height="160" data-dev-system-canvas></canvas></section>`;
    if (id === "hash") return `<div class="dev-controls">${field("Thuật toán", select("mode", [["SHA-1", "SHA-1"], ["SHA-256", "SHA-256"], ["SHA-384", "SHA-384"], ["SHA-512", "SHA-512"], ["CRC32", "CRC32"], ["HMAC", "HMAC SHA-256"]], "SHA-256"))}${field("HMAC key", '<input data-dev-option="key" placeholder="Chỉ dùng cho HMAC">')}<label class="dev-file-button">Hash tệp<input type="file" data-dev-file></label>${commonButtons("Tạo hash")}</div><div class="dev-editor-grid">${editorPane("Văn bản", "Nội dung cần tạo hash...")}${outputPane()}</div>`;
    if (id === "encryption") return `<div class="dev-controls">${field("Tác vụ", select("mode", [["encrypt", "AES-GCM Encrypt"], ["decrypt", "AES-GCM Decrypt"], ["key", "Generate secret key"], ["jwt", "JWT Inspector"]]))}${field("Mật khẩu", '<input type="password" data-dev-option="password" placeholder="Mật khẩu mạnh">')}${commonButtons("Thực hiện")}</div><div class="dev-editor-grid">${editorPane("Dữ liệu", "Văn bản cần mã hóa hoặc payload đã mã hóa...")}${outputPane()}</div>`;
    if (id === "url") return `<div class="dev-controls">${field("Tác vụ", select("mode", [["inspect", "URL Inspector"], ["encode", "Encode component"], ["decode", "Decode component"], ["query", "Query parser"], ["utm", "UTM Builder"]]))}${field("Source", '<input data-dev-option="source" placeholder="google, facebook...">')}${field("Medium", '<input data-dev-option="medium" placeholder="social, cpc...">')}${field("Campaign", '<input data-dev-option="campaign" placeholder="summer_launch">')}${commonButtons("Xử lý URL")}</div><div class="dev-editor-grid">${editorPane("URL / nội dung", "https://example.com/path?name=HH")}${outputPane()}</div>`;
    if (id === "qr-barcode") return `<div class="dev-controls">${field("Loại", select("mode", [["qr", "QR Code"], ["code39", "Barcode Code 39"]]))}${field("Kích thước", '<input type="number" min="128" max="1200" value="420" data-dev-option="size">')}${field("Màu", '<input type="color" value="#071018" data-dev-option="dark">')}${field("Nền", '<input type="color" value="#ffffff" data-dev-option="light">')}<button class="is-primary" type="button" data-dev-run>Tạo mã</button><button type="button" data-dev-canvas-download>Tải PNG</button></div><div class="dev-editor-grid">${editorPane("Nội dung", "https://hoangdaika13.github.io/")}<section class="dev-pane dev-canvas-pane"><header><strong>Preview</strong><small>Canvas</small></header><canvas width="420" height="420" data-dev-canvas></canvas></section></div>`;
    if (id === "api") return `<div class="dev-controls">${field("Method", select("method", [["GET", "GET"], ["POST", "POST"], ["PUT", "PUT"], ["PATCH", "PATCH"], ["DELETE", "DELETE"]]))}${field("URL", '<input data-dev-option="url" value="https://api.github.com/repos/hoangdaika13/hoangdaika13.github.io">')}<button class="is-primary" type="button" data-dev-run>Gửi request</button><button type="button" data-dev-api-cancel>Hủy</button></div><div class="dev-editor-grid dev-editor-grid--three">${editorPane("Headers (JSON)", '{\n  "Accept": "application/json"\n}')}<section class="dev-pane"><header><strong>Body</strong><small>JSON / Text</small></header><textarea data-dev-secondary spellcheck="false" placeholder="{ }"></textarea></section>${outputPane("Response")}</div>`;
    if (id === "image") return `<div class="dev-controls"><label class="dev-file-button">Chọn ảnh<input type="file" accept="image/*" data-dev-file></label>${field("Rộng", '<input type="number" min="1" max="8000" data-dev-option="width" placeholder="Tự động">')}${field("Cao", '<input type="number" min="1" max="8000" data-dev-option="height" placeholder="Tự động">')}${field("Filter", select("filter", [["none", "Gốc"], ["grayscale(1)", "Grayscale"], ["sepia(1)", "Sepia"], ["contrast(1.25) saturate(1.2)", "Vivid"], ["blur(6px)", "Blur"], ["pixelate", "Pixelate"]]))}${field("Định dạng", select("format", [["image/png", "PNG"], ["image/jpeg", "JPEG"], ["image/webp", "WebP"]], "image/webp"))}${field("Chất lượng", '<input type="range" min="20" max="100" value="88" data-dev-option="quality">')}<button class="is-primary" type="button" data-dev-run>Xử lý ảnh</button><button type="button" data-dev-canvas-download>Tải ảnh</button></div><div class="dev-image-layout"><section class="dev-pane dev-canvas-pane"><header><strong>Preview</strong><small data-dev-image-meta>Chưa có ảnh</small></header><canvas width="900" height="540" data-dev-canvas></canvas></section>${outputPane("Thông tin")}</div>`;
    if (id === "sql") return `<div class="dev-controls">${field("Tác vụ", select("mode", [["format", "Beautify"], ["minify", "Minify"], ["upper", "Uppercase keywords"], ["lower", "Lowercase keywords"]]))}${commonButtons("Xử lý SQL")}</div><div class="dev-editor-grid">${editorPane("SQL", "select u.id,u.name from users u where u.active=1 order by u.name;")}${outputPane()}</div>`;
    if (id === "markdown") return `<div class="dev-controls"><button class="is-primary" type="button" data-dev-run>Cập nhật preview</button><button type="button" data-dev-markdown-toc>Tạo mục lục</button><button type="button" data-dev-markdown-export>Xuất HTML</button><button type="button" data-dev-clear>Xóa</button></div><div class="dev-editor-grid"><section class="dev-pane"><header><strong>Markdown</strong><small>Autosave</small></header><textarea data-dev-input spellcheck="false" placeholder="# Tiêu đề\n\nNội dung **Markdown**..."></textarea></section><section class="dev-pane"><header><strong>Preview</strong><small>Sanitized</small></header><article class="dev-markdown-preview" data-dev-output></article></section></div>`;
    if (id === "cron") return `<div class="dev-controls">${field("Preset", select("preset", [["", "Tùy chỉnh"], ["*/5 * * * *", "Mỗi 5 phút"], ["0 * * * *", "Mỗi giờ"], ["0 9 * * 1-5", "09:00 ngày làm việc"], ["0 0 1 * *", "Đầu tháng"]]))}${field("Số lần tiếp theo", '<input type="number" min="1" max="50" value="10" data-dev-option="count">')}${commonButtons("Phân tích Cron")}</div><div class="dev-editor-grid">${editorPane("Cron expression (5 trường)", "*/15 9-17 * * 1-5")}${outputPane()}</div>`;
    if (id === "network") return `<div class="dev-controls">${field("Tác vụ", select("mode", [["dns", "Google DNS lookup"], ["ip", "Public IP"], ["headers", "HTTP Headers"], ["ping", "HTTP latency"]]))}${field("DNS type", select("type", [["A", "A"], ["AAAA", "AAAA"], ["MX", "MX"], ["TXT", "TXT"], ["CNAME", "CNAME"], ["NS", "NS"]]))}${commonButtons("Tra cứu")}</div><div class="dev-editor-grid">${editorPane("Tên miền hoặc URL", "hoangdaika13.github.io")}${outputPane()}</div>`;
    return "";
  }

  function pageMarkup(tool) {
    const store = readStore(), favorites = store.favorites || [];
    return `<section class="dev-page" data-dev-page>
      <header class="dev-hero"><div><span class="dev-eyebrow"><i></i> HH DEVELOPER TOOLBOX</span><h2>Build, inspect và chuyển đổi ngay trong một workspace.</h2><p>22 công cụ chuyên nghiệp, ưu tiên xử lý cục bộ, không gửi dữ liệu riêng tư lên máy chủ.</p></div><div class="dev-hero__status"><strong>22</strong><span>tool engines</span><small><i></i> Runtime sẵn sàng</small></div></header>
      <div class="dev-metrics"><div><span>Đang mở</span><strong>${esc(tool.name)}</strong></div><div><span>Yêu thích</span><strong data-dev-favorite-count>${favorites.length}</strong></div><div><span>Lịch sử</span><strong data-dev-history-count>${(store.history || []).length}</strong></div><div><span>Xử lý</span><strong>Local-first</strong></div></div><nav class="dev-quick" data-dev-quick aria-label="Công cụ truy cập nhanh">${quickMarkup(store)}</nav>
      <section class="dev-workbench">
        <header class="dev-context"><div class="dev-context__identity"><span>${tool.icon}</span><div><small>${esc(tool.group)} · DEV LOCAL</small><h3>${esc(tool.name)}</h3><p>${esc(tool.description)}</p></div></div><div class="dev-context__caps">${tool.caps.map((cap) => `<span>${esc(cap)}</span>`).join("")}</div><div class="dev-context__actions"><button type="button" data-dev-undo title="Hoàn tác">↶</button><button type="button" data-dev-redo title="Làm lại">↷</button><button type="button" data-dev-favorite class="${favorites.includes(tool.id) ? "is-active" : ""}" title="Yêu thích">☆</button><button type="button" data-dev-fullscreen title="Toàn màn hình">□</button><button type="button" data-dev-export-session title="Xuất phiên">⇩</button><label title="Nhập phiên">⇧<input type="file" accept="application/json" data-dev-import-session></label></div></header>
        <div class="dev-runtime"><span><i></i> Ready</span><span>Dữ liệu: <b>trên thiết bị</b></span><span>Autosave: <b>bật</b></span><span data-dev-status>Chờ thao tác.</span></div>
        <main class="dev-work" data-dev-work>${toolMarkup(tool.id)}</main>
      </section><div class="dev-toast" data-dev-toast role="status" aria-live="polite" hidden></div>
    </section>`;
  }

  function updateMetrics() { const store = readStore(); const favorite = $(state.root, "[data-dev-favorite-count]"), history = $(state.root, "[data-dev-history-count]"), quick = $(state.root, "[data-dev-quick]"); if (favorite) favorite.textContent = (store.favorites || []).length; if (history) history.textContent = (store.history || []).length; if (quick) quick.innerHTML = quickMarkup(store); }
  function cleanup() { clearInterval(state.systemTimer); clearTimeout(state.timer); if (state.imageUrl) URL.revokeObjectURL(state.imageUrl); state.imageUrl = ""; state.image = null; state.file = null; state.root = null; state.host = null; }
  function mount(host, { toolId = "json" } = {}) {
    cleanup(); state.host = host; state.active = toolById(toolId).id; state.undo = []; state.redo = []; const tool = toolById(state.active); host.innerHTML = pageMarkup(tool); state.root = $(host, "[data-dev-page]"); bind(); restoreDraft(); pushSnapshot(); if (state.active === "notes") renderNotes(); if (state.active === "system") renderSystem(); if (state.active === "color") runColor(); if (state.active === "markdown") runMarkdown();
  }

  function bind() {
    state.root.addEventListener("click", handleClick);
    state.root.addEventListener("input", (event) => { if (event.target.matches("textarea,input,select")) { clearTimeout(state.autosaveTimer); state.autosaveTimer = setTimeout(saveDraft, 220); clearTimeout(state.snapshotTimer); state.snapshotTimer = setTimeout(pushSnapshot, 420); } if (state.active === "color" && event.target.matches("[data-dev-option]")) { if (event.target.dataset.devOption === "color") $(state.root, "[data-dev-option='colorText']").value = event.target.value; if (event.target.dataset.devOption === "colorText" && /^#[0-9a-f]{6}$/i.test(event.target.value)) $(state.root, "[data-dev-option='color']").value = event.target.value; runColor(); } if (state.active === "markdown" && event.target.matches("[data-dev-input]")) runMarkdown(); if (state.active === "notes" && event.target.matches("[data-dev-option='search']")) renderNotes(); });
    state.root.addEventListener("change", handleChange);
  }

  async function handleClick(event) {
    if (event.target.closest("[data-dev-run]")) return execute().catch(showError);
    if (event.target.closest("[data-dev-copy]")) return copy(state.lastOutput || $(state.root, "[data-dev-output]")?.textContent || "");
    if (event.target.closest("[data-dev-download]")) return download(state.lastOutput || "", `${state.active}-result.txt`);
    if (event.target.closest("[data-dev-clear]")) { $$ (state.root, "textarea").forEach((node) => { node.value = ""; }); setOutput(""); saveDraft(); return; }
    if (event.target.closest("[data-dev-favorite]")) return toggleFavorite(event.target.closest("[data-dev-favorite]"));
    if (event.target.closest("[data-dev-undo]")) return undoDraft();
    if (event.target.closest("[data-dev-redo]")) return redoDraft();
    if (event.target.closest("[data-dev-fullscreen]")) return toggleFullscreen();
    if (event.target.closest("[data-dev-export-session]")) return exportSession();
    if (event.target.closest("[data-dev-now]")) { $(state.root, "[data-dev-input]").value = new Date().toISOString(); return execute().catch(showError); }
    if (event.target.closest("[data-dev-pwned]")) return checkPwned().catch(showError);
    if (event.target.closest("[data-dev-note-add]")) return addNote();
    if (event.target.closest("[data-dev-note-toggle]")) return toggleNote(event.target.closest("[data-dev-note-toggle]").dataset.devNoteToggle);
    if (event.target.closest("[data-dev-note-pin]")) return updateNote(event.target.closest("[data-dev-note-pin]").dataset.devNotePin, "pin");
    if (event.target.closest("[data-dev-note-delete]")) return updateNote(event.target.closest("[data-dev-note-delete]").dataset.devNoteDelete, "delete");
    if (event.target.closest("[data-dev-notes-export]")) return download(JSON.stringify(readStore().notes || [], null, 2), "hh-dev-notes.json", "application/json");
    if (event.target.closest("[data-dev-system-refresh]")) return renderSystem();
    if (event.target.closest("[data-dev-system-copy]")) return copy(state.lastOutput);
    if (event.target.closest("[data-dev-canvas-download]")) return downloadCanvas();
    if (event.target.closest("[data-dev-api-cancel]")) { state.controller?.abort(); setStatus("Đã hủy request."); return; }
    if (event.target.closest("[data-dev-markdown-toc]")) return markdownToc();
    if (event.target.closest("[data-dev-markdown-export]")) return exportMarkdown();
    const color = event.target.closest("[data-dev-color-copy]"); if (color) return copy(color.dataset.devColorCopy);
  }

  async function handleChange(event) {
    if (event.target.matches("[data-dev-file]")) { state.file = event.target.files[0] || null; if (!state.file) return; if (state.active === "image") await loadDevImage(state.file); else { const input = $(state.root, "[data-dev-input]"); if (input && state.file.type.startsWith("text/") && state.file.size < 5e6) input.value = await state.file.text(); setStatus(`${state.file.name} · ${formatBytes(state.file.size)}`, "success"); } }
    if (event.target.matches("[data-dev-import-session]")) { const file = event.target.files[0]; if (file) importSession(file).catch(showError); }
    if (event.target.matches("[data-dev-option='preset']") && event.target.value) { $(state.root, "[data-dev-input]").value = event.target.value; }
  }

  function toggleFavorite(button) { const store = readStore(), current = store.favorites || [], active = current.includes(state.active), favorites = active ? current.filter((id) => id !== state.active) : [state.active, ...current]; writeStore({ favorites }); button.classList.toggle("is-active", !active); updateMetrics(); toast(active ? "Đã bỏ yêu thích." : "Đã thêm vào yêu thích.", "success"); }
  function snapshotValue() { const controls = {}; $$ (state.root, "[data-dev-input],[data-dev-secondary],[data-dev-option]").forEach((control) => { const key = control.dataset.devOption ? `option:${control.dataset.devOption}` : control.dataset.devSecondary !== undefined ? "secondary" : "input"; controls[key] = control.value; }); return controls; }
  function pushSnapshot() { if (!state.root) return; const snapshot = snapshotValue(), serialized = JSON.stringify(snapshot); if (JSON.stringify(state.undo.at(-1) || {}) === serialized) return; state.undo.push(snapshot); if (state.undo.length > 50) state.undo.shift(); state.redo = []; }
  function restoreSnapshot(snapshot) { if (!snapshot) return; Object.entries(snapshot).forEach(([key, value]) => { const control = key === "input" ? $(state.root, "[data-dev-input]") : key === "secondary" ? $(state.root, "[data-dev-secondary]") : $(state.root, `[data-dev-option='${key.slice(7)}']`); if (control) control.value = value; }); saveDraft(); if (state.active === "color") runColor(); if (state.active === "markdown") runMarkdown(); }
  function undoDraft() { if (state.undo.length < 2) return toast("Không còn thao tác để hoàn tác."); const current = state.undo.pop(); state.redo.push(current); restoreSnapshot(state.undo.at(-1)); }
  function redoDraft() { const next = state.redo.pop(); if (!next) return toast("Không còn thao tác để làm lại."); state.undo.push(next); restoreSnapshot(next); }
  async function toggleFullscreen() { const panel = $(state.root, ".dev-workbench"); if (document.fullscreenElement) await document.exitFullscreen(); else await panel.requestFullscreen(); }
  function exportSession() { const store = readStore(), payload = { format: "HH Developer Toolbox Session", version: 2, tool: state.active, draft: store.drafts?.[state.active] || {}, output: state.lastOutput, exportedAt: new Date().toISOString() }; download(JSON.stringify(payload, null, 2), `hh-dev-${state.active}.json`, "application/json"); }
  async function importSession(file) { const data = JSON.parse(await file.text()); if (data.format !== "HH Developer Toolbox Session") throw new Error("Tệp phiên không hợp lệ."); const store = readStore(); writeStore({ drafts: { ...(store.drafts || {}), [state.active]: data.draft || {} } }); restoreDraft(); setOutput(data.output || ""); toast("Đã nhập phiên làm việc.", "success"); }
  function showError(error) { console.error(error); setStatus(error.message || "Không thể hoàn thành tác vụ.", "error"); setOutput(`Lỗi: ${error.message || error}`); }

  async function execute() {
    setStatus("Đang xử lý...", "loading"); const started = performance.now();
    const runners = { json: runJson, base64: runBase64, uuid: runUuid, password: runPassword, timestamp: runTimestamp, regex: runRegex, text: runText, color: runColor, compare: runCompare, calculator: runCalculator, hash: runHash, encryption: runEncryption, url: runUrl, "qr-barcode": runCode, api: runApi, image: runImage, sql: runSql, markdown: runMarkdown, cron: runCron, network: runNetwork };
    const runner = runners[state.active]; if (!runner) throw new Error("Công cụ này sử dụng thao tác trực tiếp trên giao diện."); await runner(); const elapsed = performance.now() - started; setStatus(`Hoàn tất trong ${elapsed.toFixed(1)} ms.`, "success"); recordHistory(`${toolById(state.active).name} · ${elapsed.toFixed(1)} ms`); saveDraft();
  }

  function jsonToYaml(value, depth = 0) { const pad = "  ".repeat(depth); if (Array.isArray(value)) return value.map((item) => typeof item === "object" && item !== null ? `${pad}-\n${jsonToYaml(item, depth + 1)}` : `${pad}- ${String(item)}`).join("\n"); if (value && typeof value === "object") return Object.entries(value).map(([key, item]) => typeof item === "object" && item !== null ? `${pad}${key}:\n${jsonToYaml(item, depth + 1)}` : `${pad}${key}: ${typeof item === "string" ? JSON.stringify(item) : item}`).join("\n"); return `${pad}${value}`; }
  function jsonToXml(value, tag = "root") { const safeTag = String(tag).replace(/[^\w:-]/g, "_"); if (Array.isArray(value)) return value.map((item) => jsonToXml(item, "item")).join(""); if (value && typeof value === "object") return `<${safeTag}>${Object.entries(value).map(([key, item]) => jsonToXml(item, key)).join("")}</${safeTag}>`; return `<${safeTag}>${esc(value)}</${safeTag}>`; }
  function jsonToCsv(value) { const rows = Array.isArray(value) ? value : [value]; if (!rows.every((row) => row && typeof row === "object" && !Array.isArray(row))) throw new Error("CSV yêu cầu object hoặc mảng object."); const keys = [...new Set(rows.flatMap(Object.keys))], quote = (item) => `"${String(item ?? "").replace(/"/g, '""')}"`; return [keys.map(quote).join(","), ...rows.map((row) => keys.map((key) => quote(typeof row[key] === "object" ? JSON.stringify(row[key]) : row[key])).join(","))].join("\n"); }
  function jsonToToml(value) { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("TOML yêu cầu JSON object."); const scalar = (item) => typeof item === "string" ? JSON.stringify(item) : Array.isArray(item) ? `[${item.map(scalar).join(", ")}]` : String(item); const lines = [], sections = []; Object.entries(value).forEach(([key, item]) => { if (item && typeof item === "object" && !Array.isArray(item)) sections.push(`[${key}]\n${Object.entries(item).map(([sub, val]) => `${sub} = ${scalar(val)}`).join("\n")}`); else lines.push(`${key} = ${scalar(item)}`); }); return [...lines, ...sections].join("\n\n"); }
  function markdownTable(value) { const rows = Array.isArray(value) ? value : [value], keys = [...new Set(rows.flatMap((row) => Object.keys(row || {})))]; return `| ${keys.join(" | ")} |\n| ${keys.map(() => "---").join(" | ")} |\n${rows.map((row) => `| ${keys.map((key) => String(row?.[key] ?? "").replace(/\|/g, "\\|")).join(" | ")} |`).join("\n")}`; }
  function jsonPath(value, path) { if (!path.trim() || path.trim() === "$") return value; return path.replace(/^\$\.?/, "").replace(/\[(\d+)\]/g, ".$1").split(".").filter(Boolean).reduce((current, key) => current?.[key], value); }
  function validateSchema(value, schema, path = "$") { const errors = []; const expected = schema?.type; if (expected) { const actual = Array.isArray(value) ? "array" : value === null ? "null" : typeof value; if (actual !== expected) errors.push(`${path}: cần ${expected}, nhận ${actual}`); } (schema?.required || []).forEach((key) => { if (!(key in (value || {}))) errors.push(`${path}.${key}: thiếu trường bắt buộc`); }); Object.entries(schema?.properties || {}).forEach(([key, child]) => { if (value?.[key] !== undefined) errors.push(...validateSchema(value[key], child, `${path}.${key}`)); }); return errors; }
  function jsonTree(value, key = "root") { if (value && typeof value === "object") { const entries = Object.entries(value); return `<details open><summary>${esc(key)} <small>${Array.isArray(value) ? `[${entries.length}]` : `{${entries.length}}`}</small></summary><div>${entries.map(([childKey, child]) => jsonTree(child, childKey)).join("")}</div></details>`; } return `<p><b>${esc(key)}</b>: <span>${esc(JSON.stringify(value))}</span></p>`; }
  function lineDiff(a, b) { const A = a.split("\n"), B = b.split("\n"), matrix = Array.from({ length: A.length + 1 }, () => Array(B.length + 1).fill(0)); for (let i = A.length - 1; i >= 0; i--) for (let j = B.length - 1; j >= 0; j--) matrix[i][j] = A[i] === B[j] ? matrix[i + 1][j + 1] + 1 : Math.max(matrix[i + 1][j], matrix[i][j + 1]); const out = []; let i = 0, j = 0; while (i < A.length || j < B.length) { if (i < A.length && j < B.length && A[i] === B[j]) { out.push({ type: "same", text: A[i++] }); j++; } else if (j < B.length && (i === A.length || matrix[i][j + 1] >= matrix[i + 1][j])) out.push({ type: "add", text: B[j++] }); else out.push({ type: "remove", text: A[i++] }); } return out; }
  async function runJson() { const mode = option("mode"), value = JSON.parse(currentInput()); let result; if (mode === "beautify") result = JSON.stringify(value, null, 2); else if (mode === "minify") result = JSON.stringify(value); else if (mode === "validate") result = `JSON hợp lệ.\nKiểu: ${Array.isArray(value) ? "Array" : typeof value}\nKích thước minify: ${new Blob([JSON.stringify(value)]).size} bytes`; else if (mode === "path") result = JSON.stringify(jsonPath(value, option("query")), null, 2); else if (mode === "yaml") result = jsonToYaml(value); else if (mode === "xml") result = `<?xml version="1.0" encoding="UTF-8"?>\n${jsonToXml(value)}`; else if (mode === "csv") result = jsonToCsv(value); else if (mode === "toml") result = jsonToToml(value); else if (mode === "markdown") result = markdownTable(value); else if (mode === "schema") { const errors = validateSchema(value, JSON.parse(secondInput())); result = errors.length ? `Không đạt schema:\n${errors.join("\n")}` : "JSON đạt schema đã cung cấp."; } else if (mode === "diff") { const right = JSON.stringify(JSON.parse(secondInput()), null, 2), diff = lineDiff(JSON.stringify(value, null, 2), right); result = diff.map((row) => `${row.type === "add" ? "+" : row.type === "remove" ? "-" : " "} ${row.text}`).join("\n"); } else if (mode === "tree") { const html = `<div class="dev-json-tree">${jsonTree(value)}</div>`; state.lastOutput = JSON.stringify(value, null, 2); setOutput(html, { html: true }); return; } setOutput(result); }

  async function runBase64() { const mode = option("mode"), input = currentInput(); let result; if (mode === "encode") result = utf8ToBase64(input); else if (mode === "decode") result = base64ToUtf8(input.replace(/^data:[^,]+,/, "")); else if (mode === "hex-encode") result = hex(new TextEncoder().encode(input)); else if (mode === "hex-decode") result = new TextDecoder().decode(Uint8Array.from((input.match(/[0-9a-f]{2}/gi) || []).map((item) => parseInt(item, 16)))); else { if (!state.file) throw new Error("Hãy chọn một tệp."); result = `data:${state.file.type || "application/octet-stream"};base64,${bytesToBase64(new Uint8Array(await state.file.arrayBuffer()))}`; } if (checked("urlsafe")) result = result.replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, ""); setOutput(result); }
  function formatUuid(bytes) { const value = hex(bytes); return `${value.slice(0, 8)}-${value.slice(8, 12)}-${value.slice(12, 16)}-${value.slice(16, 20)}-${value.slice(20)}`; }
  function uuidV1() { const ticks = BigInt(Date.now()) * 10000n + 0x01b21dd213814000n, bytes = randomBytes(16), low = Number(ticks & 0xffffffffn), mid = Number((ticks >> 32n) & 0xffffn), high = Number((ticks >> 48n) & 0x0fffn) | 0x1000; new DataView(bytes.buffer).setUint32(0, low); new DataView(bytes.buffer).setUint16(4, mid); new DataView(bytes.buffer).setUint16(6, high); bytes[8] = (bytes[8] & 0x3f) | 0x80; return formatUuid(bytes); }
  function uuidV6() { const ticks = BigInt(Date.now()) * 10000n + 0x01b21dd213814000n, bytes = randomBytes(16); new DataView(bytes.buffer).setUint32(0, Number((ticks >> 28n) & 0xffffffffn)); new DataView(bytes.buffer).setUint16(4, Number((ticks >> 12n) & 0xffffn)); new DataView(bytes.buffer).setUint16(6, Number(ticks & 0xfffn) | 0x6000); bytes[8] = (bytes[8] & 0x3f) | 0x80; return formatUuid(bytes); }
  function uuidV7() { const bytes = randomBytes(16), time = BigInt(Date.now()); for (let index = 5; index >= 0; index--) bytes[index] = Number((time >> BigInt((5 - index) * 8)) & 255n); bytes[6] = (bytes[6] & 0x0f) | 0x70; bytes[8] = (bytes[8] & 0x3f) | 0x80; return formatUuid(bytes); }
  function ulid() { const alphabet = "0123456789ABCDEFGHJKMNPQRSTVWXYZ", time = Date.now(); let value = "", current = time; for (let index = 0; index < 10; index++) { value = alphabet[current % 32] + value; current = Math.floor(current / 32); } return value + [...randomBytes(16)].slice(0, 16).map((item) => alphabet[item % 32]).join(""); }
  function jwtDecode(token) { const parts = token.trim().split("."); if (parts.length < 2) throw new Error("JWT không hợp lệ."); const decode = (part) => JSON.parse(new TextDecoder().decode(base64ToBytes(part))); const header = decode(parts[0]), payload = decode(parts[1]), expiration = payload.exp ? new Date(payload.exp * 1000) : null; return { header, payload, signaturePresent: Boolean(parts[2]), expiration: expiration?.toISOString() || null, expired: expiration ? expiration < new Date() : null }; }
  async function runUuid() { const mode = option("mode"), count = clamp(option("count"), 1, 100), length = clamp(option("length"), 8, 256); if (mode === "jwt") { setOutput(JSON.stringify(jwtDecode(currentInput()), null, 2)); return; } const alphabet = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz-", make = () => { if (mode === "v1") return uuidV1(); if (mode === "v4") return crypto.randomUUID(); if (mode === "v6") return uuidV6(); if (mode === "v7") return uuidV7(); if (mode === "ulid") return ulid(); if (mode === "nanoid") return [...randomBytes(length)].map((item) => alphabet[item % alphabet.length]).join(""); const token = hex(randomBytes(Math.ceil(length / 2))).slice(0, length); return mode === "api" ? `hh_${token}` : mode === "session" ? `sess_${token}` : token; }; const values = Array.from({ length: count }, make), entropy = Math.floor(Math.log2(mode === "nanoid" ? alphabet.length : 16) * length); setOutput(`${values.join("\n")}\n\nƯớc tính entropy: ${entropy} bits`); }

  const WORDS = ["aurora", "canvas", "cipher", "cloud", "comet", "cosmos", "delta", "ember", "falcon", "forest", "galaxy", "harbor", "matrix", "neon", "nova", "orbit", "pixel", "quartz", "river", "signal", "solar", "vertex", "violet", "wave"];
  async function runPassword() { const mode = option("mode"), count = clamp(option("count"), 1, 50), length = clamp(option("length"), 4, 256); let chars = ""; if (checked("upper")) chars += "ABCDEFGHIJKLMNOPQRSTUVWXYZ"; if (checked("lower")) chars += "abcdefghijklmnopqrstuvwxyz"; if (checked("number")) chars += "0123456789"; if (checked("special")) chars += "!@#$%^&*()-_=+[]{}"; if (checked("similar")) chars = chars.replace(/[Il1O0o]/g, ""); if (mode === "custom") chars = currentInput(); if (!chars && mode !== "passphrase") throw new Error("Hãy chọn ít nhất một nhóm ký tự."); const make = () => mode === "passphrase" ? Array.from({ length: Math.max(3, Math.round(length / 6)) }, () => WORDS[randomBytes(1)[0] % WORDS.length]).join("-") : [...randomBytes(length)].map((item) => chars[item % chars.length]).join(""); const values = Array.from({ length: count }, make), base = mode === "passphrase" ? WORDS.length : chars.length, entropy = Math.round(Math.log2(base) * (mode === "passphrase" ? Math.max(3, Math.round(length / 6)) : length)), grade = entropy >= 100 ? "Rất mạnh" : entropy >= 70 ? "Mạnh" : entropy >= 45 ? "Trung bình" : "Yếu"; setOutput(`${values.join("\n")}\n\nĐộ mạnh: ${grade}\nEntropy ước tính: ${entropy} bits`); }
  async function checkPwned() { const password = currentInput(); if (!password) throw new Error("Nhập mật khẩu cần kiểm tra vào ô dữ liệu."); setStatus("Đang kiểm tra theo k-anonymity..."); const digest = (await crypto.subtle.digest("SHA-1", new TextEncoder().encode(password))), hashValue = hex(digest).toUpperCase(), prefix = hashValue.slice(0, 5), suffix = hashValue.slice(5); const response = await fetch(`https://api.pwnedpasswords.com/range/${prefix}`); if (!response.ok) throw new Error(`Dịch vụ trả HTTP ${response.status}.`); const found = (await response.text()).split("\n").find((line) => line.startsWith(suffix)); setOutput(found ? `Cảnh báo: mật khẩu xuất hiện ${Number(found.split(":")[1]).toLocaleString("vi-VN")} lần trong dữ liệu rò rỉ.\nKhông nên tiếp tục sử dụng.` : "Không tìm thấy mật khẩu trong tập dữ liệu rò rỉ đã biết. Đây không phải đảm bảo tuyệt đối."); setStatus("Kiểm tra hoàn tất. Chỉ 5 ký tự đầu của SHA-1 được gửi đi.", "success"); }

  function parseDate(value) { if (!value.trim()) return new Date(); if (/^\d+$/.test(value.trim())) { const number = Number(value); return new Date(number < 1e12 ? number * 1000 : number); } return new Date(value); }
  async function runTimestamp() { const date = parseDate(currentInput()); if (Number.isNaN(date.valueOf())) throw new Error("Ngày hoặc timestamp không hợp lệ."); const zone = option("timezone") || "Asia/Bangkok", second = option("second") ? parseDate(option("second")) : null, diff = second && !Number.isNaN(second.valueOf()) ? second - date : null, relative = Math.round((date - Date.now()) / 1000), relativeText = new Intl.RelativeTimeFormat("vi", { numeric: "auto" }).format(Math.abs(relative) >= 86400 ? Math.round(relative / 86400) : Math.abs(relative) >= 3600 ? Math.round(relative / 3600) : Math.round(relative / 60), Math.abs(relative) >= 86400 ? "day" : Math.abs(relative) >= 3600 ? "hour" : "minute"); setOutput(`Unix: ${Math.floor(date.valueOf() / 1000)}\nMilliseconds: ${date.valueOf()}\nISO 8601: ${date.toISOString()}\nUTC: ${date.toUTCString()}\nRFC 2822: ${date.toUTCString()}\n${zone}: ${new Intl.DateTimeFormat("vi-VN", { dateStyle: "full", timeStyle: "long", timeZone: zone }).format(date)}\nRelative: ${relativeText}${diff === null ? "" : `\nChênh lệch: ${(diff / 86400000).toFixed(2)} ngày (${diff.toLocaleString("vi-VN")} ms)`}\nNăm nhuận: ${new Date(date.getFullYear(), 1, 29).getMonth() === 1 ? "Có" : "Không"}`); }
  async function runRegex() { const pattern = option("pattern"), flags = [...new Set(option("flags"))].join(""), mode = option("mode"), input = currentInput(), started = performance.now(), regex = new RegExp(pattern, flags.includes("g") ? flags : `${flags}g`), matches = [...input.matchAll(regex)], elapsed = performance.now() - started; if (mode === "replace") { setOutput(input.replace(new RegExp(pattern, flags), option("replace"))); return; } if (mode === "split") { setOutput(input.split(new RegExp(pattern, flags)).join("\n")); return; } const rows = matches.map((match, index) => `${index + 1}. ${JSON.stringify(match[0])} · index ${match.index}${match.length > 1 ? `\n   groups: ${match.slice(1).map((item) => JSON.stringify(item)).join(", ")}` : ""}`); setOutput(`Matches: ${matches.length}\nTime: ${elapsed.toFixed(3)} ms\nFlags: ${flags || "none"}\n\n${rows.join("\n") || "Không có kết quả."}`); }
  function words(value) { return value.trim() ? value.trim().split(/\s+/) : []; }
  function titleCase(value) { return value.toLowerCase().replace(/(^|\s|[-_/])\p{L}/gu, (match) => match.toUpperCase()); }
  function slugify(value, separator = "-") { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, separator).replace(new RegExp(`^\\${separator}+|\\${separator}+$`, "g"), ""); }
  async function runText() { const mode = option("mode"), input = currentInput(), wordList = words(input); const operations = { upper: () => input.toUpperCase(), lower: () => input.toLowerCase(), title: () => titleCase(input), sentence: () => input.toLowerCase().replace(/(^\s*\p{L}|[.!?]\s+\p{L})/gu, (match) => match.toUpperCase()), camel: () => slugify(input).replace(/-([a-z0-9])/g, (_, char) => char.toUpperCase()), pascal: () => titleCase(slugify(input).replace(/-/g, " ")).replace(/\s/g, ""), snake: () => slugify(input, "_"), kebab: () => slugify(input), slug: () => slugify(input), trim: () => input.split("\n").map((line) => line.trim()).join("\n").trim(), dedupe: () => [...new Set(input.split("\n"))].join("\n"), empty: () => input.split("\n").filter((line) => line.trim()).join("\n"), "html-strip": () => new DOMParser().parseFromString(input, "text/html").body.textContent || "", "markdown-strip": () => input.replace(/[`*_>#\[\]()~-]/g, ""), sort: () => input.split("\n").sort((a, b) => a.localeCompare(b, "vi")).join("\n"), reverse: () => [...input].reverse().join(""), "url-encode": () => encodeURIComponent(input), "url-decode": () => decodeURIComponent(input), "html-encode": () => esc(input), "html-decode": () => new DOMParser().parseFromString(input, "text/html").documentElement.textContent, rot13: () => input.replace(/[a-z]/gi, (char) => String.fromCharCode(char.charCodeAt(0) + (char.toLowerCase() < "n" ? 13 : -13))), stats: () => `Words: ${wordList.length}\nCharacters: ${input.length}\nCharacters (no spaces): ${input.replace(/\s/g, "").length}\nLines: ${input.split("\n").length}\nSentences: ${(input.match(/[.!?]+(?=\s|$)/g) || []).length}\nReading time: ${Math.max(1, Math.ceil(wordList.length / 220))} phút` }; setOutput(operations[mode]?.() ?? input); }

  function parseHex(value) { const match = String(value).trim().match(/^#?([0-9a-f]{3}|[0-9a-f]{6})$/i); if (!match) throw new Error("Màu HEX không hợp lệ."); const raw = match[1].length === 3 ? [...match[1]].map((char) => char + char).join("") : match[1]; return [parseInt(raw.slice(0, 2), 16), parseInt(raw.slice(2, 4), 16), parseInt(raw.slice(4, 6), 16)]; }
  const rgbHex = (rgb) => `#${rgb.map((value) => clamp(Math.round(value), 0, 255).toString(16).padStart(2, "0")).join("")}`.toUpperCase();
  function rgbHsl([r, g, b]) { r /= 255; g /= 255; b /= 255; const max = Math.max(r, g, b), min = Math.min(r, g, b), delta = max - min; let h = 0; if (delta) h = max === r ? ((g - b) / delta) % 6 : max === g ? (b - r) / delta + 2 : (r - g) / delta + 4; h = Math.round(h * 60); if (h < 0) h += 360; const l = (max + min) / 2, s = delta ? delta / (1 - Math.abs(2 * l - 1)) : 0; return [h, Math.round(s * 100), Math.round(l * 100)]; }
  function luminance(rgb) { const values = rgb.map((value) => { const channel = value / 255; return channel <= .03928 ? channel / 12.92 : ((channel + .055) / 1.055) ** 2.4; }); return .2126 * values[0] + .7152 * values[1] + .0722 * values[2]; }
  function mixColor(rgb, target, amount) { return rgb.map((value, index) => value + (target[index] - value) * amount); }
  async function runColor() { const input = option("colorText") || option("color"), rgb = parseHex(input), color = rgbHex(rgb), foreground = option("foreground") || "#081018", fg = parseHex(foreground), hsl = rgbHsl(rgb), cmykK = 1 - Math.max(...rgb.map((value) => value / 255)), cmyk = cmykK === 1 ? [0, 0, 0, 100] : [...rgb.map((value) => Math.round((1 - value / 255 - cmykK) / (1 - cmykK) * 100)), Math.round(cmykK * 100)], ratio = (Math.max(luminance(rgb), luminance(fg)) + .05) / (Math.min(luminance(rgb), luminance(fg)) + .05), palette = [mixColor(rgb, [255, 255, 255], .8), mixColor(rgb, [255, 255, 255], .5), rgb, mixColor(rgb, [0, 0, 0], .28), mixColor(rgb, [0, 0, 0], .58)].map(rgbHex), gradient = `linear-gradient(${clamp(option("angle"), 0, 360)}deg, ${color}, ${option("second")})`; const preview = $(state.root, "[data-dev-color-preview]"); if (preview) { preview.style.background = color; preview.style.color = foreground; } const paletteNode = $(state.root, "[data-dev-palette]"); if (paletteNode) paletteNode.innerHTML = palette.map((item) => `<button type="button" style="--color:${item}" data-dev-color-copy="${item}" title="Sao chép ${item}"><span>${item}</span></button>`).join(""); setOutput(`HEX: ${color}\nRGB: rgb(${rgb.join(", ")})\nHSL: hsl(${hsl[0]} ${hsl[1]}% ${hsl[2]}%)\nCMYK: ${cmyk.join("%, ")}%\nContrast: ${ratio.toFixed(2)}:1 · ${ratio >= 7 ? "AAA" : ratio >= 4.5 ? "AA" : ratio >= 3 ? "AA Large" : "Không đạt"}\n\nCSS gradient:\nbackground: ${gradient};\n\nBox shadow:\nbox-shadow: 0 18px 48px ${color}55;`); }
  async function runCompare() { let a = currentInput(), b = secondInput(); const normalizeLine = (line) => { let value = line; if (checked("space")) value = value.replace(/\s+/g, " ").trim(); if (checked("case")) value = value.toLowerCase(); return value; }; if (checked("blank")) { a = a.split("\n").filter((line) => line.trim()).join("\n"); b = b.split("\n").filter((line) => line.trim()).join("\n"); } const original = lineDiff(a, b), comparable = lineDiff(a.split("\n").map(normalizeLine).join("\n"), b.split("\n").map(normalizeLine).join("\n")), adds = comparable.filter((row) => row.type === "add").length, removes = comparable.filter((row) => row.type === "remove").length; setOutput(`${original.map((row) => `${row.type === "add" ? "+" : row.type === "remove" ? "-" : " "} ${row.text}`).join("\n")}\n\nStatistics: +${adds} / -${removes} / ${comparable.filter((row) => row.type === "same").length} unchanged`); }
  function unitConvert(value, from, to) { const length = { km: 1000, m: 1, cm: .01, mi: 1609.344 }, mass = { kg: 1, lb: .45359237 }; if (from === to) return value; if (from in length && to in length) return value * length[from] / length[to]; if (from in mass && to in mass) return value * mass[from] / mass[to]; if (from === "c" && to === "f") return value * 9 / 5 + 32; if (from === "f" && to === "c") return (value - 32) * 5 / 9; throw new Error("Hai đơn vị không cùng loại."); }
  function evaluateMath(expression) { const source = expression.replace(/\^/g, "**").replace(/(\d+(?:\.\d+)?)%/g, "($1/100)"); if (!/^[\d\s+\-*/().,%A-Za-z_]+$/.test(source)) throw new Error("Biểu thức chứa ký tự không được phép."); const allowed = ["sin", "cos", "tan", "asin", "acos", "atan", "sqrt", "abs", "log", "log10", "pow", "min", "max", "round", "floor", "ceil", "PI", "E"], names = source.match(/[A-Za-z_]+/g) || []; if (names.some((name) => !allowed.includes(name))) throw new Error("Hàm toán học không được hỗ trợ."); return Function("Math", `"use strict"; const {${allowed.join(",")}}=Math; return (${source});`)(Math); }
  async function runCalculator() { const mode = option("mode"), input = currentInput(); let result; if (mode === "unit") result = `${unitConvert(Number(input), option("from"), option("to"))} ${option("to")}`; else if (mode === "programmer") { const value = Math.trunc(evaluateMath(input)); result = `Decimal: ${value}\nBinary: ${value.toString(2)}\nOctal: ${value.toString(8)}\nHex: ${value.toString(16).toUpperCase()}`; } else if (mode === "percentage") { const match = input.match(/^([\d.]+)\s*%\s*(?:of)?\s*([\d.]+)$/i); if (!match) throw new Error("Dùng cú pháp: 15% of 1200"); result = String(Number(match[1]) / 100 * Number(match[2])); } else if (mode === "bmi") { const [weight, height] = input.split(/[\/,\s]+/).map(Number), bmi = weight / height ** 2; result = `BMI: ${bmi.toFixed(2)}\n${bmi < 18.5 ? "Thiếu cân" : bmi < 25 ? "Bình thường" : bmi < 30 ? "Thừa cân" : "Béo phì"}`; } else result = String(evaluateMath(input)); const store = readStore(); writeStore({ calculatorHistory: [{ expression: input, result, at: Date.now() }, ...(store.calculatorHistory || [])].slice(0, 30) }); setOutput(result); }

  function renderNotes() { const list = $(state.root, "[data-dev-note-list]"); if (!list) return; const store = readStore(), search = (option("search") || "").toLowerCase(), notes = (store.notes || []).filter((note) => !search || `${note.text} ${note.tags}`.toLowerCase().includes(search)).sort((a, b) => Number(b.pinned) - Number(a.pinned) || b.updatedAt - a.updatedAt); list.innerHTML = notes.length ? notes.map((note) => `<article class="dev-note ${note.done ? "is-done" : ""}" data-priority="${note.priority}"><header><span>${note.type === "todo" ? "TODO" : "NOTE"}</span><time>${new Date(note.updatedAt).toLocaleString("vi-VN")}</time><button type="button" data-dev-note-pin="${note.id}" title="Ghim">${note.pinned ? "★" : "☆"}</button><button type="button" data-dev-note-delete="${note.id}" title="Xóa">×</button></header><p>${esc(note.text)}</p><footer><small>${esc(note.tags || "Không có tag")}</small>${note.type === "todo" ? `<button type="button" data-dev-note-toggle="${note.id}">${note.done ? "Mở lại" : "Hoàn thành"}</button>` : ""}</footer></article>`).join("") : '<div class="dev-empty"><strong>Chưa có ghi chú</strong><p>Viết nội dung và nhấn Thêm mới.</p></div>'; }
  function addNote() { const text = currentInput().trim(); if (!text) return toast("Hãy nhập nội dung.", "error"); const store = readStore(), note = { id: uid(), text, type: option("mode") || "note", priority: option("priority") || "normal", tags: option("tags"), done: false, pinned: false, updatedAt: Date.now() }; writeStore({ notes: [note, ...(store.notes || [])].slice(0, 200) }); $(state.root, "[data-dev-input]").value = ""; renderNotes(); recordHistory(`Đã thêm ${note.type}`); toast("Đã lưu trên thiết bị.", "success"); }
  function toggleNote(id) { const store = readStore(), notes = (store.notes || []).map((note) => note.id === id ? { ...note, done: !note.done, updatedAt: Date.now() } : note); writeStore({ notes }); renderNotes(); }
  function updateNote(id, action) { const store = readStore(), notes = action === "delete" ? (store.notes || []).filter((note) => note.id !== id) : (store.notes || []).map((note) => note.id === id ? { ...note, pinned: !note.pinned, updatedAt: Date.now() } : note); writeStore({ notes }); renderNotes(); }
  async function renderSystem() { const grid = $(state.root, "[data-dev-system-grid]"); if (!grid) return; const connection = navigator.connection || {}, memory = performance.memory || {}, battery = await navigator.getBattery?.().catch(() => null), canvas = document.createElement("canvas"), gl = canvas.getContext("webgl"), debug = gl?.getExtension("WEBGL_debug_renderer_info"), renderer = debug ? gl.getParameter(debug.UNMASKED_RENDERER_WEBGL) : "WebGL renderer bị ẩn", rows = [
    ["CPU logical cores", navigator.hardwareConcurrency || "N/A", "Hardware"], ["Device memory", navigator.deviceMemory ? `${navigator.deviceMemory} GB` : "N/A", "Approximate"], ["JS Heap", memory.usedJSHeapSize ? `${formatBytes(memory.usedJSHeapSize)} / ${formatBytes(memory.jsHeapSizeLimit)}` : "N/A", "Performance API"], ["Battery", battery ? `${Math.round(battery.level * 100)}% · ${battery.charging ? "Đang sạc" : "Dùng pin"}` : "N/A", "Battery API"], ["Network", `${connection.effectiveType || "N/A"} · ${connection.downlink || "?"} Mbps`, navigator.onLine ? "Online" : "Offline"], ["Screen", `${screen.width}×${screen.height} @${devicePixelRatio}x`, `${screen.colorDepth}-bit`], ["Viewport", `${innerWidth}×${innerHeight}`, matchMedia("(pointer:coarse)").matches ? "Touch" : "Pointer"], ["Platform", navigator.userAgentData?.platform || navigator.platform, navigator.language], ["GPU / WebGL", renderer, gl ? `WebGL ${gl.getParameter(gl.VERSION)}` : "Unavailable"], ["Storage quota", "Đang đo...", "Storage API"]
  ]; grid.innerHTML = rows.map(([label, value, detail]) => `<article><span>${label}</span><strong>${esc(value)}</strong><small>${esc(detail)}</small></article>`).join(""); const estimate = await navigator.storage?.estimate?.(); if (estimate) { const cards = $$ (grid, "article"), target = cards.at(-1); target.querySelector("strong").textContent = `${formatBytes(estimate.usage || 0)} / ${formatBytes(estimate.quota || 0)}`; target.querySelector("small").textContent = `${((estimate.usage || 0) / (estimate.quota || 1) * 100).toFixed(2)}% đã dùng`; } state.lastOutput = rows.map((row) => `${row[0]}: ${row[1]} (${row[2]})`).join("\n"); drawSystemGraph(); }
  function drawSystemGraph() { clearInterval(state.systemTimer); const canvas = $(state.root, "[data-dev-system-canvas]"); if (!canvas) return; const ctx = canvas.getContext("2d"), samples = Array(90).fill(0); let last = performance.now(), frames = 0, fps = 60; const frame = (now) => { frames++; if (now - last >= 500) { fps = frames * 1000 / (now - last); frames = 0; last = now; } if (state.root?.isConnected) requestAnimationFrame(frame); }; requestAnimationFrame(frame); const draw = () => { samples.push(fps); samples.shift(); ctx.clearRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = "#071019"; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.strokeStyle = "#55e4e9"; ctx.lineWidth = 2; ctx.beginPath(); samples.forEach((value, index) => { const x = index / (samples.length - 1) * canvas.width, y = canvas.height - value / 75 * canvas.height; index ? ctx.lineTo(x, y) : ctx.moveTo(x, y); }); ctx.stroke(); ctx.fillStyle = "#9aabba"; ctx.font = "12px sans-serif"; ctx.fillText(`FPS ${fps.toFixed(0)}`, 12, 20); }; draw(); state.systemTimer = setInterval(draw, 800); }

  function crc32(bytes) { let crc = 0xffffffff; for (const byte of bytes) { crc ^= byte; for (let bit = 0; bit < 8; bit++) crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0); } return ((crc ^ 0xffffffff) >>> 0).toString(16).padStart(8, "0"); }
  async function runHash() { const mode = option("mode"), bytes = state.file ? new Uint8Array(await state.file.arrayBuffer()) : new TextEncoder().encode(currentInput()); let result; if (mode === "CRC32") result = crc32(bytes); else if (mode === "HMAC") { const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(option("key")), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); result = hex(await crypto.subtle.sign("HMAC", key, bytes)); } else result = hex(await crypto.subtle.digest(mode, bytes)); setOutput(`${mode}:\n${result}\n\nInput: ${state.file ? `${state.file.name} · ${formatBytes(state.file.size)}` : `${bytes.length} bytes`}`); }
  async function deriveAes(password, salt, usages) { const material = await crypto.subtle.importKey("raw", new TextEncoder().encode(password), "PBKDF2", false, ["deriveKey"]); return crypto.subtle.deriveKey({ name: "PBKDF2", salt, iterations: 210000, hash: "SHA-256" }, material, { name: "AES-GCM", length: 256 }, false, usages); }
  async function runEncryption() { const mode = option("mode"), input = currentInput(), password = option("password"); if (mode === "key") { setOutput(bytesToBase64(randomBytes(32))); return; } if (mode === "jwt") { setOutput(JSON.stringify(jwtDecode(input), null, 2)); return; } if (!password) throw new Error("Hãy nhập mật khẩu mã hóa."); if (mode === "encrypt") { const salt = randomBytes(16), iv = randomBytes(12), key = await deriveAes(password, salt, ["encrypt"]), cipher = new Uint8Array(await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, new TextEncoder().encode(input))); setOutput(JSON.stringify({ v: 1, alg: "AES-256-GCM", kdf: "PBKDF2-SHA256-210000", salt: bytesToBase64(salt), iv: bytesToBase64(iv), data: bytesToBase64(cipher) })); } else { const payload = JSON.parse(input), salt = base64ToBytes(payload.salt), iv = base64ToBytes(payload.iv), key = await deriveAes(password, salt, ["decrypt"]), plain = await crypto.subtle.decrypt({ name: "AES-GCM", iv }, key, base64ToBytes(payload.data)); setOutput(new TextDecoder().decode(plain)); } }
  async function runUrl() { const mode = option("mode"), input = currentInput(); if (mode === "encode") return setOutput(encodeURIComponent(input)); if (mode === "decode") return setOutput(decodeURIComponent(input)); const url = new URL(input.includes("://") ? input : `https://${input}`); if (mode === "utm") { if (option("source")) url.searchParams.set("utm_source", option("source")); if (option("medium")) url.searchParams.set("utm_medium", option("medium")); if (option("campaign")) url.searchParams.set("utm_campaign", option("campaign")); return setOutput(url.href); } const params = Object.fromEntries(url.searchParams); if (mode === "query") return setOutput(JSON.stringify(params, null, 2)); setOutput(`Protocol: ${url.protocol}\nOrigin: ${url.origin}\nHostname: ${url.hostname}\nPort: ${url.port || "default"}\nPath: ${url.pathname}\nQuery: ${url.search || "none"}\nHash: ${url.hash || "none"}\n\nParameters:\n${JSON.stringify(params, null, 2)}`); }
  const libraryJobs = new Map();
  function loadScript(key, src, ready) { if (ready()) return Promise.resolve(); if (libraryJobs.has(key)) return libraryJobs.get(key); const job = new Promise((resolve, reject) => { const script = document.createElement("script"); script.src = src; script.onload = () => ready() ? resolve() : reject(new Error(`Không thể khởi tạo ${key}.`)); script.onerror = () => reject(new Error(`Không thể tải ${key}.`)); document.head.append(script); }); libraryJobs.set(key, job); return job; }
  const CODE39 = { "0": "101001101101", "1": "110100101011", "2": "101100101011", "3": "110110010101", "4": "101001101011", "5": "110100110101", "6": "101100110101", "7": "101001011011", "8": "110100101101", "9": "101100101101", A: "110101001011", B: "101101001011", C: "110110100101", D: "101011001011", E: "110101100101", F: "101101100101", G: "101010011011", H: "110101001101", I: "101101001101", J: "101011001101", K: "110101010011", L: "101101010011", M: "110110101001", N: "101011010011", O: "110101101001", P: "101101101001", Q: "101010110011", R: "110101011001", S: "101101011001", T: "101011011001", U: "110010101011", V: "100110101011", W: "110011010101", X: "100101101011", Y: "110010110101", Z: "100110110101", "-": "100101011011", ".": "110010101101", " ": "100110101101", "$": "100100100101", "/": "100100101001", "+": "100101001001", "%": "101001001001", "*": "100101101101" };
  async function runCode() { const mode = option("mode"), text = currentInput().trim(), size = clamp(option("size"), 128, 1200), canvas = $(state.root, "[data-dev-canvas]"), ctx = canvas.getContext("2d"), dark = option("dark"), light = option("light"); if (!text) throw new Error("Nội dung đang trống."); if (mode === "qr") { await loadScript("QR", "vendor/qrcode.js?v=2.0.4", () => Boolean(window.qrcode)); const qr = window.qrcode(0, "M"); qr.addData(text); qr.make(); const count = qr.getModuleCount(), margin = Math.round(size * .06), cell = (size - margin * 2) / count; canvas.width = size; canvas.height = size; ctx.fillStyle = light; ctx.fillRect(0, 0, size, size); ctx.fillStyle = dark; for (let row = 0; row < count; row++) for (let col = 0; col < count; col++) if (qr.isDark(row, col)) ctx.fillRect(Math.floor(margin + col * cell), Math.floor(margin + row * cell), Math.ceil(cell), Math.ceil(cell)); } else { const value = `*${text.toUpperCase()}*`; if ([...value].some((char) => !CODE39[char])) throw new Error("Code 39 chỉ hỗ trợ A-Z, 0-9 và - . $ / + %."); const pattern = [...value].map((char) => CODE39[char]).join("0"), width = Math.max(size, pattern.length * 2 + 40); canvas.width = width; canvas.height = Math.round(size * .5); ctx.fillStyle = light; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = dark; const unit = (canvas.width - 40) / pattern.length; [...pattern].forEach((bit, index) => { if (bit === "1") ctx.fillRect(20 + index * unit, 18, Math.ceil(unit), canvas.height - 55); }); ctx.font = `${Math.max(14, size * .04)}px sans-serif`; ctx.textAlign = "center"; ctx.fillText(text, canvas.width / 2, canvas.height - 16); } state.lastOutput = `${mode.toUpperCase()}: ${text}`; }
  function downloadCanvas() { const canvas = $(state.root, "[data-dev-canvas]"); if (!canvas || !canvas.width) return toast("Chưa có dữ liệu canvas.", "error"); const type = state.active === "image" ? option("format") || "image/png" : "image/png", quality = state.active === "image" ? clamp(option("quality"), 20, 100) / 100 : 1, extension = type === "image/jpeg" ? "jpg" : type === "image/webp" ? "webp" : "png"; canvas.toBlob((blob) => blob && download(blob, `${state.active}-${Date.now()}.${extension}`, type), type, quality); }
  async function runApi() { const method = option("method"), url = option("url"); if (!/^https?:\/\//i.test(url)) throw new Error("URL API phải bắt đầu bằng http:// hoặc https://"); let headers = {}; if (currentInput().trim()) headers = JSON.parse(currentInput()); state.controller?.abort(); state.controller = new AbortController(); const init = { method, headers, signal: state.controller.signal }; if (!["GET", "HEAD"].includes(method) && secondInput().trim()) init.body = secondInput(); const start = performance.now(), response = await fetch(url, init), elapsed = performance.now() - start, contentType = response.headers.get("content-type") || "", raw = await response.text(); let body = raw; if (contentType.includes("json")) { try { body = JSON.stringify(JSON.parse(raw), null, 2); } catch {} } setOutput(`${method} ${url}\nHTTP ${response.status} ${response.statusText}\nTime: ${elapsed.toFixed(1)} ms\nSize: ${formatBytes(new Blob([raw]).size)}\n\nResponse headers:\n${[...response.headers].map(([key, value]) => `${key}: ${value}`).join("\n")}\n\nBody:\n${body}`); }
  async function loadDevImage(file) { if (state.imageUrl) URL.revokeObjectURL(state.imageUrl); state.imageUrl = URL.createObjectURL(file); const image = new Image(); await new Promise((resolve, reject) => { image.onload = resolve; image.onerror = () => reject(new Error("Không thể đọc ảnh.")); image.src = state.imageUrl; }); state.image = image; $(state.root, "[data-dev-option='width']").value = image.naturalWidth; $(state.root, "[data-dev-option='height']").value = image.naturalHeight; $(state.root, "[data-dev-image-meta]").textContent = `${image.naturalWidth}×${image.naturalHeight} · ${formatBytes(file.size)}`; await runImage(); }
  async function runImage() { if (!state.image) throw new Error("Hãy chọn ảnh trước."); const width = clamp(option("width") || state.image.naturalWidth, 1, 8000), height = clamp(option("height") || Math.round(width / state.image.naturalWidth * state.image.naturalHeight), 1, 8000), canvas = $(state.root, "[data-dev-canvas]"), ctx = canvas.getContext("2d"), filter = option("filter"); canvas.width = width; canvas.height = height; ctx.imageSmoothingQuality = "high"; if (filter === "pixelate") { const smallWidth = Math.max(1, Math.round(width / 24)), smallHeight = Math.max(1, Math.round(height / 24)), temp = document.createElement("canvas"); temp.width = smallWidth; temp.height = smallHeight; temp.getContext("2d").drawImage(state.image, 0, 0, smallWidth, smallHeight); ctx.imageSmoothingEnabled = false; ctx.drawImage(temp, 0, 0, width, height); } else { ctx.filter = filter || "none"; ctx.drawImage(state.image, 0, 0, width, height); ctx.filter = "none"; } state.lastOutput = `Tên: ${state.file.name}\nKích thước gốc: ${state.image.naturalWidth}×${state.image.naturalHeight}\nĐầu ra: ${width}×${height}\nMIME: ${state.file.type}\nDung lượng gốc: ${formatBytes(state.file.size)}\nFilter: ${filter}`; setOutput(state.lastOutput); }
  const SQL_KEYWORDS = ["select", "from", "where", "join", "left join", "right join", "inner join", "outer join", "on", "group by", "order by", "having", "limit", "offset", "insert into", "values", "update", "set", "delete from", "create table", "alter table", "drop table", "union", "union all", "and", "or", "as", "case", "when", "then", "else", "end", "distinct"];
  function sqlKeywords(value, upper = true) { return SQL_KEYWORDS.sort((a, b) => b.length - a.length).reduce((text, keyword) => text.replace(new RegExp(`\\b${keyword.replace(" ", "\\s+")}\\b`, "gi"), upper ? keyword.toUpperCase() : keyword.toLowerCase()), value); }
  async function runSql() { const mode = option("mode"), input = currentInput(); if (mode === "minify") return setOutput(input.replace(/--.*$/gm, "").replace(/\s+/g, " ").trim()); if (mode === "upper" || mode === "lower") return setOutput(sqlKeywords(input, mode === "upper")); let output = sqlKeywords(input, true).replace(/\s+(FROM|WHERE|LEFT JOIN|RIGHT JOIN|INNER JOIN|OUTER JOIN|GROUP BY|ORDER BY|HAVING|LIMIT|UNION|VALUES|SET)\b/g, "\n$1").replace(/\s+(AND|OR)\s+/g, "\n  $1 ").replace(/,\s*/g, ",\n  "); setOutput(output.trim()); }
  function markdownHtml(source) { let html = esc(source); html = html.replace(/^######\s+(.+)$/gm, "<h6>$1</h6>").replace(/^#####\s+(.+)$/gm, "<h5>$1</h5>").replace(/^####\s+(.+)$/gm, "<h4>$1</h4>").replace(/^###\s+(.+)$/gm, "<h3>$1</h3>").replace(/^##\s+(.+)$/gm, "<h2>$1</h2>").replace(/^#\s+(.+)$/gm, "<h1>$1</h1>").replace(/```([\s\S]*?)```/g, "<pre><code>$1</code></pre>").replace(/`([^`]+)`/g, "<code>$1</code>").replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>").replace(/\*([^*]+)\*/g, "<em>$1</em>").replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g, '<a href="$2" target="_blank" rel="noopener">$1</a>').replace(/^&gt;\s+(.+)$/gm, "<blockquote>$1</blockquote>").replace(/^[-*]\s+(.+)$/gm, "<li>$1</li>").replace(/(?:<li>.*<\/li>\n?)+/g, "<ul>$&</ul>").replace(/\n{2,}/g, "</p><p>").replace(/\n/g, "<br>"); return `<p>${html}</p>`; }
  async function runMarkdown() { const html = markdownHtml(currentInput()), output = $(state.root, "[data-dev-output]"); if (output) output.innerHTML = html; state.lastOutput = html; }
  function markdownToc() { const headings = currentInput().split("\n").filter((line) => /^#{1,6}\s/.test(line)), toc = headings.map((line) => { const [, hashes, title] = line.match(/^(#+)\s+(.+)$/); return `${"  ".repeat(hashes.length - 1)}- [${title}](#${slugify(title)})`; }).join("\n"); setOutput(toc || "Không tìm thấy heading."); }
  function exportMarkdown() { const body = markdownHtml(currentInput()), page = `<!doctype html><html lang="vi"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>HH Markdown Export</title><style>body{max-width:850px;margin:40px auto;padding:0 20px;font:16px/1.7 system-ui;color:#172033}pre,code{background:#f0f3f7;border-radius:5px}pre{padding:14px;overflow:auto}blockquote{border-left:3px solid #17a7b5;padding-left:14px;color:#536273}</style><body>${body}</body></html>`; download(page, "hh-markdown.html", "text/html;charset=utf-8"); }
  function parseCronField(field, min, max) { const values = new Set(); const addRange = (start, end, step = 1) => { for (let value = start; value <= end; value += step) values.add(value); }; field.split(",").forEach((part) => { const [base, stepRaw] = part.split("/"), step = Number(stepRaw) || 1; if (base === "*") addRange(min, max, step); else if (base.includes("-")) { const [start, end] = base.split("-").map(Number); addRange(start, end, step); } else { const value = Number(base); if (value >= min && value <= max) values.add(value); } }); if (!values.size) throw new Error(`Cron field không hợp lệ: ${field}`); return values; }
  async function runCron() { const fields = currentInput().trim().split(/\s+/); if (fields.length !== 5) throw new Error("Cron chuẩn cần 5 trường: phút giờ ngày tháng thứ."); const [minutes, hours, days, months, weekdays] = [parseCronField(fields[0], 0, 59), parseCronField(fields[1], 0, 23), parseCronField(fields[2], 1, 31), parseCronField(fields[3], 1, 12), parseCronField(fields[4], 0, 6)], count = clamp(option("count"), 1, 50), results = [], cursor = new Date(); cursor.setSeconds(0, 0); cursor.setMinutes(cursor.getMinutes() + 1); for (let checkedMinutes = 0; checkedMinutes < 525600 * 3 && results.length < count; checkedMinutes++) { if (minutes.has(cursor.getMinutes()) && hours.has(cursor.getHours()) && days.has(cursor.getDate()) && months.has(cursor.getMonth() + 1) && weekdays.has(cursor.getDay())) results.push(new Date(cursor)); cursor.setMinutes(cursor.getMinutes() + 1); } setOutput(`Expression: ${fields.join(" ")}\nGiải thích: phút [${[...minutes].slice(0, 8).join(",")}${minutes.size > 8 ? "..." : ""}], giờ [${[...hours].join(",")}], ngày/tháng/thứ theo lịch.\n\nLần chạy tiếp theo:\n${results.map((date, index) => `${index + 1}. ${date.toLocaleString("vi-VN", { dateStyle: "full", timeStyle: "medium" })}`).join("\n") || "Không tìm thấy trong 3 năm tới."}`); }
  async function runNetwork() { const mode = option("mode"), input = currentInput().trim(); if (mode === "ip") { const start = performance.now(), response = await fetch("https://api.ipify.org?format=json"), data = await response.json(); setOutput(`Public IP: ${data.ip}\nLatency: ${(performance.now() - start).toFixed(1)} ms\nNguồn: api.ipify.org`); return; } if (mode === "dns") { const name = input.replace(/^https?:\/\//, "").split("/")[0], start = performance.now(), response = await fetch(`https://dns.google/resolve?name=${encodeURIComponent(name)}&type=${encodeURIComponent(option("type"))}`), data = await response.json(); setOutput(`Google DNS over HTTPS\nName: ${name}\nType: ${option("type")}\nStatus: ${data.Status}\nLatency: ${(performance.now() - start).toFixed(1)} ms\n\nAnswers:\n${(data.Answer || []).map((row) => `${row.name} · TTL ${row.TTL} · ${row.data}`).join("\n") || "Không có answer."}`); return; } const url = /^https?:\/\//i.test(input) ? input : `https://${input}`, start = performance.now(), response = await fetch(url, { method: mode === "headers" ? "HEAD" : "GET", cache: "no-store" }), elapsed = performance.now() - start; setOutput(`${mode === "ping" ? "HTTP latency" : "HTTP headers"}\nURL: ${url}\nStatus: ${response.status} ${response.statusText}\nTime: ${elapsed.toFixed(1)} ms\n\n${[...response.headers].map(([key, value]) => `${key}: ${value}`).join("\n")}\n\nLưu ý: website đích phải cho phép CORS.`); }

  addEventListener("keydown", (event) => { if (!state.root?.isConnected) return; const command = event.ctrlKey || event.metaKey, key = event.key.toLowerCase(); if (command && event.key === "Enter") { event.preventDefault(); execute().catch(showError); } if (command && key === "s") { event.preventDefault(); exportSession(); } if (command && key === "z") { event.preventDefault(); undoDraft(); } if (command && key === "y") { event.preventDefault(); redoDraft(); } });
  window.HHDeveloperTools = { mount, cleanup, tools: () => TOOLS.map((tool) => ({ ...tool })), groups: () => [...GROUPS] };
  dispatchEvent(new CustomEvent("hh:developer-tools-ready"));
})();
