(() => {
  "use strict";
  const KEY="hh-professional-tools";
  const safe=(v)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||"{}");}catch{return {};}};
  const write=(value)=>localStorage.setItem(KEY,JSON.stringify(value));
  const tools={
    json:{name:"JSON Formatter",placeholder:'{"hello":"world"}',run:v=>JSON.stringify(JSON.parse(v),null,2)},
    base64:{name:"Base64",placeholder:"Nhập văn bản Unicode",run:v=>btoa(unescape(encodeURIComponent(v))),alt:v=>decodeURIComponent(escape(atob(v)))},
    uuid:{name:"UUID & Token",placeholder:"Độ dài token (mặc định 32)",run:v=>`${crypto.randomUUID()}\n${Array.from(crypto.getRandomValues(new Uint8Array(Math.max(8,Math.min(128,Number(v)||32))))).map(x=>x.toString(16).padStart(2,"0")).join("")}`},
    password:{name:"Password Generator",placeholder:"Độ dài (12-128)",run:v=>{const chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%&*";return Array.from(crypto.getRandomValues(new Uint32Array(Math.max(12,Math.min(128,Number(v)||20)))),x=>chars[x%chars.length]).join("")}},
    timestamp:{name:"Timestamp",placeholder:"ISO, Unix hoặc ngày",run:v=>{const d=!v?new Date():/^\d+$/.test(v)?new Date(Number(v)*1000):new Date(v);if(Number.isNaN(d.valueOf()))throw Error("Ngày không hợp lệ");return `ISO: ${d.toISOString()}\nUnix: ${Math.floor(d.valueOf()/1000)}\nLocal: ${d.toLocaleString("vi-VN")}`}},
    regex:{name:"Regex Tester",placeholder:"Dòng 1: biểu thức\nCác dòng sau: văn bản",run:v=>{const [pattern,...rows]=v.split("\n");const matches=[...rows.join("\n").matchAll(new RegExp(pattern,"gmi"))];return `Matches: ${matches.length}\n${matches.map((m,i)=>`${i+1}. ${m[0]} @${m.index}`).join("\n")}`}},
    text:{name:"Text Utilities",placeholder:"Nhập văn bản",run:v=>`Words: ${v.trim()?v.trim().split(/\s+/).length:0}\nCharacters: ${v.length}\nSlug: ${v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}\n\n${v.toUpperCase()}`},
    color:{name:"Color Studio",placeholder:"#00e5ff",run:v=>{const hex=(v.match(/[0-9a-f]{6}/i)||["00e5ff"])[0];const n=parseInt(hex,16),rgb=[n>>16,(n>>8)&255,n&255];return `HEX: #${hex}\nRGB: rgb(${rgb.join(", ")})\nGradient: linear-gradient(135deg, #${hex}, #ff3bd1)`}},
    compare:{name:"Text Compare",placeholder:"Văn bản A\n---\nVăn bản B",run:v=>{const [a="",b=""]=v.split(/\n---\n/);const A=a.split("\n"),B=b.split("\n");return [...new Set([...A,...B])].map(x=>`${A.includes(x)&&B.includes(x)?" ":A.includes(x)?"-":"+"} ${x}`).join("\n")}},
    calculator:{name:"Calculator",placeholder:"Ví dụ: (1200*15)/100",run:v=>{if(!/^[\d\s+\-*/().%]+$/.test(v))throw Error("Chỉ chấp nhận phép tính số");return String(Function(`"use strict";return (${v})`)())}}
  };
  document.body.insertAdjacentHTML("beforeend",`<button class="pro-tools-launcher" type="button" aria-label="Mở Professional Toolkit">DEV</button><section class="pro-tools" hidden aria-label="Professional Toolkit"><div class="pro-tools__panel"><header class="pro-tools__head"><div><small>HH AI DEV HUB</small><h2>Professional Toolkit</h2></div><button type="button" data-pro-close>Đóng · Esc</button></header><div class="pro-tools__body"><nav class="pro-tools__nav">${Object.entries(tools).map(([id,t],i)=>`<button type="button" class="${i?"":"active"}" data-pro-tool="${id}">${t.name}</button>`).join("")}<button type="button" data-pro-tool="notes">Notes & Todo</button><button type="button" data-pro-tool="system">System Monitor</button></nav><main class="pro-tools__work"><label>Công cụ<select data-pro-select>${Object.entries(tools).map(([id,t])=>`<option value="${id}">${t.name}</option>`).join("")}<option value="notes">Notes & Todo</option><option value="system">System Monitor</option></select></label><label data-pro-input-wrap>Dữ liệu đầu vào<textarea data-pro-input></textarea></label><div class="pro-tools__actions"><button type="button" data-pro-run>Chạy</button><button type="button" data-pro-alt>Giải mã / tác vụ phụ</button><button type="button" data-pro-copy>Sao chép</button><button type="button" data-pro-save>Lưu phiên</button></div><pre data-pro-output>Sẵn sàng.</pre><div data-pro-extra></div><span class="pro-tools__status" data-pro-status>Dữ liệu được xử lý trên thiết bị của bạn.</span></main></div></div></section>`);
  const root=document.querySelector(".pro-tools"),select=root.querySelector("[data-pro-select]"),input=root.querySelector("[data-pro-input]"),output=root.querySelector("[data-pro-output]"),extra=root.querySelector("[data-pro-extra]");
  const choose=id=>{select.value=id;root.querySelectorAll("[data-pro-tool]").forEach(x=>x.classList.toggle("active",x.dataset.proTool===id));input.placeholder=tools[id]?.placeholder||"";extra.innerHTML="";if(id==="notes"){const s=read();input.value=s.notes||"";extra.innerHTML=`<div class="pro-tools__todo">${(s.todos||[]).map((x,i)=>`<label><input type="checkbox" data-pro-todo="${i}" ${x.done?"checked":""}>${safe(x.text)}</label>`).join("")}<button type="button" data-pro-add-todo>+ Todo</button></div>`;}if(id==="system"){const used=JSON.stringify(localStorage).length;output.textContent=`Network: ${navigator.onLine?"Online":"Offline"}\nViewport: ${innerWidth}×${innerHeight}\nCPU cores: ${navigator.hardwareConcurrency||"N/A"}\nMemory: ${navigator.deviceMemory||"N/A"} GB\nLocalStorage: ${(used/1024).toFixed(1)} KB`;}};
  const open=()=>{root.hidden=false;choose(select.value);input.focus()};const close=()=>root.hidden=true;
  document.querySelector(".pro-tools-launcher").onclick=open;root.querySelector("[data-pro-close]").onclick=close;
  root.onclick=e=>{const nav=e.target.closest("[data-pro-tool]");if(nav)choose(nav.dataset.proTool);if(e.target.closest("[data-pro-run]")){try{output.textContent=tools[select.value]?.run(input.value)||"Chọn một công cụ xử lý.";}catch(err){output.textContent=`Lỗi: ${err.message}`}}if(e.target.closest("[data-pro-alt]")){try{output.textContent=tools[select.value]?.alt?.(input.value)||"Công cụ này không có tác vụ phụ.";}catch(err){output.textContent=`Lỗi: ${err.message}`}}if(e.target.closest("[data-pro-copy]"))navigator.clipboard.writeText(output.textContent);if(e.target.closest("[data-pro-save]")){const s=read();s.notes=input.value;s.history=[{tool:select.value,input:input.value,output:output.textContent,at:new Date().toISOString()},...(s.history||[])].slice(0,50);write(s);root.querySelector("[data-pro-status]").textContent="Đã tự động lưu."}if(e.target.closest("[data-pro-add-todo]")){const text=prompt("Việc cần làm:")?.trim();if(text){const s=read();s.todos=[...(s.todos||[]),{text,done:false}];write(s);choose("notes")}}};
  root.onchange=e=>{if(e.target===select)choose(select.value);if(e.target.matches("[data-pro-todo]")){const s=read();if(s.todos?.[Number(e.target.dataset.proTodo)])s.todos[Number(e.target.dataset.proTodo)].done=e.target.checked;write(s)}};
  addEventListener("keydown",e=>{if(e.key==="Escape")close();if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==="p"){e.preventDefault();open()}});
  addEventListener("online",()=>select.value==="system"&&choose("system"));addEventListener("offline",()=>select.value==="system"&&choose("system"));
  if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
})();
