(function(root){
  "use strict";
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const labels={home:"Tổng quan",calendar:"Lịch học",tasks:"Nhiệm vụ",notes:"Ghi chú chung",quiz:"Quiz",cards:"Flashcard",chat:"Chat lớp",news:"Thông báo"};
  const btn=(action,label,extra="")=>'<button type="button" data-hsp-action="'+action+'" '+extra+'>'+label+'</button>';
  const dates=ms=>new Date(ms).toLocaleString("vi-VN",{dateStyle:"short",timeStyle:"short"});
  function mount(host,o){
    const core=root.HHStudyCampusCore,cls=o.class,manager=["owner","assistant"].includes(cls.role),leader=manager||cls.role==="presenter";
    let alive=true,busy=false,tab="home",state=null,quizzes=[],bank=null,quiz=null,messages=[],cardIndex=0,flipped=false,followCards=false,clock=0,view="list",offset=0,replyTo=null;
    const uiKey="hh.studyTogether.campusView.v1."+o.user.id+"."+cls.id;try{const v=JSON.parse(localStorage.getItem(uiKey)||"{}");if(Object.hasOwn(labels,v.tab))tab=v.tab;if(Number.isSafeInteger(v.cardIndex)&&v.cardIndex>=0&&v.cardIndex<50)cardIndex=v.cardIndex;}catch{}
    const listeners=[],urls=new Set(),detailsState={},prefix="hh.studyTogether.campusDraft.v1."+o.user.id+"."+cls.id+".";
    const q=s=>host.querySelector(s),on=(node,type,fn)=>{node.addEventListener(type,fn);listeners.push(()=>node.removeEventListener(type,fn));};
    host.innerHTML='<section class="hsp" aria-label="Cosmic Study Campus"><header class="hsp-heading"><div><small>COSMIC STUDY CAMPUS</small><h4>Không gian của lớp</h4></div>'+btn("refresh","Đồng bộ bản mới")+'</header><p data-hsp-status role="status">Đang tải công cụ lớp…</p><nav aria-label="Công cụ lớp">'+Object.entries(labels).map(([id,label])=>btn("tab",label,'data-tab="'+id+'" aria-pressed="'+(id===tab)+'"')).join("")+'</nav><div data-hsp-body></div></section>';
    const api=(action,body={})=>o.api(action,{...body,classId:cls.id});
    const memberOptions=selected=>'<option value="">Chưa phân công</option>'+cls.members.filter(m=>m.role!=="blocked").map(m=>'<option value="'+esc(m.userId)+'" '+(m.userId===selected?'selected':'')+'>'+esc(m.name)+'</option>').join("");
    const documents=selected=>'<option value="">Không liên kết</option>'+cls.documents.map(d=>'<option value="'+esc(d.id)+'" '+(d.id===selected?'selected':'')+'>'+esc(d.name)+'</option>').join("");
    function status(message,bad=false){if(alive){q("[data-hsp-status]").textContent=message;q("[data-hsp-status]").dataset.error=String(bad);}}
    function controls(){host.querySelectorAll("button,input,select,textarea").forEach(n=>n.disabled=busy);}
    async function run(work){if(busy||!alive)return;const active=host.contains(document.activeElement)?document.activeElement:null,action=active?.dataset.hspAction,kind=active?.closest("form")?.dataset.hspForm,name=active?.name;busy=true;controls();status("Đang xử lý yêu cầu…");try{await work();}catch(e){status(e.message+" Bản nháp chưa bị xóa.",true);}finally{busy=false;if(alive){controls();const target=active?.isConnected?active:action?q('[data-hsp-action="'+CSS.escape(action)+'"]'):kind&&name?q('[data-hsp-form="'+CSS.escape(kind)+'"] [name="'+CSS.escape(name)+'"]'):q('[data-tab="'+tab+'"]');target?.focus({preventScroll:true});if(q("[data-hsp-status]").textContent==="Đang xử lý yêu cầu…")status("Đã xử lý yêu cầu và nhận phản hồi backend.");}}}
    function saveDraft(form){const values={};for(const n of form.elements)if(n.name&&n.type!=="file"&&(n.type!=="radio"||n.checked))values[n.name]=n.type==="checkbox"?n.checked:n.value;try{localStorage.setItem(prefix+form.dataset.hspForm,JSON.stringify({values,revision:Number(form.dataset.revision),at:Date.now()}));status("Bản nháp đã lưu trên thiết bị. Chưa lưu lên lớp.");}catch{status("Không lưu được bản nháp trên thiết bị. Có thể xuất trước khi rời.",true);}}
    function restore(){host.querySelectorAll("form[data-hsp-form]").forEach(f=>{try{const d=JSON.parse(localStorage.getItem(prefix+f.dataset.hspForm)||"null");if(!d)return;for(const[name,value]of Object.entries(d.values)){const n=f.elements.namedItem(name);if(n){if(n.type==="checkbox")n.checked=value;else if(typeof value==="string")n.value=value;}}f.dataset.revision=String(d.revision);f.dataset.draft="true";}catch{}});}
    function discard(kind){try{localStorage.removeItem(prefix+kind);}catch{}}
    const revision=form=>Number(form.dataset.revision);
    const form=(kind,field,contents)=>'<form data-hsp-form="'+kind+'" data-revision="'+(field==="bank"?bank?.revision||0:state?.[field]?.revision||0)+'">'+contents+'<div class="hst-actions"><button>Lưu vào lớp</button>'+btn("discard","Bỏ bản nháp",'data-kind="'+kind+'"')+btn("export-draft","Xuất bản nháp",'data-kind="'+kind+'"')+'</div></form>';
    function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type}));urls.add(url);const a=document.createElement("a");a.href=url;a.download=name;host.append(a);a.click();a.remove();setTimeout(()=>{URL.revokeObjectURL(url);urls.delete(url);},1000);}
    async function load(){const data=await api("campus-get");if(!alive)return;for(const key of Object.keys(data.campus))if((state?.[key]?.revision||0)>(data.campus[key]?.revision||0))data.campus[key]=state[key];state=data.campus;quizzes=data.quizzes;render();status("Đã tải dữ liệu lớp thật. Các mục có revision riêng; lưu xung đột sẽ giữ bản nháp.");}
    function render(){
      if(!state||!alive)return;
      try{localStorage.setItem(uiKey,JSON.stringify({tab,cardIndex}));}catch{}
      host.querySelectorAll("[data-tab]").forEach(b=>b.setAttribute("aria-pressed",String(b.dataset.tab===tab)));
      const body=q("[data-hsp-body]");if(body.dataset.tab)detailsState[body.dataset.tab]=[...body.querySelectorAll("details[open]>summary")].map(n=>n.textContent);body.dataset.tab=tab;
      if(tab==="home"){
        const upcoming=core.occurrences(state.calendar.events,Date.now()).filter(e=>!e.cancelled).slice(0,3),tasks=state.tasks.items.filter(t=>t.status!=="done");
        body.innerHTML='<div class="hsp-dashboard"><article><h5>Buổi học sắp tới</h5>'+(upcoming.length?upcoming.map(e=>'<p><strong>'+esc(e.title)+'</strong><br>'+esc(dates(e.startsAt))+' · '+esc(e.zone)+'</p>').join(""):'<p>Chưa có buổi học được lên lịch.</p>')+btn("tab","Mở lịch",'data-tab="calendar"')+'</article><article><h5>Nhiệm vụ đang mở</h5><p>'+tasks.length+' nhiệm vụ chưa hoàn thành từ bảng lớp.</p>'+tasks.slice(0,3).map(t=>'<p>'+esc(t.title)+'</p>').join("")+btn("tab","Mở Kanban",'data-tab="tasks"')+'</article><article><h5>Kế hoạch hiện tại</h5><p>'+esc(cls.plan?.goal||"Chưa có mục tiêu chung.")+'</p><p>'+cls.documents.length+' / 20 tài liệu · '+Math.ceil(cls.documents.reduce((n,d)=>n+d.size,0)/1024)+' / 8192 KiB.</p><p>Giữ đến '+esc(dates(cls.expiresAt))+'.</p></article><article><h5>Tài liệu mới nhất</h5>'+(cls.documents.length?cls.documents.slice(-3).reverse().map(d=>btn("document",esc(d.name),'data-id="'+esc(d.id)+'"')).join(""):'<p>Tải tài liệu bằng thư viện lớp bên dưới.</p>')+'</article></div><p class="hst-help">Số liệu là dữ liệu đã lưu, không đo sự chú ý hay thời gian học của người tham gia.</p>';
      }
      if(tab==="calendar"){
        const now=new Date(),base=new Date(now.getFullYear(),now.getMonth()+(view==="month"?offset:0),now.getDate()+(view==="week"?offset*7:0)),start=view==="month"?new Date(base.getFullYear(),base.getMonth(),1).getTime():view==="week"?new Date(base.getFullYear(),base.getMonth(),base.getDate()-((base.getDay()+6)%7)).getTime():Date.now()-86400000,end=view==="month"?new Date(base.getFullYear(),base.getMonth()+1,1).getTime():view==="week"?start+7*86400000:start+90*86400000,events=core.occurrences(state.calendar.events,start,end);
        body.innerHTML='<div class="hst-actions">'+["list","week","month"].map(v=>btn("calendar-view",{list:"Danh sách",week:"Tuần",month:"Tháng"}[v],'data-view="'+v+'" aria-pressed="'+(view===v)+'"')).join("")+btn("calendar-prev","Kỳ trước")+btn("calendar-next","Kỳ sau")+btn("ics","Xuất .ics")+'</div><p>'+esc(dates(start))+' — '+esc(dates(end))+'</p><div class="hsp-calendar" data-view="'+view+'">'+(events.length?events.map(e=>'<article data-cancelled="'+e.cancelled+'"><strong>'+esc(e.title)+'</strong><span>'+esc(dates(e.startsAt))+' · '+e.minutes+' phút</span><small>'+esc(e.zone)+(e.cancelled?' · Đã hủy':'')+'</small>'+(manager?btn("edit-event","Sửa chuỗi",'data-id="'+esc(e.id)+'"')+btn("delete-event","Xóa chuỗi",'data-id="'+esc(e.id)+'"'):'')+'</article>').join(""):'<p>Không có lịch trong kỳ này.</p>')+'</div><p class="hst-help">Lịch hiển thị theo giờ thiết bị; mỗi buổi giữ múi giờ đã chọn. Xuất .ics để dùng nhắc lịch của ứng dụng lịch. Website chưa có dịch vụ gửi nhắc lịch. Vào phiên bằng danh sách phiên thật, không tự tạo cuộc gọi từ lịch.</p>'+(manager?form("calendar","calendar",'<input type="hidden" name="eventId"><label>Chủ đề<input name="title" maxlength="120" required></label><label>Ngày giờ theo múi giờ bên dưới<input name="localStart" type="datetime-local" required></label><label>Múi giờ IANA<input name="zone" value="'+esc(Intl.DateTimeFormat().resolvedOptions().timeZone)+'" maxlength="80" required list="hsp-zones"><datalist id="hsp-zones"><option>Asia/Ho_Chi_Minh</option><option>Asia/Bangkok</option><option>Asia/Tokyo</option><option>Europe/London</option><option>America/New_York</option></datalist></label><label>Phút<input name="minutes" type="number" min="5" max="240" value="60" required></label><label>Lặp<select name="repeat"><option value="none">Một lần</option><option value="weekly">Hằng tuần</option></select></label><label>Lặp đến ngày<input name="until" type="date"></label><label>Phụ trách<select name="leader">'+memberOptions("")+'</select></label><label>Ngoại lệ · mỗi dòng: ngày | hủy hoặc ngày | giờ mới<textarea name="exceptions" placeholder="2026-10-16 | hủy&#10;2026-10-23 | 2026-10-23T21:00"></textarea></label><label class="hst-check"><input name="cancelled" type="checkbox">Hủy cả chuỗi (giữ trên lịch)</label>'):'');
      }
      if(tab==="tasks"){
        body.innerHTML='<div class="hsp-kanban">'+Object.entries({todo:"Cần làm",doing:"Đang làm",done:"Hoàn thành"}).map(([status,label])=>'<section data-hsp-drop="'+status+'" aria-label="'+label+'"><h5>'+label+'</h5>'+(state.tasks.items.filter(t=>t.status===status).map(t=>'<article draggable="'+(manager||t.assignee===o.user.id)+'" data-task="'+esc(t.id)+'"><strong>'+esc(t.title)+'</strong><p>'+esc(t.description)+'</p><small>'+esc(cls.members.find(m=>m.userId===t.assignee)?.name||"Chưa giao")+' · '+esc({low:"Thấp",normal:"Bình thường",high:"Cao"}[t.priority])+(t.due?' · '+esc(dates(t.due)):'')+'</small>'+(t.documentId?btn("document","Mở tài liệu",'data-id="'+esc(t.documentId)+'"'):'')+((manager||t.assignee===o.user.id)?'<label>Chuyển cột (bàn phím)<select data-hsp-task-status="'+esc(t.id)+'">'+["todo","doing","done"].map(s=>'<option value="'+s+'" '+(s===t.status?'selected':'')+'>'+({todo:"Cần làm",doing:"Đang làm",done:"Hoàn thành"}[s])+'</option>').join("")+'</select></label>':'')+(manager?btn("edit-task","Sửa",'data-id="'+esc(t.id)+'"')+btn("delete-task","Xóa",'data-id="'+esc(t.id)+'"'):'')+'</article>').join("")||'<p>Chưa có nhiệm vụ.</p>')+'</section>').join("")+'</div>'+(manager?form("task","tasks",'<input type="hidden" name="taskId"><label>Nhiệm vụ<input name="title" maxlength="160" required></label><label>Mô tả<textarea name="description" maxlength="1000"></textarea></label><label>Người nhận<select name="assignee">'+memberOptions("")+'</select></label><label>Hạn (giờ thiết bị)<input name="due" type="datetime-local"></label><label>Ưu tiên<select name="priority"><option value="normal">Bình thường</option><option value="high">Cao</option><option value="low">Thấp</option></select></label><label>Cột<select name="status"><option value="todo">Cần làm</option><option value="doing">Đang làm</option><option value="done">Hoàn thành</option></select></label><label>Tài liệu<select name="documentId">'+documents("")+'</select></label>'):'');
      }
      if(tab==="notes")body.innerHTML='<p>Ghi chú/checklist/biên bản chung · mọi thành viên lớp được sửa. Bản nháp riêng giữ nguyên khi có xung đột; tải bản mới không tự ghép nội dung.</p>'+form("notes","notes",'<label>Nội dung chung<textarea name="text" rows="12" maxlength="12000">'+esc(state.notes.text)+'</textarea></label>')+'<p>Revision '+state.notes.revision+(state.notes.at?' · Lưu '+esc(dates(state.notes.at)):' · Chưa có bản lưu')+'</p>';
      if(tab==="quiz"){
        body.innerHTML='<div class="hsp-quiz-list">'+(quizzes.length?quizzes.map(x=>btn("quiz",esc(x.title)+' · '+esc({draft:"Nháp",open:"Đang mở",closed:"Đã đóng"}[x.state]),'data-id="'+esc(x.id)+'"')).join(""):'<p>Chưa có bài quiz. Người quản lý tự tạo câu hỏi; không dùng AI chưa cấu hình.</p>')+'</div><div data-hsp-quiz-detail></div>'+(manager?'<details><summary>Ngân hàng câu hỏi & tạo bài</summary>'+btn("bank","Tải ngân hàng có đáp án")+'<div data-hsp-bank></div>'+form("question","bank",'<input type="hidden" name="questionId"><label>Loại<select name="type"><option value="mcq">Trắc nghiệm</option><option value="truefalse">Đúng / sai</option><option value="short">Câu trả lời ngắn (chấm tay)</option></select></label><label>Câu hỏi<textarea name="prompt" maxlength="500" required></textarea></label><label>Đáp án lựa chọn · mỗi dòng một mục<textarea name="options"></textarea></label><label>Đáp án đúng · số từ 1, hoặc đáp án tham khảo cho câu ngắn<input name="answer" required maxlength="500"></label>')+form("new-quiz","bank",'<label>Tên bài<input name="title" maxlength="120" required></label><label>Thời lượng phút<input name="minutes" type="number" min="1" max="90" value="10"></label><label>ID câu hỏi · tối đa 10, mỗi dòng một ID<textarea name="questionIds" required></textarea></label>')+'</details>':'');
        if(quiz)renderQuiz();
      }
      if(tab==="cards"){
        const cards=state.cards.cards;if(cardIndex>=cards.length)cardIndex=0;const live=cards.find(c=>c.id===state.liveCards.cardId),c=followCards?live:cards[cardIndex],revealed=followCards?state.liveCards.revealed:flipped;
        body.innerHTML='<label class="hst-check"><input type="checkbox" data-hsp-follow-cards '+(followCards?'checked':'')+'>Theo thẻ người trình bày (không ảnh hưởng luyện riêng)</label><article class="hsp-flashcard"><small>'+(followCards?'Thẻ chung':'Luyện riêng')+'</small><p>'+esc(c?(revealed?c.back:c.front):"Chưa có thẻ đang học.")+'</p></article><div class="hst-actions">'+btn("card-prev","Thẻ trước")+btn("card-flip",revealed?"Xem câu hỏi":"Lật thẻ")+btn("card-next","Thẻ sau")+(leader?btn("card-lead","Trình bày thẻ này")+btn("card-reveal","Lật thẻ chung")+btn("card-stop","Dừng thẻ chung"):'')+'</div><div class="hsp-card-list">'+cards.map((c,i)=>btn("select-card",esc(c.front.slice(0,80)),'data-index="'+i+'"')+(manager?btn("delete-card","Xóa",'data-id="'+esc(c.id)+'"'):'')).join("")+'</div>'+(manager?form("card","cards",'<label>Mặt trước<textarea name="front" maxlength="500" required></textarea></label><label>Mặt sau<textarea name="back" maxlength="1000" required></textarea></label>'):'');
      }
      if(tab==="chat")body.innerHTML='<p>Chat phiên LiveKit vẫn tạm thời. Chat lớp dưới đây là kênh khác: '+(state.policy.chatEnabled?'đang lưu tối đa '+state.policy.chatDays+' ngày (không quá hạn lớp).':'không lưu tin mới. Tin cũ vẫn giữ theo hạn đã chọn trước đó.')+'</p>'+(manager?form("chat-policy","policy",'<label class="hst-check"><input name="enabled" type="checkbox" '+(state.policy.chatEnabled?'checked':'')+'>Bật lưu chat lớp dài hạn</label><label>Thời hạn tin mới<select name="days">'+[1,7,30].map(n=>'<option '+(n===state.policy.chatDays?'selected':'')+'>'+n+'</option>').join("")+'</select></label>'):'')+(state.policy.chatEnabled?'<div class="hst-actions">'+btn("load-chat","Tải chat")+btn("export-chat","Xuất chat JSON")+'</div><div data-hsp-messages role="log" aria-label="Tin lớp"></div>'+form("message","policy",'<p data-hsp-reply></p><label>Tin nhắn<textarea name="text" maxlength="1000" required></textarea></label><label>Liên kết tài liệu/nhiệm vụ<select name="resourceId">'+documents("")+state.tasks.items.map(t=>'<option value="'+esc(t.id)+'">'+esc(t.title)+'</option>').join("")+'</select></label>')+(manager?'<details class="hsc-danger"><summary>Xóa toàn bộ lịch sử chat lớp</summary><label class="hst-check"><input type="checkbox" data-hsp-clear-confirm>Tôi đã xuất dữ liệu cần giữ.</label>'+btn("clear-chat","Xóa lịch sử chat")+'</details>':''):'<p>Người quản lý có thể bật bằng lựa chọn rõ ràng. Không có lịch sử giả.</p><div class="hst-actions">'+btn('load-chat','Tải lịch sử còn hạn')+btn('export-chat','Xuất chat JSON')+'</div><div data-hsp-messages role="log" aria-label="Lịch sử chat lớp"></div>'+(manager?'<details class="hsc-danger"><summary>Xóa lịch sử còn lưu</summary><label class="hst-check"><input type="checkbox" data-hsp-clear-confirm>Tôi đã xuất dữ liệu cần giữ.</label>'+btn('clear-chat','Xóa lịch sử chat')+'</details>':''));
      if(tab==="news")body.innerHTML='<div class="hsp-news">'+(state.announcements.posts.length?state.announcements.posts.map(p=>'<article><h5>'+esc(p.title)+'</h5><p>'+esc(p.text)+'</p><small>'+esc(p.name)+' · '+esc(dates(p.at))+'</small>'+(manager?btn("delete-post","Xóa thông báo",'data-id="'+esc(p.id)+'"'):'')+'</article>').join(""):'<p>Chưa có thông báo lớp.</p>')+'</div>'+(manager?form("news","announcements",'<label>Tiêu đề<input name="title" maxlength="160" required></label><label>Thông báo<textarea name="text" maxlength="2000" required></textarea></label>'):'');
      body.querySelectorAll("details").forEach(d=>d.open=(detailsState[tab]||[]).includes(d.querySelector("summary")?.textContent));
      restore();if(tab==="chat")renderMessages();if(tab==="quiz"&&bank)renderBank();controls();schedule();
    }
    function renderBank(){const box=q("[data-hsp-bank]");if(box&&bank)box.innerHTML=bank.questions.length?bank.questions.map(x=>'<article><strong>'+esc(x.prompt)+'</strong><code>'+esc(x.id)+'</code>'+btn("edit-question","Sửa",'data-id="'+esc(x.id)+'"')+btn("delete-question","Xóa",'data-id="'+esc(x.id)+'"')+'</article>').join(""):'<p>Ngân hàng chưa có câu.</p>';}
    function renderQuiz(){
      const box=q("[data-hsp-quiz-detail]");if(!box||!quiz)return;const x=quiz.quiz;
      box.innerHTML='<article class="hsp-quiz"><h5>'+esc(x.title)+'</h5><p>'+esc({draft:"Bản nháp",open:"Đang mở",closed:"Đã đóng"}[x.state])+(x.deadline?' · Hạn '+esc(dates(x.deadline)):'')+'</p>'+(manager?'<div class="hst-actions">'+(x.state==="draft"?btn("quiz-open","Mở bài"):x.state==="open"?btn("quiz-close","Đóng bài"):btn("quiz-reveal","Công bố đáp án & điểm"))+(x.state!=="open"?btn("quiz-delete","Xóa bài"):'')+'</div>':'')+(quiz.submitted?'<p>Đã nộp thật: '+esc(dates(quiz.receipt.at))+'. Không gửi lại phiếu khác.</p>':'<p>Chưa nộp.</p>')+(quiz.result?'<p>Kết quả: '+quiz.result.earned+' / '+quiz.result.max+' · '+quiz.result.pending+' câu chờ chấm tay.</p>':'')+'<form data-hsp-form="answers" data-revision="'+x.revision+'">'+x.questions.map((c,i)=>'<fieldset><legend>'+(i+1)+'. '+esc(c.prompt)+'</legend>'+(c.type==="short"?'<textarea name="'+esc(c.id)+'" maxlength="1000" required></textarea>':c.options.map((v,k)=>'<label class="hst-check"><input type="radio" name="'+esc(c.id)+'" value="'+k+'" required>'+esc(v)+'</label>').join(""))+(Object.hasOwn(c,"answer")?'<p>Đáp án: '+esc(c.type==="short"?c.answer:c.options[c.answer])+'</p>':'')+'</fieldset>').join("")+(x.state==="open"&&!quiz.submitted?'<button>Nộp bài một lần</button>':'')+'</form>'+(manager&&quiz.submissions?'<h5>Bài đã nộp ('+quiz.submissions.length+')</h5>'+quiz.submissions.map(p=>'<article><strong>'+esc(p.name)+'</strong><p>'+p.earned+' / '+p.max+' · '+p.pending+' câu chờ chấm</p>'+x.questions.filter(c=>c.type==="short").map(c=>'<p>'+esc(c.prompt)+': '+esc(p.answers.find(a=>a.id===c.id)?.value)+'</p>'+btn("grade","0 điểm",'data-user="'+esc(p.userId)+'" data-question="'+esc(c.id)+'" data-points="0" data-revision="'+p.revision+'"')+btn("grade","1 điểm",'data-user="'+esc(p.userId)+'" data-question="'+esc(c.id)+'" data-points="1" data-revision="'+p.revision+'"')).join("")+'</article>').join(""):'')+'</article>';
      restore();
    }
    function renderMessages(){const box=q("[data-hsp-messages]");if(!box)return;box.innerHTML=messages.length?messages.map(m=>'<article data-pinned="'+m.pinned+'"><strong>'+esc(m.name)+(m.pinned?' · Ghim':'')+'</strong><small>'+esc(dates(m.at))+'</small>'+(m.replyTo?'<blockquote>'+esc(messages.find(x=>x.id===m.replyTo)?.text||"Tin được trả lời đã hết hạn")+'</blockquote>':'')+'<p>'+esc(m.text)+'</p>'+(m.resourceId?btn("resource","Mở liên kết",'data-id="'+esc(m.resourceId)+'"'):'')+'<div class="hst-actions">'+["👍","💡","❤️","👏"].map(e=>btn("reaction",e+' '+(m.reactions?.[e]?.length||0),'data-id="'+esc(m.id)+'" data-emoji="'+e+'"')).join("")+btn("reply","Trả lời",'data-id="'+esc(m.id)+'"')+(manager?btn("pin-message",m.pinned?"Bỏ ghim":"Ghim",'data-id="'+esc(m.id)+'" data-pinned="'+!m.pinned+'"'):'')+(manager||m.userId===o.user.id?btn("delete-message","Xóa",'data-id="'+esc(m.id)+'"'):'')+'</div></article>').join(""):'<p>Chưa có tin được lưu.</p>';}
    async function chatLoad(){const d=await api("campus-chat");if(!alive)return;messages=d.messages;renderMessages();}
    async function quizLoad(id){quiz=await api("campus-quiz",{quizId:id});if(alive)renderQuiz();}
    function edit(kind,values){const f=q('[data-hsp-form="'+kind+'"]');if(!f)return;discard(kind);for(const[name,value]of Object.entries(values)){const n=f.elements.namedItem(name);if(n){if(n.type==="checkbox")n.checked=value;else n.value=value??"";}}f.dataset.revision=String(state[{calendar:"calendar",task:"tasks",question:"bank"}[kind]]?.revision||bank?.revision||0);saveDraft(f);f.querySelector("input:not([type=hidden]),textarea")?.focus();}
    function schedule(){clearTimeout(clock);clock=0;if(!alive||document.hidden||!host.getClientRects().length||!["chat","cards","quiz"].includes(tab))return;clock=setTimeout(async()=>{try{if(!busy){if(tab==="chat"&&state.policy.chatEnabled)await chatLoad();if(tab==="cards"&&followCards&&!host.contains(document.activeElement)){const d=await api("campus-get");if(alive){if(d.campus.liveCards.revision>=state.liveCards.revision)state.liveCards=d.campus.liveCards;if(d.campus.cards.revision>=state.cards.revision)state.cards=d.campus.cards;render();}}}}catch(e){status("Đồng bộ tạm dừng: "+e.message,true);}finally{schedule();}},8000);}
    on(host,"input",e=>{const f=e.target.closest("form[data-hsp-form]");if(f)saveDraft(f);});
    on(host,"change",e=>{if(e.target.dataset.hspTaskStatus)run(async()=>{await api("campus-task-status",{taskId:e.target.dataset.hspTaskStatus,status:e.target.value,revision:state.tasks.revision});await load();status("Đã lưu trên backend và tải lại bản đã lưu.");});if(e.target.hasAttribute("data-hsp-follow-cards")){followCards=e.target.checked;render();}});
    on(host,"dragstart",e=>{const card=e.target.closest("[data-task]");if(card?.getAttribute("draggable")==="true")e.dataTransfer.setData("text/plain",card.dataset.task);});
    on(host,"dragover",e=>{if(e.target.closest("[data-hsp-drop]"))e.preventDefault();});
    on(host,"drop",e=>{const target=e.target.closest("[data-hsp-drop]");if(!target)return;e.preventDefault();const id=e.dataTransfer.getData("text/plain");if(!state.tasks.items.some(t=>t.id===id))return;run(async()=>{await api("campus-task-status",{taskId:id,status:target.dataset.hspDrop,revision:state.tasks.revision});await load();});});
    on(host,"click",e=>{
      e.stopPropagation();
      const b=e.target.closest("[data-hsp-action]");if(!b)return;const action=b.dataset.hspAction,id=b.dataset.id;
      if(action==="tab"){tab=b.dataset.tab;render();if(tab==="chat"&&state.policy.chatEnabled)run(chatLoad);return;}
      if(action==="discard"){discard(b.dataset.kind);if(b.dataset.kind==="answers")renderQuiz();else render();status("Đã bỏ bản nháp riêng; dữ liệu lớp không đổi.");return;}
      if(action==="export-draft"){const value=localStorage.getItem(prefix+b.dataset.kind);if(value)download(value,"HH-Campus-draft.json","application/json");else status("Chưa có bản nháp.");return;}
      if(action==="document"){o.document(id);return;}
      if(action==="calendar-view"){view=b.dataset.view;offset=0;render();return;}
      if(action==="calendar-prev"||action==="calendar-next"){offset+=action==="calendar-next"?1:-1;render();return;}
      if(action==="ics"){download(core.ics(state.calendar.events),"HH-Class-calendar.ics","text/calendar;charset=utf-8");return;}
      if(action==="edit-event"){const x=state.calendar.events.find(x=>x.id===id);edit("calendar",{...x,eventId:x.id,exceptions:x.exceptions.map(e=>e.date+" | "+(e.cancelled?"hủy":e.localStart)).join("\n")});return;}
      if(action==="edit-task"){const t=state.tasks.items.find(t=>t.id===id);edit("task",{...t,taskId:t.id,due:t.due?new Date(new Date(t.due)-new Date(t.due).getTimezoneOffset()*60000).toISOString().slice(0,16):""});return;}
      if(action==="edit-question"){const x=bank.questions.find(x=>x.id===id);edit("question",{...x,questionId:x.id,options:x.options.join("\n"),answer:x.type==="short"?x.answer:x.answer+1});return;}
      if(["card-prev","card-next","card-flip","select-card"].includes(action)){followCards=false;flipped=action==="card-flip"?!flipped:false;cardIndex=action==="select-card"?Number(b.dataset.index):action==="card-prev"?(cardIndex+state.cards.cards.length-1)%Math.max(1,state.cards.cards.length):action==="card-next"?(cardIndex+1)%Math.max(1,state.cards.cards.length):cardIndex;render();return;}
      if(action==="reply"){if(!state.policy.chatEnabled){status("Lớp đang tắt lưu tin mới.");return;}replyTo=id;q("[data-hsp-reply]").textContent="Trả lời: "+messages.find(m=>m.id===id)?.text;q('[data-hsp-form="message"] textarea').focus();return;}
      if(action==="resource"){if(cls.documents.some(d=>d.id===id))o.document(id);else{tab="tasks";render();q('[data-task="'+CSS.escape(id)+'"]')?.scrollIntoView({block:"nearest"});}return;}
      run(async()=>{
        if(action==="refresh"){await load();if(tab==="quiz"&&quiz)await quizLoad(quiz.quiz.id);}
        if(action==="bank"){const d=await api("campus-bank");bank=d.bank;render();status("Ngân hàng chỉ trả đáp án cho người quản lý.");}
        if(action==="quiz")await quizLoad(id);
        if(action.startsWith("quiz-")&&["open","close","reveal","delete"].includes(action.slice(5))){const id=quiz.quiz.id;await api("campus-quiz-state",{quizId:id,revision:quiz.quiz.revision,mode:action.slice(5)});if(action==="quiz-delete")quiz=null;await load();if(quiz)await quizLoad(id);}
        if(action==="grade"){await api("campus-grade",{quizId:quiz.quiz.id,userId:b.dataset.user,questionId:b.dataset.question,points:Number(b.dataset.points),revision:Number(b.dataset.revision)});await quizLoad(quiz.quiz.id);}
        if(action==="delete-event"){await api("campus-calendar",{mode:"delete",eventId:id,revision:state.calendar.revision});await load();}
        if(action==="delete-task"){await api("campus-task",{mode:"delete",taskId:id,revision:state.tasks.revision});await load();}
        if(action==="delete-question"){const d=await api("campus-bank-save",{mode:"delete",questionId:id,revision:bank.revision});bank=d.field;await load();}
        if(action==="delete-card"){await api("campus-card",{mode:"delete",cardId:id,revision:state.cards.revision});await load();}
        if(action==="delete-post"){await api("campus-announcement",{mode:"delete",postId:id,revision:state.announcements.revision});await load();}
        if(["card-lead","card-reveal","card-stop"].includes(action)){const card=state.cards.cards[cardIndex];if(!card&&action!=="card-stop")throw Error("Chưa có thẻ.");await api("campus-live-card",{cardId:action==="card-stop"?null:action==="card-reveal"?state.liveCards.cardId:card.id,revealed:action==="card-reveal"?!state.liveCards.revealed:false,revision:state.liveCards.revision});await load();}
        if(action==="load-chat")await chatLoad();
        if(action==="export-chat"){await chatLoad();download(JSON.stringify(messages,null,2),"HH-Class-chat.json","application/json");}
        if(["reaction","pin-message","delete-message"].includes(action)){await api("campus-chat-moderate",{messageId:id,mode:{reaction:"reaction","pin-message":"pin","delete-message":"delete"}[action],emoji:b.dataset.emoji,pinned:b.dataset.pinned==="true"});await chatLoad();}
        if(action==="clear-chat"){if(!q("[data-hsp-clear-confirm]").checked)throw Error("Cần xác nhận đã xuất dữ liệu cần giữ.");await api("campus-chat-clear",{confirm:true});await chatLoad();}
      });
    });
    on(host,"submit",e=>{
      const f=e.target;if(!f.dataset.hspForm)return;e.preventDefault();e.stopPropagation();const kind=f.dataset.hspForm,v=Object.fromEntries(new FormData(f));saveDraft(f);
      run(async()=>{
        const rev=revision(f);
        if(kind==="calendar"){const exceptions=v.exceptions.split(/\r?\n/).map(s=>s.trim()).filter(Boolean).map(line=>{const[date,time]=line.split("|").map(s=>s.trim());return {date,cancelled:time==="hủy",...(time!=="hủy"?{localStart:time}: {})};});await api("campus-calendar",{eventId:v.eventId||undefined,revision:rev,event:{...v,minutes:Number(v.minutes),cancelled:f.elements.cancelled.checked,exceptions}});}
        if(kind==="task")await api("campus-task",{taskId:v.taskId||undefined,revision:rev,task:{...v,due:v.due?new Date(v.due).toISOString():null}});
        if(kind==="notes")await api("campus-notes",{text:v.text,revision:rev});
        if(kind==="question"){if(!bank)throw Error("Tải ngân hàng trước khi lưu câu.");const d=await api("campus-bank-save",{questionId:v.questionId||undefined,revision:rev,question:{...v,options:v.options.split(/\r?\n/).map(s=>s.trim()).filter(Boolean),answer:v.type==="short"?v.answer:Number(v.answer)-1}});bank=d.field;}
        if(kind==="new-quiz"){await api("campus-quiz-create",{title:v.title,minutes:Number(v.minutes),questionIds:v.questionIds.split(/\r?\n/).map(s=>s.trim()).filter(Boolean)});}
        if(kind==="answers"){const answers=quiz.quiz.questions.map(x=>({id:x.id,value:x.type==="short"?v[x.id]:Number(v[x.id])}));await api("campus-submit",{quizId:quiz.quiz.id,answers});discard(kind);await quizLoad(quiz.quiz.id);status("Bài đã nộp vào backend, điểm chỉ hiện sau khi được công bố.");return;}
        if(kind==="card")await api("campus-card",{front:v.front,back:v.back,revision:rev});
        if(kind==="news")await api("campus-announcement",{title:v.title,text:v.text,revision:rev});
        if(kind==="chat-policy")await api("campus-chat-policy",{enabled:f.elements.enabled.checked,days:Number(v.days),revision:rev});
        if(kind==="message"){await api("campus-chat-send",{text:v.text,replyTo,resourceId:v.resourceId||null});replyTo=null;discard(kind);f.reset();q("[data-hsp-reply]").textContent="";await chatLoad();status("Tin đã lưu theo thời hạn lớp.");return;}
        discard(kind);await load();status("Đã lưu trên backend và tải lại bản đã lưu.");
      });
    });
    on(document,"visibilitychange",schedule);const observer=root.IntersectionObserver?new root.IntersectionObserver(schedule):{observe(){},disconnect(){}};observer.observe(host);run(load);
    return {refresh:()=>run(load),destroy(){alive=false;clearTimeout(clock);observer.disconnect();listeners.forEach(off=>off());urls.forEach(url=>URL.revokeObjectURL(url));host.replaceChildren();}};
  }
  root.HHStudyCampus=Object.freeze({mount});
})(window);
