const CACHE = "hh-identity-portal-v217";
// Compatibility aliases are kept as documentation for clients upgrading from the
// previous route loader. They are not fetched; RUNTIME_ASSETS below is canonical.
// communication-suite.css?v=1 communication-suite.js?v=1 communication-command-center.css?v=1 communication-command-center.js?v=1 communication-messenger-next.css?v=1 communication-messenger-next.js?v=1 communication-channels-forum.css?v=1 communication-channels-forum.js?v=1 communication-live-room.css?v=1 communication-live-room.js?v=1 communication-canvas-automation.css?v=1 communication-canvas-automation.js?v=1 communication-intelligence.css?v=1 communication-intelligence.js?v=1
// learning-suite.css?v=2 learning-home.css?v=2 learning-paths.css?v=2 learning-review.css?v=2 learning-lesson-player.css?v=2 learning-coach-labs.css?v=2 learning-classroom.css?v=2 learning-platform-core.js?v=2 learning-home.js?v=2 learning-paths.js?v=2 learning-review.js?v=2 learning-lesson-player.js?v=2 learning-coach-labs.js?v=2 learning-classroom.js?v=2 learning-suite.js?v=2
const RUNTIME_ASSETS = [
  "./",
  "./index.html",
  "./app-shell.css?v=51",
  "./dashboard-aurora.css?v=3",
  "./command-center-pro.css?v=4",
  "./home-daily-command.css?v=4",
  "./home-command-search.css?v=2",
  "./home-widget-project-pulse.css?v=2",
  "./home-health-focus.css?v=2",
  "./professional-tools.css?v=3",
  "./dev-pro-suite.css?v=1",
  "./dev-delivery-workflow.css?v=2",
  "./dev-smart-recipe.css?v=1",
  "./dev-api-studio.css?v=1",
  "./dev-data-security.css?v=1",
  "./dev-regex-database.css?v=1",
  "./dev-code-git.css?v=1",
  "./dev-diagnostics-ai.css?v=1",
  "./feature-lab.css?v=5",
  "./platform-tools.css?v=1",
  "./tool-workspace-pro.css?v=1",
  "./utility-lab-tools.css?v=9",
  "./media-design-pro.css?v=1",
  "./media-design-page.css?v=9",
  "./media-production-workflow.css?v=2",
  "./universal-media-project.css?v=1",
  "./media-design-advanced.css?v=3",
  "./media-design-publish.css?v=1",
  "./video-editor-studio.css?v=2",
  "./video-editor-resolve.css?v=6",
  "./photo-editor-pro.css?v=4",
  "./editor-workflow-pro.css?v=1",
  "./support-platform.css?v=9",
  "./script.js?v=130",
  "./graphic-design-studio.css?v=6",
  "./graphic-design-animation.js?v=1",
  "./graphic-design-3d.js?v=2",
  "./graphic-design-prototype.js?v=1",
  "./graphic-design-motion.js?v=1",
  "./graphic-design-quick-motion.js?v=1",
  "./graphic-design-mockup.js?v=1",
  "./graphic-design-character.js?v=1",
  "./graphic-design-vector-core.js?v=2",
  "./graphic-design-state-machine.js?v=2",
  "./graphic-design-adaptive.js?v=2",
  "./graphic-design-project-store.js?v=2",
  "./graphic-design-collaboration.js?v=2",
  "./graphic-design-dev-ai.js?v=2",
  "./graphic-design-composer.js?v=2",
  "./graphic-design-nondestructive.js?v=1",
  "./graphic-design-typography-pro.js?v=1",
  "./graphic-design-node-effects.js?v=1",
  "./graphic-design-character-pro.js?v=1",
  "./graphic-design-simulation.js?v=1",
  "./graphic-design-data-driven.js?v=1",
  "./graphic-design-components.js?v=2",
  "./graphic-design-color-pro.js?v=1",
  "./graphic-design-export-center.js?v=2",
  "./graphic-design-plugins.js?v=1",
  "./graphic-design-review.js?v=2",
  "./graphic-design-performance.js?v=1",
  "./graphic-design-workflow.js?v=2",
  "./graphic-design-studio.js?v=6",
  "./vendor/three.module.min.js",
  "./vendor/three.core.min.js",
  "./music-ai-studio.css?v=6",
  "./music-ai-apps.css?v=2",
  "./youtube-publisher.css?v=2",
  "./youtube-publisher.js?v=2",
  "./music-production-suite.css?v=1",
  "./music-daw-workspace.css?v=1",
  "./music-composer-lyrics.css?v=1",
  "./music-audio-labs.css?v=1",
  "./music-mix-master.css?v=1",
  "./music-visual-studio.css?v=1",
  "./music-publishing-rights.css?v=1",
  "./music-intelligence-engine.css?v=1",
  "./music-generative-arrangement.css?v=1",
  "./music-adaptive-library.css?v=1",
  "./music-mix-performance.css?v=1",
  "./music-project-governance.css?v=1",
  "./music-daw-workspace.js?v=1",
  "./music-composer-lyrics.js?v=1",
  "./music-audio-labs.js?v=1",
  "./music-mix-master.js?v=1",
  "./music-visual-studio.js?v=1",
  "./music-publishing-rights.js?v=1",
  "./music-intelligence-engine.js?v=1",
  "./music-generative-arrangement.js?v=1",
  "./music-adaptive-library.js?v=1",
  "./music-mix-performance.js?v=1",
  "./music-project-governance.js?v=1",
  "./music-production-suite.js?v=1",
  "./music-ai-apps.js?v=2",
  "./music-ai-studio.js?v=8",
  "./dashboard-aurora.js?v=3",
  "./command-center-pro.js?v=5",
  "./home-daily-command.js?v=5",
  "./home-command-search.js?v=2",
  "./home-widget-project-pulse.js?v=2",
  "./home-health-focus.js?v=2",
  "./extension-suite.css?v=1",
  "./auth-experience.css?v=6",
  "./auth-neon-gateway.css?v=5",
  "./auth-living-background.css?v=1",
  "./auth-spatial-aurora.css?v=1",
  "./auth-identity-constellation.css?v=1",
  "./auth-creative-universe.css?v=5",
  "./auth-universe-memory.css?v=1",
  "./auth-logo-motion.css?v=1",
  "./auth-emotional-logo.css?v=1",
  "./auth-form-motion.css?v=4",
  "./auth-quantum-flow.css?v=1",
  "./auth-transition-runtime.css?v=2",
  "./auth-trust-director.css?v=1",
  "./auth-cosmic-prism-background.css?v=2",
  "./auth-cosmic-prism-form.css?v=2",
  "./auth-cosmic-prism-interactions.css?v=2",
  "./auth-zoom-resilience.css?v=3",
  "./auth-typography-unified.css?v=2",
  "./assets/hh-neon-logo-v2.png?v=3",
  "./auth-platform.js?v=11",
  "./auth-experience.js?v=8",
  "./auth-neon-gateway.js?v=3",
  "./auth-living-background.js?v=1",
  "./auth-spatial-aurora.js?v=1",
  "./auth-identity-constellation.js?v=2",
  "./auth-creative-universe.js?v=5",
  "./auth-universe-memory.js?v=2",
  "./auth-logo-motion.js?v=1",
  "./auth-emotional-logo.js?v=1",
  "./auth-form-motion.js?v=3",
  "./auth-transition-runtime.js?v=2",
  "./auth-quantum-flow.js?v=2",
  "./auth-trust-director.js?v=2",
  "./auth-cosmic-prism-background.js?v=2",
  "./auth-cosmic-prism-form.js?v=2",
  "./auth-cosmic-prism-interactions.js?v=2",
  "./auth-zoom-resilience.js?v=4",
  "./search-watch-center.css?v=5",
  "./search-watch-center.js?v=7",
  "./youtube-pip.html",
  "./communication-overview.css?v=1",
  "./communication-overview.js?v=2",
  "./communication-suite.css?v=2",
  "./communication-workspace-fix.css?v=1",
  "./communication-suite.js?v=2",
  "./communication-command-center.css?v=1",
  "./communication-command-center.js?v=2",
  "./communication-messenger-next.css?v=2",
  "./communication-messenger-next.js?v=2",
  "./communication-channels-forum.css?v=1",
  "./communication-channels-forum.js?v=2",
  "./communication-live-room.css?v=1",
  "./communication-live-room.js?v=1",
  "./communication-canvas-automation.css?v=1",
  "./communication-canvas-automation.js?v=1",
  "./communication-intelligence.css?v=3",
  "./communication-intelligence.js?v=3",
  "./work-center.css?v=3",
  "./work-center.js?v=3",
  "./download-center-pro.css?v=1",
  "./team-collaboration-pro.css?v=2",
  "./team-collaboration-pro.js?v=2",
  "./creative-suite.css?v=6",
  "./ai-center-pro.css?v=1",
  "./ai-center-advanced.css?v=1",
  "./ai-center-advanced.js?v=1",
  "./platform-p0.css?v=1",
  "./platform-p0.js?v=1",
  "./platform-orchestrator.js?v=2",
  "./platform-module-bridge.js?v=2",
  "./system-platform.css?v=1",
  "./system-platform.js?v=3",
  "./sidebar-navigation-pro.css?v=5",
  "./game-runtime.css?v=1",
  "./space-explorer.css?v=4",
  "./game-center.css?v=4",
  "./astra-universe-expansion.css?v=4",
  "./game-arcade.css?v=4",
  "./learning-suite.css?v=3",
  "./learning-home.css?v=2",
  "./learning-paths.css?v=3",
  "./learning-review.css?v=3",
  "./learning-lesson-player.css?v=2",
  "./learning-coach-labs.css?v=3",
  "./learning-classroom.css?v=3",
  "./english-learning.css?v=11",
  "./english-voice-coach.css?v=4",
  "./community-social-pro.css?v=3",
  "./community-social-pro.js?v=4",
  "./community-platform-v2.css?v=10",
  "./community-platform-v2.js?v=12",
  "./community-messenger-pro.css?v=1",
  "./community-calls.js?v=1",
  "./community-admin.css?v=6",
  "./community-admin.js?v=8",
  "./insights-pro.css?v=2",
  "./privacy-consent-center.css?v=2",
  "./auth-login-repair.css?v=2",
  "./motion-comfort.css?v=1",
  "./insights-pro.js?v=6",
  "./privacy-consent-center.js?v=2",
  "./creative-suite.js?v=7",
  "./creative-os.css?v=1",
  "./creative-os.js?v=3",
  "./creative-os-core.js?v=1",
  "./creative-command-center.css?v=2",
  "./creative-command-center.js?v=2",
  "./creative-preproduction.css?v=1",
  "./creative-preproduction.js?v=1",
  "./creative-ai-workflow.css?v=3",
  "./creative-ai-workflow.js?v=3",
  "./creative-production-lab.css?v=1",
  "./creative-production-lab.js?v=1",
  "./creative-collaboration-os.css?v=1",
  "./creative-collaboration-os.js?v=1",
  "./creative-publishing.css?v=1",
  "./creative-publishing.js?v=1",
  "./creative-marketplace.css?v=1",
  "./creative-marketplace.js?v=1",
  "./extension-suite.js?v=2",
  "./professional-tools.js?v=4",
  "./dev-smart-recipe.js?v=1",
  "./dev-api-studio.js?v=1",
  "./dev-data-security.js?v=1",
  "./dev-regex-database.js?v=1",
  "./dev-code-git.js?v=1",
  "./dev-diagnostics-ai.js?v=1",
  "./dev-pro-suite.js?v=2",
  "./dev-delivery-workflow.js?v=2",
  "./media-design-studio.js?v=1",
  "./media-design-pro.js?v=2",
  "./media-design-advanced.js?v=3",
  "./media-design-publish.js?v=1",
  "./video-editor-studio.js?v=2",
  "./video-editor-resolve.js?v=7",
  "./photo-editor-pro.js?v=3",
  "./universal-media-project.js?v=1",
  "./media-production-workflow.js?v=2",
  "./editor-workflow-pro.js?v=1",
  "./support-platform.js?v=13",
  "./media-design-page.js?v=9",
  "./tool-manifests.js?v=1",
  "./tool-runtime.js?v=1",
  "./feature-lab.js?v=6",
  "./platform-tools.js?v=1",
  "./tool-workspace-pro.js?v=1",
  "./utility-lab-tools.js?v=9",
  "./feature-engines.js?v=2",
  "./game-platform-adapters.js?v=1",
  "./game-runtime.js?v=1",
  "./space-explorer.js?v=4",
  "./game-center.js?v=4",
  "./astra-universe-expansion.js?v=4",
  "./game-arcade.js?v=4",
  "./learning-platform-core.js?v=5",
  "./learning-home.js?v=2",
  "./learning-paths.js?v=3",
  "./learning-review.js?v=3",
  "./learning-lesson-player.js?v=2",
  "./learning-coach-labs.js?v=3",
  "./learning-classroom.js?v=4",
  "./learning-suite.js?v=3",
  "./english-curriculum.js?v=1",
  "./english-career-expansion.js?v=1",
  "./english-career-curriculum.js?v=2",
  "./english-learning.js?v=16",
  "./config.js?v=8",
  "./data/ai-super-platform-modules.json"
];
const CORE = [
  "./",
  "./index.html",
  "./app-shell.css?v=51",
  "./sidebar-navigation-pro.css?v=5",
  "./auth-experience.css?v=6",
  "./auth-neon-gateway.css?v=5",
  "./auth-zoom-resilience.css?v=3",
  "./auth-typography-unified.css?v=2",
  "./privacy-consent-center.css?v=2",
  "./motion-comfort.css?v=1",
  "./assets/hh-neon-logo-v2.png?v=3",
  "./config.js?v=8",
  "./platform-orchestrator.js?v=2",
  "./platform-module-bridge.js?v=2",
  "./performance-loader.js?v=17",
  "./auth-platform.js?v=11",
  "./auth-neon-gateway.js?v=3",
  "./script.js?v=130"
];
self.addEventListener("install", event => event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(CORE)).then(() => self.skipWaiting())));
self.addEventListener("activate", event => event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim())));
self.addEventListener("fetch", event => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  const isPrivateRequest = url.pathname.startsWith("/api/") || request.headers.has("authorization");
  if (url.origin !== self.location.origin || isPrivateRequest) {
    event.respondWith(fetch(request));
    return;
  }

  if (request.mode === "navigate") {
    event.respondWith(fetch(request).then(response => {
      if (response.ok && response.type === "basic") {
        const copy = response.clone();
        event.waitUntil(caches.open(CACHE).then(cache => cache.put("./index.html", copy)));
      }
      return response;
    }).catch(() => caches.match("./index.html")));
    return;
  }

  event.respondWith(caches.match(request).then(cached => {
    const refresh = fetch(request).then(response => {
      if (response.ok && response.type === "basic") {
        const copy = response.clone();
        event.waitUntil(caches.open(CACHE).then(cache => cache.put(request, copy)));
      }
      return response;
    });
    if (cached) {
      event.waitUntil(refresh.catch(() => undefined));
      return cached;
    }
    return refresh.catch(() => Response.error());
  }));
});
