const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");

test("Solar Secret stays isolated to the login sun", () => {
  const script = read("auth-solar-secret.js");
  const css = read("auth-solar-secret.css");
  const html = read("index.html");
  assert.match(script, /#authGate/);
  assert.match(script, /data-solar-sun-hit/);
  assert.match(script, /data-solar-trigger/);
  assert.match(script, /data-solar-continue/);
  assert.match(script, /data-solar-stop/);
  assert.match(script, /data-solar-choice/);
  assert.match(script, /data-solar-puzzle/);
  assert.match(script, /data-puzzle-token/);
  assert.match(script, /data-solar-auto-solve/);
  assert.match(script, /data-solar-journal/);
  assert.match(script, /data-solar-sound/);
  assert.match(script, /data-solar-volume/);
  assert.match(script, /data-solar-progressbar/);
  assert.match(script, /data-solar-summary/);
  assert.match(script, /data-solar-reset/);
  assert.match(script, /data-solar-replay/);
  assert.match(script, /getProgress/);
  assert.match(script, /pointerdown|holdMs/);
  assert.match(script, /pointerenter|is-hovering/);
  assert.match(script, /hh:auth-solar-secret/);
  assert.match(script, /window\.addEventListener\("hh:auth-change"/);
  assert.match(script, /pagehide|AbortController/);
  const stages = script.match(/const STAGES = Object\.freeze\(\[([\s\S]*?)\]\.map\(Object\.freeze\)\);/);
  assert.ok(stages);
  assert.equal((stages[1].match(/kind:\s*"/g) || []).length, 21, "the trail needs one idle state plus twenty playable stages");
  assert.match(script, /STAGE_COUNT\s*=\s*20/);
  assert.match(script, /kind:\s*"puzzle"/);
  assert.match(script, /kind:\s*"choice"/);
  assert.match(script, /kind:\s*"ending"/);
  assert.match(script, /kind:\s*"summary"/);
  assert.match(script, /portal:\s*Object\.freeze/);
  assert.match(script, /orbit:\s*Object\.freeze/);
  assert.match(script, /ufo:\s*Object\.freeze/);
  assert.match(script, /sleep:\s*Object\.freeze/);
  assert.match(script, /merge:\s*Object\.freeze/);
  assert.match(script, /dragstart|dataTransfer/);
  assert.match(script, /ArrowLeft|ArrowRight/);
  assert.match(script, /visibilitychange/);
  assert.match(css, /pointer-events:\s*none/);
  assert.match(css, /prefers-reduced-motion:\s*reduce/);
  assert.match(css, /prefers-contrast:\s*more/);
  assert.match(css, /forced-colors:\s*active/);
  assert.match(css, /hh-solar-ufo/);
  assert.match(css, /hh-solar-meteor/);
  assert.match(css, /hh-solar-eclipse/);
  assert.match(css, /hh-solar-secret__puzzle/);
  assert.match(css, /hh-solar-secret__journal/);
  assert.match(css, /hh-solar-red-alert/);
  assert.match(script, /hh:solar-resonance-stage/);
  assert.match(script, /hh:solar-resonance-preview/);
  assert.match(script, /hh:solar-resonance-reset/);
  assert.match(script, /captureGalaxyState|restoreGalaxyState/);
  assert.match(script, /pointerover[\s\S]*previewBranch/);
  assert.match(css, /hh-solar-resonance-fx/);
  assert.match(html, /auth-solar-secret\.css\?v=8/);
  assert.match(html, /auth-solar-secret\.js\?v=6/);
});

test("Solar Secret uses inline confirmation, local progress and opt-in procedural sound", () => {
  const source = `${read("auth-solar-secret.js")}\n${read("auth-solar-secret.css")}`;
  assert.match(source, /Bạn thực sự muốn tiếp tục/);
  assert.doesNotMatch(source, /(?:window\.)?(?:alert|prompt|confirm)\s*\(/);
  assert.match(source, /hh\.solar-secret\.progress\.v3/);
  assert.match(source, /replayCount|lastDiscovered|storageAvailable/);
  assert.doesNotMatch(source, /fetch\s*\(|XMLHttpRequest|WebSocket/);
  assert.match(source, /window\.AudioContext|window\.webkitAudioContext/);
  assert.match(source, /soundEnabled\s*=\s*false/);
  assert.doesNotMatch(source, /new\s+Audio\s*\(|\.play\s*\(/);
  assert.match(source, /Escape|keydown/);
});
