const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function harness(){let user={_id:'user-a'},rows=[],audits=[];const match=(row,q)=>Object.entries(q).every(([k,v])=>v&&typeof v==='object'&&'$exists'in v?(row[k]!==undefined)===v.$exists:row[k]===v);
  const collection={createIndex:async()=>{},findOne:async q=>{const row=rows.find(r=>match(r,q));return row?structuredClone(row):null;},updateOne:async(q,u,o)=>{let row=rows.find(r=>match(r,q));if(!row&&o.upsert){if(rows.some(r=>r.ownerId===q.ownerId&&r.learnerProfileId===q.learnerProfileId))throw Object.assign(Error('duplicate'),{code:11000});row={...u.$setOnInsert};rows.push(row);}if(!row)return{matchedCount:0};Object.assign(row,u.$set);return{matchedCount:1};},deleteOne:async q=>{const index=rows.findIndex(r=>match(r,q));if(index<0)return{deletedCount:0};rows.splice(index,1);return{deletedCount:1};}};
  const db={collection:name=>name==='englishLearningStates'?collection:{createIndex:async()=>{},insertOne:async v=>audits.push(v)}};
  const platform={clean:(v,n)=>String(v??'').slice(0,n),currentUser:async()=>user,enforceRateLimit:async()=>{},withApi:async(req,res,fn)=>{try{return await fn({db,body:req.body||{}});}catch(e){return res.status(e.statusCode||500).json({error:e.message,code:e.code});}}};
  const module={exports:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../services/englishLearningSync'),'utf8'),{module,Buffer,Date,require:p=>p==='../utils/platform'?platform:require(p)});
  async function call(method,body={},query={},headers={}){const response={statusCode:200,status(n){this.statusCode=n;return this;},json(data){this.data=JSON.parse(JSON.stringify(data));return this;},setHeader(){}};await module.exports({method,body,query,headers},response);return response;}
  return{call,rows,setUser:u=>user=u};
}
const state=()=>({version:1,learnerProfileId:'default',writingDraft:'A',ownerId:'attacker',settings:{apiKey:'never persist'}});
test('actual endpoint CAS is account/profile scoped, idempotent and rejects reused mutation content',async()=>{const h=harness(),a=await h.call('PUT',{state:state(),revision:0,clientMutationId:'first'},{action:'sync'});assert.equal(a.statusCode,200);assert.equal(a.data.revision,1);assert.equal(h.rows[0].ownerId,'user-a');assert.equal(h.rows[0].state.ownerId,undefined);assert.equal(h.rows[0].state.settings.apiKey,undefined);assert.equal((await h.call('PUT',{state:state(),revision:0,clientMutationId:'first'},{action:'sync'})).data.duplicate,true);assert.equal((await h.call('PUT',{state:{...state(),writingDraft:'B'},revision:1,clientMutationId:'first'},{action:'sync'})).data.code,'LEARNING_MUTATION_REUSED');assert.equal((await h.call('PUT',{state:state(),revision:0,clientMutationId:'second'},{action:'sync'})).statusCode,409);h.setUser({_id:'user-b'});assert.equal((await h.call('GET')).statusCode,404);assert.equal((await h.call('GET',{}, {},{'x-hh-learner-owner':'user-a'})).statusCode,403);});
test('simultaneous first saves have one winner instead of overwriting initial state',async()=>{const h=harness(),results=await Promise.all(['one','two'].map(clientMutationId=>h.call('PUT',{state:{...state(),writingDraft:clientMutationId},revision:0,clientMutationId},{action:'sync'})));assert.deepEqual(results.map(r=>r.statusCode).sort(),[200,409]);assert.equal(h.rows.length,1);assert.equal(h.rows[0].revision,1);});
test('invalid revision, restricted/unauthenticated users and long profiles are rejected; delete supports 72 chars',async()=>{const h=harness();for(const revision of [-1,1.5,'0',null])assert.equal((await h.call('PUT',{state:state(),revision,clientMutationId:'x'},{action:'sync'})).statusCode,400);assert.equal((await h.call('GET',{}, {learnerProfileId:'x'.repeat(73)})).statusCode,400);h.setUser(null);assert.equal((await h.call('GET')).statusCode,401);h.setUser({_id:'a',restrictedFeatures:['english']});assert.equal((await h.call('GET')).statusCode,403);h.setUser({_id:'a'});const profile='a'.repeat(72);assert.equal((await h.call('PUT',{state:state(),learnerProfileId:profile,revision:0,clientMutationId:'long'},{action:'sync'})).statusCode,200);assert.equal((await h.call('DELETE',{}, {learnerProfileId:profile},{'x-hh-confirm-delete':profile})).data.deleted,true);});
