const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");

test("login mounts a real WebGL living galaxy without replacing authentication", () => {
  const html = read("index.html");
  const gateway = read("auth-neon-gateway.js");
  const runtime = read("auth-living-galaxy-3d.js");
  const css = read("auth-living-galaxy-3d.css");

  assert.match(html, /auth-living-galaxy-3d\.css\?v=11/);
  assert.match(gateway, /auth-living-galaxy-3d\.js\?v=16/);
  assert.match(gateway, /high:\s*"Điện ảnh"/);
  assert.match(gateway, /soft:\s*"Cân bằng"/);
  assert.match(gateway, /off:\s*"Tĩnh"/);
  assert.match(runtime, /import\(THREE_URL\)/);
  assert.match(runtime, /new THREE\.WebGLRenderer/);
  assert.match(runtime, /THREE\.ACESFilmicToneMapping/);
  assert.match(runtime, /new THREE\.PointLight/);
  assert.match(runtime, /new THREE\.MeshStandardMaterial/);
  assert.match(runtime, /THREE\.AdditiveBlending/);
  assert.match(runtime, /new THREE\.FogExp2/);
  assert.match(runtime, /routeUsage/);
  assert.match(runtime, /realSignals/);
  assert.match(runtime, /prefers-reduced-motion/);
  assert.match(runtime, /saveData/);
  assert.match(runtime, /visibilitychange/);
  assert.match(runtime, /hh-living-warp/);
  assert.match(runtime, /createOrbitMaterial/);
  assert.match(runtime, /new THREE\.ShaderMaterial/);
  assert.match(runtime, /vFront/);
  assert.match(runtime, /const tilt = new THREE\.Euler/);
  assert.match(runtime, /planet\.energy\.forEach/);
  assert.match(runtime, /detailLimit = currentMode === "cinematic" \? 11 : 6/);
  assert.match(runtime, /makePlanetSurface/);
  assert.match(runtime, /button\.dataset\.hhModel/);
  assert.match(runtime, /button\.dataset\.hhWeight/);
  assert.match(runtime, /bumpMap:\s*surface\.bumpMap/);
  assert.match(runtime, /new THREE\.RingGeometry/);
  assert.match(runtime, /createAtmosphereMaterial/);
  assert.match(runtime, /createSunSurfaceMaterial/);
  assert.match(runtime, /createSolarCorona/);
  assert.doesNotMatch(runtime, /makeHTexture|fillText\("H"/);
  assert.doesNotMatch(runtime, /core\.textContent\s*=\s*"H"|hh-living-galaxy-core/);
  assert.match(runtime, /createAsteroidBelt/);
  assert.match(runtime, /planet\.clouds/);
  assert.match(runtime, /planet\.moonPivots/);
  assert.match(runtime, /orbitMaterial\.uniforms\.uOpacity/);
  assert.match(runtime, /spawnMeteor/);
  for (const layer of ["far", "mid", "near"]) assert.match(runtime, new RegExp(`${layer}: \\{ z:`));
  for (const color of ["#62e8ff", "#b36dff", "#ff65c8", "#ffd86b"]) assert.match(runtime, new RegExp(color, "i"));
  assert.match(runtime, /mode\(\) === "cinematic" \? 3 : 2/);
  assert.match(runtime, /nextShowerAt/);
  assert.match(runtime, /orbitAngle = \(planet\.orbitAngle \+ delta \* planet\.speed \* warpBoost\) % ORBIT_TAU/);
  assert.match(runtime, /particle\.angle = \(particle\.angle \+ delta \* particle\.speed \* warpBoost\) % ORBIT_TAU/);
  assert.match(runtime, /currentMode === "static" \? "0\.00" : "1\.00"/);
  assert.doesNotMatch(runtime, /speedFactor|speedTarget|selectionHoldUntil|pointerInGalaxy|onGalaxyHover|onGalaxyLeave/);
  assert.match(runtime, /warpBoostUntil/);
  assert.match(runtime, /errorPulseUntil/);
  assert.match(runtime, /hh:galaxy-notification/);
  assert.match(runtime, /hh-living-meteor-layer/);
  assert.match(runtime, /spawnDomMeteor/);
  assert.match(css, /hh-living-meteor-flight/);
  assert.match(css, /@media \(max-width: 760px\)/);
  assert.match(css, /scroll-snap-type:\s*x mandatory/);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)/);
  assert.match(html, /data-oauth-provider="google"/);
  assert.match(html, /id="gateLoginForm"/);
  assert.match(html, /data-guest-login/);
});

test("home living galaxy exposes seventeen domains and uses real local progress", () => {
  const runtime = read("home-galaxy-command.js");
  const css = read("home-galaxy-command.css");
  const loader = read("performance-loader.js");

  const block = runtime.match(/const PLANETS = Object\.freeze\(\[([\s\S]*?)\]\);/);
  assert.ok(block);
  assert.equal((block[1].match(/\{\s*id:/g) || []).length, 17);
  assert.match(runtime, /HÔM NAY/);
  assert.match(runtime, /THIÊN HÀ 17 MỤC/);
  assert.match(runtime, /TRUNG TÂM THÔNG TIN/);
  assert.match(runtime, /data-hgc-info-panel="progress"/);
  assert.match(runtime, /class="hgc-dock"/);
  assert.match(runtime, /updateLivingPanels/);
  assert.match(runtime, /hh\.app-shell\.recent/);
  assert.match(runtime, /hh\.communication\.intelligence\.v1/);
  assert.match(runtime, /hh\.learning\.os\.v1/);
  assert.match(runtime, /hh-project-center/);
  assert.match(runtime, /Chỉ hiển thị mục chưa đọc/);
  assert.doesNotMatch(runtime, /Math\.random\(\).*progress|fakeProgress|mockProgress/);
  assert.match(css, /\.hgc-planet--15/);
  assert.match(css, /\.hgc-today/);
  assert.match(css, /\.hgc-constellation/);
  assert.match(css, /\.hgc-dock/);
  assert.match(css, /scroll-snap-type:\s*x mandatory/);
  assert.match(loader, /home-galaxy-command\.css\?v=13/);
  assert.match(loader, /home-galaxy-command\.js\?v=14/);
});
