const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const D=require('../patin-data'),X=require('../patin-learning-data'),C=require('../patin-core'),read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
const memory=()=>{const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};};
const id=D.videos[0].id;
test('24 original additions and 75 publisher videos have unique real skill/source references',()=>{
  assert.equal(X.entries.length,24);assert.equal(D.skills.length,148);assert.equal(D.videos.length,75);assert.equal(new Set(D.videos.map(v=>v.id)).size,75);
  for(const s of X.entries){assert.ok(s.goal&&s.drill&&s.check&&s.mistake);assert.equal(s.reviewedAt,null);assert.ok(s.sources.every(id=>D.sources.some(s=>s.id===id)));}
  for(const v of D.videos){assert.match(v.youtubeId,/^[a-zA-Z0-9_-]{11}$/);assert.equal(new URL(v.sourceUrl).protocol,'https:');assert.ok(v.skillIds.every(id=>D.skills.some(s=>s.id===id)));assert.equal(v.observations.length,3);assert.match(v.rights,/no redistribution license asserted/);assert.equal(v.checkedAt,'2026-10-10');}
  assert.deepEqual([...new Set(D.videos.map(v=>v.publisher))].sort(),['InMoveSkates','Rollerblade','SIKANA English','SkateIA']);
});
test('v1 state missing video tools adds defaults without changing journal, old IDs or schema',()=>{const old=C.blank();delete old.workshop.videos;old.favorites=['fish'];C.setNote(old,'heel-brake','Old');C.addEntry(old,{id:'old-1',date:'2026-10-10',minutes:4,note:'Keep',skills:['fish']});const next=C.validate(old);assert.equal(next.version,1);assert.deepEqual(next.workshop.videos,{version:1,lastVideo:null,favorites:[],records:{},library:require('../patin-video-curriculum').defaults()});assert.equal(next.progress['heel-brake'].note,'Old');assert.deepEqual(next.journal,old.journal);});
test('actual video notes, manual reviewed, bookmarks, last video and timestamps persist and export in account scope',()=>{const storage=memory(),s=C.createStore({id:'video-a'},storage);s.mutate(x=>{C.setVideoNote(x,id,'<script> text','');C.toggleVideoFavorite(x,id);C.setVideoReviewed(x,id,true);C.setLastVideo(x,id);C.setVideoMarker(x,id,44,'Ask coach');C.setVideoMarker(x,id,4,'Earlier');C.setVideoMarker(x,id,44,'Updated');});const back=C.createStore({id:'video-a'},storage);assert.equal(back.getState().workshop.videos.records[id].note,'<script> text');assert.deepEqual(back.getState().workshop.videos.records[id].markers,[{seconds:4,note:'Earlier'},{seconds:44,note:'Updated'}]);assert.equal(back.getState().workshop.videos.lastVideo,id);assert.equal(C.summary(back.getState()).minutes,0);assert.equal(C.summary(back.getState()).read,0);assert.equal(C.createStore({id:'video-b'},storage).getState().workshop.videos.records[id],undefined);assert.deepEqual(C.parse(C.readImport(back.export())),back.getState());back.mutate(x=>C.removeVideoMarker(x,id,44));assert.equal(back.getState().workshop.videos.records[id].markers.length,1);});
test('concurrent note changes reject stale expected text, while independent bookmarks merge',()=>{const storage=memory(),a=C.createStore({id:'video-concurrent'},storage),b=C.createStore({id:'video-concurrent'},storage);a.mutate(s=>C.setVideoNote(s,id,'First',''));assert.throws(()=>b.mutate(s=>C.setVideoNote(s,id,'Stale','')),/tab khác/);b.mutate(s=>C.toggleVideoFavorite(s,id));assert.equal(C.createStore({id:'video-concurrent'},storage).getState().workshop.videos.records[id].note,'First');});
test('unknown IDs, nested versions, overflow notes, marker bounds and duplicates fail atomically',()=>{const storage=memory(),s=C.createStore({id:'video-bounds'},storage);s.mutate(x=>C.setVideoNote(x,id,'Keep',''));for(const fn of [x=>C.setVideoNote(x,'unknown','bad',''),x=>C.setVideoNote(x,id,'x'.repeat(2001),'Keep'),x=>C.setVideoMarker(x,id,-1,'bad'),x=>C.setVideoMarker(x,id,1.5,'bad'),x=>C.setVideoMarker(x,id,86401,'bad'),x=>C.setVideoMarker(x,id,1,'x'.repeat(161)),x=>C.setVideoReviewed(x,id,'true')])assert.throws(()=>s.mutate(fn));assert.equal(s.getState().workshop.videos.records[id].note,'Keep');for(let i=0;i<12;i++)s.mutate(x=>C.setVideoMarker(x,id,i,'M'));assert.throws(()=>s.mutate(x=>C.setVideoMarker(x,id,100,'extra')));const bad=s.getState();bad.workshop.videos.records[id].markers[1].seconds=0;assert.throws(()=>C.validate(bad));assert.throws(()=>C.validate({...bad,workshop:{...bad.workshop,videos:{version:9}}}));});
test('quota/denied storage stays truthful and only retains scoped pending video drafts',()=>{const s=C.createStore({id:'video-no-storage'},null);assert.equal(s.mutate(x=>C.setVideoNote(x,id,'Unsaved','')),false);assert.equal(s.getStatus().pending,true);assert.equal(C.createStore({id:'video-no-storage'},null).getState().workshop.videos.records[id].note,'Unsaved');assert.equal(C.createStore({id:'another-video-no-storage'},null).getState().workshop.videos.records[id],undefined);});
test('video fields are whitelist-cleaned; private local files, tokens and secrets never enter export',()=>{const state=C.blank();state.workshop.videos.password='secret';state.workshop.videos.records[id]={note:'Good',reviewed:false,markers:[],blobUrl:'blob:private',token:'secret'};const next=C.validate(state);assert.doesNotMatch(JSON.stringify(next),/secret|blob:private|password/);assert.throws(()=>C.validate({...state,workshop:{...state.workshop,videos:{...state.workshop.videos,records:{'__unknown__':{note:'',reviewed:false,markers:[]}}}}}));});
test('opt-in nocookie iframe and native device-only AB controls add no first-paint dependency, API or device permission',()=>{const ui=read('patin-video.js'),shell=read('patin.js'),loader=read('performance-loader.js'),sw=read('sw.js');assert.match(ui,/www\.youtube-nocookie\.com\/embed\//);assert.match(ui,/autoplay=0/);assert.match(ui,/strict-origin-when-cross-origin/);assert.match(ui,/visibilitychange/);assert.match(ui,/frame\.remove/);assert.match(ui,/URL\.revokeObjectURL/);assert.match(ui,/timeupdate/);assert.match(ui,/playbackRate/);assert.match(ui,/data-pt-local-loop/);assert.doesNotMatch(ui,/fetch\(|sendBeacon|iframe_api|getUserMedia|AudioContext|setInterval|requestAnimationFrame|i\.ytimg/);assert.match(shell,/videoCleanup\?\.\(\)/);for(const f of ['patin-learning-data.js?v=1','patin-video.js?v=3']){assert.ok(loader.includes(f));assert.equal(sw.split('"./'+f+'"').length-1,1);}assert.match(read('script.js'),/route: "\/patin\/videos"/);assert.doesNotMatch(read('index.html').replace(/<!--[\s\S]*?-->/g,''),/<script[^>]*src="patin/);});
