#!/usr/bin/env python3
"""Build compact, license-preserving HH English term packs from ESDB/SCOWL."""

from __future__ import annotations

import argparse
import hashlib
import json
import sqlite3
from pathlib import Path


SCHEMA_VERSION = 1
SOURCE_NAME = "English Speller Database (ESDB/SCOWL)"
SOURCE_URL = "https://github.com/en-wl/wordlist"
SOURCE_COMMIT = "1e5b7d3a72f47a71da5d28686c1dd4b397178485"
TERM_LIMIT = 30_000
PACK_SIZE = 5_000


def compact_json(value: object) -> bytes:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":")).encode("utf-8")


def sha256(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def normalize_pos(value: str) -> str:
    values = set((value or "").split(","))
    if "n" in values:
        return "noun"
    if "v" in values:
        return "verb"
    if "aj" in values:
        return "adjective"
    if "av" in values:
        return "adverb"
    return "word"


def load_terms(database: Path) -> list[list[str]]:
    connection = sqlite3.connect(database)
    try:
        rows = connection.execute(
            """
            SELECT lower(word) AS term, group_concat(DISTINCT pos) AS poses
            FROM scowl_v0
            WHERE size <= 35
              AND variant_level <= 1
              AND spelling IN ('_', 'A')
              AND region IN ('US', '')
              AND category = ''
              AND lower(word) = word
              AND length(word) BETWEEN 2 AND 24
              AND word NOT GLOB '*[^a-z-]*'
            GROUP BY lower(word)
            ORDER BY lower(word)
            LIMIT ?
            """,
            (TERM_LIMIT,),
        ).fetchall()
    finally:
        connection.close()
    terms = [[term, normalize_pos(poses)] for term, poses in rows]
    if len(terms) != TERM_LIMIT:
        raise RuntimeError(f"Expected {TERM_LIMIT} unique terms, got {len(terms)}")
    return terms


def build(database: Path, copyright_file: Path, output: Path) -> None:
    output.mkdir(parents=True, exist_ok=True)
    terms = load_terms(database)
    packs = []
    for offset in range(0, len(terms), PACK_SIZE):
        number = offset // PACK_SIZE + 1
        pack_id = f"esdb-{number:02d}"
        items = terms[offset : offset + PACK_SIZE]
        payload = {
            "schemaVersion": SCHEMA_VERSION,
            "id": pack_id,
            "source": "esdb",
            "verification": "term-index",
            "level": None,
            "items": items,
        }
        data = compact_json(payload)
        filename = f"{pack_id}.json"
        (output / filename).write_bytes(data)
        packs.append(
            {
                "id": pack_id,
                "file": f"assets/english-vocabulary/{filename}",
                "count": len(items),
                "first": items[0][0],
                "last": items[-1][0],
                "bytes": len(data),
                "sha256": sha256(data),
                "verification": "term-index",
            }
        )

    index_payload = {
        "schemaVersion": SCHEMA_VERSION,
        "source": "esdb",
        "count": len(terms),
        "packSize": PACK_SIZE,
        "terms": [row[0] for row in terms],
    }
    index_data = compact_json(index_payload)
    index_name = "search-index.json"
    (output / index_name).write_bytes(index_data)

    manifest = {
        "schemaVersion": SCHEMA_VERSION,
        "version": "2026.08.04-v1",
        "source": {
            "name": SOURCE_NAME,
            "url": SOURCE_URL,
            "commit": SOURCE_COMMIT,
            "license": "ESDB permissive notice; see ESDB-Copyright.txt",
        },
        "quality": {
            "termIndex": "vetted-spelling",
            "meaning": "not-assigned",
            "cefr": "not-assigned",
            "note": "HH only adds Vietnamese meanings and CEFR from reviewed in-app curriculum data.",
        },
        "targets": {
            "unique": 30_000,
            "core": 5_000,
            "cefr": 12_000,
            "academic": 3_000,
            "career": 15_000,
            "phrasalVerbs": 2_000,
            "idioms": 2_000,
            "collocations": 15_000,
            "confusables": 1_000,
        },
        "actual": {"termIndex": len(terms), "reviewed": "runtime"},
        "index": {
            "file": f"assets/english-vocabulary/{index_name}",
            "count": len(terms),
            "bytes": len(index_data),
            "sha256": sha256(index_data),
        },
        "packs": packs,
    }
    (output / "manifest.json").write_bytes(compact_json(manifest))
    (output / "ESDB-Copyright.txt").write_text(copyright_file.read_text(encoding="utf-8"), encoding="utf-8")
    (output / "README.md").write_text(
        "# HH English vocabulary packs\n\n"
        "Generated by `scripts/generate-english-vocabulary-packs.py` from ESDB/SCOWL. "
        "These packs are a spelling/term index only. They intentionally do not assign Vietnamese meanings or CEFR levels. "
        "Reviewed HH curriculum and career entries are merged at runtime.\n",
        encoding="utf-8",
    )
    print(json.dumps({"terms": len(terms), "packs": len(packs), "output": str(output)}, ensure_ascii=False))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--db", type=Path, required=True)
    parser.add_argument("--copyright", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    build(args.db.resolve(), args.copyright.resolve(), args.output.resolve())


if __name__ == "__main__":
    main()
