/* Isolated local browser QA. No production requests, users or device permissions. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{chromium}=require(process.env.HH_QA_PLAYWRIGHT||'playwright');
const repo=path.resolve(__dirname,'..'),out=path.join(repo,'.study-local/patin-qa'),results=[];
const server=http.createServer((req,res)=>{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=path.resolve(repo,'.'+name);if(!file.startsWith(repo+path.sep)||name.split('/').some(p=>p.startsWith('.')||p==='node_modules')){res.writeHead(403).end();return;}if(!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.json':'application/json','.svg':'image/svg+xml','.woff2':'font/woff2'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
const pass=name=>{results.push(name);console.log('PASS '+name);};
async function main(){fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;let browser;
  try{
    browser=await chromium.launch({headless:true,executablePath:process.env.HH_QA_CHROMIUM});
    const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true,serviceWorkers:'block'}),page=await context.newPage(),errors=[],external=[];page.on('pageerror',err=>errors.push(err.message));page.on('request',req=>{if(!req.url().startsWith(origin))external.push(req.url());});
    const go=async route=>{await page.evaluate(route=>location.hash='#'+route,route);await page.waitForFunction(route=>{const p=route.split('/'),root=document.querySelector('.pt-root');return root?.dataset.ptView===(p[2]||'home')&&root?.dataset.ptSkill===(p[3]||'');},route);};
    const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem(HHPatinCore.keyFor(JSON.parse(localStorage.getItem('hh.qa.patin.user')||'null')))||JSON.stringify(HHPatinCore.blank())));
    await page.goto(origin+'/tests/fixtures/patin.html#/patin');await page.locator('.pt-root').waitFor();assert.equal(await page.locator('.pt-nav a').count(),9);assert.match(await page.locator('.pt-hero').innerText(),/130 kỹ năng/);pass('overview and all nine real destinations');
    await go('/patin/skills');assert.equal(await page.locator('.pt-skill').count(),12);await page.locator('[data-pt-query]').fill('luot mot chan');assert.equal(await page.locator('.pt-skill').count(),1);assert.match(await page.locator('.pt-skill').innerText(),/Lướt một chân/);await page.locator('[data-pt-query]').fill('');await page.locator('[data-pt-category]').selectOption('quad');assert.equal(await page.locator('.pt-skill').count(),3);await page.locator('[data-pt-level]').selectOption('advanced');assert.equal(await page.locator('.pt-skill').count(),1);await page.locator('[data-pt-star="artistic-intro"]').click();await page.locator('[data-pt-category]').selectOption('all');await page.locator('[data-pt-level]').selectOption('all');await page.locator('[data-pt-favorites]').check();assert.equal(await page.locator('.pt-skill').count(),1);await page.locator('[data-pt-favorites]').uncheck();await page.locator('[data-pt-page="1"]').click();assert.match(await page.locator('[data-pt-count]').innerText(),/trang 2\/11/);pass('search without accents, category/level/bookmark filters and pagination');
    await go('/patin/skills/heel-brake');await page.locator('[data-pt-progress="read"]').check();await page.locator('[data-pt-progress="tried"]').check();await page.locator('[data-pt-note]').fill('Guest note <img src=x onerror=alert(1)>');await page.locator('[data-pt-star="heel-brake"]').click();assert.equal(await page.locator('[data-pt-note]').inputValue(),'Guest note <img src=x onerror=alert(1)>');await go('/patin/path');await page.goBack();await page.locator('[data-pt-note]').waitFor();assert.match(await page.locator('[data-pt-note]').inputValue(),/Guest note/);await page.reload();await page.locator('[data-pt-note]').waitFor();assert.equal(await page.locator('[data-pt-progress="read"]').isChecked(),true);assert.equal(await page.locator('[data-pt-progress="tried"]').isChecked(),true);assert.equal(await page.locator('[data-pt-note] img').count(),0);pass('notes, bookmarks, independent read/tried survive Back and reload; HTML stays text');
    for(const skill of require('../patin-data.js').skills){await go('/patin/skills/'+skill.id);assert.equal(await page.locator('.pt-detail h2').innerText(),skill.title);assert.equal(await page.locator('.pt-detail [data-pt-note]').count(),1);}
    pass('all 130 detail routes render actual unique content');
    await go('/patin/path');assert.equal(await page.locator('.pt-path>li').count(),5);await page.locator('[data-pt-plan]').selectOption('30');assert.match(await page.locator('[data-pt-plan-list]').innerText(),/16 phút/);pass('five-phase pathway and working 10/20/30 minute planner');
    await go('/patin/gear');for(const n of await page.locator('[data-pt-safety]').all())await n.check();assert.match(await page.locator('[data-pt-safety-status]').innerText(),/7\/7/);await page.locator('[data-pt-safety-reset]').click();assert.equal(await page.locator('[data-pt-safety]:checked').count(),0);await page.locator('[data-pt-safety]').first().check();await page.reload();assert.equal(await page.locator('[data-pt-safety]:checked').count(),0);pass('preflight checklist resets explicitly and on a new session, never claims verified safety');
    await go('/patin/resources');await page.locator('[data-pt-glossary]').fill('vong bi');assert.equal(await page.locator('.pt-glossary>div').count(),2);await page.locator('[data-pt-glossary]').fill('');for(const q of require('../patin-data.js').quiz)await page.locator(`[name="${q.id}"][value="${q.answer}"]`).check();await page.locator('[data-pt-quiz] button[type="submit"]').click();assert.match(await page.locator('[data-pt-quiz-summary]').innerText(),/6\/6/);await page.locator('[name="q1"][value="1"]').check();assert.match(await page.locator('[data-pt-quiz-summary]').innerText(),/thay đổi/);await page.locator('[data-pt-quiz-reset]').click();assert.equal(await page.locator('[data-pt-quiz] input:checked').count(),0);pass('glossary search, actual knowledge quiz scoring, answer invalidation and reset');
    await go('/patin/journal');const form=page.locator('[data-pt-journal-form]');await form.locator('[name="date"]').fill('2026-10-10');await form.locator('[name="minutes"]').fill('24');await form.locator('[name="skill"]').selectOption('heel-brake');await form.locator('[name="note"]').fill('Buổi thực tế <script>alert(1)</script>');await form.locator('button[type="submit"]').click();assert.equal(await page.locator('.pt-entry').count(),1);assert.equal((await state()).journal[0].minutes,24);assert.equal(await page.locator('.pt-entry script').count(),0);await page.reload();assert.equal(await page.locator('.pt-entry').count(),1);const download=page.waitForEvent('download');await page.locator('[data-pt-export]').click();const backup=path.join(out,'backup.json');await(await download).saveAs(backup);assert.equal(JSON.parse(fs.readFileSync(backup,'utf8')).state.journal.length,1);await page.locator('[data-pt-delete]').click();await page.locator('[data-pt-delete-cancel]').click();assert.equal(await page.locator('.pt-entry').count(),1);await page.locator('[data-pt-delete]').click();await page.locator('[data-pt-delete-yes]').click();assert.equal(await page.locator('.pt-entry').count(),0);await page.locator('[data-pt-import]').setInputFiles(backup);await page.locator('[data-pt-import-yes]').click();assert.equal(await page.locator('.pt-entry').count(),1);pass('manual journal save/reload, real download, confirmed delete and validated JSON import');
    await page.locator('[data-pt-import]').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":999}')});await page.waitForFunction(()=>document.querySelector('[data-pt-status]').textContent.includes('Không phải'));assert.equal(await page.locator('.pt-entry').count(),1);await page.locator('[data-pt-reset-open]').click();await page.locator('[data-pt-cancel]').click();assert.equal(await page.locator('.pt-entry').count(),1);pass('invalid import preserves data; destructive reset requires confirmation');
    await go('/patin/skills/heel-brake');await page.evaluate(()=>{localStorage.setItem('hh.qa.patin.user',JSON.stringify({id:'patin-qa-a'}));window.dispatchEvent(new CustomEvent('hh:auth-change',{detail:{user:{id:'patin-qa-a'}}}));});assert.equal(await page.locator('[data-pt-note]').inputValue(),'');await page.locator('[data-pt-note]').fill('Account A private');await page.evaluate(()=>{localStorage.setItem('hh.qa.patin.user',JSON.stringify({id:'patin-qa-b'}));window.dispatchEvent(new CustomEvent('hh:auth-change',{detail:{user:{id:'patin-qa-b'}}}));});assert.equal(await page.locator('[data-pt-note]').inputValue(),'');await page.locator('[data-pt-note]').fill('Account B private');await page.reload();assert.equal(await page.locator('[data-pt-note]').inputValue(),'Account B private');await page.evaluate(()=>{localStorage.removeItem('hh.qa.patin.user');window.dispatchEvent(new CustomEvent('hh:auth-change',{detail:{user:null}}));});assert.match(await page.locator('[data-pt-note]').inputValue(),/Guest note/);pass('live auth changes and reload isolate guest/A/B notes and journal');
    const other=await context.newPage();await other.goto(origin+'/tests/fixtures/patin.html#/patin/skills');await other.locator('[data-pt-query]').fill('kiểm tra');await other.locator('[data-pt-star="gear-check"]').click();await page.waitForFunction(()=>document.querySelector('[data-pt-status]').textContent.includes('tab khác'));await page.reload();assert.equal((await state()).favorites.includes('gear-check'),true);await other.close();pass('another tab bookmark update retained without overwriting the open note');
    for(const width of [1440,768,375]){await page.setViewportSize({width,height:950});for(const route of ['/patin','/patin/skills','/patin/studio','/patin/disciplines','/patin/speed','/patin/slide','/patin/slalom','/patin/path','/patin/gear','/patin/journal','/patin/resources','/patin/skills/t-stop']){await go(route);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+width+' '+route);await page.locator('.pt-footer').scrollIntoViewIfNeeded();assert.equal(await page.locator('.pt-footer').isVisible(),true);}await go('/patin');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(out,'patin-'+width+'.png'),fullPage:false});pass('all views scroll and fit '+width+'px without horizontal overflow');}
    await page.setViewportSize({width:750,height:950});await page.evaluate(()=>document.documentElement.style.zoom='2');for(const r of ['/patin/skills','/patin/journal','/patin/resources']){await go(r);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'zoom '+r);}await page.emulateMedia({reducedMotion:'reduce',forcedColors:'active'});await go('/patin/skills/t-stop');await page.locator('[data-pt-note]').focus();assert.notEqual(await page.locator('[data-pt-note]').evaluate(n=>getComputedStyle(n).outlineStyle),'none');await page.locator('[data-pt-progress="read"]').focus();await page.keyboard.press('Space');assert.equal((await state()).progress['t-stop'].read,true);await page.screenshot({path:path.join(out,'patin-forced-colors-200.png'),fullPage:false});pass('200% zoom, forced colors, reduced motion and keyboard checkbox/focus');
    await page.evaluate(()=>HHPatin.unmount());assert.equal(await page.evaluate(()=>HHPatin.activeHost()),null);assert.deepEqual(errors,[]);assert.deepEqual(external,[]);pass('no uncaught errors, external requests, autoplay or extra render loop; unmount cleanup');await context.close();
    const shellContext=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'}),shell=await shellContext.newPage(),shellErrors=[];shell.on('pageerror',err=>shellErrors.push(err.message));await shellContext.route('**/api/**',r=>r.fulfill({status:r.request().url().includes('/providers')?200:401,contentType:'application/json',body:JSON.stringify({google:false,email:false,error:'Local QA backend double'})}));await shell.goto(origin+'/index.html?api=local#/platform',{waitUntil:'domcontentloaded'});await shell.locator('[data-guest-login]').click();await shell.locator('.app-main .php').waitFor({timeout:45000});const privacy=shell.getByRole('button',{name:'Từ chối tùy chọn',exact:true});if(await privacy.isVisible())await privacy.click();assert.equal(await shell.evaluate(()=>!!window.HHPatin),false);await shell.locator('[data-sidebar-search]').fill('Patin');const sidebar=shell.locator('.app-sidebar [data-app-route="/patin"]').first();await sidebar.click();await shell.locator('.pt-root').waitFor({timeout:45000});assert.match(shell.url(),/#\/patin$/);assert.match(await shell.locator('[data-pt-status]').innerText(),/dữ liệu khách/);assert.equal(await shell.locator('.app-header').count(),1);assert.equal(await shell.locator('.app-sidebar').count(),1);assert.match(await shell.locator('.app-page-header').innerText(),/Giải trí & Nội dung/i);assert.equal(await shell.locator('[data-hh-planet]').count(),25);pass('actual shell: guest Platform → sidebar Patin, lazy load, stable chrome, unchanged login planets');
    await shell.locator('.pt-nav [data-app-route="/patin/skills"]').click();await shell.locator('[data-pt-query]').waitFor();await shell.locator('[data-pt-query]').fill('phanh gót');await shell.locator('.pt-skill h3 a[href="#/patin/skills/heel-brake"]').click();await shell.locator('[data-pt-note]').fill('Real shell saved note');await shell.evaluate(()=>location.hash='#/platform');await shell.locator('.app-main .php').waitFor();assert.equal(await shell.evaluate(()=>HHPatin.activeHost()),null);await shell.goBack();await shell.locator('[data-pt-note]').waitFor();assert.equal(await shell.locator('[data-pt-note]').inputValue(),'Real shell saved note');await shell.reload({waitUntil:'domcontentloaded'});await shell.locator('[data-pt-note]').waitFor({timeout:45000});assert.equal(await shell.locator('[data-pt-note]').inputValue(),'Real shell saved note');await shell.goBack();await shell.goForward();await shell.locator('[data-pt-note]').waitFor();pass('real shell skill route, note persistence, workspace cleanup, Back/Forward and reload');
    await shell.evaluate(()=>location.hash='#/platform');await shell.locator('.app-main .php').waitFor();await shell.locator('[data-php-search]').fill('Patin');assert.equal(await shell.locator('[data-php-card="/patin"]').isVisible(),true);await shell.keyboard.press('Control+k');await shell.locator('#commandPaletteInput').fill('Patin');assert.equal(await shell.locator('#commandPaletteResults [data-app-route="/patin"]').count(),1);await shell.locator('#commandPaletteResults [data-app-route="/patin"]').click();await shell.locator('.pt-hero').waitFor();await shell.waitForFunction(()=>!document.documentElement.dataset.routeDirection&&!document.querySelector('#appCosmicLoader')?.classList.contains('is-active'));pass('homepage catalog and global command palette find and open Patin');
    for(const width of [1440,768,375]){await shell.setViewportSize({width,height:950});assert.ok(await shell.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'shell overflow '+width);await shell.locator('.pt-footer').scrollIntoViewIfNeeded();assert.equal(await shell.locator('.pt-footer').isVisible(),true);await shell.locator('.pt-nav').scrollIntoViewIfNeeded();await shell.screenshot({path:path.join(out,'patin-real-shell-'+width+'.png'),fullPage:false});}await shell.setViewportSize({width:1440,height:1000});await shell.evaluate(()=>document.documentElement.style.zoom='2');assert.ok(await shell.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shell.locator('.pt-footer').scrollIntoViewIfNeeded();assert.equal(await shell.locator('.pt-footer').isVisible(),true);assert.deepEqual(shellErrors,[]);pass('actual shell desktop/tablet/375px, 200% zoom, usable scroll and no uncaught exceptions');await shellContext.close();
  }finally{await browser?.close();await new Promise(r=>server.close(r));fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({date:new Date().toISOString(),results},null,2));}
}
main().catch(err=>{console.error(err);process.exitCode=1;});
