(function initCharacterNetworkReplicator(root) {
  "use strict";
  const A = root.HHAstraCharacter || (typeof require === "function" ? require("./AstraCharacterCore.js") : {});
  const FIELDS = ["characterId", "animationState", "normalizedTime", "locomotionVector", "facingYaw", "aimPitch", "weaponId", "actionSequenceId", "combatState", "expressionId", "serverTimestamp"];
  class CharacterNetworkReplicator {
    constructor(options = {}) { this.snapshots = []; this.maxSnapshots = A.clamp(options.maxSnapshots || 32, 4, 120); this.lastSequence = new Map(); this.maxSpeed = A.clamp(options.maxSpeed || 12, 1, 40); this.lastReconciliation = null; }
    sanitize(packet = {}) { const output = {}; FIELDS.forEach((key) => { if (packet[key] !== undefined) output[key] = packet[key]; }); output.characterId = A.safeId(output.characterId || "unknown", "characterId"); output.animationState = String(output.animationState || "idle").slice(0, 48); output.normalizedTime = A.clamp(output.normalizedTime || 0, 0, 1); output.locomotionVector = A.normalize2(output.locomotionVector); output.facingYaw = A.clamp(output.facingYaw || 0, -Math.PI * 4, Math.PI * 4); output.aimPitch = A.clamp(output.aimPitch || 0, -Math.PI / 2, Math.PI / 2); output.weaponId = String(output.weaponId || "unarmed").slice(0, 80); output.actionSequenceId = String(output.actionSequenceId || "").slice(0, 100); output.combatState = String(output.combatState || "ready").slice(0, 40); output.expressionId = String(output.expressionId || "neutral").slice(0, 32); output.serverTimestamp = Math.max(0, Number(output.serverTimestamp || Date.now())); return output; }
    acceptSnapshot(packet) { let clean; try { clean = this.sanitize(packet); } catch (error) { return { accepted: false, reason: error.message }; } const previous = this.snapshots[this.snapshots.length - 1]; if (previous && clean.serverTimestamp <= previous.serverTimestamp) return { accepted: false, reason: "stale-snapshot" }; if (clean.actionSequenceId) { const last = this.lastSequence.get(clean.characterId); if (last === clean.actionSequenceId) return { accepted: false, reason: "duplicate-sequence" }; this.lastSequence.set(clean.characterId, clean.actionSequenceId); } this.snapshots.push(clean); this.snapshots = this.snapshots.slice(-this.maxSnapshots); return { accepted: true, packet: clean }; }
    sample(renderTimestamp) { if (!this.snapshots.length) return null; if (this.snapshots.length === 1) return this.snapshots[0]; let before = this.snapshots[0], after = this.snapshots[this.snapshots.length - 1]; for (let index = 1; index < this.snapshots.length; index += 1) if (this.snapshots[index].serverTimestamp >= renderTimestamp) { before = this.snapshots[index - 1]; after = this.snapshots[index]; break; } const alpha = A.clamp((renderTimestamp - before.serverTimestamp) / Math.max(1, after.serverTimestamp - before.serverTimestamp), 0, 1); return { ...after, normalizedTime: before.normalizedTime + (after.normalizedTime - before.normalizedTime) * alpha, facingYaw: before.facingYaw + A.angleDelta(before.facingYaw, after.facingYaw) * alpha, locomotionVector: { x: before.locomotionVector.x + (after.locomotionVector.x - before.locomotionVector.x) * alpha, z: before.locomotionVector.z + (after.locomotionVector.z - before.locomotionVector.z) * alpha } }; }
    reconcile(authoritative = {}, predicted = {}) { const distance = Math.hypot((authoritative.x || 0) - (predicted.x || 0), (authoritative.z || 0) - (predicted.z || 0)); this.lastReconciliation = { distance, snap: distance > 3, blendMs: distance > 3 ? 0 : A.clamp(distance * 180, 60, 280), timestamp: A.now() }; return this.lastReconciliation; }
    dispose() { this.snapshots.length = 0; this.lastSequence.clear(); }
  }
  CharacterNetworkReplicator.FIELDS = FIELDS;
  A.CharacterNetworkReplicator = CharacterNetworkReplicator;
  if (typeof module !== "undefined" && module.exports) module.exports = CharacterNetworkReplicator;
})(typeof window !== "undefined" ? window : globalThis);
